### ISSUE TITLE
erroneous term "gamification" in rewards notification message

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#1001]
**Steps to reproduce**

When receiving a notification about rewards for a period, the message  looks like this : 

> Vous avez gagné 83,904 Ɱ en récompense pour vos 4 475 gamification durant la période : 5 juin 2023 à 11 juin 2023

![Screenshot 2023-06-22 at 16 51 28](https://github.com/Meeds-io/meeds/assets/227828/3a235634-1735-47a7-bb76-7c6479810c2f)

the term "gamification" is misleading. It should be "points"

**Comment by srenault-meeds** [comment]
I have seen you have proposed a fix from crowdin. Is that ok now?

**Comment by srenault-meeds** [comment]
The source string was not updated so it is still ko. Should be ok after next deployment
