### ISSUE TITLE
Add expand option to task drawer

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#1020]
I suggest to add the expand (like announcement drawer or transaction drawer) option to the task drawer

**Comment by boubaker** [comment]
+1 related to https://github.com/Meeds-io/meeds/issues/198 suggestion as well. IMO to include to ideation.

**Comment by boubaker** [comment]
We can even imagine different UIs in "expanded" & "collapsed" views as made for Engagement Programs & Rules. @srenault-meeds WDYT ?

**Comment by srenault-meeds** [comment]
yes indeed and with a dedicated link if needed to share it 
-> Like this: /taskID#expanded
