### ISSUE TITLE
Bad Performances for Recent Spaces Drawer

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#1022]
**Steps to reproduce**

1. Open left menu
2. Hover the 'recent spaces' expand icon
3. The recent spaces drawer takes a lot of time to load

https://github.com/Meeds-io/meeds/assets/594824/d37b85fa-4b88-4231-8d57-3ec09aa2a897

**Comment by srenault-meeds** [comment]
@rdenarie we discussed it during the product committee (October, 16th). Is it done?
cc @boubaker

**Comment by boubaker** [comment]
@srenault-meeds I think we should consider this in our board since it's a global performance issue not related to an existing MIP.

**Comment by srenault-meeds** [comment]
Ok but eXo was identified to deal with this. So waiting for @rdenarie confirmation that we can do this.

**Comment by rdenarie** [comment]
This issue is doing in maintenance board

**Comment by srenault-meeds** [comment]
Ok thanks

**Comment by srenault-meeds** [comment]
@Jihed525 @rdenarie we will take care of it if no objection for you

**Comment by rdenarie** [comment]
ok for me

**Comment by srenault-meeds** [comment]
ok done FYI @rdenarie
