### ISSUE TITLE
Allow to expand Achievement comment drawer

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#1035]
**Is your feature request related to a problem? Please describe.**
On the new Actions activities, achievements are added as comments. Some may be very verbose and so not very comfortable to read in a drawer. 

see an example
<img width="413" alt="Screenshot 2023-07-21 at 15 31 42" src="https://github.com/Meeds-io/meeds/assets/227828/944a832c-2770-42cd-b7e7-b4d24f7c7528">

**Describe the solution you'd like**

The drawer should be expandable.

**Comment by srenault-meeds** [comment]
It is actually expandable.
Can you precise which browser you use, please?

**Comment by plamarque** [comment]
It was chrome but I think on a smaller size window
