### ISSUE TITLE
FR: Agenda event scheduling requires choosing a space

### ISSUE THREAD

**Issue by sergeByishimo** [Meeds-io/meeds#1040]
Any luck this feature exists and I can not see it?

**Is your feature request related to a problem? Please describe.**
It seems I cant schedule an event without specifying a space.

**Describe the solution you'd like**
I want to be able to schedule an event with people without having to choose a space.

**Additional context**
The event can show up in my personal calendar just like others.

**Comment by plamarque** [comment]
Hi Serge, I guess this is a request for eXo Platform Agenda app. Meeds does not have such an app.

You may want to ask in their forum maybe ?

 https://github.com/exoplatform/agenda/issues
