### ISSUE TITLE
UI glitches on title for the gadgets of the page overview (my contributions, challenges overviews, etc.)

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#1043]
Go to page 'stream

If the different gadgets are in a page that isn't the page overview, there are some UI glitches on title 

For example the title is in lower case for the gadget Challenge overview in the page stream

![image](https://github.com/Meeds-io/meeds/assets/31288011/7f715e9b-f31c-41be-9ea3-4e5fcd6b5c19)

Another example

![image](https://github.com/Meeds-io/meeds/assets/31288011/2b3fa4bc-caa7-4028-a883-abfcbf2446d5)

it should be in upper case and the font size should be 16px

**Comment by boubaker** [comment]
Duplicates https://github.com/Meeds-io/meeds/issues/1042

**Comment by boubaker** [comment]
Seems related to title of widget, not of action, reopened.

**Comment by srenault-meeds** [comment]
Hi @margondicco uppercase style has to be done from crowdin so it is easier to maintain. 
Regarding the font-size, I don't reproduce it. Can you please report the meeds version used in the platform you used for the screenshot?

**Comment by srenault-meeds** [comment]
Fixed with MIP81 Cleanup portlets
