### ISSUE TITLE
Gamification : Managing Domains and Rules

### ISSUE THREAD

**Issue by sergeByishimo** [Meeds-io/meeds#1055]
eXo 6.4.1 
Gamification :: Portlets Pack Version: 2.4.1-exo

**Is your feature request related to a problem? Please describe.**
I can not see how to manage domains and rules.

**Describe the solution you'd like**
In this latest [documentation](https://exo-documentation.readthedocs.io/en/latest/Administration.html?highlight=domains#manage-domains) they show options to manage domains and rules.

![Screen Shot 2023-08-07 at 12 42 26](https://github.com/Meeds-io/meeds/assets/32865999/1beb3162-793c-42d5-a201-1877e925e9f9)
 
BUT I can not see the options as you can see, I can only manage Badges.

![Screen Shot 2023-08-07 at 12 47 33](https://github.com/Meeds-io/meeds/assets/32865999/3fcc1965-e479-459f-ae26-3b7954e597aa)

**Comment by srenault-meeds** [comment]
Hi, this documentation is eXo-related so I suggest you to ask eXo community.
