### ISSUE TITLE
Task Rest Endpoint miss @Produces annotation

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1067]
**Steps to reproduce**

1. Try to add a comment in a task using curl, without using Accept Header

**Current behaviour**

There is an error in log :

> 2023-08-17 07:40:27,350 | ERROR | Not found writer for class org.exoplatform.task.rest.model.CommentEntity and MIME type */* [exo.ws.rest.core.ContainerResponse<http-nio-0.0.0.0-8080-exec-9>] 
> 2023-08-17 07:40:27,350 | WARN  | An error occurred while calling REST endpoint /rest/private/tasks/comments/65878, method: POST [exo.ws.rest.core.RestServlet<http-nio-0.0.0.0-8080-exec-9>] 
> javax.ws.rs.WebApplicationException: null
> 	at org.exoplatform.services.rest.impl.ContainerResponse.writeResponse(ContainerResponse.java:193)
> 	at org.exoplatform.services.rest.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:213)
> 	at org.exoplatform.services.rest.servlet.RestServlet.onService(RestServlet.java:100)
> 	at org.exoplatform.container.web.AbstractHttpServlet.service(AbstractHttpServlet.java:133)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)

**Comment by srenault-meeds** [comment]
is it done?

**Comment by rdenarie** [comment]
Yes it is. Thanks
