### ISSUE TITLE
No key for Documents label in settings>Manage notifications page

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#1074]
**Steps to reproduce**

1. My platform is configurated to any language except English

2. I go to my settings>Manage notifications page

3. Check the Documents label

**Current behaviour**

the label: "documents" isn't translated to the selected plf language.

**Expected behavior**

Add a key to "documents" label so it could be translated via Crowdin

**Comment by srenault-meeds** [comment]
is it done?
