### ISSUE TITLE
Wallet Reward Transaction erased by Job

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#1086]
**Steps to reproduce**

1. Go to Wallet Rewarding UI
2. Click on 'Send Rewards' at the exact same time than the reward computing Job 

**Current behaviour**

The Wallet Reward is duplicated for a given user and period.

**Expected behavior**

The Wallet Reward should be unique for a given user and period.

**Comment by srenault-meeds** [comment]
Closed as completed
