### ISSUE TITLE
Task - Arrow not displayed for a folded section

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1088]
**Steps to reproduce**

1. Go to Task app
2. Apply a group by filter
3. Click on the arrow of a group to fold it

https://github.com/Meeds-io/meeds/assets/105866381/6742ffd9-3650-4310-8dfe-2cc9f046e890

See video

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The arrow disappears and we can't click on it anymore to unfold it.

**Expected behavior**

We should have an arrow pointing to the right displayed and we could click on it. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Closed as done :)
