### ISSUE TITLE
Unread activity improvements

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1091]
**Is your feature request related to a problem? Please describe.**
Unread activity is really useful but when you have a lot of them in a lot of spaces and especially spaces you didn't check frequently, it starts to be painful to read them. 
 
I don't want to mute the space, I just want to find the unread activities quickly. 

**Describe the solution you'd like**
I might be interesting to implement several improvements to facilitate how to access them : 

On the Stream page
- Filter "Unread activities": to display only the unread activities of all my spaces. I could quickly check them
- Mark all as unread button when filtered on Unread activities: quickly mark all as unread. Presently I have to click almost 10 times on See more on the navigation menu + open the second level navigation to mark as read. As the loading of the space automatically scrolls I even miss some spaces. 

On navigation menu
- Quick filter with unread activities: to display only the spaces with unread activities. I could quickly check which spaces have it and see if there are ones in my VIP spaces so I can go quickly to it. 

https://github.com/Meeds-io/meeds/assets/105866381/16b4870a-37ab-4bbc-b7a5-21c653528a10

**Describe alternatives you've considered**

**Additional context**

**Comment by srenault-meeds** [comment]
Done with MIP96
