### ISSUE TITLE
[Contributions] link to comment achievement is ko

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1094]
**Steps to reproduce**

1. Go to achievements
2. Click on spark discussion action link to access the discussion
3. See error: the link to the comment is not correct and the activity is not found (see video)

https://github.com/Meeds-io/meeds/assets/58853195/ff67f499-95c9-4b9b-9922-46cab544433f

**Comment by srenault-meeds** [comment]
Is that because the comment has been deleted? I don't find it. 
cc @boubaker do you have something I can use to try finding the comment?
here is the link: https://builders.meeds.io/portal/meeds/activity?id=comment6909

**Comment by boubaker** [comment]
> Is that because the comment has been deleted? I don't find it. cc @boubaker do you have something I can use to try finding the comment? here is the link: https://builders.meeds.io/portal/meeds/activity?id=comment6909

The link works for me

**Comment by srenault-meeds** [comment]
Ok strange, this is ok now (while it was not when doing the recording). Nevermind, thanks. closed as not planned and thanks for taking time to check
