### ISSUE TITLE
Redirection problem when using a link in notification while not connected

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1104]
Environment : 6.3

Prerequires :

configure with SAML

Scenario : 

- While not connected, click on a link in a notification. For example : [servername/portal/dw/activities?activityId=3](https://servername/portal/dw/activities?activityId=3) : the link in the title of the news notification
- Log in SAML

Current Behaviour : Stream page is displayed
Expected : The page of the link on which I click is displayed

**Comment by srenault-meeds** [comment]
Is it done?

**Comment by rdenarie** [comment]
Yes it is. Thanks
