### ISSUE TITLE
Notification center - open in a new tab do not mark the notification as read

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1111]
**Steps to reproduce**

1. Go to the notification center
2. Click on an unread notification with the third click button or right click open in a new tab
3. The notification is opened in a new tab
4. Check the number of notifications. See error

https://github.com/Meeds-io/meeds/assets/105866381/9cb985d1-7baa-43b6-bf18-62d27bbeb33e

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**
When I open a notification in a new tab, it's not marked as read. 

**Expected behavior**

When I open a notification in a new tab, it's mark as read. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Should be ok once deployed
