### ISSUE TITLE
[Notifications] Wrong html on the notification summary of the commented post

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#1117]
**Steps to reproduce**

1. Go check your notification drawer
2. View a comment notification
3. A html code is displayed in the summary of the commented post
4. When hovering on the summary of the notified post, we don't have the same style when hovering on other elements 

**Expected behavior**

We should not have html code in the summary of the notified post and hovering on it should respect the correct style
![bug ](https://github.com/Meeds-io/meeds/assets/1579929/58361ba0-0de5-4467-98e4-0b7d13f12a61)

**Comment by srenault-meeds** [comment]
Hi, I don't reproduce this behaviour. Can you please tell me if you reproduce with Meeds plf?
Thanks

**Comment by srenault-meeds** [comment]
@azayati up?

**Comment by srenault-meeds** [comment]
As I don't get any answer, I consider it as done.
cc @azayati

**Comment by srenault-meeds** [comment]
I reopen this issue as we have reproduced it
