### ISSUE TITLE
[Image] Orientation issue of images

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1126]
**Steps to reproduce**

1. Post a message, a comment and attach an image including some EXIF data
2. See error: once posted, the image is displayed as wrongly-oriented

This might be related to the thumbnail service which compress the image rendering to avoid lack of display performance 

**Expected behavior**

Study the thumbnail service to avoid such behaviour and to keep respecting performance guidelines for image display

Video here (in French) 
https://youtu.be/IR48Y_fKjJ4

**Comment by rdenarie** [comment]
My 2 cts : 
When an image is displayed in the activity, we ask to the ThumbnailService to serve it, providing the size of the area in which the image is displayed. 
The idea is to say : if the image is displayed in small area (200x100 for example), no need to send it in the full resolution (4000x3000). Reducing it saves bandwith. 

The thumbnailService uses a library to make the resize : [Scalr](https://github.com/rkalla/imgscalr)
When this library resize the image, the EXIF data are removed, so the browser is not able to read it to display the image correctly. 
This library do not support EXIF data.

So we have 2 options : 
- Find another library to make the resize, with a requirement about exif data
- Add stuff to preserv EXIF data (save it before the resize, then readd it after, or do not resize the image if there is the EXIF data Orientation). This additional stuff should not increase the execution time of the resize, and stay reasonable.

For the first option, when I searched another library, I had difficulties to find alternatives. 
And for the second option, extracting EXIF data from and image requires another library, so I decide to not add this part when the feature was realised.

I'm open to discussion, but, it is not as trivial as it seems.

**Comment by plamarque** [comment]
How about adding support for preserving EXIF data to Scalr? It's Apache2 license.

**Comment by rdenarie** [comment]
Yes, it is also an option

**Comment by srenault-meeds** [comment]
Ok thanks guys for taking time to suggest technical answers.
One question from an ignorant: why preserving exif data is useful?
Indeed, for example:
1. Share an image with EXIF data in a post - orientation image issue
2. Share this same image on discord - no orientation image issue and EXIF data have been removed

Now, the question is who can take care of this?
It seems that your customers (eXo) are the most complaining ones about it

**Comment by rdenarie** [comment]
Generally, EXIF data are read by browser and used to orient the image.

> EXIF data have been removed

How you see that EXIF data are removed after posting image on discord ?

**Comment by rdenarie** [comment]
It seems that Discord change physically the image orientation and remove the exif data. 

Example : you have an image which make 500px width and 200px height, representing a tree, rotated on the left (i.e. with exif data orientation set to 'top.left' : 
When you open it in your computer file explorer, or in preview in eXo, the browser read the exif data, and turn the image to display it with 500px height and 200px width.
When this image is resize, the library we use keep the image ratio, and reduce the size to (for example) 250px width and 100px height, and remove exif data. 
As there is no more exif data, the browser is not able to know that he must rotate it.

When you upload the same image in discord, then click to see it in detail, and right click to download the image, the downloaded image have no EXIF data, but the size is 200px width and 500px height. The rotation is "forced".
So yes Discrod remove the exif, but change the image orientation.

Lets ping me if not clear

**Comment by srenault-meeds** [comment]
Clear to me. And I like the fact that rotation is forced. WDYT?

**Comment by rdenarie** [comment]
It is an option, which implies that we modify the image sent by the user.
