### ISSUE TITLE
fix : The user's avatar is still displayed for disabled users.

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#1129]
**Steps to reproduce**

1. User1 has an avatar picture and has some activities in space1
2. With admin disable user1
3. Check his profile page, his card in space1 members app and hover on his name on his activities

**Current behaviour**

The user avatar remains the same and is not replaced by the default one instead

**Expected behavior**

The default user avatar should be displayed

**Comment by srenault-meeds** [comment]
Is that done?

**Comment by srenault-meeds** [comment]
What's the status please? @Jihed525

**Comment by Jihed525** [comment]
issue fixed already on eXo side
