### ISSUE TITLE
[Groups] Data protection group is not relevant

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1138]
**Is your feature request related to a problem? Please describe.**
When going to groups management and using meeds, we have a group called "Data protection" but this group is not used at all in Meeds feature.
This should be removed from meeds code, IMO

**Comment by plamarque** [comment]
YES

**Comment by rdenarie** [comment]
This group is defined in an exoplatform addon. 
As I can see, it is not present in meedsv2 acceptance. 

On which platform did you see it ?
Have you a screenshot ?

**Comment by srenault-meeds** [comment]
Yes, it is present in builders app / prod
<img width="680" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/401c8b1b-d1ad-49a0-81db-0d55c0f33db6">

**Comment by rdenarie** [comment]
I think it comes from the first iterations of the deployment.

As meeds do not have dlp addon, the dlp group should not be present.

You should be able to remove it manually. 
When I start from scratch, the group is not present.

Try on your ppr, then restart to ensure that it is not recreated.

**Comment by srenault-meeds** [comment]
Ok, group removed from PPR, we will see how it goes after restart. Thanks

**Comment by srenault-meeds** [comment]
I have removed it from PPR last Friday and today, it is there again.

**Comment by rdenarie** [comment]
I'm afraid that ppr data are reloaded from production each week end. 
So, as the group is present in production, the data restore get it.
Can you try to delete it in ppr today, then check tomorrow ?

**Comment by azayati** [comment]
if there is a dev instance, you can also delete and restart

**Comment by srenault-meeds** [comment]
Only prod is here concerned. So I have removed from PPR again and we will see tomorrow

**Comment by srenault-meeds** [comment]
Ok when removing the group from ppr so I have done it on prod too
