### ISSUE TITLE
Display a Builder's user profile : My gamified bloc displayed ?

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#1141]
**Steps to reproduce**

1. display details of  any user profile
2. Check the below bloc

![Screenshot from 2023-09-29 17-18-51](https://github.com/Meeds-io/meeds/assets/31882754/4a0815a6-7834-4e03-8fd9-1dd46cd02b36)

Indicate the version where the bug is observed.
https://builders.meeds.io/portal/meeds/stream

**Current behaviour**
bloc message displayed :
messageMy Gamified Profiles
Not yet connected ? Go see your settings

**Expected behavior**
I shouldn't get such bloc displayed on another people profiles, no ?
Else, on my part, my hithub account is well connected

**(optional) Affected environments**  
Please complete the following information: 
 - OS: Ubuntu
 - Browser Brave
 - Version Latest stable 1.59.102
 - Device: Laptop

**Comment by srenault-meeds** [comment]
Fixed!
