### ISSUE TITLE
[Cache Issue] Activity is not displayed

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1145]
**Steps to reproduce**

1. Log with root,
2. Create 2 users : john  and mary
3. Log with john, create a space, in creation drawer invite Mary into the space. Validate the space creation
4. Create an activity in the space.
5. Logout with john, log in with mary
6. Click on Stream in left menu : you dont see the new space nor the activity into because mary has not accepted the invitation
7. Go In space list, accept the invitation,
8. In space stream, you see the activity
9. Go back in global stream => activity is not visible

Start of analyze : 
In step 6, an activity list is cached with CachedActivityStorage.
When accepting the space invitation, the cache is not invalidated
So in step 9, the cached activity list is used and displayed, without the new activity

Video explaination : https://youtu.be/oU7TqlNUdQ4

**Comment by srenault-meeds** [comment]
Hi, is it done? 
@Jihed525 @rdenarie

**Comment by rdenarie** [comment]
Yes we can close
