### ISSUE TITLE
Issue when you reply to an action where you are mention

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1151]
**Steps to reproduce**

1. User A declares an action and mentions User B 
2. With User B click on reply to the mail notification or go to the page to have access to the acitvity to click on Reply

https://github.com/Meeds-io/meeds/assets/105866381/3fc13cfa-b682-4d1a-944c-f3a857714ada

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The comment drawer opens but not on the corresponding comments and there is no rich editor who opens. It opens on the first comment. I have to click on the second page then click on reply.

**Expected behavior**

The drawer opens on the corresponding post and the rich editor is directly opens.

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Fixed
