### ISSUE TITLE
[Notifications] Snackbar UI (desktop)

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1152]
**Is your feature request related to a problem? Please describe.**
Notifications that are displayed when error, info, success or warning are not following UX guidelines as expected.
Currently: 
- text is centered aligned
- the width of the notification is not dynamic depending on the text length
- close icon must not have same style as the colored vertical bar

**Describe the solution you'd like**
- Text:
. Left aligned, 
. 16px font-size
. If more than 45 char., line break is done automatically

- If CTA link
. font-size is 16px as well 
. color of hyperlink text

- Close icon to be only a cross (not times-circle, but times) and color is allPagesGreyColorLighten1

- Snackbar style:
. No icon before label
. Height: 57px 
. Width is maximum 480px and minimum 400px
. border-radius: 4px
. colored vertical line to the left: 8px 

<img width="587" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/e16b9fb7-dbc8-4c89-873a-001fe29266cb">

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds to be sure I understand correctly. The width of the notification could be dynamic as long as it's between 400px and 480px, is that right? 

I'm not against fixing the minimum and maximum width but what advantage will it have? 

I'm not a big fan of the center-aligned especially if we have a minimum width. On your video, for the mute, I could see it and I don't find it nice. We have a feeling of emptiness. I find it more suitable to be left-aligned.

In your examples here, they are all left-aligned.

**Comment by srenault-meeds** [comment]
>  The width of the notification could be dynamic as long as it's between 400px and 480px, is that right?

Yes, indeed

> I'm not against fixing the minimum and maximum width but what advantage will it have?

To avoid having really small snackbar or too large snackbar

> I'm not a big fan of the center-aligned especially if we have a minimum width. On your video, for the mute, I could see it and I don't find it nice. We have a feeling of emptiness. I find it more suitable to be left-aligned.
In your examples here, they are all left-aligned.

Yes this is why at first I created this issue. Because this is a generic component and the alignment is by default centered. If you don't see it, then the component used is not the one you must use OR an override is done.
