### ISSUE TITLE
Switch to Indonesian language displays 404 error

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#1163]
**Steps to reproduce**

1. connect with any user

2. go to personal settings

3. switch language to indonesian

**Current behaviour**

404 error page.

**Expected behavior**

the indoensian related code is wrong , it should be in instead of id, eXo Platform language should be switched to indeonesian

**Comment by srenault-meeds** [comment]
Is it done?

**Comment by Jihed525** [comment]
fixed and validated on eXo side

**Comment by Jihed525** [comment]
I believe the issue is not fixed for meeds, can you check @srenault-meeds ?
sample https://builders.meeds.io/portal/id/meeds

**Comment by srenault-meeds** [comment]
Yes, maybe because the CI/CD have been blocked due to failed tests.
