### ISSUE TITLE
[Richeditor] Review border-style of composer / comment field

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1177]
**Is your feature request related to a problem? Please describe.**
When adding, editing a content in an activity, in a comment, the border seems too much dark comparing to other border. 
See screenshot below

<img width="405" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/e690dc26-4526-4f46-b762-de908c4ef62e">

**Describe the solution you'd like**
Same border color as the used for space suggestor for example

<img width="386" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/9e35d683-f411-4c1c-bb54-13e6f739fbe2">

**Comment by Julien-Dubois-eXo** [comment]
I agree that we need to harmonize. 

You did not mention the UX depending on the case: field active (we are editing the field) and field not active (we are not editing the field). 

I'm okay with your proposition for inactive UI. 

Do you plan to also harmonize the UX when it's active? I find it good the way "Choose a space" behaves when it's active.

**Comment by srenault-meeds** [comment]
I wondered myself too about it but I find this UX too much pushy for the user. Indeed, it looks like it is mandatory.


We might need to improve it but in another issue maybe
WDYT?

**Comment by srenault-meeds** [comment]
Will be ok after next deployment
