### ISSUE TITLE
Program owners not consistently displayed

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#1182]
**Problem**
On some program cards, we see the avatars of the owners,s but for others, it's written rewarding administrators.
It's inconsistent and  not very user-friendly (who are these 'administrators' ?)

![Screenshot 2023-10-12 at 17 22 32](https://github.com/Meeds-io/meeds/assets/227828/b26148dd-4b80-4eb3-b00d-51fbdbd835ca)

**Solution **
Even when program is managed by a group, we should see the avatars of the members of the group rather than the text label.

**Comment by srenault-meeds** [comment]
+1 indeed. WDYT @boubaker ?

**Comment by boubaker** [comment]
> +1 indeed. WDYT @boubaker ?

Up to you to decide if it's relevant. Technically, we will have to make sure that it's performant.
