### ISSUE TITLE
Unable to create a user with hyphen in user name even if setting the validator property

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1197]
Environment : 6.5.0-20231018
Scenario :
Add this property : gatein.validators.userName.regexp=^[a-zA-Z0-9._-]{3,}$ to allow username with '-'
Start platform
Create a user with username = 'john-smith'
Current Behaviour :
Error message saying that the format is not correct
Expected behaviour : user is created

**Comment by srenault-meeds** [comment]
Is it done?

**Comment by rdenarie** [comment]
Yes it is, thanks
