### ISSUE TITLE
fix: Apostrophe in group synchronized name block the display of processes.

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#1228]
**Steps to reproduce**

1. Steps to reproduce the behavior:
2. set some profile attributes as "group synchronized" exp: departement
3. create a process
4. user1 is included in the list "Who can manage the process" & Who can make a request (member in the mentionned space)
5. as user1 open your profile
6. click on edit icon from contact informations
7. in departement attribute type a text containing apostrophe and save
8. go to process app

**Current behaviour**

No process is displayed
message in console "Uncaught (in promise) Error: Response code indicates a server error

**Expected behavior**
The processes should be displayed

**Comment by srenault-meeds** [comment]
Hi, can you please categorize it?
- add a label
- add it in bug hunt project

**Comment by srenault-meeds** [comment]
cc @sofyenne

**Comment by srenault-meeds** [comment]
as no answer, I consider this as closed
