### ISSUE TITLE
[Navigation] Redirection business rules when accessing [domain name].meeds.io/ 

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1234]
**Is your feature request related to a problem? Please describe.**

When not logged in AND public site, and trying to access the site [domain name].meeds.io/ then it sends the user to /portal/login

**Describe the solution you'd like**

_if no public site (not made visible):_
- AND not logged in, any URL [domain name].meeds.io/ or [domain name].meeds.io/[...] sends the user to login page
- AND logged in, any URL [domain name].meeds.io/ or [domain name].meeds.io/[...] sends the user to /portal page

_if public site made visible:_
- AND not logged in, any URL [domain name].meeds.io/ or [domain name].meeds.io/[...] sends the user to public site
- AND logged in, any URL [domain name].meeds.io/ or [domain name].meeds.io/[...] sends the user to /portal page

**Comment by srenault-meeds** [comment]
@rdenarie here is a proposition to deal with redirection problems when accessing [domain name].meeds.io/
is there any conflict with what you guys are working on (sites navigation for example)?

**Comment by rdenarie** [comment]
Yes it seems ok for me

**Comment by srenault-meeds** [comment]
Thanks confirmed as considered.
