### ISSUE TITLE
[Navigation] Redirection business rules when accessing public site while not logged in

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1235]
**Is your feature request related to a problem? Please describe.**

When logged in AND site is not visible, and trying to access the public site /portal/public, then it sends a 403 error

**Describe the solution you'd like**

if public site not made visible AND logged in, /portal/public sends the user to the default site

**Comment by srenault-meeds** [comment]
@rdenarie here is a proposition to deal with 403 redirection when accessing public site while logged in.

is there any conflict with what you guys are working on (sites navigation for example)?

**Comment by rdenarie** [comment]
ok for me

**Comment by srenault-meeds** [comment]
Thanks. Confirmed as considered
