### ISSUE TITLE
Task - comments are not working

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#1242]
**Steps to reproduce**

1. create spaceX

2. on spaceX create task project ABC

3. on project ABC create task

4. open task comments drawer and close it or click on back arrow

5. open again task comments drawer

**Current behaviour**

Task comments can't be added.

**Expected behavior**

each time task comments drawer opened, task comments can be added.

**Comment by srenault-meeds** [comment]
Duplicated with https://github.com/Meeds-io/meeds/issues/1184
