### ISSUE TITLE
[People] [Spaces] Pagination is missing

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1243]
**Steps to reproduce**

No pagination (filter by netwok or not) in people or spaces pages

See screenshots
People
<img width="282" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/785b94ec-bb70-4e2b-b601-e2ad25083df5">

<img width="350" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/e5598da4-11d2-4029-a4ed-b34f8f92b4a9">

Spaces
<img width="335" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/97d758e1-76f7-46aa-8873-de5ec4b44c82">

**Comment by srenault-meeds** [comment]
hello @rdenarie @Jihed525 
I have noticed this. Have you observed this too?

cc @boubaker

**Comment by rdenarie** [comment]
Did you test on builders ?
I have correctly the see more button on my side :
People :
![image](https://github.com/Meeds-io/meeds/assets/807839/2ca255a3-4b6f-499f-8d2b-7a2c4226f095)

For spaces, there are only few ones (14 on your screen, 13 on my side), so there is no pagination

**Comment by srenault-meeds** [comment]
Well yes I have tested it on builders and it was not ok. and now this is ok -_-
Sorry, wrong alert...
I close the issue then
