### ISSUE TITLE
[Activity Composer] Problem when option post to network is set to false

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1273]
*Environment* : 1.5.x-SNAPSHOT
*Scenario* :

- Configure your platform with property : exo.feature.PostToNetwork.enabled=true
- Log in the platform
- Create a space
- In main activity stream (not space), click on ocmpose a message.
- In the drawer, you can select the audience :
  - to network
  - to a space
- Choose to a space, and select a space in the suggester
- The suggester is replaced by the space
- Now, disable the feature with the property exo.feature.PostToNetwork.enabled=false
- In main activity stream (not space), click on ocmpose a message.
- In the drawer, you cannot select the audience, you only have the suggester
- Select a space :

*Current Behaviour :*
the space is only added in the suggester, the behaviour is different than when the feature is activated

*Expected* : Consistant behaviour

**Comment by rdenarie** [comment]
Fixed

**Comment by rdenarie** [comment]
I reopen this issue.
The initial fix was reverted because it create problems to edit the activity.

Need to rework it

**Comment by Jihed525** [comment]
related exo task https://community.exoplatform.com/portal/dw/tasks/taskDetail/67423
