### ISSUE TITLE
[Notifications] Different colour buton between activty comment notification , and task comment notification

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1277]
In notifications, the color button for task comment notification and activity comment notification is different : 
![2023-11-13_11-22_1](https://github.com/Meeds-io/meeds/assets/807839/7b7bee4b-4602-4f80-8f70-64024348d0a2)
![2023-11-13_11-22](https://github.com/Meeds-io/meeds/assets/807839/442cbe43-7dc1-44bb-b793-d928bfe62e0c)

As you can see, both noitifications are unread, but one have white button, the other have a pale blue button.
We should align the 2 notifications

**Comment by srenault-meeds** [comment]
Hello, 
IMO, the expected is to have no background.

We'll take care of this.
Thanks

**Comment by srenault-meeds** [comment]
Fixed!
