### ISSUE TITLE
[Profile] "Send meeds token" randomly appear on some profiles

### ISSUE THREAD

**Issue by jeremi** [Meeds-io/meeds#129]
In some cases, when I navigate to a profile, the button is not there, and when I refresh it appears. Sometimes, the opposite happens (even after waiting 30sec).
![image](https://user-images.githubusercontent.com/9537/163721745-924f3e53-6b5e-4e99-a919-fcc37bcdc201.png)

![image](https://user-images.githubusercontent.com/9537/163721758-8a5df81c-735a-4be1-a52a-b61941776c53.png)

**Comment by srenault-meeds** [comment]
This option is not provided anymore from now on
