### ISSUE TITLE
[Notes] Wrong name for the editor page

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1294]
**Steps to reproduce**

1. Go to a space
2. From notes app, edit a notes page
3. See error: page name is = to public site

<img width="754" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/8295c489-39b5-4be1-bd73-2d60178ae76e">

**Expected behavior**

Page name for notes edition must be "Notes editor" as it was previously

**Comment by boubaker** [comment]
That's normal, the URL is `/portal/public`, the concern is that the notes editor has to open from `/public/meeds` instead, that's what to change in fact. (Global pages shouldn't be accessed from public site, thus we should move all global pages into dedicated Node navigation of its site)
