### ISSUE TITLE
Addition of expiry time for temporary tasks

### ISSUE THREAD

**Issue by UYOBONG** [Meeds-io/meeds#1321]
I understand that the community is developing and testing some features.

I'll suggest that we pay attention to tasks and the duration they are open.
An example is the Community call task, if there should be a call, submission to that task should be open for a period of 48-72 hours and then closed. This will help organize tasks and also not be misleading.

The same applies to every other task that is time-based.

**Comment by srenault-meeds** [comment]
You're right and this is already possible thanks to duration conditions.
Thanks for this feedback
