### ISSUE TITLE
Extra margin in the top of administration site

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#1325]
**Steps to reproduce**

1. Go to Administration Site
2. See extra margin in top site layer

![image](https://github.com/Meeds-io/meeds/assets/594824/3cfe664f-8863-4962-acb6-935d9ba6845b)

**Solution**

Delete extra margin defined in `.UIContainer.SimpleTableContainer`

**Comment by srenault-meeds** [comment]
Will be ok FYI @margondicco after merge and following deployment
