### ISSUE TITLE
Administration Menu is loaded at last 

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#1326]
**Steps to reproduce**

1. Go to any `meeds` page with an admin account
2. See loading effect of Cog icon to access administration site

**Current behavior**

A blink effect is observed in administration icon loading

**Expected behavior**

The administration icon should be loaded at the same time as other elements.

**Comment by srenault-meeds** [comment]
@boubaker I don't reproduce it even with a bad network emulator. Can you please share a screencast?

**Comment by srenault-meeds** [comment]
ok reproduced with a new fresh platform. thanks.
