### ISSUE TITLE
[Navigation] Vertical menu - bad alignment of items

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1330]
**Steps to reproduce**

1. Go to administration site
2. Check the vertical menu
3. See error: items are not aligned in a nice way

<img width="234" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/b937c7e1-0cd5-4dbd-9228-1369abf57b83">

**Expected behavior**

1. Each icon is centered aligned vertically so all icons are aligned the same way. Might be interesting to provide a "box" where icons can be added there so we make sure it is still well aligned no matter which icon is used
2. Each label is aligned to the left vertically with a minimum of 12px padding between the icon and the label

**Comment by azayati** [comment]
@srenault-meeds a part of this issue is already reported [here](https://community.exoplatform.com/portal/dw/tasks/taskDetail/67683) by @margondicco, can we complete that or create another one @margondicco with the second part ?

**Comment by srenault-meeds** [comment]
@azayati @margondicco 
When I check the task, I see it is about the horizontal alignment of the label and icon and not about the whole alignment of items.
So what do you plan to do?

**Comment by srenault-meeds** [comment]
And please @azayati where is the issue in github? We really need it so we avoid working on the same thing.

**Comment by azayati** [comment]
> And please @azayati where is the issue in github? We really need it so we avoid working on the same thing.

we haven't created yet a github issue for that, we will use this one since the first part mentioned in this github issue is the same as the one in the task

> When I check the task, I see it is about the horizontal alignment of the label and icon and not about the whole alignment of items.
> So what do you plan to do?

As I have said above, I have asked @margondicco to complete the task in order to match exactly with this github issue

**Comment by srenault-meeds** [comment]
Will be ok FYI @margondicco after merge and following deployment
