### ISSUE TITLE
[navigation] Wrong navigation in a space

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1334]
**Steps to reproduce**

1. Open the admin site, keep it opened
2. From the platform (other tab), go to a space
3. See error: navigation is wrongly displayed:
- we miss the topbar navigation
- we miss the left navigation
- the space menu is displayed below the banner

<img width="1277" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/d324a6f3-82df-4aca-a981-6033e33f5f8a">

**Expected behavior**

Expected navigation is proposed to the user

**Comment by azayati** [comment]
@srenault-meeds do you confirm that this problem occurs when opening the admin site then returning to the space navigation as mentioned in this [issue ](https://community.exoplatform.com/portal/dw/tasks/taskDetail/67454) ?

**Comment by srenault-meeds** [comment]
yes why?

**Comment by azayati** [comment]
> yes why?

just to not create another new github issue, can you just please update the scenario and mention that it occurs only when the admin site is opened at the same time in a second tab (same as the task) ?

**Comment by srenault-meeds** [comment]
Ok done. Thanks

**Comment by srenault-meeds** [comment]
@GouadriaHanen @azayati It seems you didn't check the status of the issue (doing). That means, that if not you, then we are on it.
Thus, no need to take more time on it.

**Comment by srenault-meeds** [comment]
Will be ok FYI @margondicco after merge and following deployment
