### ISSUE TITLE
[Notes] Not same font-color between edit and view mode

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1335]
**Steps to reproduce**

1. Go to a note
2. Add a note with different headers style
3. Save
4. See error: not same font-color is applied
<img width="1469" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/966f846d-458d-4efa-95b6-f211105ce203">

<img width="1465" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/4eb6418d-a171-4fdb-b514-1da9c2acec6f">

**Expected behavior**

Apply same font-color for both view -> --allPagesBaseTextColor: #20282c;

**Comment by Julien-Dubois-eXo** [comment]
This one is already identified and will be fixed during TC. It was identified when you were working on SNV so we decided to fix it after.

**Comment by srenault-meeds** [comment]
I don't see the relation with SNV but anyway, we will take care of it as it is already live on meeds platform.

**Comment by Julien-Dubois-eXo** [comment]
I have understood during our discussion to avoid working on Notes during you were working on SNV. 

That's the reason we tracked this item until the work on SNV was done and do it during the TC. As well as the add of the arrow next to the text color options.
