### ISSUE TITLE
Mobile app issue with several accounts

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#134]
I am using 3 differents servers:
-bonitameeds (sso)
-exotribe (login/passwd)
-meeds dao builders (login/passwd)

I have successfully used bonitameeds + exotribe in the same mobile app.
I tried to install daobuilders and I can connect OK but then the 2 previous ones do not work anymore and the crashes.
I can get it work if I unstall bonitameeds and install again.

**Comment by srenault-meeds** [comment]
As meeds does not provide any mobile app, you should report this to eXo support please @souillac
