### ISSUE TITLE
[Vertical menu] Left menu height and scroll UI / behaviour different

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1347]
**Steps to reproduce**

1. Go to admin site
2. Click on connectors for example
3. Scroll down to the bottom
4. See error: the vertical menu is "truncated" and this looks inconsistent with the left menu which takes the whole height of the page

<img width="1236" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/2b23ca3d-e68c-4b76-93a6-d48097a7ecef">

+

The scroll bar is not similar to the one used for the left menu

<img width="443" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/ad004e58-2069-4397-82a7-3d1dfe7be6b9">

Left menu
<img width="582" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/eb932c70-e7c9-4769-ac63-3c11cba6d2cf">

**Expected behavior**

Same UI: Whole height of the page is taken
Same behaviour: Same scroll bar style

**Comment by srenault-meeds** [comment]
Will be ok after next deployment

**Comment by srenault-meeds** [comment]
Backported? @rdenarie I don't see the label

**Comment by rdenarie** [comment]
There is no commit associated to this pr. So I dont know what to backport :)

**Comment by boubaker** [comment]
> There is no commit associated to this pr. So I dont know what to backport :)

No dedicated commit, included in another Menu rework commit https://github.com/Meeds-io/social/commit/9beeabdde3bad82d492992a489d8497b20ab7767#diff-099c42ff6a75d8fde27dddcd529c3495b6582865eff48a4fe8681092184dee80R36

**Comment by rdenarie** [comment]
Ok, this one is backported, as labelled on #1326
