### ISSUE TITLE
Combining several login mechanism in the mobile app requires to enter credentials everytime

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#135]
looks like if I use servers with both sso and login/pwd, sso is taking over and I must enter login/pwd again (one time looks enough)

**Comment by souillac** [comment]
not sure if this helps but maybe the wrong credentials are stored in cache, cf PJ. Note: I always entered the correct login/pwd
<img width="1003" alt="Capture d’écran 2022-04-21 à 15 13 14" src="https://user-images.githubusercontent.com/5012996/164465740-3471ce70-818d-48eb-96e6-3148fb7c6c8f.png">

**Comment by plamarque** [comment]
There's a new anti-brute force mechanism that misbehaves with MetaMask authentication plugin : A failed login attempts counter is not properly reset. A refactoring to handle the case is being worked on by  @rdenarie

**Comment by rdenarie** [comment]
Hello. The refactoring is now deployed, and the counter is properly reset. 
The misbehave with Metamask is ok now.

Have you still the problem of locked account ? 
Have you still the problem of entering login/pwd each time ?

**Comment by souillac** [comment]
Hello,

sounds like it is ok for now, will let you know if I experience something similar

**Comment by rdenarie** [comment]
Ok, thanks for your reply. I close the issue for now. Feel free to open a new one if you experience the problem
