### ISSUE TITLE
[Navigation] Create the "Contribute" & "My Craft" Site

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1351]
**Is your feature request related to a problem? Please describe.**
When accessing the platform, you are sent by default to overview page. Thus, you can access the navigation from the topbar to browse other related pages (actions, programs, achievements, perks). 
The problem is that when visiting a space, you cannot access directly the actions page. You need to go back to a "generic" page like overview, stream, etc. from the left menu

**Describe the solution you'd like**

Provide dedicated sites with proper navigation so the user can access directly a page from the left menu.
Organize pages in dedicated sites.

Thus, the left menu must propose the following organization:
1. Contribute
- Dedicated site /portal/contribute
- First node is Actions page (/portal/contribute or /portal/contribute/actions)
- Second nodes to actions one are: Programs, Perks

<img width="569" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/87393189-3247-4db4-9bcd-ad6ad050480e">

2. My Craft
- Dedicated site /portal/mycraft
- First node is Dashboard page (/portal/mycraft or /portal/mycraft/dashboard)
- Second nodes to Dashboard one are: Tasks, Achievements, Wallet
<img width="575" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/ef9573d4-b09b-4480-9cab-bf998f3c9d91">

3. Master site pages follow these first entries from the left menu:
- Stream
- People
- Spaces

<img width="289" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/bfe67ba9-10ba-4f84-aebe-562e2f82ab4b">

**Comment by azayati** [comment]
@srenault-meeds I think that the url of the site is /portal/engage and not /portal/contribute

**Comment by srenault-meeds** [comment]
Actually, as it is an enhancement we need to have in meeds package, I've been asked to change the name of the site from "engage" to "contribute".
So updating the link to make sure it is compliant with the name would be better.
Now, if that goes against your will, ok for me.

**Comment by srenault-meeds** [comment]
-- 
@margondicco I let you check if this issue is ok for you

**Comment by margondicco** [comment]
OK it seems good

**Comment by plamarque** [comment]
@srenault-meeds  Perk**s** (plural)

**Comment by azayati** [comment]
> Now, if that goes against your will, ok for me.

I thought that you will take exactly what it is existing now, no problem for me since it is an enhancement.

**Comment by srenault-meeds** [comment]
> @srenault-meeds Perk**s** (plural)

yes indeed, ok in the task
Will review the label in the image

**Comment by boubaker** [comment]
PRs:
* https://github.com/Meeds-io/gatein-portal/pull/765
* https://github.com/Meeds-io/platform-ui/pull/722
* https://github.com/Meeds-io/social/pull/3267
* https://github.com/Meeds-io/gamification/pull/1368
* https://github.com/Meeds-io/kudos/pull/441
* https://github.com/Meeds-io/perk-store/pull/304
* https://github.com/Meeds-io/notes/pull/896
* https://github.com/Meeds-io/poll/pull/123
* https://github.com/Meeds-io/task/pull/327
* https://github.com/Meeds-io/meeds/pull/1387
* https://github.com/Meeds-io/meeds-qa-ui/pull/226

**Comment by rdenarie** [comment]
Hi. As I can see, the layout for sites engage and contribute were not reused.

We defined it here : 

- https://github.com/exoplatform/digital-workplace/blob/develop/digital-workplace-webapps/src/main/webapp/WEB-INF/conf/digital-workplace/portal/engage/portal.xml
- https://github.com/exoplatform/digital-workplace/blob/develop/digital-workplace-webapps/src/main/webapp/WEB-INF/conf/digital-workplace/portal/mycraft/portal.xml

I understand that for meeds, theses sites are "aggregated" so their site layout will be not visible, and meed do not provide the possibility to switch from aggregated to standalone.

In addition, in the site layout we defined, the portlet SiteNavigation is present, and not available in meeds context.

So, what are the possibilities to keep theses layouts for theses sites on exoplatform side ?


cc @margondicco

**Comment by boubaker** [comment]
> Hi. As I can see, the layout for sites engage and contribute were not reused.
> 
> We defined it here :
> 
> * https://github.com/exoplatform/digital-workplace/blob/develop/digital-workplace-webapps/src/main/webapp/WEB-INF/conf/digital-workplace/portal/engage/portal.xml
> * https://github.com/exoplatform/digital-workplace/blob/develop/digital-workplace-webapps/src/main/webapp/WEB-INF/conf/digital-workplace/portal/mycraft/portal.xml
> 
> I understand that for meeds, theses sites are "aggregated" so their site layout will be not visible, and meed do not provide the possibility to switch from aggregated to standalone.

It has ben reused, see the PR on digital-workplace
https://github.com/exoplatform/digital-workplace/pull/95/files
* https://github.com/exoplatform/digital-workplace/pull/95/files#diff-78b4aa25738b193b232e851373a973892034096ef3558165ee70db9c25108b4f
* https://github.com/exoplatform/digital-workplace/pull/95/files#diff-9719514f850806f86b57b3efded17152ad0e916c231e7f8bde2c4dfbbeb212f3

![image](https://github.com/Meeds-io/meeds/assets/594824/8fb410a7-4f28-47c4-b905-25430f842fe4)

**Comment by rdenarie** [comment]
Ok, didnt catch that. Thanks for the precision

cc @margondicco @azayati

**Comment by rdenarie** [comment]
@boubaker when checking on https://exo-mips-ft.meeds.io/portal/contribute
The contribute site is set to standalone, but the site layout is not displayed.
Same for mycraft : https://exo-mips-ft.meeds.io/portal/mycraft

**Comment by azayati** [comment]
hello, I have tested the mips server locally, with empty data and after upgrade from an old version, the eXo nodes of mycraft site (drives, process, agenda) are not displayed
![image](https://github.com/Meeds-io/meeds/assets/1579929/4ca94634-b308-4b02-8f21-eb3c4b3c967b)

VS

![image](https://github.com/Meeds-io/meeds/assets/1579929/69788c58-bfc0-4aaf-9db5-4f1f5e11464c)

**Comment by boubaker** [comment]
> hello, I have tested the mips server locally, with empty data and after upgrade from an old version, the eXo nodes of mycraft site (drives, process, agenda) are not displayed

Yes, extension mechanism priority not set on `digital-workplace` (it must be set more prioritized than `sites.war` extension)
I 'll add it, thanks.

**Comment by azayati** [comment]
> Yes, extension mechanism priority not set on digital-workplace (it must be set more prioritized than sites.war extension)
> I 'll add it, thanks.

Thanks @boubaker effectively I have thought about that and I have set locally digital-workplace priority to 400 (more than the 200 of sites extension), I let you see from your side, I will test again.

**Comment by boubaker** [comment]
> > hello, I have tested the mips server locally, with empty data and after upgrade from an old version, the eXo nodes of mycraft site (drives, process, agenda) are not displayed
> 
> Yes, extension mechanism priority not set on `digital-workplace` (it must be set more prioritized than `sites.war` extension) I 'll add it, thanks.

Done.

> Thanks @boubaker effectively I have thought about that and I have set locally digital-workplace priority to 400 (more than the 300 of sites extension), I let you see from your side, I will test again.

In fact `sites.war` is using `200` as priority, see it here https://github.com/Meeds-io/meeds/blob/develop/webapps/plf-sites-extension/src/main/webapp/META-INF/exo-conf/configuration.xml#L34

**Comment by boubaker** [comment]
> @boubaker when checking on https://exo-mips-ft.meeds.io/portal/contribute

Same, fixed by the increased priority of `digital-workplace` extension @rdenarie

**Comment by azayati** [comment]
@boubaker I have tested, it seems good now, thanks

**Comment by boubaker** [comment]
> @boubaker I have tested, it seems good now, thanks

Thanks, I will tell you when it's merged to develop to let you merge the PR of digital-worplace when you're ready.

**Comment by boubaker** [comment]
> > @boubaker I have tested, it seems good now, thanks
> 
> Thanks, I will tell you when it's merged to develop to let you merge the PR of digital-worplace when you're ready.

Merged to develop.
