### ISSUE TITLE
Auto suggest using @ or in space invitations is slow and buggy

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#137]
It happens on every kind of posts (activity, comment) and also when you create a space and invite people.
If you go fast and use the keyboard for the next autosuggest right after validating the previous one by clic, then the first 2 characters are "lost" and autosuggestion is not suggesting the right values

**Comment by srenault-meeds** [comment]
Fixed now and will be available with the 1.4 version of the meeds software.
What we have done is the following:

- Start searching only when the user stops writing content
- Display a label "Search in progress" when it is searching
- Display "Not found" when the user cannot be found (not in the space for example)
