### ISSUE TITLE
[Applications] Update of application setup: No default application anymore

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1371]
**Is your feature request related to a problem? Please describe.**
End-users send feedbacks regarding the application center arguing that mandatory / default apps are not useful and it would be more interesting to have only apps the user decides to bookmark as "favorite"

**Describe the solution you'd like**
Remove mandatory status to any app and keep it as available for the user

<img width="655" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/7ca90af2-15ca-40a9-af9e-4c2b385be562">

**Comment by srenault-meeds** [comment]
@margondicco FYI
And we will add a placeholder when not having apps selected yet

**Comment by margondicco** [comment]
Great
