### ISSUE TITLE
Auto suggest is not working anymore

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#138]
Using the @ sign does not open suggestions, cf attach

https://user-images.githubusercontent.com/5012996/166420712-c819a3fa-8d77-4fb1-933d-880e065a270b.mov

ed video

**Comment by srenault-meeds** [comment]
Hi @souillac, do you still face this issue, please?
If so, does the user you want to mention is member of the space from which the message is written?
Thanks

**Comment by srenault-meeds** [comment]
Not reproduced in the 1.4 version.
Should be fixed with the impv done on the @ option (search in progress label, search started once the user stops writing, etc.)
