### ISSUE TITLE
[Navigation] Improve images rendering of contribute - mycraft sites 

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1386]
**Is your feature request related to a problem? Please describe.**
Images added for my craft and contribute sites looks too small with low resolution

**Describe the solution you'd like**
Add better resolution images

**Comment by srenault-meeds** [comment]
Will be improved at the next deployment

**Comment by rdenarie** [comment]
Hello. @boubaker what is the pr of this issue ?
I shoud consider it for backport

**Comment by boubaker** [comment]
> Hello. @boubaker what is the pr of this issue ?
> I shoud consider it for backport

To backport where to eXo ? I don't pay attention to internal processes for eXo, I let you make the followup.

**Comment by rdenarie** [comment]
Commits integrated in meeds-io/meeds-1387.
No need to backport
