### ISSUE TITLE
[Navigation] Radius applied to notif drawer

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1405]
**Steps to reproduce**

1. from branding option, apply a radius of 20px
2. from the platform, open the notification drawer
3. See error: the notif drawer gets the radius applied to it

<img width="226" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/234a2e33-cded-4b04-8914-8df920f142c9">

**Expected behavior**

No radius applied to notif drawer
AND radius well applied to notif center when expanding the drawer

**Comment by rdenarie** [comment]
@boubaker Does this one is fixed by another issue/mip ?

**Comment by srenault-meeds** [comment]
If I can help, I'd say this one but not sure: https://github.com/Meeds-io/social/pull/3288/commits/1456c2cdc4d1617f0505fda62374e7f5dc18edfe

**Comment by boubaker** [comment]
> If I can help, I'd say this one but not sure: [Meeds-io/social@1456c2c](https://github.com/Meeds-io/social/commit/1456c2cdc4d1617f0505fda62374e7f5dc18edfe)

Yes, https://github.com/Meeds-io/social/commit/1456c2cdc4d1617f0505fda62374e7f5dc18edfe#diff-84a75862154478ada8d320decdeee24bd58ce28c88125fe425a4533c9c3a6886L92-R96

**Comment by rdenarie** [comment]
So it is backported
