### ISSUE TITLE
[PFR] [Notifications] Mark the unread notification as read if its link is opened from Right click contextual menu

### ISSUE THREAD

**Issue by sirinebenabbes** [Meeds-io/meeds#1406]
**Current behavior**

In full screen notification center, when right clicking on an unread notification, the contextual menu opens and the notification is marked as read before opening its link.

**Suggestion**
On right click, the notification should be marked as read only if one of the options **'open link'** is clicked

[right click on unread notification.webm](https://github.com/Meeds-io/meeds/assets/75303292/d1bb9b6a-b5f2-4a35-88cc-015b1cad21e8)

**Comment by srenault-meeds** [comment]
Done with https://github.com/Meeds-io/meeds/issues/1404#event-11150342325
