### ISSUE TITLE
[Contributions] Challenge announce message not update user's name after profile update.

### ISSUE THREAD

**Issue by uocnb** [Meeds-io/meeds#142]
**Describe the bug**
Challenge announce message keep old name instead of current user's profile name.

**To Reproduce**
1. Go to 'Challenges'
2. Click on 'Announce'
3. Go to 'Profile'
4. Update 'Full name'
5. See old 'Full name' in the challenge announce message.

**Expected behavior**
User's profile in the challenge announce message should be updated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 101.0.4951.67 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by srenault-meeds** [comment]
Should be fixed in next deployment

**Comment by srenault-meeds** [comment]
I reopen it as now we have a regression for other activities.
Check screenshot: 

<img width="899" alt="image" src="https://user-images.githubusercontent.com/58853195/217491246-e082570c-0017-42d2-9f71-22a16d455caf.png">

**Comment by srenault-meeds** [comment]
Ok fixed actually now. Thanks
