### ISSUE TITLE
[Snackbar] Cannot remove a snackbar anymore

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1425]
**Steps to reproduce**

1. Go to a stream with unread notif
2. Filter by unread 
3. Mark as read
4. a snackbar is displayed
5. See error: when clicking to cross icon to close the snackbar, it is not working. 

Tried with other snackbar and same behaviour (tasks for example, actions)

**Expected behavior**

When clicking to the snackbar close option, then the snackbar is closed

**Comment by Jihed525** [comment]
eXo related issue https://community.exoplatform.com/portal/dw/tasks/taskDetail/68048

**Comment by srenault-meeds** [comment]
Thanks @Jihed525 tell us please when doing. Thanks

**Comment by Jihed525** [comment]
@srenault-meeds fixed by @akhanfir and validated 
backport PRs are on the way

**Comment by Jihed525** [comment]
MErged & backported

**Comment by srenault-meeds** [comment]
ok. Thanks. You can close it if needed once it is done for you (merged to develop and fixed)
