### ISSUE TITLE
Actions of CKeditor is task's description field do not work

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#143]
**Describe the bug**
Actions of CKeditor is task's description field do not work

**To Reproduce**
1. Go to Tasks app > Select a project
2. Click to create a task (either through the +icon or through the + Add task button)
3. Fill in the title, Description
4. Select some text from the description and click on one of the toolbar actions (Bold, Italic, bulleted list,...)

**Current behavior**
The description field leaves the edit mode and the selected text is not formatted according to the selected action

**Expected behavior**
The description field should remain in the edit mode and the selected text should be formatted

Related task https://builders.meeds.io/portal/g/:spaces:developers/developers/tasks/taskDetail/118

**Comment by srenault-meeds** [comment]
Cannot reproduce it. Did you use the keyboard to reproduce this?

**Comment by srenault-meeds** [comment]
Seems to be fixed as cannot reproduce it. Thanks
