### ISSUE TITLE
[App Center] fix : Addressing XSS Vulnerability in App Center

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#1441]
**Steps to reproduce**

Create an application using the API tool with an incorrect URL or Help URL format containing a JavaScript alert.

**Current behaviour**

Clicking on the created application triggers the display of a JavaScript alert

**Expected behavior**

Application URL and application help URL should be sanitized

**Comment by Jihed525** [comment]
validated - merged & backported
@srenault-meeds do you allow me to close or leave it to you ?

**Comment by srenault-meeds** [comment]
ok. Thanks. You can close it if needed once it is done for you (merged to develop and fixed). I close this one. Next time, do it at your convenience
