### ISSUE TITLE
[User creation] Problem when creating a user with rest service

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1447]
**Steps to reproduce**

1. With a curl script or postman create a user by rest service using /portal/rest/v1/users
2. in POST body, use 
```
{
  "email": "john8.smith@acme.com",
  "firstName": "John8",
  "lastName": "Smith8",
  "password": "Password1234",
  "userName": "jsmith8"
}
```
Do not set "enabled":true

**(optional) Affected version**

Indicate the version where the bug is observed.
meeds-1.6.0-231211

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.
The user is create, but not visible in user management. When looking in database, the object in table jbid_io is create with enabled=true, but the object in SOC_IDENTITY is created with enabled = false :
![image](https://github.com/Meeds-io/meeds/assets/807839/f714279e-a943-4a78-b3ac-206409608b2c)

**Expected behavior**

If enabled is not set, user is created as enable in all the platform

**Comment by boubaker** [comment]
I wasn't able to reproduce on develop nor develop-meed using query:

```javascript
fetch("/portal/rest/v1/users", {
  "headers": {
    "content-type": "application/json",
  },
  "body": JSON.stringify({
    "userName":"testuser",
    "firstName": "Test",
    "lastName": "User",
    "email":"testuser@localhost.com",
    "password":"Test1234@",
    "confirmNewPassword":"Test1234@",
  }),
  "method": "POST",
  "credentials": "include"
})
```

In fact, when not using `enabled: true`, the created user will be disabled by default.

**Comment by rdenarie** [comment]
In fact, this point is ok.

The fact that the search does not work with disabled filter makes me wrong.
I close
