### ISSUE TITLE
GitHub PR informations related to wrong task in meeds builder community

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#145]
**Describe the bug**
I have noticed that some tasks get comments from the github connector in the builders community's task board "Deeds App UX Backlog" 
Unfortunately, it seems that this PR in github has no relation at all with the task in the backlog.
Check this task for example: https://builders.meeds.io/portal/meeds/tasks/taskDetail/59

**Expected behavior**
Only github PR related to the task should be linked to this task.
We need to check why this bug occurs.

**Comment by plamarque** [comment]
I believe it's because the PR comment contains '#66' which is also the ID of the task in builders.
isn't it @hbenali ?

**Comment by hbenali** [comment]
Yes it is

**Comment by hbenali** [comment]
I've added an improvement to avoid as possible such kind issues.
https://github.com/Meeds-io/meeds/commit/d9196ce9ff4e2671cfd3f62a6d0efc8505b22e86

**Comment by srenault-meeds** [comment]
Yes, seems ok now thanks
