### ISSUE TITLE
Add expand option to activity composer drawer

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#1466]
For more UX consistency and when we have an activity with a long text + many options like (send kudos + create a poll + write an article + ...) I think it's better to have the expand option to read all the drawer content in a full display.

**Comment by srenault-meeds** [comment]
Hi @SaraBoutej 

Can you please describe more this feedback?
Indeed, I would like to hear from you what the problem is and how expanding the drawer would be helpful.

Thanks

**Comment by SaraBoutej** [comment]
> Can you please describe more this feedback? Indeed, I would like to hear from you what the problem is and how expanding the drawer would be helpful.

done cc @srenault-meeds
