### ISSUE TITLE
Analysing the Meeds Builders Contribution Point on Spreadsheet

### ISSUE THREAD

**Issue by UYOBONG** [Meeds-io/meeds#1468]
I just analyzed the contributor's sheet and I realized there are only datasets of Comments, Likes, and Kudos.

Please update it to hold datasets of all the activities such as Medium post, Tweets etc for a transparent analysis

**Comment by srenault-meeds** [comment]
Hi, 
Indeed, this is a bug being fixed.
Thanks for this feedback!

**Comment by srenault-meeds** [comment]
Ok now @UYOBONG  ;-)
