### ISSUE TITLE
Chat icon doesn't appear

### ISSUE THREAD

**Issue by MayTekayaa** [Meeds-io/meeds#147]
**Describe the bug**
When i opened my personal account in builders app, the chat icon is missed.

**To Reproduce**
1. Go to the link of builders app: https://builders.meeds.io/portal/meeds.

**Expected behavior**
The chat icon must be displayed in the navBar in the top next to notifications icon.

**Screenshots**
![Screenshot from 2022-05-19 07-56-46](https://user-images.githubusercontent.com/100131287/169231280-149fb650-b85e-490c-8eda-37253639e59e.png)

**Comment by plamarque** [comment]
There is no chat app in Meeds software.
