### ISSUE TITLE
Need for daily tweet on the official twitter handle of meeds to be posted daily 

### ISSUE THREAD

**Issue by kuvaMan** [Meeds-io/meeds#1477]
the meeds task have been updated and it on daily to boost one of the post the official post daily 

solution , content should be posted on a daily by the team , for the users to be able to boost and promote meeds .

**Comment by srenault-meeds** [comment]
Hi @kuvaMan 

Do you mean that this action should be proposed each time a new tweet is posted instead of a generic one?
Thanks.

cc @plamarque FYI

**Comment by plamarque** [comment]
@srenault-meeds This is not a feature request. This is a request for tweeting more content :-)

@kuvaMan to busy reviewing other contributions to tweet ;-)

**Comment by kuvaMan** [comment]
Am proposing for a daily tweet for users to have what to retweet, remember
it part of our task to boost the Tweeter handle
