### ISSUE TITLE
Mobile app stream does not display replies / comments on the first element of the stream

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#148]
It looks like a very specific bug related to the "limits" (limit = 1).

When I open eXo tribe using the mobile app, the first activity only displays the original activity message and not the replies. The activity also does not dusplay the meta information displayed on others such "xx comments" even if there are comments.

On the following stream elements, this is different, we can see comments normally.

As I cannot "open" the activity by selecting it, I'm stuck using mobile for this activity

**Comment by souillac** [comment]
Update: using a different space, I have the same issue on activities not being the first one only, looks like it depends on each activity

**Comment by srenault-meeds** [comment]
As meeds software does not propose a mobile app, this should be raised to eXo support. Thanks
