### ISSUE TITLE
reversed image for posted image in stream of space

### ISSUE THREAD

**Issue by hthabti** [Meeds-io/meeds#1487]
steps:
using a smart phone, in a vertical position capture a photo (mobile not held horizontally)
connect to plf
post the captured image as short message in spacex
check preview

actual:
the image is reversed

expected:
preview image should be well displayed

**Comment by srenault-meeds** [comment]
@hthabti thanks. This is duplicated. https://github.com/Meeds-io/meeds/issues/1126 
We have talked about it with @rdenarie changes are needed to the thumbnail service

And BTW, it is not reproduced with any smartphone. It is related to metadata created by the camera tool.

cc @Jihed525

**Comment by Jihed525** [comment]
thanks for the reminder @srenault-meeds 
I knew it was an already ongoing subject yet I lost the links
My bad sorry

**Comment by Jihed525** [comment]
fyi @hthabti
