### ISSUE TITLE
"Comment an activity stream"  does not work anymore on mobile

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#149]
When I choose "comment" on an activity stream on eXo tribe using mobile, the "drawer is displayed" but the input text area is not displayed and not active thus. I cannot write any comment then.

**Comment by srenault-meeds** [comment]
Hi, can you please confirm me the following characteristics?
- Device
- OS Version 
- App version

Thanks!

**Comment by souillac** [comment]
iPhone 15.4.1
Don't know where to find the app version

**Comment by plamarque** [comment]
meeds does not have a mobile app (yet). This should be raised to eXo support.

**Comment by srenault-meeds** [comment]
As meeds does not provide a mobile app, this should be raised to eXo support. So I close this issue here.
