### ISSUE TITLE
anchor disappear in notes app for accentuated chars

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#1495]
**Steps to reproduce**

1. create/ edit note1 or article1

2. add some lines in the body

3. select a text click on anchor icon in ckeditor

4. in Anchor Name type text containing accents (é or è)

5. save note/news

6. edit note/news

7. check previous anchor

**Current behaviour**

anchor containing accentuated chars disappear

**Expected behavior**

anchors are well displayed

**Comment by Humblespino** [comment]
**Code** well fixed. Anchor now displayed well
