### ISSUE TITLE
[CKEDITOR] title 3 color is different

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#1500]
steps
Create a note
Add a title
Define it as title 3
actual
In the editor, the title 3 is in blue by default. If you save the note, it has the good color
expected
The title 3 should has the same color as the other title.

eXo Task : https://community.exoplatform.com/portal/dw/tasks/taskDetail/68247

**Comment by srenault-meeds** [comment]
FYI don't know why but wasn't reproduced on meeds

**Comment by srenault-meeds** [comment]
Hi, is that ok?
