### ISSUE TITLE
[Images] Images or GIF attached to richeditor not listed

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1506]
**Steps to reproduce**

Case 1
1. Attach images to a message using activity composer
2. Post the message
3. See error: message is posted but the image is not listed

OK when editing the activity or when commenting

Case 2
1. Attach GIF to a message using activity composer
2. Post the message
3. See error: GIF is not listed even when editing the activity.
4. See error: Same behaviour when commenting, when describing a task, etc.

Case 3
1. Attach images to a task description
2. Edit the task description
3. Add new images
4. See error: New images attached are not listed. Only initial ones are listed

**Expected behavior**

When attaching images no matter the type, the images are listed as expected.

**(optional) Affected environments**  
1.6.x

**Comment by rdenarie** [comment]
No need to backport as it is related to Tomcat 10 modifications
