### ISSUE TITLE
Trending Meeds on Facebook 

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1508]
Hello, good morning, I'll like to suggest meeds to add a task that enables an individual to post its contents on **Facebook**.

This will bring awareness to many users as more people make good use of Facebook often and browse it randomly.

Creating awareness on Facebook will help boost, expand meeds range. It will also open a part for many people, groups to invest in meeds 

Thanks.

**Comment by srenault-meeds** [comment]
Duplication with https://github.com/Meeds-io/meeds/issues/1525 I think.
