### ISSUE TITLE
[Space management] join request "lost" when we change the host

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#151]
Here is the flow:
- I have created a space with "validation" right settings
- I invited someone to be manager: manager
- someone asked to join requester (different from manager)
- I promoted manager as "host"
- I downgraded myself to "normal" user and left the space
- In the meantime I received the "request" from request
- I clic "accept" but nothing happens as I don't have the rights anymore
- manager is the new host but he did not receive the request as he was not host at the time the request was done

=> no way for manager to accept the invitation neither to invite again

I have asked manager to promote me again and then I went back to my notifications to get it working

**Comment by srenault-meeds** [comment]
Can't reproduce it. To be studied
cc @Imenmakni

**Comment by srenault-meeds** [comment]
@Imenmakni I can't reproduce it. Can you please tell me if you reproduce it?
Thanks
