### ISSUE TITLE
Questions and Answers Task on Meeds

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1510]
Greetings great team. So far the platform have been a wonderful and inspiring site for people to learn and earn while growing and also in acquiring knowledge.
What I'll suggest for the team to add as a task is the Questions and Answers session task that can come up twice in a week whereby questions will be asked randomly on the globe and an individual provides answer to it base on his or her experience.
Thanks.

**Comment by srenault-meeds** [comment]
Looks like it is related to community FAQ. It might be interesting to use the dedicated channel for it in the discord server. 
So I close it. 
Thanks
