### ISSUE TITLE
Building up on Discord

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1512]
Hi great team, the works on meeds is extremely great and of a high value. What I'll love to suggest today is building up members and making the channel to be active on discord channel. At the looks of things over there the general channel is not really booming and discussions of topics is not really been carried out. I'll suggest the team to add some interesting channels like educative game channels such as trivia etc., And in some basis competitions should be set and announced. This will make members to learn and have fun thereby boosting the greet name of meeds. 
Thank you.

**Comment by srenault-meeds** [comment]
Hi, 
I suggest you propose this on discord server. That way, other community members can interact with this proposition.
