### ISSUE TITLE
Meeds Twitter Trending 

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1515]
Good evening great team, what I'll love to suggest is a new way of trending meeds token on Twitter. I believe if banners, links and twitter site of meeds are being shill repeatedly it will bring more knowledge to people. Thanks

**Comment by srenault-meeds** [comment]
Hi @Humblespino

Thanks for your proposition. It seems that it is more related to community management. Thus, I recommend you to post this kind of message in the Discord server to engage a conversation with other members.
Here indeed, this is more about features and product feedbacks.

cc @plamarque

**Comment by Humblespino** [comment]
Alright, I'll do so
