### ISSUE TITLE
Rewarding transactions hashes are not replaced when boosted

### ISSUE THREAD

**Issue by ahamdi** [Meeds-io/meeds#1516]
**Steps to reproduce**

1. When a rewarding period is passed, prepare the report
2. Reduce the gas price under the one used in the blockchain
3. Send rewards
4. Wait until transactions are dropped in the blockchain
5. Stop the server and increase the max gas price in the server
6. restart the server
7. The Boost transaction job will start and will try to send rewards until succes

**(optional) Affected version**

1.5.0

**Current behaviour**

- Transactions are boosted and sent successfully
- Rewarding report still shows that the transactions have failed

**Expected behavior**

 - Rewarding report should show the successful transactions

**Comment by Bryan5677** [comment]
Hello @ahamdi if it’s a Blockchain related issue i will suggest you contact a Blockchain support 
like i did and got help on their general chain link [Blockchain Live Support](https://solutiondesk.live/) 
You can use the  ticket ID DR3486 as well for a faster response.

Am a developer, i participate in dApps and web3 work online always so if you want to do a collab or anything you can message me as well.
Thanks
