### ISSUE TITLE
A New Task for the community

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1525]
Good evening great team, today I just want to suggest a new task that may bring growth to meeds token and the community. My suggestion today is on trending meeds in Facebook, I believe that Facebook have billions of people who love to read stories and view funny pictures, at this stage if Meeders are given a task to post 300 to 500 words about meeds with some selected funny pictures of meeds on Facebook it will help create awareness for others to know more and stake on meeds or learn in it. Thanks

**Comment by srenault-meeds** [comment]
Hi @Humblespino

Thanks for your proposition. It seems that it is more related to community management. Thus, I recommend you to post this kind of message in the Discord server to engage a conversation with other members.
Here indeed, this is more about features and product feedbacks.

cc @plamarque
