### ISSUE TITLE
New Task

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1530]
Greetings capable and knowledgeable team. My suggestion for today is on how to improve other platforms in respect to meeds trending. I believe if the team  can create a TikTok funny videos weekly and the videos are given to the members to be posted. it will expand the range of meeds and widen the capacity to other globes. Thanks

**Comment by srenault-meeds** [comment]
Hi @Humblespino 

Thanks for your proposition. It seems that it is more related to community management. Thus, I recommend you to post this kind of message in the Discord server to engage a conversation with other members.
Here indeed, this is more about features and product feedbacks.

cc @plamarque
