### ISSUE TITLE
Interactive learning and live events 

### ISSUE THREAD

**Issue by kuvaMan** [Meeds-io/meeds#1531]
Dear meeds.io Team,

I hope this message finds you well. I am an enthusiastic user of meeds.io and have been actively engaging with the platform in the evolving Web 3 crypto space. Firstly, I want to commend your team on creating a dynamic and community-driven environment. However, I'd like to offer a suggestion to further enhance user engagement and experience.
Interactive Learning Resources:
Develop interactive learning resources that cater to users at various levels of expertise. Video tutorials, quizzes, or interactive workshops can make it easier for users to understand the platform's functionalities and encourage wider participation.

Live Events and Webinars:
Organize live events and webinars to create a real-time connection between the community and the platform. This can include AMAs (Ask Me Anything) sessions with key team members, expert panels, or discussions on the latest trends in the Web 3 space. Live interactions can enhance community bonding and provide valuable insights.

**Comment by srenault-meeds** [comment]
Hi @kuvaMan 

Thanks for your proposition. It seems that it is more related to community management. Thus, I recommend you to post this kind of message in the Discord server to engage a conversation with other members.
Here indeed, this is more about features and product feedbacks.

cc @plamarque

**Comment by plamarque** [comment]
Yes, thanks for the suggestions. I like them.. actually we started user guide docs,  quick video tutorials and we've community calls now. 
I agree we could develop more resources and initiatives over time. And maybe we can discuss some during next call on Friday @kuvaMan . 

Discord is or the Meeds Builders Hub are probably better places to discuss such community improvement ideas.

On GitHub, we'll rather track software related issues.
