### ISSUE TITLE
SNV - Radius missing

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1536]
**Steps to reproduce**

1. Add an SNV to a page
2. Click on 'Edit'
3. Add a some content
4. Save
5. See error

https://github.com/Meeds-io/meeds/assets/105866381/d19b3088-9334-41e7-8121-37d1ed989972

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

In edition, the container is not similar as the view mode. It's bigger and the corner are not the same. The edit options make it higher but it makes it difficult to correctly align the element in a page as we don't know the bottom limit

**Expected behavior**

In edition and view mode the container should have the same height, the edit option should not change the height of the container. Maybe the edit option should be in a top bar that is displayed with a hovering-over effect to display it. Another idea is an option to hide the edition options but we can still edit the content. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Hello, 
ok for radius, this has to be fixed.
Regarding the topbar, Nogo for now. Indeed, this would mean that we enhance the way editors are displayed when writing an activity for example, etc. And this is enhancement so different concern.

**Comment by srenault-meeds** [comment]
I changes the title accordingly
