### ISSUE TITLE
SNV - UI issue in the action menu

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1537]
**Steps to reproduce**

1. Go to a page with an SNV
2. Click on the 3 dots
3. See error

https://github.com/Meeds-io/meeds/assets/105866381/5ab73b21-4e72-48a0-85cb-fdfb1ffd9fc0

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The icons and the text of the actions are not aligned

**Expected behavior**
The icon and the text are aligned

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Hi, 
Looks like something we need to generalize. But not sure it is related to SNV.
@boubaker can you confirm please?

**Comment by boubaker** [comment]
This is due to specific CSS in eXo side, see attached screenshot

![image](https://github.com/Meeds-io/meeds/assets/594824/418b4240-f768-4c7e-8c99-d96a8cc80705)

**Comment by srenault-meeds** [comment]
Ok indeed. Thanks @boubaker 
So rejected @Julien-Dubois-eXo FYI

I let you take care of this feedback
