### ISSUE TITLE
Action publisher earns points for every submission

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#1543]
**Is your feature request related to a problem? Please describe.**

On Builders the action "[Spark a Discussion](https://builders.meeds.io/portal/contribute/contributions/actions/121)"  corresponds to "your post has been replied by peers".

When you publish a new action on the stream, you are the author of a post on the stream on which easy contribution submission will be added as a comment.

As a consequence, it will trigger the event every time and so the action publisher will earn a lot of points. It feels unjustified and unfair to earn forever passively.

The workaround is to disable or reduce the action, but it's not optimal because we may still want to reward real authors sparking new discussions.

**Describe the solution you'd like**
I think the announcement activities should not be done on behalf of a specific user, but maybe just on behalf of the space.

**Describe alternatives you've considered**
Alternatively, we could avoid triggering the event for this particular type of comment.

**Additional context**

Example of excessive earnings on my own account : 
![Screenshot 2024-01-16 at 10 05 35](https://github.com/Meeds-io/meeds/assets/227828/8d626961-8e18-44a9-a2cb-00433a37fd85)

**Comment by srenault-meeds** [comment]
Good one indeed! 
I suggest to not consider announcements as comments to avoid any confusion. And BTW the announcement is already rewarded.
Thus that would mean that:
- the announcer won't receive points as comment of an activity for announcing something
- the action publisher won't receive points as comment of an activity for any new announcement
BUT
- any other comment would be rewarded
WDYT?

**Comment by plamarque** [comment]
LGTM
