### ISSUE TITLE
Stream - The color of the thumbnail when mentionning is not the primary

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1547]
**Steps to reproduce**

1. Change the default primary color
2. Make a post and mention someone
3. See error

![Capture d'écran 2024-01-17 122317](https://github.com/Meeds-io/meeds/assets/105866381/ab7b7ec7-a779-4927-a938-c87cfe788941)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The color of the user thumbnail is always the same no matter the primary color. It seems that it's the primary color of Meeds platform that is hard coded.

**Expected behavior**

The color of the user thumbnail should be the primary color

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
ok we take care of it. Thanks
