### ISSUE TITLE
Zero balance in wallet

### ISSUE THREAD

**Issue by Bigemaa** [Meeds-io/meeds#1552]
I am yet to withdraw from my wallet but the balance I am seeing now is 0
![Meeds](https://github.com/Meeds-io/meeds/assets/156846993/3ab00688-34a3-4336-b8a4-4c6f38e22ba5)

**Comment by boubaker** [comment]
Hello,

In fact, it seems that [you 've received the rewards of last week](https://polygonscan.com/token/0x6aca77cf3bab0c4e8210a09b57b07854a995289a?a=0xdea9c61da7a382e4d7c0be81e61fd13d82bc6e5d) but you changed your wallet (using Metamask) on which you want to receive the rewards of this week.
We send the **rewards weekly**, thus, you will get the rewards of **current** week on your newly associated wallet address **next week**.

I hope this helps.
Thanks for the feedback.

**Comment by Bigemaa** [comment]
Yes, This means If I switch to the Main wallet, I will be able to transfer my reward?

**Comment by Bigemaa** [comment]
I have disconnected Metamask and found my reward there
