### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by Bigemaa** [Meeds-io/meeds#1555]
![Meed Trans](https://github.com/Meeds-io/meeds/assets/156846993/bf7f10b2-bbe9-4449-9563-84f193460957)
I tried transferring to my Metamask wallet, it showed the transaction sent. But the receiving wallet is yet to be credited

**Comment by plamarque** [comment]
Time to complete depend on network congestion. You can follow the transaction status on Polygonscan by clicking on "see transaction" or from the tx link you'll find in the transactions drawer (Last Transactions button)
