### ISSUE TITLE
Transfer issue

### ISSUE THREAD

**Issue by Bigemaa** [Meeds-io/meeds#1556]
Checking through transaction Hash, For hours now, nothing is showing.
The token is still in my wallet
![Hash](https://github.com/Meeds-io/meeds/assets/156846993/ca05125f-0aa4-4aec-809e-79947e975fae)

**Comment by boubaker** [comment]
![image](https://github.com/Meeds-io/meeds/assets/594824/7def9a8d-87db-4acf-befb-46ed51459208)

You [don't have Matic](https://polygonscan.com/address/0xdea9c61da7a382e4d7c0be81e61fd13d82bc6e5d) to pay the **transaction fees on Polygon** to send a transaction.
