### ISSUE TITLE
Strange looking unread activity

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#1559]
**Steps to reproduce**

1. Go to 'https://builders.meeds.io/portal/g/:spaces:meeds_1_ft/'
2. Click on 'activity filter', select Unread activities and save.

![Screenshot 2024-01-19 at 11 07 19](https://github.com/Meeds-io/meeds/assets/227828/c9e9c04f-49b2-450c-b2b7-c618a8a2a982)

**Current behavior**

The activity looks empty, there is no content and the user avatar is blank

**Expected behavior**

An activity with OP avatar and name and content is displayed.

**Comment by srenault-meeds** [comment]
Yes indeed, it is a deleted activity (I had posted one activity and then deleted it). So to fix indeed.
Thanks

**Comment by plamarque** [comment]
also noticed that there is no way to remove the unread notification in that case.

**Comment by boubaker** [comment]
> also noticed that there is no way to remove the unread notification in that case.

You can click on this button to remove it
![image](https://github.com/Meeds-io/meeds/assets/594824/68f7a406-4548-4fae-a116-bfe32dbb46ef)

**Comment by plamarque** [comment]
Doesn't work.

**Comment by srenault-meeds** [comment]
Try the option from the left menu.

**Comment by plamarque** [comment]
It worked, thanks!

**Comment by srenault-meeds** [comment]
We don't succeed to reproduce the case.
Indeed, I have tried with different use cases:
- text without mention then deleted by userAlpha. 
- text with mention everyone then deleted by userAlpha
- text with mention hosts then deleted by userAlpha
- filter unread set or not set 

UserBeta don't see this blanked activity and the notif badge from the left menu disappeared

Yet, no reproduction.
I will close it as not reproduced. 
However, in case you meet this issue again, please contact me to understand better the use case.
