### ISSUE TITLE
[login] Duplicate account

### ISSUE THREAD

**Issue by halaya** [Meeds-io/meeds#156]
**Describe the bug**
I have 2 wallets the first one I connect with it on meeds io, and the second one I created on meeds io. when i connect with the second one it will create a new account despite that the public key of the wallet does exist.

**To Reproduce**
- Go to logout to disconnect the first wallet
- change account on metamask (second wallet)
- connect with metamask with the second wallet
- it will create a new account with my second wallet

Uploading Meeds-bug.mp4…

**Comment by srenault-meeds** [comment]
Hello @halaya as you are trying to connect with another wallet, this is expected to be considered as a new user. Indeed, credentials are not the same and we cannot know you are the same user, so we create another user.

Does your feedback relate to something else?
Thanks
