### ISSUE TITLE
New Task on Meeds

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1560]
Good evening, today I just want to give a suggestion on a new task to be added to Meeds. If a task like daily contribution to a random specific topic is being inserted for members to give answers to it base on their own understanding I think this will boost the knowledge of members. This task can be pinned on a separate group in discord and a link being brought up here on the portal and once a member clicks on it, it will take the person to the Question. We can name the Task Question of the Day, then members will answer it base on their experience or exposures. Thanks

**Comment by plamarque** [comment]
Well received @Humblespino 

We don't use GitHub issues to discuss organizational/community stuff, but rather software related issues. 

I will close this but I invite you to open this discussion thread on builder's Hub (there is a Learn space that seems appropriate for it) or directly on Discord #contribute channel
