### ISSUE TITLE
Register page: Exceptions/errors management

### ISSUE THREAD

**Issue by wzlitni** [Meeds-io/meeds#1567]
In the registration page
https://builders.meeds.io/portal/external-registration?xxxx
Due to some difficulties to show exception/error message in some browser or devices and in order to facilitate the registration process and, we want to add a red border to point out the field conytaining the error. (including the captcha)
![meeds-register-captcha-exception](https://github.com/Meeds-io/meeds/assets/62754091/6109fef3-c243-459f-81d7-3e39af232cef)
![meeds-register-password-exception](https://github.com/Meeds-io/meeds/assets/62754091/dbba74c4-3118-49a3-a0c1-ad3250a4c114)

**Comment by srenault-meeds** [comment]
Close it as this duplicated with https://github.com/Meeds-io/meeds/issues/1572
