### ISSUE TITLE
Register page: replace 'Save' by 'Login' in the confirmation button

### ISSUE THREAD

**Issue by wzlitni** [Meeds-io/meeds#1568]
I the registration page, after  filling and confirming our account informations/credentials by clicking on 'Save' button, we are redirected to the Meeds builders, platform.
Based on this principle, 
![meeds-register-save-button](https://github.com/Meeds-io/meeds/assets/62754091/70942b74-39fc-4bcc-a7d4-aebf8d93a5b4)
i suggest to replace 'Save' by 'login' to simplify and add more transparency to the registration process.

**Comment by srenault-meeds** [comment]
Close it as this duplicated with https://github.com/Meeds-io/meeds/issues/1571
