### ISSUE TITLE
Register page: Exceptions/errors management

### ISSUE THREAD

**Issue by wzlitni** [Meeds-io/meeds#1572]
In the registration page
https://builders.meeds.io/portal/external-registration?xxxx
Due to some difficulties to show exception/error message in some browser or devices and in order to facilitate the registration process and, we want to add a red border to point out the field conytaining the error. (including the captcha)

![meeds-register-captcha-exception](https://github.com/Meeds-io/meeds/assets/62754091/fa8b9493-e35a-4d8e-af36-c729a74ff65d)
![meeds-register-password-exception](https://github.com/Meeds-io/meeds/assets/62754091/c20196a7-38ea-41c6-9219-a1f52c8501b8)

**Comment by srenault-meeds** [comment]
Enhanced! thanks
