### ISSUE TITLE
Insert link on a shot message UX issues

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1574]
**Steps to reproduce**

1. Go to space
2. Click on post
3. Write a text
4. Select a part of the text
5. Click on the selected text
6. See error
9. Select all the text
10. Click on the text or the composer
11. See error

**(optional) Affected version**

Don't pay attention to the point about double click to select all in the video.

https://github.com/Meeds-io/meeds/assets/105866381/165a1eb9-061b-4117-b3a2-d9cf4fc56006

**Current behaviour**

There are 3 issues:

1. When I click on a selected text nothing happens
2. When you select all the text you cannot unselect it or continue your redaction. 

**Expected behavior**

1. Clicking on a selected text, unselect it
2. clicking outsite the selected text in the composed unselect it

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Ok I don't reproduce this case. And I don't see it in your video.
> When I click on a selected text nothing happens

Can you check your extensions, please?

Regarding the fact that when selecting, you cannot unselect it using touchpad or pad, yes we will take a look at it. Thanks

**Comment by Julien-Dubois-eXo** [comment]
The video extension is mp4. I can play it in my case. 

I can show you if needed.

**Comment by srenault-meeds** [comment]
No I meant I don't see it **in the video** :)

**Comment by srenault-meeds** [comment]
Enhanced ;-) @Julien-Dubois-eXo
