### ISSUE TITLE
Completion of Whitepaper Translation 

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1575]
Good afternoon Sir, my little suggestion today is on the whitepaper translation to many languages. What i want to say is that a note should be pasted and each individual should complete their translation on any of the languages they choose instead of opening multiple languages to translate. Each week if an individual have been able to make 1000+ translation, another week he should continue from where he stops and until he completes the first language in which he chooses before he can now proceed to another language

**Comment by plamarque** [comment]
To be discussed on builder's or discord.

Issues on GitHub are for software bugs and improvements
