### ISSUE TITLE
Ckeditor - Quote color hardcoded

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1578]
**Steps to reproduce**

1. Edit to a note/post
2. Click on quote

![image](https://github.com/Meeds-io/meeds/assets/105866381/bd7bbd32-667d-4bb0-84e9-2657becd3e47)
![image](https://github.com/Meeds-io/meeds/assets/105866381/69ee4cea-d3a0-4e0a-b75e-8b196115b8ac)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The color of the quote border in Edit mode is the Meeds primary color even if you have changed the primary color.

On view mode it's the good primary color that is displayed.

**Expected behavior**

The color should be the color defined as primary color

**(optional) Affected environments**  
Please complete the following information:

**Comment by Julien-Dubois-eXo** [comment]
The description was updated to be more specific in the current behavior as I noticed the issue is only on edit mode.

**Comment by srenault-meeds** [comment]
Not reproduced on meeds
can you double check please?

**Comment by Julien-Dubois-eXo** [comment]
It seems fixed. You can close it. Thanks
