### ISSUE TITLE
[Tasks] Placeholder displayed when searching for a project and no result

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1581]
**Steps to reproduce**

1. Go to task application
2. In project tab, type something on filter. It must not correspond to a project name
3. The page display this :
![image](https://github.com/Meeds-io/meeds/assets/807839/4b9918c9-de20-47e6-842a-712a9af67cf4)

**(optional) Affected version**
Last version

**Current behaviour**
There is no way to get back to unfiltered project list

**Expected behavior**
To define, but, if my search do nothing, I want to get back to project list

**Comment by srenault-meeds** [comment]
Ok I see your problem now. It is only when searching for a task project. 
We have another item to deal with. https://github.com/Meeds-io/meeds/issues/1587

**Comment by srenault-meeds** [comment]
And same when searching for a task (not only when searching for a project)
