### ISSUE TITLE
EYE CARE

### ISSUE THREAD

**Issue by Sirmiesticks** [Meeds-io/meeds#1583]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sirmiesticks** [comment]
I think there show be a daylight mood and a night mood for users.

**Comment by srenault-meeds** [comment]
Thanks for this feedback!
Duplicated with this: https://github.com/Meeds-io/meeds/issues/510
