### ISSUE TITLE
API malfunction on the Task 'mention @iomeeds on Twitter/X

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1585]
After tweeting 65+ characters on Twitter and mentioning @iomeeds, then wait for about 10mins

**Steps to reproduce**

1. Go to 'Promote'
2. Scroll down to 'Mention @iomeeds on Twitter/X'
3. Click on 'Mention @iomeeds on Twitter/X'
4. API not showing 'Already done today try again tomorrow' after 7mins of mentioning IoMeeds on twitter
5.

**Affected task**
Mention @iomeeds on Twitter/X

The task is not been carried out due to the API not detecting the said task when a user carried it out

**Expected behavior**
Expecting the bot to detected and marked the said task when carried out successfully.

**Comment by srenault-meeds** [comment]
Hi, indeed, there is a problem with the Twitter API which is being dealt by Twitter itself. We'll let you know once it is back 

cc @plamarque

**Comment by srenault-meeds** [comment]
related to twitter action and now solved
