### ISSUE TITLE
maximum ether value is incorrect

### ISSUE THREAD

**Issue by MayTekayaa** [Meeds-io/meeds#161]
**Describe the bug**
Going to https://investors.meeds.io/dapp/ in the snaphot tab, under buy/sell (ethers and meeds), when I try to buy meeds with my maximum ether balance, it shows me a wrong value.

**Screenshots**
![Screenshot from 2022-05-27 14-52-30](https://user-images.githubusercontent.com/100131287/170713302-7aea009b-a857-47b6-8a49-0c734c24377d.png)

**Comment by mzorai** [comment]
Related task https://builders.meeds.io/portal/meeds/tasks/taskDetail/364

**Comment by srenault-meeds** [comment]
@MayTekayaa can you please tell me if you can reproduce it?
Thanks
