### ISSUE TITLE
More languages 

### ISSUE THREAD

**Issue by Sirmiesticks** [Meeds-io/meeds#1611]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sirmiesticks** [comment]
I feel that more indigenous languages should be incorporated not only popular languages

**Comment by Sirmiesticks** [comment]
That's all

**Comment by srenault-meeds** [comment]
Hi @Sirmiesticks 

Thanks. 
Can you please precise which language you need?
Indeed, we provide around 24 languages for our end-users. To decide which one to use, please access your settings

Check screenshot

<img width="222" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/d6e8dfe7-f453-4fdd-b261-66366492df86">
