### ISSUE TITLE
Logging im

### ISSUE THREAD

**Issue by PrinceTroyC** [Meeds-io/meeds#1612]
**Is your feature request related to a problem? Please describe.**
Can't log in on Chrome 

**Describe the solution you'd like**
To be able to log in properly or connect wallet 

**Describe alternatives you've considered**
Just add a wallet connect 

**Additional context**
Ok

**Comment by srenault-meeds** [comment]
Hi @PrinceTroyC 
Thanks for this feedback. 
Yet, I am not sure to understand well this one.

Indeed:
1. logging in using Chrome is possible (I do it myself)
2. You can log in using email/password form or Metamask wallet connection

I have the feeling that you'd like to have another wallet connection than the Metamask one.
Can you please precise?
Thanks

**Comment by srenault-meeds** [comment]
Close as no answer
