### ISSUE TITLE
Trending Meeds Banner

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1613]
Greetings, today I'll love to suggest for the team to make provision for another set of banner designs to announce our awareness to the public. We can publish it on Medium and Twitter with a nice text contents.
Thanks.

**Comment by srenault-meeds** [comment]
Rejected for same reason than previous feedback. Not the right channel

**Comment by kuvaMan** [comment]
Greetings all, I think we have fews days to our events,  I think it will be nice for us to have a reminder design for the Video call on Discord , this my suggestion

**Comment by plamarque** [comment]
@srenault-meeds I think you were right in saying we'd need a button in the UI where users can suggest new actions.
