### ISSUE TITLE
[Stream] Put "about one hour" instead of "about 60 minutes"

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#162]
**Describe the bug**
In the Head of the activity when it has been posted about one hour, it puts in the time section "about 60 minutes"

**To Reproduce**
1. Create an activity
2. Go in the Activity stream page after 60 minutes exactly
3. It display 'about 60 minutes"

**Expected behavior**
It should display "about 1 hour" instead of "about 60 minutes"

**Screenshots**
![Screenshot from 2022-05-31 16-50-45](https://user-images.githubusercontent.com/40363501/171442180-8d53f8c4-a6bc-4301-a7bd-095ea5b76748.png)

**Comment by srenault-meeds** [comment]
Fixed
