### ISSUE TITLE
[Contributions] Access to announce link in challenges app

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#163]
Add the possibility to access to announce activity link in challenges app

![announce](https://user-images.githubusercontent.com/1579929/171512162-2959c126-017d-4944-aa8d-5086d3952de7.png)

**Comment by srenault-meeds** [comment]
Hi, Actually you can do it, but it is not that obvious. Indeed, click to timestamp and you can access the challenge activity.
Need to improve this indeed.

**Comment by srenault-meeds** [comment]
Done :-)
