### ISSUE TITLE
API Malfunction and proper way to handle the task on Mention @Iomeeds on X

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1648]
Good evening, I want to give a suggestion on how to simply correct the API malfunction on the said task on each weeks that emerges. The twitter robot sense the at-tags as a spam and triggered the API to malfunction. What I'll suggest is for the task to go back to its normal way of being manual, with this the reviewers can use the link to check if a user's content is accurate or is deceptive. Many tweet may be falsely and the task accepted it when using automatic detection. So I believe if the manual way is been inserted back it will be of good measures to the community. Thanks

**Comment by Kayplus73** [comment]
Quite suggestive for me.

**Comment by srenault-meeds** [comment]
@plamarque your opinion?

**Comment by plamarque** [comment]
my opinion is that it works as intended. the Twitter action captures the interactiions to avoid users to submit each time.
Automatic capture does not mean automatic review. Other criteria are checked manually as in all other actions.
