### ISSUE TITLE
I would like to suggest an improvement it would be better if messaging via this portal would be possible. Because some of us can I have issues and don't know where to complain about it. I am so sorry familiar with the Discord app

### ISSUE THREAD

**Issue by Frankiblac** [Meeds-io/meeds#1656]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by srenault-meeds** [comment]
Hi @Frankiblac please use the form and don't use the title to explain your problem and your suggestion

**Comment by srenault-meeds** [comment]
As no answer, I close it
