### ISSUE TITLE
It would be better if messaging via this portal would be possible, because most of us aren't familiar with Discord app

### ISSUE THREAD

**Issue by Frankiblac** [Meeds-io/meeds#1657]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Frankiblac** [comment]
It is just a suggestion

**Comment by Callmepope1** [comment]
It would actually be better to message via this portal as such will aid the improvement and development of the portal

**Comment by srenault-meeds** [comment]
Duplicated with https://github.com/Meeds-io/meeds/issues/1526
