### ISSUE TITLE
Some aren’t actually bugs

### ISSUE THREAD

**Issue by Callmepope1** [Meeds-io/meeds#1659]
**Steps to reproduce**

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.

**Expected behavior**

**(optional) Affected environments**  
Please complete the following information:

**Comment by Callmepope1** [comment]
Some problems aren’t actually bugs

**Comment by srenault-meeds** [comment]
No issue reported. Rejected
