### ISSUE TITLE
Connection of site to metamask wallet 

### ISSUE THREAD

**Issue by Nsisong9** [Meeds-io/meeds#1662]
I was frustrated when I tried to connect my metamask account to the website, the connect button was locked, thereby making it impossible to connect my extension wallet .

I think you should make the website to be compatible for all devices and browsers.

**Comment by srenault-meeds** [comment]
Which browser do you use?
We indeed support chrome, firefox, safari, edge (chromium) and metamask as well.
This will be rejected if no answer from tomorrow night

**Comment by srenault-meeds** [comment]
As no answer, I close it
