### ISSUE TITLE
Generating of Traffic for Meeds

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1663]
Good afternoon, on today's suggestion I believed if a task like time range is introduce into Meeds it will be of a great value for generating of Traffic for the platform. What I'm saying in essence is if an individual wants to claim this particular task he or she should interract (be online in the platform) for 35minutes or so. This aid in making the platform busy and productive. Thanks

**Comment by plamarque** [comment]
Reasoning in terms of feature, we can already archive this by creating an action with event Meeds : Sign in on. Specific date range.

Now, in terms of use case, I'm not sure what kind of value it could bring to gather users at the same time?
