### ISSUE TITLE
Connect button doesn't change it's status when sending request connection from Members Tab of a space 

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#167]
**steps to reproduce :** 
1- Access to Members TAB of a space 
2- click on the "Connect" button for a member CARD to send a connection request 

**Actual behavior:** Connect button does not change its status and gives the impression that the request is not sent 
**Expected behavior:** Connect button should be replaced by "Cancel request" as  the case on the people page

**Comment by srenault-meeds** [comment]
seems to be ok
