### ISSUE TITLE
Difficulty in Logging into the MeedsDao platform 

### ISSUE THREAD

**Issue by Rolandkenneth101** [Meeds-io/meeds#1678]
**Steps to reproduce**

1. Go to  log in 
2. Click on log in 
3. Scroll down to 

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.

**Expected behavior**

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
hi

**Comment by srenault-meeds** [comment]
Please detail your problem next time.
I put on waiting on until it is detailed

**Comment by srenault-meeds** [comment]
No answer. I close it for now
