### ISSUE TITLE
i18n description problem 

### ISSUE THREAD

**Issue by wassimmhamdi** [Meeds-io/meeds#168]
**Describe the bug**
When changing the plf language to french or Arabic and   hovering on a space in the activity stream a poup-over appear with wrong description of the space that is not translated like the others .

**To Reproduce**
1. connect to builders.meeds.io
2. Change language to french or Arabic
3. hover on a space in the activity stream 
4. See that the description of the space is not whit that language 

**Expected behavior**
The description of the space must bee with the same language 

**Screenshots**
![challenge](https://user-images.githubusercontent.com/92787714/171839338-bf044cea-040f-4b14-8d1c-aa1eef4435f0.png)

**Comment by srenault-meeds** [comment]
The description is not i18n so this is not a problem actually. Indeed, description is something space hosts manage to add, so it can be i18n for now.
Thanks
