### ISSUE TITLE
More reviewers for easy works

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1686]
Greetings, there have been huge works for the numbers of reviewers inwhich the platform have and this is leading to delayed in the aspect of reviews coupled with the numbers of contributors on the platform

The alternative inwhich I consider will be for the team to bring up qualified and transparent reviewers to soften the work load 

Adding competent reviewers, scheduling and swapping of their duties will aid in generating a transparent background (for example if a reviewer handle a video task for the week, next week he or she shoulf handle another task). If a timetable is schedule for a reviewer in task swapping it will aid reduce stress and piled up of works. 

More reviewers is really needed to speed up the process of reviewing.
Thank you.

**Comment by Kriztech25** [comment]
No bug
