### ISSUE TITLE
Link is not clickable in the description message of an activity such as a challenge announcement

### ISSUE THREAD

**Issue by abenmbarek** [Meeds-io/meeds#169]
steps to reproduce :
1- Go to challenge application
2- Choose a challenge to announce
3- copy and past a link in the announcement description
4- Click on Create and go to the Activity Stream Page

Actual behavior: the link pasted in the announcement description is just a text and not clickable.
Expected behavior: the link pasted in the announcement have to be clickable.

![image](https://user-images.githubusercontent.com/92788696/171843936-4258093d-e180-429b-9476-a4f0fd10ca80.png)

**Comment by boubaker** [comment]
Already fixed, needed to wait for CI/CD to get it deployed.
