### ISSUE TITLE
Comment on a community post 

### ISSUE THREAD

**Issue by Nsisong9** [Meeds-io/meeds#1699]
More task should be added to keep the community growing and increase ways to earn points.

Contributors should be awarded points for engaging(i.e commenting) in a community post 

It should be a daily task

**Comment by Gideonokon** [comment]
Yes this is true, I support this

**Comment by srenault-meeds** [comment]
Not a bug hunt, neither a feature request

**Comment by JosephineEzekiel** [comment]
Yes, because I often times find myself running out of tasks.
