### ISSUE TITLE
Sites management - Site names are transformed in the card

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1706]
Scenario

- Create a site or rename an existing site
- Name it with several words in lower cases
- Go to Sites page administration
- See error

Current behavior

The name is displayed in upper case for each word no matter what has been written in the menu.

![image](https://github.com/Meeds-io/meeds/assets/807839/ed0d78d0-23eb-4758-84a1-7201c90e4c46)

Expected behavior

The displayed name in the site card should respect the case written in the drawer.

**Comment by rdenarie** [comment]
This issues was fixed on exoplatform/layout-management, on develop branch, by this commit 
https://github.com/exoplatform/layout-management/commit/2e70282772033088f003c369b9c3acaa2ac3a7ed

**Comment by srenault-meeds** [comment]
Is it done?

**Comment by rdenarie** [comment]
Hello @srenault-meeds 
This task is fixed in exoplatform/layout-management, after this module was copied in meeds-io/layout

I commented this task with the commit, so that you are able to choose if you need to backport this fix in your module, or if  it is already fixed.

So, yes it is fixed on eXo side. 
For the meeds part, you need to check if you need to backport
