### ISSUE TITLE
Poll can't be posted

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#1708]
Steps to reproduce:
in space1
create a poll by clicking on Poll (not by clicking on start a post)
click on post
reopen poll drawer / start an post and choose Poll
Current behavior:
message your poll has been created
click on post : browser errors displayed
I can't post any short message (unless I refresh)
Expected behavior:
If poll empty, once drawer closed the message should be CREATE YOUR POLL
If poll drawer and post message drawer are closed, next time I should be able to post a message
Browser errors should be treated

**Comment by srenault-meeds** [comment]
Is it done?

**Comment by azayati** [comment]
yes it is done @srenault-meeds
