### ISSUE TITLE
QUICK REQUEST

### ISSUE THREAD

**Issue by Aineehub** [Meeds-io/meeds#1709]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I come on the Meeds DAO platform and cannot figure out which notifications are relevant to me

**Describe the solution you'd like**
I'd like for the notifications to be sorted into personal, connections and those concerning tasks.

**Comment by srenault-meeds** [comment]
@Aineehub it is actually already the case. Please click to expand option from the notification drawer and then you will be able to manage your notification by category as below:
<img width="1414" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/0e3212db-3848-45fc-adb5-4f145a487d8f">
