### ISSUE TITLE
[Contributions] Search challenge winners

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#171]
It is painful to find my posted challenges from activity stream, so I suggest to add some filters to the activity stream or a filter winners to facilitate searching that

**Comment by srenault-meeds** [comment]
Two thinks to consider this feedback:
- Add advanced filters for stream filtering with not only challenges but polls, notes, etc. I have posted, the host has posted, etc.
- Filters in the contributions center to list the challenges recently done by the current user

**Comment by srenault-meeds** [comment]
You can search it from the action itself now.
Considered as done
