### ISSUE TITLE
Addition of more tasks 

### ISSUE THREAD

**Issue by Callmepope1** [Meeds-io/meeds#1718]
**Steps to reproduce**

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.

**Expected behavior**

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Not a bug issue, neither a feature enhancement. More related to community question to be adressed on discord
