### ISSUE TITLE
Empty comment when mentioning user which its name contains accents 

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#172]
Empty comment when mentioning user which its name contains accents 

Comment on the activity and  mention a user which its name contains accents 

Current behavior :
comment is empty 

![mentionUserBug](https://user-images.githubusercontent.com/49310007/172387240-6507334f-4494-44b3-b595-6b9edec6266b.png)

**Comment by srenault-meeds** [comment]
Hi @GouadriaHanen I can't reproduce it and it seems that these comments are now well displayed. Can you confirm, please?

**Comment by srenault-meeds** [comment]
Reproduced and fixing in progress (in the next deployment). Not due to accent in name but ' in the profile position or in the name

**Comment by srenault-meeds** [comment]
Fixed @GouadriaHanen
