### ISSUE TITLE
Link portlet - Remove the header char limit

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#1722]
**Is your feature request related to a problem? Please describe.**
When we delivered this feature to our customers to replace the old CLV we had several cases where we could not put the same title because of the 25 chars limit.

Do we have a specific reason to implement a text restriction? It should be up to the user to decide if he wants something long or not. It's his choice. 

**Describe the solution you'd like**
Remove the limitation. 

**Describe alternatives you've considered**

**Additional context**

**Comment by srenault-meeds** [comment]
The limitation was based on the fact that portlets can be added to secundary columns and 25 looks to be the best to make sure we can see it.
I agree we can extend the limitation to 50 characters for example. But with still one line max then elipsis.
If we completely remove this limitation, users might see unbalanced UI and we need to guide them.
So, my suggestion to yours is: review the limitation to another one. Is 50 enough for you?
Thanks

**Comment by Julien-Dubois-eXo** [comment]
I understand your concern about the potential UI issues but IMO it's not our role to tell the end user what they should do or not in terms of UI. What looks nice is just a point of view. 

In the majority, they will see it in the preview and limit by themselves. In a few cases, if they want a 3 line header it's up to them. Sometimes they will prefer to have something meaningful because it's the more important thing.

**Comment by srenault-meeds** [comment]
I disagree with this:
> if they want a 3 line header it's up to them

It is our job to guide them.

Your concern is different IMO:
> Sometimes they will prefer to have something meaningful because it's the more important thing.

Indeed this is not a header when more than one line, it is a summary :)

**Comment by Julien-Dubois-eXo** [comment]
> Your concern is different IMO
No, my concern is by restricting the number of chars we generate frustration because we forbid something to the user. 

I think about it, and it's the way we are guiding that should be changed. 

We should allow them and keep the harmony of the UI.

IMO we should implement a maximum of line, not a char limit = 2 lines no matter the width of the app and if the header is longer we display an ellipsys + the full name on hovering over the name. 

That way we guide them to let them know that a header should not be longer than 2 lines and they can still put a long name that can be read. 

IMO it's more efficient for responsiveness as we can still have a long header for the app that will take all the page width. 

WDYT?

**Comment by srenault-meeds** [comment]
I still disagree with the suggestion of having 2 lines. Indeed, you can't be sure about the width of the app and thus, 2 lines will be different between devices used. So you can't easily implement it.

And again, if your concern is about having more than one line, then it is not a header you need, but a summary.

Furthermore, regarding this:
> the full name on hovering over the name.

too much tooltips already and I am not ok with this.

**Comment by srenault-meeds** [comment]
Will be reworked in another issue #1842

**Comment by srenault-meeds** [comment]
Hello @Julien-Dubois-eXo as explained a month ago, it has been reworked for your information.
Result: extend the limitation of 25 char. to 50 char.
