### ISSUE TITLE
Completed Tasks Feature

### ISSUE THREAD

**Issue by JosephineEzekiel** [Meeds-io/meeds#1724]
Users on the Meeds platform often find it challenging to keep track of tasks they have already performed, leading to inefficiency.

Introduce a Completed Tasks feature within the Meeds platform that allows users to easily view and manage tasks they have already completed. This feature would provide users with a dedicated section or tab where they can access a list of tasks they have marked as completed. Key components of this feature include.

Task Archiving: Instead of a dedicated Completed Tasks feature, Meeds could implement a task archiving functionality where users can manually archive completed tasks.

Additionally, the "Completed Tasks" feature could include options for users to:
1. View a history of their completed tasks
2. Filter and search through completed tasks

**Comment by srenault-meeds** [comment]
Hi @JosephineEzekiel are you talking about tasks management or contributions tasks?
Indeed, the tasks management app provided by Meeds already proposed such archiving feature.

Thanks for clarification

**Comment by srenault-meeds** [comment]
No reply. I close it for now. Will be reopen once something comes up

**Comment by JosephineEzekiel** [comment]
Hello, Good morning, I can no longer access my page, can't log in anymore.
