### ISSUE TITLE
Weekly payment.

### ISSUE THREAD

**Issue by Nsisong9** [Meeds-io/meeds#1725]
I'm was frustrated when i linked my wallet address and my account and my balance disappeared.

I think there should be a space for saving unclaimed rewards

**Comment by srenault-meeds** [comment]
When switching to another bank, it is your role to get your money to the new bank account (except when the transfer can be done between banks and this is a service they can offer). Here, it is the same case.
As it is your personal wallet, we can't manage such switch.
