### ISSUE TITLE
More task for meeds on Twitter 

### ISSUE THREAD

**Issue by YangAlhaji** [Meeds-io/meeds#1726]
I feel like there should be more task on meeds like making a tweet or thread and top 5 or 10 with the highest engagement or likes get like 1000 or more points. It will be nice to still great a competitive environment and people get to write on Twitter too instead of only medium that way meeds dao will have more reach since everyone will want to try there luck and see if they win

**Comment by srenault-meeds** [comment]
To discuss in our discord server
