### ISSUE TITLE
Making the website compactible for people with eye probems

### ISSUE THREAD

**Issue by Khaymee** [Meeds-io/meeds#1727]
I'm always frustrated when i logging to the website and could not find a darkmood feature that could help reduce the light that is coming into my eyes

i think darkmood features should be added to the website

**Comment by Khaymee** [comment]
I'm always frustrated when i logging to the website and could not find a darkmood feature that could help reduce the light that is coming into my eyes

i think darkmood features should be added to the website

**Comment by srenault-meeds** [comment]
Hello,
This is possible indeed. You have two choices:
1. If your browser is set to automatically be in dark theme, then the automatic theme is the dark one.
2. If you want to change it manually, go to the footer and select the theme you want. 
Thanks
