### ISSUE TITLE
Bug Report - 500 Internal Server Error on Meeds.io

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1732]
**Steps to reproduce**

Visit Meeds.io homepage.

Attempt to log in or navigate to different sections.

Error consistently appears, displaying "500 Internal Server Error."

**(optional) Affected version**

Indicate the version where the bug is observed.
The bug was observed in the current version 

**Current behaviour**

Encountered a recurring issue on Meeds.io where a "500 Internal Server Error" occurs during various interactions on the website.

**Expected behavior**

Smooth navigation and functionality without encountering server errors.

**(optional) Affected environments**  
Please complete the following information: 
 - OS: [Microsoft windows]
 - Browser [chrome]
 - Version [Microsoft windows 10 and chrome 123.0.63]
 - Device: [Dell Inspiron 15 i5558 ]

**Comment by srenault-meeds** [comment]
Hi, 
Can you precise the page please?
Indeed, it is not currently reproduced.
Thanks

**Comment by srenault-meeds** [comment]
I close it for now as no reply. I will reopen it if needed
