### ISSUE TITLE
Educational Game Channel

### ISSUE THREAD

**Issue by Humblespino** [Meeds-io/meeds#1739]
Greetings, this week short suggestion in which I'll love to suggest on will be for the team to insert a channel on discord which will be tabled "Education". There in the channel contributors can have knowledge on words interpretations/spellings. It should look like a game channel whereby incomplete words will be displayed and a contributor will be asked to spell it correctly for it to pass to another question. The timer can be 10secs per question, and at the end of the three questions that will be asked an overall score should appear and a contributor takes a screenshot and inserted it on the Meeds platform. This channel can be opened trice a week and an individual should be entitled to perform the task once in a set day. This is also to test the knowledge of a contributor on how fast he or she can spell a word accurately. Thanks

**Comment by srenault-meeds** [comment]
Why not proposing this in the Meeds discord?
Indeed, this is not the place to suggest such item.
