### ISSUE TITLE
Challenge announcement links not cliquable 

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#174]
When we achieve a challenge, add an announcement whose achievement contains a link, the link is not cliquable in the related activity.

 
![links](https://user-images.githubusercontent.com/1579929/172659168-290f8a55-8660-4e83-b005-311cf07fb49a.png)

**Comment by plamarque** [comment]
duplicate - already reported in #169

**Comment by boubaker** [comment]
Already fixed, needed to wait for CI/CD to get it deployed.
