### ISSUE TITLE
Social Media 

### ISSUE THREAD

**Issue by AbasifrekeAkpakpan** [Meeds-io/meeds#1759]
There aren't a lot of social media platforms to make contributions like Facebook, telegram, Instagram.

Provisions should be made to add more social media networks that are accessible to more people. This can actually improve engagement and reach audiences that are not available on the social platforms available on Meeds

**Comment by srenault-meeds** [comment]
No bug issue, nor product feedback. It is a community feedback to address on discord. thanks
