### ISSUE TITLE
[Contents] Attach image or file for challenges

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#176]
Sometimes we need to attach images in challenges or achievements description to be displayed with the body.
I suggest to add this feature

**Comment by mzorai** [comment]
Feature accepted, already on our backlog https://builders.meeds.io/portal/g/:spaces:developers/developers/tasks/taskDetail/148

**Comment by srenault-meeds** [comment]
Done with MIP53 https://github.com/Meeds-io/MIPs/issues/53
