### ISSUE TITLE
Suggestions an improvement 

### ISSUE THREAD

**Issue by Victorjames17** [Meeds-io/meeds#1761]
I get frustrated sometimes when the tasks to be performed are clearly define , which can result in difficulty perform tasks.

The executives should work on giving adequate directions on how to successfully complete a tasks and put them in a more comprehensible manner.

These are some of the alternatives I think should be implied.Divide the task into smaller, manageable parts and discussing the task with peers or mentors to gain different perspectives.

![Screenshot_20240310-141405](https://github.com/Meeds-io/meeds/assets/162636653/a4d85777-af17-4c01-82c3-2894f4f5c13d)

**Comment by srenault-meeds** [comment]
No bug issue, nor product feedback. It is a community feedback to address on discord. thanks
