### ISSUE TITLE
The delaying of tasks 

### ISSUE THREAD

**Issue by Chifrank12** [Meeds-io/meeds#1762]
I get delayed sometimes when I’m performing a tasks to which sometimes makes me make mistake or make tasks difficulty to perform.

The administrative should work on how to give people performing tasks  to successfully complete their tasks without any disturbance.

These are some of my opinion that I think should be implied difficulty and dullness of managing long pull requests.

**Comment by srenault-meeds** [comment]
No bug issue, nor product feedback. It is a community feedback to address on discord. thanks
