### ISSUE TITLE
Inconsistency on the amount of estimated meeds token 

### ISSUE THREAD

**Issue by Isehunyime** [Meeds-io/meeds#1766]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] I am always disappointed when my estimated meeds is reduced for some reason base know to the reviews 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. I wish and want meeds DAO to have a quick and a standby reviewers that will always review each tasks immediately 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Or creat a system that won't allow wrong task or actions to be submitted 

**Additional context**
Add any other context or screenshots about the feature request here. It is not nice to see some amount of tokens this night and tomorrow I will be seeing another thing 

![Screenshot_20240304-214138.jpg](https://github.com/Meeds-io/meeds/assets/161561377/d170bf07-7e63-4ed9-a8fc-52b17e95f7a2)

**Comment by Isehunyime** [comment]
Meed DAO should have a system that do not bring high and reduce the estimate amount of meeds tokens as make participants feel disappointed

**Comment by srenault-meeds** [comment]
Already taken in consideration in the [#mip#122](https://github.com/Meeds-io/MIPs/issues/122)
