### ISSUE TITLE
Fix: Attach image in task description rich editor allows to Attach Non-Image file types

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#1767]
**Steps to reproduce**

1. Open the task description rich editor
2. click to attach image button 
3. select non-image file type

**Current behavior**

File attached successfully 

**Expected behavior**

Non-image file types should not be attachable.

**Comment by srenault-meeds** [comment]
Please add it in the proper project (bug hunt or feature enhancement)
Thanks

cc @Jihed525

**Comment by srenault-meeds** [comment]
Considering it as a bug as no news from you

**Comment by Jihed525** [comment]
can be closed as already merged and validated 
sorry I missed your last comment @srenault-meeds
