### ISSUE TITLE
 container do not respect width css rule

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#1769]
steps :
given a page having a responsive column group container 
the right container has a rule on width calc(100% - 200px)
the left container has a rule on width of 200px

actual behavior
the sub-containers do not respect the CSS rules

**Comment by srenault-meeds** [comment]
Please add it in the proper project (bug hunt or feature enhancement)
Thanks

cc @Jihed525

**Comment by srenault-meeds** [comment]
Considering it as a bug as no news from you

**Comment by Jihed525** [comment]
can be closed as treatment postponed
