### ISSUE TITLE
YouTube suggestion

### ISSUE THREAD

**Issue by Deemojilover** [Meeds-io/meeds#1770]
Good day [Meeds DAO], I was going to suggest that we have a task like YouTube post, we all know we have LinkedIn, Medium and Twitter which are Vital places where informations about this project is published. YouTube is also one of them with more clarity (video), so I suggest we have a space for daily boost to enhance members visiting and viewing the videos to know how to perform better tasks.
Do well to consider, Thank you...

**Comment by srenault-meeds** [comment]
No bug issue, neither a product feedback.
Please @Dcnchidexco address it to community using the meeds discord server
