### ISSUE TITLE
Impossible to configure the number of kudos per period

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#1774]
Step of reproduction:
- Connect as an administrator
- Access to the administration site
- Access to recognition ->Setup ->Kudos

Current behavior:
It's impossible to indicate and modify the number of kudos per period

Expected behavior:
Have the ability to  indicate and modify the number of kudos par period

**Comment by srenault-meeds** [comment]
Hi @GouadriaHanen 

Please make sure it doesn't affect the original implementation. Indeed, it is ok when using meeds server
<img width="314" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/660d1385-be21-486b-a4b1-c623d2a7eb61">

But when using exoplatform one, it is not ok. You might have something different in the stylesheet of exoplatform that creates this UI bug

<img width="316" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/b0bd5a36-4712-4958-9208-6e5ceb132559">


cc @rdenarie @boubaker

**Comment by rdenarie** [comment]
@srenault-meeds 
You're right, the problem comes from a css on exo side.
We will delete this issue, and rework the fix, which will be only on our side.

Thanks for the comment

**Comment by srenault-meeds** [comment]
You're welcome. I know this can be annoying but the best to do when creating an issue is to compare behaviours between packages.
