### ISSUE TITLE
Twitter boost

### ISSUE THREAD

**Issue by Nsisong9** [Meeds-io/meeds#1775]
Although I've linked my Twitter account to the website, points are sometimes not or are always awarded late when i do the twitter boost task( note. I've meet the criteria )

**Comment by plamarque** [comment]
How late? Minutes? Hours days?

Could you point to concrete examples of tweets you interacted with and you didn't receive points or received them late?

**Comment by srenault-meeds** [comment]
I suggest you submit it again. And next time, add screenshots, screencast, links so we can better check and study your problem
