### ISSUE TITLE
[Contributions] Add emoji addition in program name / action name

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1779]
**Is your feature request related to a problem? Please describe.**
We can't access the emoji bank when entering a name for an action or a program

**Describe the solution you'd like**
Allow to access the emoji bank using the shortcut ': + ...'

**Comment by srenault-meeds** [comment]
Cancelled as name field is not using ckeditor and this is ckeditor related. Or we need a plugin for it like it is proposed in gitbook for example

**Comment by plamarque** [comment]
We don't need a UI to support emojis Our keyboards have it. The system should allow us to enter emoji in the text field

**Comment by srenault-meeds** [comment]
Yes and it is already the case, isn't it?
