### ISSUE TITLE
Typographical Error.

### ISSUE THREAD

**Issue by Favourade007** [Meeds-io/meeds#1788]
**Is your feature request related to a problem? Please describe.**
I noticed that the spelling on the Twitter Verification Task was spelt wrongly as [Tweeter]

**Describe the solution you'd like**
A correction should be made it as the spelling is not [Tweeter].

**Describe alternatives you've considered**
The write spelling is [Twitter] and should kindly be corrected, thanks.

**Additional context**

![Screenshot_20240317-210556](https://github.com/Meeds-io/meeds/assets/163509232/a8c14ada-515b-4cb8-b44b-3b685e7ef3be)

**Comment by srenault-meeds** [comment]
Thanks. Accepted even if not product feedback
