### ISSUE TITLE
[Leaderboard] The rank order of gamification is disordered for people with the same score

### ISSUE THREAD

**Issue by abenmbarek** [Meeds-io/meeds#179]
steps to reproduce :
1- Connect with User1 and do some gamified activities as creating a post.
2- Connect with User2 and do the same activity as the user1
3- Now go to the Stream page and click on the rank in the profile portlet mainly placed in the right side of the stream container.

Actual behavior: the rank of the users who have the same points is not constant or is disordered.
Expected behavior: Even if there are some many users have the same number of points, users list have to be sorted using so many level of sort criteria.

Related task link : https://builders.meeds.io/portal/meeds/tasks/taskDetail/244

![image](https://user-images.githubusercontent.com/92788696/173078762-371c8be3-434f-4531-86fb-34d0ff2d1c8b.png)

**Comment by plamarque** [comment]
what would you suggest as the second sort criteria ?

**Comment by abenmbarek** [comment]
> what would you suggest as the second sort criteria ?

In this case, I suggest to sort by the last one who have earned points , so we can use lastModificationDate or such BD attributes. WDYT ?

**Comment by plamarque** [comment]
Won’t be obvious to the reader so I suggest to use a criteria he can see : rankee display name alphabetic.

**Comment by srenault-meeds** [comment]
Fixed!
