### ISSUE TITLE
Suggestion for private notification section and tagging feature 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1797]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to go through streams and pools of notifications just to get the the notification or message that is directly addressing me or concerned with my contributions. sometimes I even end up missing informations and notifications concerning me 

**Describe the solution you'd like**
I propose the integration and introduction of a private notification section and a tagging/mentioning feature within the platform, this feature will help streamline communication within the contributors in the platform for example if I want to ask one of the reviewers a question I can simply tag or mention them in a post by their "@username" username and after the post has been sent they would receive a notification in a private section where they only see notifications that they've been tagged or mentioned in, whether this section will be visible only to the contributor being tagged or visible to all is now left to what is compatible to the community guidelines 

**Describe alternatives you've considered**
Other alternative could be communication through whatsapp or email, so that contributors will be able to see information related to them intime and efficiently without going through loads of notifications before finally reaching theirs 

**Additional context**
Github for example also has the feature as soon as I type the character '@' it automatically brings a list of other users that I can tag in that post or piece ![Screenshot_20240322-184625_GitHub.jpg](https://github.com/Meeds-io/meeds/assets/161255018/4d80688d-9ce1-44bb-9823-dc00316ef4a1)

**Comment by plamarque** [comment]
The tagging feature exists and it has a dedicated notification. Check your notification settings. 
![Screenshot_2024-03-22_at_18 20 52](https://github.com/Meeds-io/meeds/assets/227828/6a294823-a3d5-4393-bd38-25ccb104f1d7)


You're probably receiving too many notifications from others on actions where your participated, but you should be able to disable them in Activity Stream section  and keep only the @mention and reply to comment ones 

Besides MIP-122 (in progress) is adding more granular notifications for contribution status changes
