### ISSUE TITLE
Second chances for overdue contributions 

### ISSUE THREAD

**Issue by Nsisong9** [Meeds-io/meeds#1798]
The admins are really doing a great job. I think there should be a second chance or a chance to correct failed contributions even whe the time for the contributions are due.

**Comment by plamarque** [comment]
The product already allows for second chances. If your article is pending, you can still make corrections, edit the contribution proof, and @mention the reviewer to check again. Alternatively, you can abandon your current contribution by canceling it: this will unlock your contribution slot for the current period. Finally, the contribution slot is also unlocked when a contribution is rejected.

There is no limit to the number of times one can edit to correct, cancel/reject, and resubmit. So it's not just a second chance, but an unlimited number of chances.
