### ISSUE TITLE
Personalized notification 

### ISSUE THREAD

**Issue by Nsisong9** [Meeds-io/meeds#1799]
It will be better if notifications that are sent to me are those ones concerning me and my contributions

**Comment by srenault-meeds** [comment]
The tagging feature exists and it has a dedicated notification. Check your notification settings.
![image](https://github.com/Meeds-io/meeds/assets/58853195/c620b036-3e82-46b7-8b3e-80fa428edffd)


You're probably receiving too many notifications from others on actions where your participated, but you should be able to disable them in Activity Stream section and keep only the @mention and reply to comment ones
