### ISSUE TITLE
Reply button in the tasks comments area is badly displayed using small device or using responsive form

### ISSUE THREAD

**Issue by abenmbarek** [Meeds-io/meeds#180]
Steps to reproduce :

**Using responsive form or a mobile device**
1- Go to Tasks App.
2- Create a Task.
3- Open the created task and add a comment.

Actual behavior: the **Reply** button is not well adjusted with the comment's body above.

Expected behavior: we should add some margin between the container which containing the comment's body and the reply button.

See attachment below:

![Screenshot from 2022-06-13 12-36-02](https://user-images.githubusercontent.com/92788696/173348119-bcc33595-3377-4c36-b71d-05aa9705fe95.png)

**Comment by srenault-meeds** [comment]
In progress

**Comment by srenault-meeds** [comment]
Fixed
