### ISSUE TITLE
Suggestions of a direct message page/ section and awarding of points for using the 'direct messaging/DM'

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1801]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to communicate with other contributors and I can only do it through a comment format and even that method takes a  long time before I can get a reply it will be better and more efficient if I can get response immediately as the tasks on the builders hub are highly time sensitive 

**Describe the solution you'd like**
I'd like to suggest a new feature called the 'Direct Messaging' where contributors and stake holders of the platform can send messages and chats to themselves discretely and privately and also for them to be awarded points according to their level of use of the feature 

**Describe alternatives you've considered**
An alternative may be for the contributors to contact themselves through their X accounts 

**Additional context**
This will make the platform more engaging and allow for faster growth of the community as contributors can help themselves grow ![Screenshot_20240324-112140_Instagram.jpg](https://github.com/Meeds-io/meeds/assets/161255018/58281602-b89a-4d2f-9f16-ee8c7444925c)

**Comment by srenault-meeds** [comment]
The chat app is already identified as a feature request by other feedback like this one: https://github.com/Meeds-io/meeds/issues/1526

Thanks anyway for your proposition. This adds value to the first feedback
