### ISSUE TITLE
Implementation of dark mode 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1803]
**Is your feature request related to a problem? Please describe.**
Due to my highly sensitive eyes its always quite strainous to the eyes to use the platform at night especially when the lights are off, the white light may even be a trigger to people or users who suffer from epilepsy 

**Describe the solution you'd like**
I would like to suggest the implementation of a dark mode for the platform 

**Describe alternatives you've considered**
The only alternative that comes to mind is to reduce device brightness to the barest minimum 

**Additional context**
The light may be traumatic to people subject to brain seizures especially in event of a sudden notification

**Comment by srenault-meeds** [comment]
Thanks for this feedback. It already has been reported there: https://github.com/Meeds-io/meeds/issues/510
