### ISSUE TITLE
Development of a mobile app

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1804]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm using my phone to access meeds.io because there are some back end functions that are optimized for websites such as be curating of videos or searching for bugs or attempting to look for security vulnerabilities 

**Describe the solution you'd like**
I'd like to suggest the development of a mobile application 

**Describe alternatives you've considered**
Alternatives that I have considered are web applications that can be accessed through a web browser 

**Additional context**
A mobile application will be a swelled idea for it will enable and ease push notifications and even enhance monetization and the general reach of the platform

**Comment by srenault-meeds** [comment]
Thanks. It already has been proposed there: https://github.com/Meeds-io/meeds/issues/516
