### ISSUE TITLE
Characters counter not well displayed in task description

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#181]
**Steps to reproduce**

1. Go to any task project
2. Click on 'Add a new task' action from the status 
3. Click to 'Description' to add a description
4. Check the characters counter, it is not aligned to the editor options

Check screenshot

**(optional) Affected version**

6.4.x

**Current behaviour**

In the task description, when creating a task, characters counter is not displayed well.

**Expected behavior**

The characters counter should be aligned to the editor options as it is when updating a description.

**(optional) Affected environments**  
Please complete the following information: 
<img width="230" alt="Screenshot 2022-06-13 151906" src="https://user-images.githubusercontent.com/58853195/173362718-ebb6e35b-364d-4748-9652-5d3835be141d.png">
 - Browser: Brave or FF

**Comment by mzorai** [comment]
@Samuel-Renault-eXo IMO this a UX item

**Comment by srenault-meeds** [comment]
Yes, fixing in progress

**Comment by srenault-meeds** [comment]
Fixed
