### ISSUE TITLE
Points Reduction 

### ISSUE THREAD

**Issue by GvoiceCrypto** [Meeds-io/meeds#1821]
It sounds like there might be a bug in the DAO system causing approved points to be reduced. 
This could be due to various reasons such as technical glitches or errors in the validation process. One solution could be to thoroughly audit the DAO's codebase to identify and fix any bugs or vulnerabilities causing the point reduction issue. 
Additionally, implementing more robust testing procedures and error handling mechanisms can help prevent such issues in the future. Regular maintenance and updates to the DAO platform are also essential to ensure its smooth operation.

**Comment by srenault-meeds** [comment]
Hi @GvoiceCrypto can you please be more precised?
For example, which tasks are you suspecting?
