### ISSUE TITLE
Login with not existing user displays blank page

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#1826]
**Steps to reproduce**

1. Go to Login page
2. Try to login with non existing user
3. See page result

**Current behaviour**

Empty blank page is displayed

**Expected behavior**

Login page should be displayed with error message to inform that login doesn't succeeded 

**(optional) Affected environments**  
Version: 1.6.x-SNAPSHOT (develop)

**Comment by srenault-meeds** [comment]
Indeed, reproduced. Thanks
