### ISSUE TITLE
Bad display in kudos TAB when no Kudos is sent yet .

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#183]
**Steps to reproduce**
1- consult an activity with many reactions 
2- click on "X Reactions" from the reaction bar 
3-click to open "Kudos"  TAB
**Actual behavior :** 
The kudos icon and the text are not displayed as expected.

![kudos TAB display](https://user-images.githubusercontent.com/50736962/173364809-aefcf4d7-7d2b-4fa4-a873-9f534cede3f6.png)

**Expected behavior :** 
 The icon should be above then the text should be below it.

**Comment by mzorai** [comment]
@Samuel-Renault-eXo FYI

**Comment by srenault-meeds** [comment]
Yes fixed now
