### ISSUE TITLE
[Stream] Kudos message font text is smaller than expected

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1836]
**Step of reproduction:**

1- Send a kudos to someone
 2- Observe the text of the activity generated on the stream

**Current behavior:**

On kudos activities, the kudos description written by the user appears smaller than standard text size.

**Expected behavior:**

The text size must be standard (at least the same as comment)

**Comment by Prettyinem** [comment]
The text size is okay 💯
