### ISSUE TITLE
wrong number of tasks in project card detail

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#1837]
Steps to reproduce:

Go to Tasks app
Create 2 tasks
Put one task as completed
Result in this case:

the card project shows: 1: to do 0: in progress 0: waiting on 0: done

total number: 2

Actual behavior:

Completed tasks are included in the total number of tasks

Expected behavior:

Completed tasks should not be counted in the total number of tasks.

**Comment by srenault-meeds** [comment]
Hello @GouadriaHanen @Jihed525 can you please tell us what this is about? A bug or a feature enhancement?
And is it done?

**Comment by Jihed525** [comment]
Task project details counter includes the closed tasks
fix added counts only open tasks, closed ones are exluded and never counted
issue done

**Comment by Jihed525** [comment]
a bug
