### ISSUE TITLE
Enhance the way to check if I already won a challenge

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#184]
**Is your feature request related to a problem? Please describe.**
I'm always not sure when I want to announce an achievement on a challenge if I have already announced it

**Describe the solution you'd like**
I want to know if I have already announced an achievement without going to the list of winners

**Describe alternatives you've considered**
I have two alternatives:
- Indicate with an informative message that I'm already won this challenge
- In the creation step of the challenge, indicate if the challenge can be won one or more times by the same user. This will allows to disable announce button in the first case if the challenge is already announced and keep the announce button enabled anytime I want to do my announcement

**Comment by srenault-meeds** [comment]
In case you can announce a challenge only once, when you have participated once, then we inform you that you have already participated and you cannot do it again.

Considered as done
