### ISSUE TITLE
Unable to use the "forgot password"

### ISSUE THREAD

**Issue by Ryker102** [Meeds-io/meeds#1840]
**Steps to reproduce**

1. Go to 'https://builders.meeds.io/portal/meeds'
2. Click on 'forgot password'
3. Scroll down to 'username and password'

If applicable, add screenshots to help explain your problem.![Screenshot_20240404-074319_Chrome.jpg](https://github.com/Meeds-io/meeds/assets/164161732/a39aaa9a-a11b-4978-b25e-531fa461747c)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.
The landing page is blank, unable to load any further 
**Expected behavior**

The landing page is supposed to show a message that indicates that Email verification link has been sent
**(optional) Affected environments**  
Please complete the following information: 
 - Browser [e.g. chrome, safari yes]

**Comment by srenault-meeds** [comment]
Hi,

You must see this when clicking to forgot password, not a blank page. 
![Screenshot_20240408_162951](https://github.com/Meeds-io/meeds/assets/58853195/afa1f6e7-8f2f-4d72-bbbb-6886ec7c1afb)


As you reported that you scroll down to username and password, I think this is something else you are trying to report, which has been fixed. Thanks
