### ISSUE TITLE
Implementation of expert Q&A section

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1846]
**Is your feature request related to a problem? Please describe.**
It's always frustrating when i have questions to ask and there is no dedicated page on the website where I could easily go to have my questions answered instantly 

**Describe the solution you'd like**
I would like to suggest an expert Q&A section where users and contributors can have questions they have answered either automatically by a bot or manually by a person for the more complicated questions 

**Describe alternatives you've considered**
Alternative would be the use of emailing to contact the executives of the platform 

**Additional context**
I would also like to add that if this feature is implemented an additional survey be added to verify that the person making the enquiry's satisfaction has been met

**Comment by srenault-meeds** [comment]
It is actually proposed on the [discord server ](https://discord.com/channels/914550621443616830/1198150044507979836) and on the [github forum](https://github.com/orgs/Meeds-io/discussions)
