### ISSUE TITLE
Implementation of skill sharing 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1847]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I can't perform a task simply because I don't have the right skill set to perform that task 

**Describe the solution you'd like**
I would like yo suggest the provision of skill sharing in the platform when contributors can share valuable skills amongst themselves 

**Describe alternatives you've considered**
Watching available tutorials 

**Additional context**
If I may add skill sharing could even be a task on its own where contributors can earn poimts for sharing a valuable skill

**Comment by srenault-meeds** [comment]
You can ask for help to the community (discord server) and tutorials are already provided by the community
