### ISSUE TITLE
[UX] Change the cross icon used in alert notification in stream page to the correct one

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#185]
**Steps to reproduce**
1- The cross icon of alert notification for these cases ( when sharing an activity or giving a kudos comment to a user or when no more kudos are left )  still uses a cross icon that does not respect the UX guideline. 
**Actual behavior:** 
A grey cross icon is available on the alert notif 

**Expected behavior:** 
The cross icon used should be the one used in wallet, perks , tasks , challenges ( Green not grey)

**Comment by mzorai** [comment]
@Samuel-Renault-eXo FYI

**Comment by srenault-meeds** [comment]
Yes, considered
