### ISSUE TITLE
Implementation of token burn mechanism 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1853]
**Is your feature request related to a problem? Please describe.**
It's always frustrating when at the end of the week the contributors meed are distributed and the value has dropped 

**Describe the solution you'd like**
I suggest the implementation of a token burn mechanism where a portion of transaction fees or unused tokens are periodically burned, reducing the overall token supply and increasing the value of remaining tokens 

**Describe alternatives you've considered**
An alternative could be increasing the points of tasks so contributors can earn more 

**Additional context**
This suggestion is an economic one in a bid to find a way to make contributors earn more meeds

**Comment by srenault-meeds** [comment]
@plamarque WDYT?

**Comment by plamarque** [comment]
Our aim is not to artificially inflate price for swappers, it's to create value for holders.

IMO, rewards in stablecoin would be a better solution for the underlying need expressed in this issue.
