### ISSUE TITLE
The problem I'm having is that I don't see much tasks to do everyday on the social media I'm in. 

### ISSUE THREAD

**Issue by LuckyJ2** [Meeds-io/meeds#1857]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LuckyJ2** [comment]
![Screenshot_20240411-224116.png](https://github.com/Meeds-io/meeds/assets/166445827/6462580a-74be-4721-92c2-cdb9392b9798)

I'm having less daily tasks issues.

**Comment by srenault-meeds** [comment]
No relation with the product but with the community management. Please address it to the team using Discord.
