### ISSUE TITLE
Implementation of an integrated help desk 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1862]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I can't get technical problems such as doing an automated task and it not being reflected on my account to be properly attended to and solved because there is no help desk on the buildershub in meeds.io 

**Describe the solution you'd like**
Implementing an integrated help desk within the builders hub of Meeds DAO website involves incorporating a dedicated section or feature where users can access comprehensive support resources, submit inquiries, and receive assistance from customer support representatives. This help desk can include various components such as:
Knowledge Base: Create a repository of articles, FAQs, tutorials, and troubleshooting guides covering a wide range of topics related to platform usage, features, and common issues.
Ticketing System: Enable users to submit support tickets or inquiries directly from the website interface. Each ticket can be assigned a unique reference number for tracking purposes.
Live ChatSupport: Offer real-time chat support where users can interact with support agents to resolve queries or issues instantly. This feature enhances the user experience by providing immediate assistance.
**Describe alternatives you've considered**
Create a dedicated FAQ section within the website containing answers to commonly asked questions and troubleshooting tips. While helpful, this static resource may not address all user queries and lacks the interactive support features of an integrated help desk.
Clearly display contact information such as email addresses, phone numbers, and social media links for users to reach out to customer support via alternative channels if needed.

**Additional context**
implementing an integrated help desk provides an efficient support solution for Meeds DAO users, offering comprehensive assistance directly within the website interface. Alternatively, in the absence of an integrated help desk, the organization can explore alternative support channels to address user queries

**Comment by srenault-meeds** [comment]
Thanks. All of these items are already provided:
- Support team available for you on Discord Server
- [FAQ](https://github.com/orgs/Meeds-io/discussions/categories/q-a)
- [Documentation](https://meeds.gitbook.io/meeds-guides)
- [Tips and tricks Video playlist](https://www.youtube.com/watch?v=i7aXG9BV19w&list=PLKiwXWfZwt59d_FuykfsuYqco_XA-Es5t&pp=iAQB)
