### ISSUE TITLE
Implementation of file upload limits 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1864]
**Is your feature request related to a problem?  
Without these limitations, there's a risk of malicious files being uploaded, leading to security breaches, malware infections, or even the compromise of personal information and the insecurity is frustratingsometimes. Users may unknowingly download harmful files or inadvertently share sensitive data.

**Describe the solution you'd like**
administrators can implement robust file upload restrictions and validation mechanisms. This involves setting clear guidelines for acceptable file types, sizes, and naming conventions. Additionally, utilizing server-side validation techniques, such as file type verification and malware scanning, can further enhance security.

**Describe alternatives you've considered**
In the absence of proper file upload restrictions, alternative measures can be taken to mitigate risks. One approach is to disable direct file uploads altogether and instead provide users with secure, indirect methods for sharing content, such as through cloud storage services or file-sharing platforms. 

**Additional context**
Additionally, implementing user permissions and access controls can limit who can upload files and where they can be stored, reducing the likelihood of unauthorized or malicious uploads.

**Comment by srenault-meeds** [comment]
We don't provide file upload tool except the image one which is already limited.
