### ISSUE TITLE
Implementation of a dedicated contact page

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1865]
**Is your feature request related to a problem? Please describe.**
As a user, not finding a dedicated contact page can be frustrating and time-consuming. When I visit the website seeking to get in touch with the adminstrators or find their contact details, having to search through various pages or hunt for a  "Contact Us" link can be a hassle. This makes it difficult for me to reach out with questions, concerns, or inquiries.

**Describe the solution you'd like**
The solution to this issue lies in creating a dedicated contact page prominently displayed in the website's main navigation menu or header. 

**Describe alternatives you've considered**
Include a frequently asked questions (FAQ) section that addresses common inquiries, which can help alleviate the need for immediate contact in some cases.

**Additional context**
By implementing these solutions or alternatives, websites can enhance the user experience by providing easy access to contact information, ultimately leading to increased user satisfaction and engagement.

**Comment by srenault-meeds** [comment]
We already provide such option in the "[about-us](meeds.io/about-us)" page
