### ISSUE TITLE
Copy address doesn't work perfectly

### ISSUE THREAD

**Issue by MayTekayaa** [Meeds-io/meeds#187]
**Steps to reproduce**

1. Go to '" https://investors.meeds.io/dapp/snapshot "
2. Go to "Your assets" block at the bottom of the page.
3. Hover over the " i " icon.
4. Then copy the address displayed on the tooltip by clicking on the " copy " icon.

**Current behaviour**

The address connected in the top of the investors application is copied.

**Expected behavior**

The address displayed in the tooltip must be copied.

**Comment by plamarque** [comment]
which browser ?

**Comment by MayTekayaa** [comment]
I have tested chrome and Firefox browsers

**Comment by mzorai** [comment]
Related task https://builders.meeds.io/portal/meeds/tasks/taskDetail/302

**Comment by srenault-meeds** [comment]
@MayTekayaa I can't reproduce it can you tell me if you still see this behaviour?
