### ISSUE TITLE
[People] Reset CTA in placeholder doesn't work

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1874]
**Steps to reproduce**

1. Go to a profile
2. Click on an item to open the people quick search drawer
3. Search for something to make the placeholder appear
4. The placeholder suggests to reset the search
5. See error: clicking to 'Reset' doesn't work

![quick search reset ko](https://github.com/Meeds-io/meeds/assets/58853195/762594ab-dcde-4f1a-8f75-85d00000c159)

**Expected behavior**

Clicking to Reset reset the search text filters and any other filters
Once done, it updates back the list to default status

**Comment by srenault-meeds** [comment]
As discussed, here is the issue reported there https://github.com/Meeds-io/MIPs/issues/110#issuecomment-2061075455

cc @Julien-Dubois-eXo @margondicco

**Comment by srenault-meeds** [comment]
up? @Julien-Dubois-eXo

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds it's already fixed
