### ISSUE TITLE
[People] People Overview is empty - REG - 

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1878]
**Steps to reproduce**

1. Given I am a user with connections
2. Go to People
3. Chec the people overview
4. See error: it is empty

https://github.com/Meeds-io/meeds/assets/58853195/84b649c4-ee2d-4203-99c4-e5d6d2cd3171

**Expected behavior**
People overview is displayed as expected

**Comment by srenault-meeds** [comment]
@Jihed525 @Julien-Dubois-eXo @margondicco FYI

**Comment by srenault-meeds** [comment]
Hello any news please?

**Comment by srenault-meeds** [comment]
hello @Jihed525 @rdenarie @Julien-Dubois-eXo any news please? indeed, among other things, it seems to be the most annoying regression
Thanks

**Comment by rdenarie** [comment]
@srenault-meeds 
Can give more details : 

- On which instance do you the the problem ?
- With which account  ?
- In description you speaks about "People Overview", but in the screencast, you show the bloc "People Connections". Is it the same thing in your mind ?

On my side, on builder instance, no pb : 
![image](https://github.com/Meeds-io/meeds/assets/807839/507afd6a-26fb-4b2b-b227-10f85f68d484)

**Comment by srenault-meeds** [comment]
The portlet is called "People Overview"
And the platform used in the screencast is builders. I reproduce it using firefox or chrome or brave. 
And it is reproduced on tribe too

**Comment by rdenarie** [comment]
Can you confirm that the screen I provide is the expected ? 
Two information are displayed : the number of invitation I receive ("Invitations"), and the number of invitation I sent ("Demandes envoyées) ?

In the screencast, you go in your profile, then click on "Connections", which open a drawer. This drawer list validated connection, right ? So I dont understand how it is related to the gadget on people page ?

**Comment by srenault-meeds** [comment]
ok, well it seems I was wrong :D 
So I close it as not planned

It is actually ok
