### ISSUE TITLE
Implementation of improved search functionality 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1882]
**Is your feature request related to a problem? Please describe.**
As contributor in meeds.io, the lack of enhanced search functionality can be quite frustrating. When I'm trying to find specific tasks or information within the Builders Hub, the current search feature might not yield accurate or relevant results. This can waste my time and lead to a less-than-optimal user experience.

**Describe the solution you'd like**
The solution to this issue would be to implement a more robust search functionality that includes features such as:
Keyword Filtering: Allowing users to filter search results based on specific keywords related to tasks or topics they're interested in.
Advanced Filters: Providing advanced filters such as task type, reward amount, or completion status to narrow down search results further.
Auto-Suggestions: Implementing an auto-suggest feature that predicts search queries as users type, helping to speed up the search process and improve accuracy.
Search by Tags: Allowing users to search by tags or categories assigned to tasks, making it easier to find tasks within specific areas of interest.
Synonym Recognition: Recognizing synonyms and related terms to ensure that users find relevant results even if they don't use the exact keywords.
Fuzzy Search: Employing fuzzy search algorithms to account for spelling errors or variations in terminology, ensuring that users still find relevant results even with minor discrepancies.

**Describe alternatives you've considered**
Manual Browsing: Users may manually browse through task categories or listings, which can be time-consuming and less efficient compared to using a search feature.

**Additional context**
Enhancing the search functionality within meeds.io's Builders Hub would greatly improve the user experience by allowing users to quickly and efficiently find the tasks or information they're looking for, ultimately increasing user satisfaction and engagement with the platform.![Screenshot_20240420-144121_Chrome.jpg](https://github.com/Meeds-io/meeds/assets/161255018/1fee6d15-4062-4d34-ac0f-b0abcff9befa)

**Comment by srenault-meeds** [comment]
We already implement content-type filtering, tags, favorites and fuzzy search including extended search in content
