### ISSUE TITLE
Implementation enhanced task descriptions 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1883]
**Is your feature request related to a problem? Please describe.**
As a user of the Meeds DAO website, i encounter frustration with unclear task descriptions. This lack of clarity can make it challenging to understand exactly what is required to complete a task, leading to confusion and wasted time. The frustration arises when you're unsure about the specifics of a task, such as the desired outcome, the steps involved, or any specific criteria for completion. Without clear guidance, you may find yourself hesitant to start or unsure about whether your efforts align with the task's objectives. This uncertainty can lead to frustration and ultimately impact your motivation to participate in tasks.

**Describe the solution you'd like**
To address this issue, enhancing task descriptions is crucial. The solution lies in providing detailed and comprehensive explanations of each task, including clear instructions, specific requirements, and examples if possible. By clearly outlining what is expected, users can approach tasks with confidence, knowing exactly what needs to be done to succeed.

**Describe alternatives you've considered**
Task Clarification Channel: Create a dedicated channel or forum where users can request clarification on specific tasks. This allows users to seek clarification directly from platform administrators or task creators, helping to reduce ambiguity.

**Additional context**
Here are some task whose mission is quite unclear 
![Screenshot_20240420-151401_Chrome.jpg](https://github.com/Meeds-io/meeds/assets/161255018/2eba7a1f-2933-45fd-a4be-50f94073c0ff)

**Comment by srenault-meeds** [comment]
No relation with the product
