### ISSUE TITLE
Implementation of voice search functionality 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1886]
**Is your feature request related to a problem? Please describe.**
As a contributor, i frustrating to navigate through the website, especially when i am multitasking or unable to type, such as when driving or cooking. Without voice search, you're forced to manually input your queries, which can be time-consuming and inconvenient.

**Describe the solution you'd like**
The solution is to implement a voice search feature that allows users to simply speak their queries instead of typing them. This feature would utilize speech recognition technology to convert spoken words into text and then execute the search based on the input.

**Describe alternatives you've considered**
Enhance the existing search functionality with advanced filters and options to help users narrow down their search results more efficiently. This can compensate for the lack of voice search by providing a more precise search experience.

**Additional context**
implementing a voice search feature remains the most direct and user-friendly solution to address the frustration experienced by users who rely on hands-free interaction.

**Comment by srenault-meeds** [comment]
You can use the tool from your device to voice your content directly and then this will be added in the search field
