### ISSUE TITLE
Implementation of text to speech 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1888]
**Is your feature request related to a problem? Please describe.**
The lack of a Text-to-Speech feature on our website and platform can be frustrating for users who have visual impairments, learning disabilities, or simply prefer auditory input. Without this feature, these users may struggle to access and understand the content, leading to a less-than-optimal user experience. Additionally, users who are multitasking or unable to focus on reading may also find it inconvenient to navigate through text-heavy content without an alternative auditory option.

**Describe the solution you'd like**
I propose the implementation of a Text-to-Speech feature that converts written text on the website and the Builders Hub platform into spoken words. This feature will allow users to listen to the content instead of reading it, providing a more inclusive and accessible experience. Users will have the option to activate the TTS feature with a simple click or tap, enabling them to access information hands-free and on the go.

**Describe alternatives you've considered**
Users with visual impairments may already use screen reader software to navigate websites. However, this solution may not be suitable for users who do not require full screen reader functionality but still prefer auditory input.

**Additional context**
Incorporating a Text-to-Speech feature into the Meeds DAO website and the Builders Hub platform will significantly enhance accessibility, convenience, and inclusivity for all users.

**Comment by srenault-meeds** [comment]
It is already possible to use a browser extension like read aloud. Indeed, we don't plan to implement such tool while it can be added by the user itself to read any other websites
