### ISSUE TITLE
Implementation of swipe gestures for navigating the website 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1889]
**Is your feature request related to a problem? Please describe.**
Without swipe gestures, users are forced to rely solely on buttons or arrows to move through the content, which can be cumbersome and unintuitive, especially on smaller screens. This lack of swipe functionality can lead to a disjointed and frustrating user experience, as users may expect the natural gesture of swiping to navigate, similar to how they interact with other apps and websites.

**Describe the solution you'd like**
implement swipe gestures for navigating through galleries or slideshows on touch devices. By allowing users to swipe left or right to move between images or slides, the user experience becomes more intuitive and seamless. 

**Describe alternatives you've considered**
In the absence of swipe gestures, alternatives may include providing clear and prominent navigation buttons or arrows for users to click on to navigate through the content.

**Additional context**

This enhancement not only improves usability but also aligns the website's navigation with users' expectations, ultimately leading to higher engagement and satisfaction.

**Comment by srenault-meeds** [comment]
Hi, it is already possible to swipe from image to another image where multiple images are shared in a post
Same when reading notifications to either delete it or to mark it as unread.

We don't plan to extend it for now

**Comment by Abuteslimah99** [comment]
Acknowledged sir
