### ISSUE TITLE
Typo error on https://investors.meeds.io/ (french version)

### ISSUE THREAD

**Issue by RemeXo** [Meeds-io/meeds#189]
1. Go to '(https://investors.meeds.io/) FR language'
2. Click on 'Staker' section (1st screenshot) or "Deeds" section (2nd screenshot)
3. See typo errors on screenshots 

<img width="1439" alt="Capture d’écran 2022-06-20 à 18 00 45" src="https://user-images.githubusercontent.com/107874888/174641755-9a22c4d9-b1fb-4ea5-91e9-e90571ac8aed.png">
<img width="1439" alt="Capture d’écran 2022-06-20 à 18 03 00" src="https://user-images.githubusercontent.com/107874888/174641746-bd73d18f-0ac4-476a-b399-1cc2078b050e.png">

**Comment by mzorai** [comment]
I think this could be fixed in crowdin labels

**Comment by mzorai** [comment]
@plamarque could you please point me to investors app crowdin project? Thanks

**Comment by plamarque** [comment]
investors app strings are not in Crowdin (yet). It's  just in code : https://github.com/Meeds-io/deeds-dapp/blob/0b4099a0ee644a76c9f940c36db55478c9ab5151/deeds-dapp-webapp/src/main/webapp/vue-app/json/i18nMessages.json#L210

**Comment by srenault-meeds** [comment]
Fixed in crowdin. To be checked after deployment
