### ISSUE TITLE
Implementation of task history 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1892]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to check the history of my performance on a particular task and I have to sort through everyone's contribution in that particular task 

**Describe the solution you'd like**
The Introduction of a comprehensive "Task History" feature that provides users with a detailed overview of their completed tasks, associated rewards, and any feedback received. 

**Describe alternatives you've considered**
Contributors could maintain their task history manually, but this is time-consuming and prone to errors. It also lacks the convenience and integration that an automated task history feature would provide.

**Additional context**
Ensuring the Task History feature includes relevant details such as task descriptions, completion dates, reward amounts, and any accompanying feedback will enhance its usefulness to users. Providing options for users to filter and sort their task history based on various criteria, such as date range or task type, would further improve usability and accessibility.

**Comment by srenault-meeds** [comment]
It is already possible to track your own contributions. Access [this page ](https://builders.meeds.io/portal/mycraft/dashboard/achievements) and you will be on your own ;-)
