### ISSUE TITLE
Implementation of online/offline status and last seen feature 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1893]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I want to contact a fellow contributor on tye platform or a reviewer and there is no way of knowing whether they are online or not or when they were last seen online to know their availability status 

**Describe the solution you'd like**
Implementation of online/offline status and last seen feature that would indicate whether a contributor is currently on the platform or not and when they were last on the platform 

**Describe alternatives you've considered**
Alternatives would be an available/unavailable or do not disturb feature on the platform that can be adjusted manually by the cintributor depending on how available they are 

**Additional context**
![Screenshot_20240421-182944_Discord.jpg](https://github.com/Meeds-io/meeds/assets/161255018/bcc7ab06-cbb5-49a5-91dd-f5bc83389fc8)

**Comment by srenault-meeds** [comment]
We don't implement chat features so this one is not useful for now
