### ISSUE TITLE
Introduction of project collaboration spaces 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1895]
**Is your feature request related to a problem? Please describe.**
The absence of dedicated Project Collaboration Spaces within the MEEDS DAO platform has been a source of frustration for contributors. Currently, users lack a centralized platform to coordinate and collaborate on larger projects efficiently. As a result, communication is scattered across various channels, leading to confusion, delays, and missed opportunities for meaningful collaboration.

**Describe the solution you'd like**
I propose the implementation of Project Collaboration Spaces, dedicated areas within the MEEDS DAO platform where users can seamlessly collaborate on projects, share resources, assign tasks, and track progress in real-time. These spaces will provide a structured environment for users to work together effectively, fostering innovation and productivity within the community.

**Describe alternatives you've considered**
Some users may resort to using email or messaging platforms for project collaboration. However, these methods lack the structure and organization needed for effective project management and may result in important information getting lost or overlooked.

**Additional context**
The introduction of this feature aligns with our commitment to empowering our community members and fostering a culture of collaboration and innovation within the MEEDS DAO ecosystem.

**Comment by srenault-meeds** [comment]
It is already possible. Check for example the MeedsLab space
