### ISSUE TITLE
Implementation of virtual workshops 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1896]
**Is your feature request related to a problem? Please describe.**
The absence of virtual workshops on the MEEDS DAO platform is frustrating contributors who seek opportunities for skill development, knowledge sharing, and networking within the community. Without access to virtual workshops, contributors are missing out on valuable learning experiences and opportunities to connect with industry experts and peers.

**Describe the solution you'd like**
Implement virtual workshops on the MEEDS DAO platform to address the needs and frustrations of contributors. Virtual workshops will provide an interactive and educational environment where contributors can participate in live sessions, engage with expert speakers, and collaborate with fellow community members on relevant topics.

**Describe alternatives you've considered**
Utilize third-party platforms or tools to host virtual workshops if developing an in-house solution is not feasible.

**Additional context**
It is important to ensure that virtual workshops cover a diverse range of topics to cater to the interests and needs of a broad audience within the community.

**Comment by srenault-meeds** [comment]
We don't plan to implement such feature and if needed, you can use the discord server to organize such workshop
