### ISSUE TITLE
Update to jdk 21

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#1932]
JDK 21 is the last available LTS java version.

We should build and run on this version

**Comment by rdenarie** [comment]
Hi @boubaker 

I prepare PR to jump to JDK 21.

Once these PRs are merged, build will still work with JDK17.

So, my proposition is : 

- You take a quick look on 3 PRs
- If no objection, I merge on develop, ask for a release of maven-parent-pom and addon-parent-pom
- When all PRs are merged, I ask to update jenkins build job and deployment job to be update to use jdk21

**Comment by boubaker** [comment]
Great move, thanks.

@rdenarie there is already an MIP for this https://github.com/Meeds-io/MIPs/issues/91
Can you please use it for initiating the Upgrade switch MIP process

**Comment by boubaker** [comment]
Besides, I think we should do a deep cleanup to delete the usage of Security Manager in Core Foundation projects, see https://nipafx.dev/road-to-21-upgrade/ for more information about changes to take care of.

**Comment by rdenarie** [comment]
Close this issue as there is a MIP on it (meeds-io/MIPs#91)
