### ISSUE TITLE
navigation menu of notes app not displayed in home page note's body

### ISSUE THREAD

**Issue by hthabti** [Meeds-io/meeds#1934]
version 7.x
**steps:**
open note app of spacex
create notes
in home page add navigation menu through insert options
**actual:**
notes not displayed + output in browser colsole "Error when getting note TypeError: this.getNoteLanguages is not a function"
**expected:**
display notes in home page

**Comment by srenault-meeds** [comment]
Hi @hthabti ,

What it the status, please?

**Comment by Jihed525** [comment]
closed as no longer reproduced
