### ISSUE TITLE
Popular spaces gadget : "Hidden space" displayed to admin

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#194]
**Steps to reproduce**

1. Create various hidden spaces
2. Generate significant activity on them so they are featured in the Popular spaces
3. As an administrator, make sure you are NOT member of the hidden spaces
4. Look at the Popular spaces gadget, it display various "Hidden space"

<img width="309" alt="hidden-spaces" src="https://user-images.githubusercontent.com/227828/175259019-7ceed5d8-914b-4b91-bf55-da7662fd8b7e.png">

**(optional) Affected version**

Meeds 1.4

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.

**Expected behavior**

As an administrator, I should see the name and icon of these spaces but I should also be informed that they are hidden spaces.

**Comment by srenault-meeds** [comment]
Hi, I suggest to not display these spaces at all. Indeed, if the admin wants to know more about spaces use, he can check analytics. 
So the user journey should be this:
* When I browse the platform as a regular user, I see the same thing as any other regular user even I have admin role
* When I access admin features, then I can dig into more analytics to check the usage in spaces, to understand what is going on and to help space hosts if needed.

So suggestion:
* For consistency, we should not display at all these spaces no matter you are admin or not.
* Of course, an admin can still go check these spaces if needed.
WDYT?

**Comment by srenault-meeds** [comment]
In progress

**Comment by srenault-meeds** [comment]
Solved FYI
