### ISSUE TITLE
Implementation of Captchas 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1942]
**Is your feature request related to a problem? Please describe.**
As a user of Meeds DAO, I'm frustrated by the absence of CAPTCHAs, which leaves the platform vulnerable to automated bots and spam attacks.

**Describe the solution you'd like**
Implement CAPTCHAs across key interaction points on the Meeds DAO platform, such as during user registration, login, and submission of forms or tasks.

**Describe alternatives you've considered**
 In the absence of CAPTCHAs, Meeds DAO could experience an influx of spam accounts, fake registrations, and fraudulent activities. To mitigate these risks, alternative measures such as email verification, two-factor authentication (2FA), and manual account approval processes could be implemented. However, these alternatives may not offer the same level of protection against automated attacks as CAPTCHAs.

**Additional context**
CAPTCHAs serve as a crucial layer of defense against automated attacks by requiring users to prove their humanity through challenges like image recognition or text verification. By incorporating CAPTCHAs, Meeds DAO can enhance security, protect user data, and maintain the integrity of the platform

**Comment by srenault-meeds** [comment]
I disagree with this one, we already captcha for the registration process + we request the email confirmation.
For login, in case the user tries to access the platform multiple times with a wrong password, the account is suspended (anti brut force process).
Of course, we might extend this to a 2FA when accessing the platform or any page and you already have reported it [here](https://github.com/Meeds-io/meeds/issues/1822)

Thanks
