### ISSUE TITLE
Notes: If space name updated, link is broken

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#195]
**Steps to reproduce**

1. Go to a space you are hosting
2. Click on notes app, get the URL and keep it somewhere
3. In the space settings, change the name of the space
4. Then paste the notes URL in your browser
5. See error: the notes is not displayed but the user is sent to the space home. The problem is that the URL is not recognized anymore.

GIF there:
![pb notes and updated space name](https://user-images.githubusercontent.com/58853195/175482609-578d440b-ccb2-4cf8-ae9e-d6755519236b.gif)

**(optional) Affected version**

Indicate the version where the bug is observed: 1.4.x

**Expected behavior**

The notes should be displayed no matter the space has been changed.
Suggestion:
* Remove the prettyName from the URL and only keep the original name
* Or remove any mentions to the space name in the URL as other tools does so the URL is still the same no matter the notes page changes

**Comment by mzorai** [comment]
@Samuel-Renault-eXo I think this is UX WDYT ?

**Comment by srenault-meeds** [comment]
Yes, and fixed :-)
