### ISSUE TITLE
Implementation of the "Save for Later" feature 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1950]
**Is your feature request related to a problem? Please describe.**
As a contributor in the builders hub on the Meeds DAO website, the absence of a "Save for Later" feature frustrates me. Often, I come across valuable content, discussions, or projects that I wish to revisit or explore further, but without the ability to save them, I risk losing track of important information.

**Describe the solution you'd like**
Introduce a "Save for Later" feature that allows users to bookmark content, discussions, or projects for future reference. 

**Describe alternatives you've considered**
Allow users to create custom lists or folders where they can organize saved items based on their preferences or topics of interest.

**Additional context**
The "Save for Later" feature not only enhances user experience by empowering contributors to better manage and engage with platform content but also fosters a sense of ownership and investment in the community by facilitating ongoing participation and exploration.

**Comment by srenault-meeds** [comment]
Hi @Abuteslimah99 you already have this option with the bookmark feature.
Please see below:
![bookmark](https://github.com/Meeds-io/meeds/assets/58853195/26cc2c3b-1615-47bb-ae3d-94cb62010cd2)

**Comment by Abuteslimah99** [comment]
Seen sir
