### ISSUE TITLE
Implementation of Tooltips 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1951]
**Is your feature request related to a problem? Please describe.**
As a contributor on the Meeds DAO platform, navigating through its features can be daunting, especially without adequate guidance. The lack of tooltips leaves me feeling frustrated and confused, inhibiting my ability to fully utilize the platform's capabilities and contribute effectively.

**Describe the solution you'd like**
Implement tooltips strategically placed throughout the platform to provide clear explanations and guidance on various features and functionalities. These tooltips should offer concise information and actionable tips to help new contributors understand how to navigate the platform efficiently and make meaningful contributions.

**Describe alternatives you've considered**
Creation of a community forum or knowledge base where contributors can find answers to common questions and share best practices with fellow members.

**Additional context**
Providing tooltips not only enhances the user experience for new contributors but also fosters a sense of confidence and empowerment, ultimately leading to increased engagement and participation within the Meeds DAO community ![Screenshot_20240506-231946_Chrome.jpg](https://github.com/Meeds-io/meeds/assets/161255018/e37e848f-cab6-411d-8892-973631e431c2)

**Comment by srenault-meeds** [comment]
Thanks. These are already in place when needed and if tooltips are not sufficient enough, we already have a drawer to display more informations.
See examples below:

Basic tooltip:
<img width="197" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/76a00064-d2ac-42cb-a308-d313551c96e0">

Enhanced information drawer
![enhanced information drawer](https://github.com/Meeds-io/meeds/assets/58853195/799275ca-c638-4cc0-84f2-3dfe2fa2f51c)
