### ISSUE TITLE
[People] Some actions on people ui glitches the filter

### ISSUE THREAD

**Issue by mkrout** [Meeds-io/meeds#1956]
6.5 only
steps:
go to people interface
click on filter button and search for users by any profile attribute (exp: organisation=test)
once you get results click on connect/cancel reuest or see more
actual:
the results gets changed and displays not filtred users + the searched item is still maintained in the filter drawer
expected:
such actions shouldn't change the results

**Comment by srenault-meeds** [comment]
Hi @mkrout @Jihed525 ,

What it the status, please?

**Comment by Jihed525** [comment]
issue to be closed as fixed and validated
