### ISSUE TITLE
Inexistant JS Modules Error Log

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#1962]
**Steps to reproduce**

1. Start Meeds Server
2. See logs

![image](https://github.com/Meeds-io/meeds/assets/594824/03bc284e-6a34-43ef-9475-0aa1c2bd72b2)

**Current behaviour**

Some inexistant Modules are added in `content` addon

**Expected behavior**

Should remove undefined modules definition

**Comment by boubaker** [comment]
@rdenarie @azayati is this considered on your side ?

**Comment by azayati** [comment]
@boubaker ok we will consider that in the [MIP-130](https://github.com/Meeds-io/MIPs/issues/130)
