### ISSUE TITLE
Implementation of button hover effect 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1968]
**Is your feature request related to a problem? Please describe.**
As a contributor to the Meed Dao website, the absence of button hover effects has been frustrating. Without these effects, it's challenging for me to distinguish between interactive elements and static content. 

**Describe the solution you'd like**
Introducing button hover effects would greatly alleviate this frustration. When I hover over buttons, a subtle animation or color change would clearly indicate their interactive nature, guiding me towards taking action. This simple enhancement would significantly improve the user experience and make it easier for me to accomplish tasks on the website.

**Describe alternatives you've considered**
While button hover effects are the ideal solution, alternative methods could include adding text labels or tooltips to buttons, although these options may clutter the interface and detract from the overall aesthetics.

**Additional context**
This feature is essential for enhancing usability and increasing user engagement on the Meed Dao website. By providing clear visual cues, such as button hover effects, contributors like myself can navigate the site more intuitively, leading to higher productivity and satisfaction.

**Comment by srenault-meeds** [comment]
Can you please share with us factual examples? Indeed, we already provide such UX when needed

**Comment by srenault-meeds** [comment]
No update, so closed for now

**Comment by Abuteslimah99** [comment]
> Can you please share with us factual examples? Indeed, we already provide such UX when needed

![buttonstylesinspiration_feat3.gif](https://github.com/Meeds-io/meeds/assets/161255018/2061ffa2-5888-43ae-a2eb-fa0c3465012f)

**Comment by srenault-meeds** [comment]
Yes check our experience out below:
![action hover](https://github.com/Meeds-io/meeds/assets/58853195/c6a2b3ae-2dcb-495c-9dbd-f4aa271afebe)
![comment hover](https://github.com/Meeds-io/meeds/assets/58853195/757998c4-8fa6-4514-881c-7edd139a2600)
