### ISSUE TITLE
Implementation of star rating

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1969]
**Is your feature request related to a problem? Please describe.**
Absence of star ratings on a website frustrates contributors like me because it deprives me of a quick and visual way to quality guage 

**Describe the solution you'd like**
Implementation of star ratings on the platform  

**Describe alternatives you've considered**
Introduce a range of emoticons representing different levels of satisfaction, from happy to unhappy, to convey feedback.

**Additional context**
Star ratings serve as motivation for contributors, encouraging them to strive for excellence and improve their contributions.

**Comment by srenault-meeds** [comment]
Can you please explain more your concern?
Indeed, I don't clearly know where you want to add such option

**Comment by srenault-meeds** [comment]
No update, so closed for now

**Comment by Abuteslimah99** [comment]
> Can you please explain more your concern?
> Indeed, I don't clearly know where you want to add such option

To add it to uploaded content by reviewers
