### ISSUE TITLE
Implementation of opt-in cross device tracking feature 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1971]
**Is your feature request related to a problem? Please describe.**
As a user of the Meeds DAO website, I find it frustrating that I am unable to control or understand how my data is being tracked across different devices. Without the option to opt-in to cross-device tracking, I am left in the dark about how my interactions and preferences are being used to tailor my experience on the platform. 

**Describe the solution you'd like**
To address this frustration and enhance user trust and transparency, I recommend implementing an opt-in cross-device tracking feature on the Meeds DAO website. This feature would allow users to explicitly consent to having their data tracked across multiple devices for personalized experiences and improved usability. Upon visiting the website, users would be presented with a clear and concise message explaining the benefits of cross-device tracking and giving them the option to opt-in or opt-out based on their preferences.

**Describe alternatives you've considered**
Alternatively, if implementing opt-in cross-device tracking is not feasible, the Meeds DAO website could offer users the ability to manage their tracking preferences through a dedicated privacy settings section. This would allow users to selectively enable or disable certain tracking features, including cross-device tracking, based on their individual preferences and comfort levels. 

**Additional context**
By giving users control over cross-device tracking, the Meeds DAO website demonstrates a commitment to transparency and respect for user privacy, thereby enhancing trust and loyalty among its user base.

**Comment by srenault-meeds** [comment]
Are you talking about the Meeds DAO website? If so, then you have the cookie policy that is proposed when accessing the website

**Comment by srenault-meeds** [comment]
No update, so closed for now

**Comment by Abuteslimah99** [comment]
> Are you talking about the Meeds DAO website? If so, then you have the cookie policy that is proposed when accessing the website

Noted sir
