### ISSUE TITLE
Implementation of engagement metrics page/section or feature 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1972]
**Is your feature request related to a problem? Please describe.**
As a contributor to the Meeds DAO website, the absence of comprehensive engagement metrics leaves me frustrated and disconnected from understanding how users interact with my content. 

**Describe the solution you'd like**
To address this frustration and enhance the user experience for contributors like myself, I propose the implementation of robust engagement metrics tracking on the Meeds DAO website. By integrating tools such as Google Analytics or similar analytics platforms, we can gather valuable data on how users interact with our content.

**Describe alternatives you've considered**
While Google Analytics is a widely used and comprehensive analytics solution, alternative platforms such as Matomo (formerly Piwik) or Adobe Analytics could also be considered based on specific needs and preferences. 

**Additional context**
Additionally, custom-built analytics solutions tailored to the unique requirements of the Meeds DAO website could provide a more tailored approach to tracking engagement metrics.Implementing engagement metrics tracking will empower contributors to make data-driven decisions, leading to more impactful content and a better overall user experience.

**Comment by srenault-meeds** [comment]
If you talk about the website, no need to provide you such option, the association's Board can access such analytics.
If you talk about the hub, admins already have access to such analytics thanks to a built-in analytics module
