### ISSUE TITLE
Implementation of Content Security Policy(CSP)

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1978]
**Is your feature request related to a problem? Please describe.**
As a contributor to the Meeds DAO website, the absence of a Content Security Policy (CSP) has been a source of frustration for me. Without a CSP in place, our website is vulnerable to various cyber threats, including cross-site scripting (XSS) attacks. This not only jeopardizes the security of our platform but also undermines the trust of our users and contributors.

**Describe the solution you'd like**
To address this issue effectively, I propose implementing a robust Content Security Policy (CSP) for our website. A CSP serves as an additional layer of defense by specifying the trusted sources of content and scripts that can be executed on our web pages. By defining a strict CSP, we can significantly mitigate the risk of XSS attacks and other malicious activities targeting our platform.

**Describe alternatives you've considered**
If implementing a CSP directly on the website proves challenging, we can consider utilizing web security platforms or Content Delivery Networks (CDNs) that offer CSP configuration options as part of their services. Alternatively, we could explore integrating CSP management tools or plugins into our Content Management System (CMS) to streamline the implementation process.

**Additional context**
A CSP not only protects our website from XSS attacks but also helps prevent data exfiltration and other forms of code injection.

**Comment by srenault-meeds** [comment]
Our team is already aware about it. Thanks
