### ISSUE TITLE
Introduction of user generated contents 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#1982]
**Is your feature request related to a problem? Please describe.**
As an active contributor to the Meeds DAO community, the absence of a user-generated content feature on the website has been a source of frustration for me. Without the ability to showcase my contributions, share insights, or connect with fellow members through user-generated content, I feel limited in my ability to fully engage with the community and contribute meaningfully to its growth.

**Describe the solution you'd like**
Implementing a user-generated content feature on the buildershub in the Meeds DAO website would empower contributors like myself to share our experiences, insights, and ideas directly on the platform. This could include options to submit articles, blog posts, testimonials, or even multimedia content such as videos or infographics related to our involvement with Meeds DAO. By providing a dedicated space for user-generated content, the website would become a dynamic hub for community engagement, fostering collaboration, knowledge sharing, and creativity among members.

**Describe alternatives you've considered**
While third-party platforms like social media or forums can facilitate user-generated content, integrating these features directly into the Meeds DAO website would provide a cohesive and centralized experience for contributors.

**Additional context**
By introducing user-generated content functionality, the buildershub can elevate the voices of its contributors, foster a sense of ownership and belonging within the community, and ultimately strengthen the overall value proposition of the platform. This feature aligns with Meeds DAO's commitment to decentralization, inclusivity, and community-driven innovation, empowering every member to actively participate in shaping the future of decentralized finance.

**Comment by srenault-meeds** [comment]
Already the case with the educational or learn spaces and related actions
