### ISSUE TITLE
Utilization of more social media 

### ISSUE THREAD

**Issue by obajemu4255** [Meeds-io/meeds#1983]
**Is your feature request related to a problem? Please describe.**
It is a suggestion on utilization of more social media (Facebook) to reach a wider Audience for promotion. Facebook is the largest social media reaching out to every nation across the globe, it is the best place to elevate the platform and capture the widest audience 

**Describe the solution you'd like**
Creating a Facebook page of Meeds DAO will promote the platform the most and  bring more talents to the builder’s hub while also adding contributions that can be performed to earn points on the platform 

**Describe alternatives you've considered**
If their is a reason why Facebook is not being used, of course which I am not aware of then I think platforms like instagram can be used (which can be used to showcase the Meeds Banners and investment strategies) as they are pictorials, thread can also be used to promote the platform.

**Additional context**
Add any other context or screenshots about the feature requ

**Comment by srenault-meeds** [comment]
We actually tried it months ago and it didn't work as it is not reaching professional communities.
In addition to this, please submit this idea to a wider audience (e.g Discord server) to challenge it more
