### ISSUE TITLE
[PublicSite] createProgramButton Portlet is wrongly displayed

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1985]
**Steps to reproduce**

1. As not logged in, access the public site of any hubs
2. See error: the createProgramButton portlet is displayed

**Expected behavior**
This portlet must be displayed only when 2 cases are identified:
- Logged in user
- Logged as administrator (* in admin group and/or publisher in web-content group)

**Comment by boubaker** [comment]
Duplicates https://github.com/Meeds-io/meeds/issues/1984

**Comment by srenault-meeds** [comment]
Ok thanks. I cancel this one
