### ISSUE TITLE
Marketing and Awareness 

### ISSUE THREAD

**Issue by obajemu4255** [Meeds-io/meeds#1990]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when never I swap my Meeds token on comethswap about the amount I recieve as a result of low pricing of the Token 

**Describe the solution you'd like**

Produce educational content to help potential investors and users understand the benefits and potential of the token, thereby increasing demand. As a result raise the pricing of the Token 

**Describe alternatives you've considered**

Investing in marketing campaigns, including social media promotion, influencer partnerships, and public relations efforts to raise awareness and credibility.

**Additional context**
Emphasis should be stressed on the effect of adding liquidity on exchange platforms to increase the Token pricing this should be discussed more on the general group chat

**Comment by srenault-meeds** [comment]
off-topic. Please address this suggestion directly using our Discord Server
