### ISSUE TITLE
Navigation - error when i create a node with a link

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#1994]
**Steps to reproduce**

1. Create a new node
2. Select the option link
3. define the url
4. save

Result : 
error message

![image](https://github.com/Meeds-io/meeds/assets/31288011/2aec36c0-4ec6-405b-8ff2-49a90edfd64f)

![image](https://github.com/Meeds-io/meeds/assets/31288011/2ee4f1b7-8d13-475f-a4b4-f79dc231df4c)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.

**Expected behavior**

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Fixed cc @margondicco
