### ISSUE TITLE
Can't add page with link

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#1997]
**Steps to reproduce**

1. Go to Sites Management
2. Add a page with a link instead of layout
3. See error

**Current behaviour**

Can't add a page with a link

**Expected behavior**

Should be able to add a page with a link

**Comment by boubaker** [comment]
Duplicates https://github.com/Meeds-io/meeds/issues/1994

**Comment by Christyempire** [comment]
Looks little bit complicated
