### ISSUE TITLE
Enhancing Security by Limiting Login Attempts

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2008]
**Is your feature request related to a problem? Please describe.**
As a contributor to the website, I find the absence of a login attempt limit extremely frustrating. Without this feature, the website is vulnerable to brute force attacks where hackers can repeatedly try different password combinations to gain unauthorized access. This not only compromises the security of my account but also puts the entire website at risk. The constant fear of potential unauthorized access diminishes my trust in the website’s security measures and affects my willingness to contribute regularly.

**Describe the solution you'd like**
To address this issue, I propose implementing a feature that limits the number of login attempts. By restricting the number of consecutive failed login attempts to a manageable number (e.g., five attempts), and locking the account for a certain period (e.g., 15 minutes) after reaching this limit, we can significantly reduce the risk of brute force attacks.

**Describe alternatives you've considered**
After a certain number of failed login attempts, require the user to complete a CAPTCHA to prove they are human. This can help deter automated attacks.

**Additional context**
By integrating this feature, we can bolster our website’s defense mechanisms and provide contributors with peace of mind regarding the security of their accounts.

**Comment by srenault-meeds** [comment]
Already implemented :)
