### ISSUE TITLE
Enforcing Strong Password Policies 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2009]
**Is your feature request related to a problem? Please describe.**
As a contributor, the absence of strong password policies is highly frustrating and concerning. Weak passwords make our website vulnerable to unauthorized access, leading to potential data breaches and compromising the integrity of our contributions.

**Describe the solution you'd like**
Implementing a strong password policy is crucial. This policy should require all users to create passwords that are at least eight characters long and include a combination of upper and lower case letters, numbers, and special characters. 

**Describe alternatives you've considered**
Integrate a password generator tool that suggests strong, unique passwords during account creation and password updates.

**Additional context**
Enforcing strong password policies is not just a best practice; it is a necessity to protect the website from cyber threats. Weak passwords are one of the most common entry points for attackers.

**Comment by srenault-meeds** [comment]
Already the case
