### ISSUE TITLE
Collaboration Tools 

### ISSUE THREAD

**Issue by obajemu4255** [Meeds-io/meeds#2010]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when never I need to reach out to a particular individual either a reviewer or another peer and couldn’t do so immediately or it takes a longer to reach such person as a result of having to navigate to discord to communicate with such person.

**Describe the solution you'd like**

 Built-in communication channels, file sharing, and documentation tools right on the builders Hub can help  facilitate teamwork and efficient communication with contributors and reviewers as well as the management team 

**Describe alternatives you've considered**
Communication platforms can also be invited and incorporated into the Meeds DAO Ecosystem to enhance better communication and file sharing 

**Additional context**
There can be general- chat groups as in the case of Discord and icon to indicate who is currently online this will foster better communication and immediate answers to individual questions or Agitation.

**Comment by srenault-meeds** [comment]
Yes, you can use eXo which is part of the Meeds DAO Ecosystem. 
I suggest you go try their hub out
