### ISSUE TITLE
Introducing of incognito mode 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2013]
**Is your feature request related to a problem? Please describe.**
As a regular contributor to the website, I have often found the absence of an incognito mode to be quite frustrating. The inability to browse and contribute without leaving traces of my activity can be a significant concern, especially when dealing with sensitive or private content. 

**Describe the solution you'd like**
the addition of an incognito mode feature on the website. This mode would allow users to browse and contribute without leaving traces 

**Describe alternatives you've considered**
Provide more granular privacy settings that allow users to control what data is saved and shared.

**Additional context**
Additionally introducing incognito mode would significantly enhance the user experience and address the concerns of contributors who value their privacy.

**Comment by obajemu4255** [comment]
Incognito mode ??

**Comment by Abuteslimah99** [comment]
> Incognito mode ??

Beeni bros

**Comment by srenault-meeds** [comment]
Use the incognito mode of the browser ;-)
