### ISSUE TITLE
Influencer partnership 

### ISSUE THREAD

**Issue by obajemu4255** [Meeds-io/meeds#2024]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when never I decide to swap my rewards (Token) $MEED about the amount I receive. As a result of low pricing due to lack of enough liquidity 

**Describe the solution you'd like**

 Partnership with influencers and key opinion leaders in the crypto space to promote the token so as to get listed on major EXs platforms will be necessary to increase the usage of the Token $MEEDS thereby raising the value

**Describe alternatives you've considered**

Producing high-quality content, including blog posts, videos, and social media updates, to educate potential investors about the token’s value proposition will also go a long way 

**Additional context**
Seeking coverage in crypto news outlets and mainstream media to increase visibility.

**Comment by srenault-meeds** [comment]
Hi @obajemu4255 
I suggest you post this request directly in our discord server as it is related to community support and questions.
Thanks
