### ISSUE TITLE
[Challenges] the number of annoncers is incorrectly displayed when there is only one annoncer

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#203]
**Steps to reproduce**

1. Go to 'https://builders.meeds.io/portal/meeds/challenge)'
2. See challenge card when there is only one annoncer 

![image](https://user-images.githubusercontent.com/83289222/176862707-bd9c9086-bf6b-4483-987c-375d8794a8a7.png)

**Current behaviour**

the number of announcers is incorrectly displayed when there is only one annoncer

**Expected behavior**

Do not display the number of annoncers just do as done for case of two annoncers which is display only avatar

**Comment by mzorai** [comment]
Thanks @Imenmakni for reporting, could you please specify your screen's resolution?
