### ISSUE TITLE
Risk Mitigation 

### ISSUE THREAD

**Issue by obajemu4255** [Meeds-io/meeds#2032]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when never I try to buy certain amount of $MEEDS but realize that the amount of Usdt I will have to pay will not be covered by the point I will earn for performing the particular contributions. Which will be a loss to me 
**Describe the solution you'd like**

Offer features that mitigate impermanent loss, such as insurance or other protective mechanisms. 

**Describe alternatives you've considered**

better still the points earned should be  raised to cover the amount spent to buy the token and with a profit 

**Additional context**
By combining these strategies, you can create a compelling proposition for potential liquidity providers, making your liquidity pool more attractive and boosting participation.

**Comment by srenault-meeds** [comment]
@plamarque WDYT?
