### ISSUE TITLE
Implementation of multilingual feedback option 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2038]
**Is your feature request related to a problem? Please describe.**
As a contributor to the Meeds DAO community, I often find myself frustrated by the lack of multilingual feedback options on the website. This absence is particularly challenging because it limits the ability of non-English speaking contributors to share their valuable insights and feedback effectively. 

**Describe the solution you'd like**
To address this issue, I propose the implementation of multilingual feedback options on the Meeds DAO website. This feature would allow users to submit feedback in their preferred language, ensuring that language barriers do not hinder their ability to contribute.

**Describe alternatives you've considered**
Leverage community volunteers who are fluent in multiple languages to help translate and interpret feedback.

**Additional context**
Implementing multilingual feedback options is not just about overcoming language barriers; it’s about demonstrating our commitment to inclusivity and community engagement.

**Comment by srenault-meeds** [comment]
Hi,
I understand your point of view. However, we already provide multilingual support for notes or news for example.
Now, as the English is the language used abroad the whole world, we prefer keeping discussions in English so the community can support any member

If you are talking about providing automatic translation, then an issue has already been reported [here](https://github.com/Meeds-io/meeds/issues/1854)
Thanks
