### ISSUE TITLE
Introduction of contributor interviews 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2039]
**Is your feature request related to a problem? Please describe.**
As an active contributor to Meeds DAO, I often find myself frustrated by the lack of direct communication channels where I can share detailed feedback and discuss my ideas or concerns in a more interactive manner.

**Describe the solution you'd like**
I propose the introduction of scheduled one-on-one user interviews with contributors. This would involve setting up periodic, structured interviews where contributors can discuss their experiences, challenges, and suggestions directly with team members. 

**Describe alternatives you've considered**
Implement a feature allowing contributors to leave voice messages detailing their feedback, which can be reviewed by the team.

**Additional context**
By actively listening to and acting on contributor feedback, Meeds DAO can foster a more inclusive and responsive environment. This approach will likely lead to more innovative ideas, higher contributor satisfaction, and ultimately, a stronger, more cohesive community.

**Comment by srenault-meeds** [comment]
Can you please suggest it using our Discord Server?
More accurate. Thanks
