### ISSUE TITLE
Implementation of feedback development updates 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2040]
**Is your feature request related to a problem? Please describe.**
As a regular contributor to the Meeds DAO website, I often submit feedback to help improve the platform. However, the lack of activation or updates on the status of my feedback leaves me feeling ignored and frustrated.

**Describe the solution you'd like**
Implement a Feedback Acknowledgment System that responds to each feedback submission by Offer periodic updates on the status of the feedback, especially if any action is taken based on it offering periodic updates on the status of the feedback, especially as action is taken based on it.

**Describe alternatives you've considered**
Regularly publish summaries of received feedback and actions taken in community newsletters or on a dedicated blog. 

**Additional context**
Implementing a Feedback Acknowledgment System will not only improve user satisfaction but also foster a more engaged and motivated community.

**Comment by srenault-meeds** [comment]
It is already the case using this channel of github issues. Once it is implemented, we let reporters know ;-)
