### ISSUE TITLE
Introduction of user testing groups 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2041]
**Is your feature request related to a problem? Please describe.**
As a contributor to the Meeds DAO website, the absence of user testing frustrates me because it means that my experiences and feedback may not be adequately considered, leading to potential usability issues and missed opportunities for improvement. 

**Describe the solution you'd like**
The proposed solution is to implement regular user testing sessions where a select group of contributors, including myself, are invited to interact with the website and provide feedback on its usability, functionality, and overall user experience. 

**Describe alternatives you've considered**
Probable alternatives to traditional user testing sessions could include remote usability testing, where contributors are asked to perform tasks on the website while their interactions are recorded and analyzed. 

**Additional context**
It's important to note that implementing user testing can lead to significant benefits for the Meeds DAO website. By involving contributors in the testing process, we can identify usability issues early on, prioritize improvements based on real user feedback, and ultimately create a website that better serves the needs of its users.

**Comment by srenault-meeds** [comment]
Can you please suggest it using our Discord Server?
Thanks
