### ISSUE TITLE
Twitter / X actions do not accept x.com URLs

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#2042]
**Steps to reproduce**

1. Go to a program
2. Create a Twitter automated action
3. On Twitter / X copy the URL to any tweet
4. Enter the post URL in the "Tweet" field
5. See error
![Screenshot 2024-05-24 at 09 00 50](https://github.com/Meeds-io/meeds/assets/227828/8bc145bd-c2f5-4c4c-8258-637b54043b71)

**Current behaviour**

The field only accepts URLs that start with https://twitter.com

**Expected behavior**

Allow both URLs with twitter.com and x.com

**Comment by srenault-meeds** [comment]
No more reproduced. Can you please check again @plamarque?

**Comment by plamarque** [comment]
Not reproduced
