### ISSUE TITLE
Links Portlet : updates aren't considered Using Firefox unless cache is cleared

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#2043]
**Steps to reproduce**

1. Connect as Admin
2. Go to stream page and make it displayed as home
3. edit layout and add links portlet
4. add some links and choosie display 'raw' and save
5. restart server
6. Connect as Admin
7. Update links portlet : change the display to "column" OR add/edit/delete some links and save 
8. See error

Screen-cast link : https://community.exoplatform.com/portal/download-document/a9effefdac12000f260ebe2143f1ca25

**Current behaviour**

The old display persist

**Expected behavior**

Once saved and success message displayed, User doesn't have to clear cache each time to display the links updates
 
**(optional) Affected environments**  
 - Browser: Firefox

**Comment by Jihed525** [comment]
related eXo task : 71985

**Comment by Jihed525** [comment]
fixed

**Comment by rdenarie** [comment]
Fixed by https://github.com/Meeds-io/social/commit/ab86bd3df9f984137595c051ade30ffd8b38ecfc
