### ISSUE TITLE
Bugs and delayed verifications.

### ISSUE THREAD

**Issue by Ekemny** [Meeds-io/meeds#2048]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ekemny** [comment]
The first verification process which involves following meed on social media platforms takes so much time. One might start the task for the week 2 days to the end and he/she won't be able to complete other tasks because they can't access it.

**Comment by srenault-meeds** [comment]
Please address it using our discord server
