### ISSUE TITLE
Implementing homepage layout testing

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2049]
**Is your feature request related to a problem? Please describe.**
As a user of the Meed DAO website, the absence of homepage layout testing is frustrating because it leads to a static and potentially ineffective user experience.Without this feature, I'm stuck with a single homepage layout that may not effectively showcase important information, promotions, or updates. This lack of adaptability means I could be missing out on crucial updates or opportunities simply because the layout doesn't prioritize or present them effectively.

**Describe the solution you'd like**
Implementing homepage layout testing would provide a solution to this frustration. This feature would allow the website to dynamically test and optimize different layouts, ensuring that the homepage evolves to meet user needs and preferences. By testing variations, such as different arrangements of content blocks, featured sections, or calls-to-action, the website can identify the layout that maximizes user engagement, conversions, and overall satisfaction.

**Describe alternatives you've considered**
Committing to periodic reviews and updates of the homepage layout based on industry best practices, design trends, and user feedback.

**Additional context**
User expectations and browsing habits evolve over time, and a static homepage layout may become outdated or less effective at capturing and retaining user attention.

**Comment by srenault-meeds** [comment]
Hi,
Do you mean something for administrators when onboarding their own hub?
