### ISSUE TITLE
[Tasks] No space between comment button and comment CKEditor

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#205]
All in the title and show in the screenshot

![image](https://user-images.githubusercontent.com/49310007/177341609-87ed35bb-cd73-4c81-a764-c1c704bbdade.png)

**Comment by srenault-meeds** [comment]
Only for tasks comments right?

**Comment by GouadriaHanen** [comment]
> Only for tasks comments right?

yes only for tasks

**Comment by srenault-meeds** [comment]
fixed!
