### ISSUE TITLE
Implementation of color scheme testing 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2050]
**Is your feature request related to a problem? Please describe.**
As a dedicated user of the Meed DAO website, I've noticed that the current color scheme can sometimes be visually unappealing and may not enhance the readability or engagement levels optimally. The absence of a well-tested and optimized color scheme can lead to user frustration, as certain color combinations may cause eye strain or fail to highlight important information effectively.

**Describe the solution you'd like**
Implement a comprehensive A/B testing strategy for different color schemes. By experimenting with various color combinations, we can identify the most effective scheme that enhances readability, engagement, and overall user satisfaction. This could involve testing combinations of background colors, text colors, button colors, and link colors.

**Describe alternatives you've considered**
Implement a color scheme that adapts based on the time of day or the user's system preferences (e.g., dark mode vs. light mode).

**Additional context**
Color scheme optimization is a critical aspect of user experience design. Studies have shown that appropriate color choices can significantly impact user engagement, readability, and overall satisfaction. By implementing this feature, we not only enhance the visual appeal of the website but also show our commitment to user-centered design.

**Comment by srenault-meeds** [comment]
It is already provided for administrators when they need to custom the platform theme
