### ISSUE TITLE
Implementation of Navigation layout testing 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2051]
**Is your feature request related to a problem? Please describe.**
As a user of the Meed DAO website, the absence of navigation layout testing can be frustrating. Without proper testing, there's a risk that the website may not be utilizing the most intuitive and efficient navigation layout, leading to potential confusion and difficulty in finding the desired information or features.

**Describe the solution you'd like**
Implementing navigation layout testing would involve periodically evaluating different navigation structures to determine which one best facilitates user navigation and accessibility

**Describe alternatives you've considered**
If navigation layout testing is challenging to implement directly, alternative methods such as user feedback surveys, heatmaps, or usability testing sessions could provide valuable insights into user navigation preferences and pain points.

**Additional context**
Considering the dynamic nature of the crypto and blockchain space, where information and features evolve rapidly, ensuring an optimized navigation layout is crucial for users to easily navigate through the platform's offerings.

**Comment by srenault-meeds** [comment]
It is already provided by the platform for admin as it is possible to create a navigation with admin permissions only. That means they can test it out before delivering it to every user
