### ISSUE TITLE
Implementation of page loading speed testing 

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2052]
**Is your feature request related to a problem? Please describe.**
Without proper testing of page load, there's a risk that the best layout and design may not be implemented effectively. Slow-loading pages can deter users from exploring further, diminishing the impact of valuable content and features that the website offers. 

**Describe the solution you'd like**
To address this issue, I would suggest implementing page load speed testing as a priority enhancement. By regularly testing and optimizing page load speeds, the website can ensure a smooth and seamless user experience, thereby improving user satisfaction and retention. 

**Describe alternatives you've considered**
adopting a responsive design approach and optimizing code structure can further contribute to faster page loading times.

**Additional context**
Page load speed testing is essential for ensuring a positive user experience on the Meed DAO website.

**Comment by srenault-meeds** [comment]
We already include this test during our own development test.

Thanks for your proposition
