### ISSUE TITLE
Strengthening Brand Identity on the Meeds DAO Website

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2055]
**Is your feature request related to a problem? Please describe.**
As a dedicated contributor to Meeds DAO, I have noticed that our website currently lacks a consistent and strong brand identity. This absence can be frustrating for contributors and users alike, as it creates a sense of disconnection and confusion. Without a unified visual and thematic identity, the website struggles to convey the values and mission of Meeds DAO effectively, which is crucial for fostering trust and recognition among our community and potential partners.

**Describe the solution you'd like**
To address this issue, I propose a comprehensive branding overhaul for the Meeds DAO website. This would involve:

Consistent Visual Elements: Implementing a cohesive color scheme, typography, and logo placement across all pages.
Unified Messaging: Ensuring that all written content reflects the core values and voice of Meeds DAO.
Brand Guidelines: Developing a set of brand guidelines to be followed for all future content and design updates.

**Describe alternatives you've considered**
Conducting workshops or surveys within the community to gather insights and suggestions on brand elements.

**Additional context**
Strengthening our brand identity is not just about aesthetics; it is about creating a unified and recognizable presence that represents our collective vision and efforts.

**Comment by srenault-meeds** [comment]
Hi @Abuteslimah99 
It is acutally already the case. The main website (meeds.io) and the Meeds Official Hub (Builders) follow our guidelines.
As for instances, challenges for designing banners and avatars for spaces have even been suggested to contributors. And only the ones following our guidelines have been accepted among other criteria.

However, when creating your own hub, you can set it up at your convenience.
