### ISSUE TITLE
Regular workshops and webinars 

### ISSUE THREAD

**Issue by obajemu4255** [Meeds-io/meeds#2056]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when the only time we have to have a virtual meeting to communicate and educate contributors more is only once in a month which I found a little bit not enough 

**Describe the solution you'd like**

Regular Workshops and Webinars; Organize regular educational sessions, such as workshops, webinars, and hackathons, to help users develop their skills, understand the platform better, and collaborate on projects. These events can also serve as networking opportunities.

**Describe alternatives you've considered**
Our once in a month community call on discord can be made about 3-2 times in a month to get contributor more together and foster viable communications 

**Additional context**
With the implementation  of this enhancement tip, Meeds DAO can create a vibrant, engaged, and collaborative community on the Builders Hub,

**Comment by srenault-meeds** [comment]
Hi @obajemu4255 

Can you please suggest this using the Meeds Discord Server?
Indeed, this is more about community than product.

Thanks
