### ISSUE TITLE
Notification are updated even if nothing modified

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#2075]
**Steps to reproduce**

1. log in the platform with john
2. create a space with acces to validate
3. login with mary
4. request access to the space.
5. John receive the RequestJoinNotification. Accept it
6. with mary leave the space
7. wait few minutes. Log with john, the RequestJoinNotifation in notification center is displayed : 3 minutes ago
8. log with administrator, create a space binding between the space and a newly created group, for example /platform/test
9. Add user mary in group /platform/test
10. log with john. Notification time was refreshed and display "Just now"

**Current behaviour**

Notification is refreshed for the user : go to to, time displayed as "Just now", even if nothing modified

**Expected behavior**

If there is no modification to store, do not update the notification, to not have a timestamp update

**Comment by boubaker** [comment]
Seems not happening in meeds, do you know why it happens on eXo only ?

**Comment by rdenarie** [comment]
I reproduce with version [plf-community-tomcat-standalone-7.0.x-meed-20240531.103535-204.zip](https://repository.exoplatform.org/content/groups/public/io/meeds/distribution/plf-community-tomcat-standalone/7.0.x-meed-SNAPSHOT/plf-community-tomcat-standalone-7.0.x-meed-20240531.103535-204.zip)

**Comment by boubaker** [comment]
> I reproduce with version [plf-community-tomcat-standalone-7.0.x-meed-20240531.103535-204.zip](https://repository.exoplatform.org/content/groups/public/io/meeds/distribution/plf-community-tomcat-standalone/7.0.x-meed-SNAPSHOT/plf-community-tomcat-standalone-7.0.x-meed-20240531.103535-204.zip)

ok, I 'll check, in fact the fix is a workaround IMO, but I don't reproduce this on Builders, do you ?

**Comment by rdenarie** [comment]
I have'nt admin account to test on builders.
