### ISSUE TITLE
Enhancement Suggestion: Implement Comprehensive Link Tracking

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2078]
**Is your feature request related to a problem? Please describe.**
As a contributor to Meeds DAO, one of the most frustrating aspects of our current platform is the lack of comprehensive link tracking. Without detailed insights into how our shared links perform, it's challenging to measure the effectiveness of our promotional efforts. This absence hinders our ability to understand which content resonates with our audience, where our traffic is coming from, and how we can optimize our strategies to better promote Meeds DAO and its cryptocurrency, Meed.

**Describe the solution you'd like**
To address this issue, I propose implementing a robust link tracking system using UTM (Urchin Tracking Module) parameters. This would involve:

UTM Parameter Integration: Enabling the creation of custom UTM parameters for all links shared by contributors. This allows tracking the source, medium, campaign, content, and term associated with each link.
Analytics Dashboard: Developing an analytics dashboard where contributors can view detailed reports on link performance, including click-through rates, sources of traffic, and engagement metrics.
Automated Reporting: Setting up automated reports that summarize link performance and are sent to contributors regularly.

**Describe alternatives you've considered**
Basic Tracking Implementation: Starting with basic link tracking features that record simple metrics such as total clicks and referring sources. This can be a stepping stone towards more advanced tracking.

**Additional context**
The need for comprehensive link tracking is critical in today's data-driven environment.

**Comment by srenault-meeds** [comment]
Thanks. We won't implement it for now as it is not core for the product
