### ISSUE TITLE
Notification icon: Background appearing after clicking to it

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#208]
**Steps to reproduce**

1. Go to the builders plf
2. Click on notification icon
3. Close the notification drawer
4. See error, there is background behind the notification icon
![bg notif icon](https://user-images.githubusercontent.com/58853195/177935457-fca32bb2-6ed4-446b-9578-cb33d74af345.gif)

**(optional) Affected version**
1.4.x plf

**Expected behavior**

We shouldn't have any background 
reproduced using brave or FF

**Comment by mzorai** [comment]
I couldn't reproduce with Brave on Linux, to check in UX FT IMO @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
Yes, fixed after a restart. to cancel / I close it.
