### ISSUE TITLE
Implementing Internal Site Search Analytics for Enhanced Usability

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2081]
**Is your feature request related to a problem? Please describe.**
As a dedicated contributor to the Meeds DAO Builders Hub, I have found the lack of internal site search analytics to be a significant source of frustration. Without insights into what our members and visitors are searching for on the site, it becomes challenging to understand their needs, identify gaps in our content, and improve overall usability. This absence hampers our ability to provide timely and relevant resources, potentially leading to a suboptimal user experience and missed opportunities for engagement.

**Describe the solution you'd like**
To address this issue, I propose implementing a robust internal site search analytics system. This feature would track and analyze user search queries within the Builders Hub, providing valuable insights into what users are looking for and whether they are finding the content they need.

**Describe alternatives you've considered**
Conduct surveys to gather feedback on search functionality and content needs.

**Additional context**
Ensuring users can easily find relevant information will lead to a more satisfying and productive experience on the Builders Hub.

**Comment by srenault-meeds** [comment]
Are you admin for a hub? Indeed, this is already partially implemented by our analytics tool
