### ISSUE TITLE
Implementing Referral Tracking for Contributors

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2083]
**Is your feature request related to a problem? Please describe.**
I've often found myself in situations where I've recommended the platform to friends, colleagues, and acquaintances, only to realize that there's no mechanism in place to track referrals. This absence has been quite frustrating for me, as it leaves me uncertain about the impact of my efforts in promoting the platform. Not being able to track referrals not only diminishes the sense of accomplishment but also makes it challenging to gauge the effectiveness of my contributions to the community.

**Describe the solution you'd like**
To address this issue, I propose the implementation of a referral tracking system for contributors like myself. This system would enable us to generate unique referral links or codes that we can share with potential new users. Whenever someone signs up or engages with the platform using our referral link or code, the system would automatically attribute the referral to us, allowing us to track our contributions accurately.

**Describe alternatives you've considered**
While less automated, contributors could manually report their referrals, which could then be verified and attributed by the platform administrators.

**Additional context**

Implementing a referral tracking system not only acknowledges and rewards the efforts of contributors but also serves as a powerful growth tool for [Website Name]. By enabling contributors to track their referrals, we empower them to become ambassadors for the platform, driving organic growth and fostering a sense of ownership and pride in their contributions.

**Comment by srenault-meeds** [comment]
already proposed here https://github.com/Meeds-io/meeds/issues/1312
