### ISSUE TITLE
Extra field in user and user card does not change when setting changes

### ISSUE THREAD

**Issue by ahamdi** [Meeds-io/meeds#2089]
**Steps to reproduce**

1. Using an administrator, create a space and add a simple user 
2. Go to Administration -> Profile card settings
3. Change the first field to email
4. Connect with a simple user, join the space and post an activity
5. Check with the administrator the popover of the simple user and the members page

**Current behavior**
the property position of the simple user is displayed

**Expected behavior**
the property email should be displayed under the full name

**Comment by srenault-meeds** [comment]
Hi @ahamdi ,

What is the status, please?
