### ISSUE TITLE
Purge Automatically Old Analytics Indices

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#2097]
**Is your feature request related to a problem? Please describe.**

Currently Analytics indices aren't purged automatically, but manually by Ops.

**Describe the solution you'd like**

An automatic purge of indices determined by the number of days/months/years to keep an analytics index. The period of time has to be configurable through properties for now (may be added through UI when needed)

**Comment by boubaker** [comment]
Ready for test @bourasom @rdenarie  using MIPs ACCs and Artifacts on a Dev or PPR if needed (Meeds & eXo distributions)

( BTW Paramters has changed, please read more about it [here](https://github.com/Meeds-io/analytics/pull/189#issue-2341608674) )

**Comment by rdenarie** [comment]
> Ready for test @bourasom @rdenarie using MIPs ACCs and Artifacts on a Dev or PPR if needed (Meeds & eXo distributions)
> 
> ( BTW Paramters has changed, please read more about it [here](https://github.com/Meeds-io/analytics/pull/189#issue-2341608674) )

Hello
I understand that you change 2 things :

- you fix the pb to have one index per week (in fact, one index per x days, x is parameterized, default 7)
- You add a parameter to set the number of maxCount index, default value 500.

My question is : if the new version with you fix start, on a plateform which have 900 daily indexes, what will be the effect ? 
Drop the 401 olders indexes to keep 499 and allow to create 1 ?

**Comment by boubaker** [comment]
> My question is : if the new version with you fix start, on a plateform which have 900 daily indexes, what will be the effect ?
> Drop the 401 olders indexes to keep 499 and allow to create 1 ?

yes, keep only 500 indices available for analytics independently from the chosen frequency of index creation.

**Comment by rdenarie** [comment]
cc @margondicco 
It means that for customer with some history, we will have a huge drop of analytics data, the keep only 500 index (less than 2 years)

**Comment by boubaker** [comment]
> cc @margondicco It means that for customer with some history, we will have a huge drop of analytics data, the keep only 500 index (less than 2 years)

**It's parametrable**, you can choose for some of your customers to keep **more than 500**. The applied **default value** is by following recommendations on product.

**Comment by boubaker** [comment]
@rdenarie @bourasom after discussion and functional validation made, I let you review the PRs list:
- https://github.com/Meeds-io/analytics/pull/189
- https://github.com/Meeds-io/kudos/pull/498
- https://github.com/Meeds-io/gamification/pull/1607
- https://github.com/Meeds-io/app-center/pull/328
- https://github.com/Meeds-io/notes/pull/1000
- https://github.com/Meeds-io/content/pull/118
- https://github.com/Meeds-io/poll/pull/148
- https://github.com/Meeds-io/task/pull/390
- https://github.com/Meeds-io/meeds/pull/2125

eXo PRs
- https://github.com/exoplatform/ecms/pull/2363
- https://github.com/exoplatform/agenda/pull/659
- https://github.com/exoplatform/web-conferencing/pull/311
- https://github.com/exoplatform/documents/pull/1263
- https://github.com/exoplatform/processes/pull/369
- https://github.com/exoplatform/automatic-translation/pull/82
- https://github.com/exoplatform/data-upgrade/pull/230

**Comment by bourasom** [comment]
as exchanged before, I let you sync with @halaya for the approval and merges to prepare the deployment in releases

**Comment by boubaker** [comment]
Merged on develop.
