### ISSUE TITLE
[UI] A lot of margin used to display the settings portlets in mobile device

### ISSUE THREAD

**Issue by abenmbarek** [Meeds-io/meeds#210]
If i access to the user settings portlets using my mobile device, i notice that there is a lot of white spaces between settings portlets due to the margin-left and margin-right so i cannot the whole of the settings titles or descriptions in addition to the disappearance of the app center icon placed in the top right of the top bar container as described in the screenshot bellow.

I suggest to remove the usage of the margin right and left in case of mobile devices and change the display of the top bar icons to be regrouped in a topdown menu also in case of mobile devices.

![test](https://user-images.githubusercontent.com/92788696/178114778-e5359d54-de62-42da-a5b3-0510c00229f2.png)

**Comment by srenault-meeds** [comment]
This is related to Wallet setting only. Please @Imenmakni can you take a look at this?
cc @mzorai

**Comment by srenault-meeds** [comment]
Should be fixed now
