### ISSUE TITLE
Suggested filters displayed on 2 lines and does not fit all the space

### ISSUE THREAD

**Issue by ahamdi** [Meeds-io/meeds#2102]
Current behavior
When we have long suggested filters and that they exceed 3 filters

**UI:**

- the combinations are displayed in 2 lines
- in expand mode, we do not display all the combinations in the line even if we have enough space

**Expected behavior**

- We display on 1 line the complementary combinations. If more we display a "+X"
- On expand mode, we should have the same behavior so we display more filters in one line

**Comment by srenault-meeds** [comment]
Hi @ahamdi ,

What is the status, please?
