### ISSUE TITLE
Combined name & profile property returns fewer results

### ISSUE THREAD

**Issue by ahamdi** [Meeds-io/meeds#2104]
**Steps to reproduce**

- user1, user2 & user3 define same team attribute in their profile (exp: support)
- user4 go to people interface open filter drawer and type support in team input //user1, user2 & user3 are displayed
- in filter by name field type user2

**actual:**

- user1 & user2 are still displayed

**expected:**

- only searched user should be displayed

**Comment by srenault-meeds** [comment]
Hi @ahamdi ,

What is the status, please?
