### ISSUE TITLE
Recent and Spaces list drawer : mark as Favorite

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#211]
Actually, To mark space(s) as favorites i have to open the spaces page.

As a solution or a quick call to action, mark as favorite should be available in recent & spaces list drawer also.

**Comment by srenault-meeds** [comment]
We have proposed few days ago a new way to mark a space as favorite:
- from the topbar space popover
- from the space popover
- from the left menu

Does that fit your need?

**Comment by Jihed525** [comment]
Yes, it should be ok.
