### ISSUE TITLE
Hidden/Inactive properties are visible on user card

### ISSUE THREAD

**Issue by ahamdi** [Meeds-io/meeds#2112]
**Steps to reproduce**

1. Current behavior
When an attribute is hidden by a user or defined non visible by an administrator
Then the attribute is still displayed on user card on people page, space member and organizational chart.
Additionally if it's the Job title field, it's still displayed in the profile header and the user pop hover
1. Expected behavior

The attribute are not displayed according to the choice of the user or the administrator.

**Comment by srenault-meeds** [comment]
Hi @ahamdi ,

What is the status, please?
