### ISSUE TITLE
Space members : mix of enabled and disabled users

### ISSUE THREAD

**Issue by ahamdi** [Meeds-io/meeds#2119]
**Steps to reproduce**

- Given I'm a space/members
- When I access to the space members, I find all users who are enabled and disabled
- This makes administrating the space hard, especially to filter and clean up disabled users
- 
**Expected behavior**
- When a space/member of a space is deactivated
- Then the user is not displayed in the user when filtered on:
  - Members
  - Redactors
  - Publisher
  - Hosts
Besides, it will be needed to have a filter for administrators that displays the space members who are disabled

**Comment by srenault-meeds** [comment]
Hi @ahamdi ,

What is the status, please?
