### ISSUE TITLE
[Notification - drawer] By clicking on icon notifcation settings i would like to be redirected to "Manage notifications" page

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#212]
**Is your feature request related to a problem? Please describe.**
By clicking on icon notifcation settings i am redirected to global page settings

**Describe the solution you'd like**
By clicking on icon notifcation settings i want to be redirected to  "Manage notifications " page

![icon notif](https://user-images.githubusercontent.com/83289222/178839300-0085078d-af92-48ec-b3b0-ff057c9baad4.gif)

**Comment by mzorai** [comment]
In fact it redirects to settings page as there are some notification settings in the first page which is the notifications channels (email), push on-site
I propose to add an anchor to this section (we've done this for wallet settings section)
cc @Samuel-Renault-eXo 
@Imenmakni

**Comment by srenault-meeds** [comment]
Yes to think about it indeed. It looks annoying UX to me too. Or we review the way settings are conceived and the way settings page is display. I'd rather go towards a page like chrome settings for example.
