### ISSUE TITLE
[Contributions] Erroneous action list on programs detail drawer

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#2122]
**Steps to reproduce**

1. From the overview page (public site or overview page of contribute site)
2. Click on Contribution Programs >  Fund Meeds : actions are properly lsited
3. close drawer with ✖️ (cross arrow)
4. Click See All > Promote Meeds

**Current behaviour**

>> The list of actions displayed is not updated : it still displays Fund Meeds' actions

![Screenshot 2024-06-07 at 10 54 32](https://github.com/Meeds-io/meeds/assets/227828/7d77918d-eb58-4587-b1ea-8b968e520d02)

**Expected behavior**

List the actions of the requested program

** Additional observations **  
probably related : when going directly to See all then clicking any program, the list of actions is empty.

**Comment by srenault-meeds** [comment]
Fixed @plamarque
