### ISSUE TITLE
[notifications] Comment drawer is not opened when clicking on "reply " button from the mail

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#214]
**Steps to reproduce**

1. user1 post an activity ( kudos activity , simple post ...) in a space where user2 is a member
2. user2 receive a notif email about the post 
3. consult the email and click on the "Reply" button

**Current behaviour**
The comment drawer is not opened however the URL is pointing on comment ID

**Expected behavior**

The comment drawer should be displayed with an opened Ckeditor comment  .

**Comment by srenault-meeds** [comment]
@ichaieb I have tried to reproduce it and actually the comment drawer is opening. Not with the editor opened but with the comment drawer.
Can you confirm please?

**Comment by srenault-meeds** [comment]
@ichaieb Do you reproduce it?

**Comment by ichaieb** [comment]
> @ichaieb Do you reproduce it?

No it's no more reproduced for me , actually the comment drawer is opening .So we can close  the issue . Thanks
