### ISSUE TITLE
Add 'Set Space as favorite' in the recent space section

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#217]
**Is your feature request related to a problem? Please describe.**
Well, in order to add space as a favorite, we should refer to the spaces list and look for that space, then, mark it as a favorite.

**Describe the solution you'd like**
I believe most of the time, a favorite space should already have appeared in the recent space section. So it would be a fast action to mark a space as favorite :)

**Comment by srenault-meeds** [comment]
We have proposed few days ago a new way to mark a space as favorite:
- from the topbar space popover
- from the space popover
- from the left menu
Does that fit your need?

**Comment by hbenali** [comment]
Yes sounds good to me thanks!
