### ISSUE TITLE
Enhancing User Experience: Implementing Anonymous Feedback for Meed DAO

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2179]
**Is your feature request related to a problem? Please describe.**
As a dedicated contributor to Meed DAO, I greatly appreciate the platform's commitment to transparency and community involvement. However, I would like to share a concern regarding the current feedback mechanism, particularly the absence of an option for anonymous contributions.
Currently, without the ability to provide feedback anonymously, I find myself hesitant to share certain insights or suggestions that I believe could benefit our community. This limitation stems from concerns about privacy and potential repercussions for expressing views that may not align with prevailing opinions.

**Describe the solution you'd like**
To address this challenge effectively, I propose implementing an anonymous feedback feature. This feature would allow contributors like myself to provide feedback or suggestions without revealing our identities publicly. By ensuring anonymity, Meed DAO can foster a more inclusive environment where diverse perspectives can be freely shared and considered.
 

**Describe alternatives you've considered**
If implementing anonymous feedback poses technical or operational challenges, alternatives such as pseudonymous submissions or confidential feedback channels could be explored. These options could provide a balance between anonymity and accountability within the community.

**Additional context**
In our dynamic DAO environment, diverse viewpoints are crucial for innovation and growth. Anonymity in feedback encourages honest discourse and empowers contributors to share ideas without fear of judgment or reprisal. It promotes a culture where constructive criticism can thrive, ultimately strengthening our collective efforts towards shared goals.

**Comment by srenault-meeds** [comment]
We need your informations so we can check with you about the reported problem / suggested feedback.
Additionally, we need some information so you can get rewards for these contributions.

So we cannot accept this feedback. Sorry
