### ISSUE TITLE
Enhancing User Freedom: Advocating for Anonymous Contributions on Meeds DAO

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2180]
**Is your feature request related to a problem? Please describe.**
As a dedicated contributor to Meeds DAO, I deeply value transparency and inclusivity within our community. However, the absence of anonymous contributions presents a significant frustration for many of us who prioritize privacy in our interactions.Contributing to Meeds DAO requires a commitment to openness and accountability, which are commendable values. However, in certain situations, contributors may hesitate to voice their opinions or provide feedback openly due to concerns about privacy or the sensitivity of the topic at hand. This limitation can stifle valuable input from community members who prefer to remain anonymous for various valid reasons, such as personal security or confidentiality.

**Describe the solution you'd like**
Introducing an option for anonymous contributions would empower contributors to participate more freely and candidly in discussions and decision-making processes. By implementing this feature, Meeds DAO can foster a more inclusive environment where every voice matters, regardless of the contributor's comfort level with public disclosure.

**Describe alternatives you've considered**
While anonymity has its benefits, it's essential to balance this with transparency and accountability. Meeds DAO could consider implementing a hybrid approach, where certain types of contributions allow anonymity while others require identification. This flexibility ensures that contributors can choose the level of visibility that aligns with their comfort and the nature of their contribution.

**Additional context**
In today's digital landscape, privacy concerns are increasingly paramount. Many contributors, myself included, may have valuable insights or contributions to offer but feel constrained by the requirement for public acknowledgment. Providing an option for anonymous contributions not only respects individual privacy but also enriches the diversity of perspectives within our community, ultimately strengthening our collective decision-making processes.

By embracing anonymous contributions, Meeds DAO can demonstrate its commitment to fostering an environment where all voices are heard and valued, regardless of visibility. This enhancement would underscore our dedication to inclusivity and empower contributors to engage more meaningfully in shaping the future of our DAO.

**Comment by srenault-meeds** [comment]
As you know, we need informations so you can receive rewards.
In case you want to remain anonymous, you still can use an alias for your display name.
