### ISSUE TITLE
[Stream Readability] The new button see more for activity have a strange letter spacing

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#2182]
Hello,

When looking at "See More" button in activity, we can see that there is a letter spacing : 
![2024-06-17_09-12](https://github.com/Meeds-io/meeds/assets/807839/a4d7916f-82aa-4a46-a4af-6fc6a6a7f93e)

This make this text different from the text around. Should we remove the letter spacing on this button : 
![2024-06-17_09-12_1](https://github.com/Meeds-io/meeds/assets/807839/98c6626b-36d9-47f6-af28-da14b55356b4)

It will make this button more consistant with the rest of the text

**Comment by srenault-meeds** [comment]
Hi,

Is that still a problem now that we have reviewed the text style?
Thanks

**Comment by rdenarie** [comment]
Perfect, it is fixed. Thanks
