### ISSUE TITLE
[New Layout Editor] When adding few (a lot) portlet on the same page, there is a problem with the size of the request header

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#2185]
On hosting instance (on which we use nginx), we can see a problem with the layout editor.

1. Create a new page and configure like that : 
![2024-06-17_10-33](https://github.com/Meeds-io/meeds/assets/807839/f8798303-aa8b-42e2-97e6-eb9f6ed94451)

2. Add a new Image portlet in the bottom of the page : 
![2024-06-17_10-34](https://github.com/Meeds-io/meeds/assets/807839/e88d98ec-65aa-4243-9560-deeed4980fe2)

Current Behaviour : 
There is a 502 Error : 
![image](https://github.com/Meeds-io/meeds/assets/807839/afd7dc98-e72b-4c80-b7a7-8b5377c6adb2)

And we can see this in nginx error logs : 

> 2024/06/17 08:11:24 [error] 9#9: *11138 upstream sent too big header while reading response header from upstream, client: 82.66.117.96, server: exo-demo.exoplatform.org, request: "GET /portal/vivatech/home/programme/speakers HTTP/2.0", upstream: "http://172.18.0.14:8080/portal/vivatech/home/programme/speakers", host: "exo-demo.exoplatform.org", referrer: "https://exo-demo.exoplatform.org/portal/vivatech/home/programme/speakers"

**Comment by rdenarie** [comment]
A quick workaround is to modify the nginx configuration to allow larger header, but it is only push the limit.

We need a fix on product side

**Comment by boubaker** [comment]
ok, thanks. As discussed, the workaround to apply on Nginx would be https://docs.konghq.com/gateway/latest/reference/configuration/#nginx_http_large_client_header_buffers
