### ISSUE TITLE
Task - Filter drawer UI broken

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#2187]
**Steps to reproduce**

1. Go to task
2. Click on Filter

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The UI of the drawer is broken

https://github.com/Meeds-io/meeds/assets/105866381/f9a06840-76f9-40d3-9883-b003a058d33c
I have reproduce it also on Meeds.

**Expected behavior**

We have the good UI. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by boubaker** [comment]
Fixed by https://builders.meeds.io/portal/meeds/tasks/taskDetail/7077
