### ISSUE TITLE
[Layout] [Tasks] Display of tasks board when full window

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#2195]
**Is your feature request related to a problem? Please describe.**
Given the layout is updated to get a full window display of tasks page
Then the board cannot be fully seen 

<img width="1369" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/715115b7-2b9b-4b68-a2d4-0ecbdd427c87">

Indeed a container display "blocks" it
<img width="918" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/1612b970-7ff9-47f5-a4b5-260a7d80abd6">

**Describe the solution you'd like**
Adjust the display so the width is automatically set depending on the page width

**Comment by boubaker** [comment]
Should be considered in context of Meeds-io/MIPs#135 IMO
