### ISSUE TITLE
Task - UI issue for group section of task

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#2200]
**Steps to reproduce**

1. Go to a space
2. Create several tasks and add different labels + assign users
3. Group by labels then assignes
5. See error

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The UI of the number of task on the group is broken
![image](https://github.com/Meeds-io/meeds/assets/105866381/b9d8e129-5cbe-4746-9e3c-f6fa4edb1026)
![image](https://github.com/Meeds-io/meeds/assets/105866381/5d1fcff2-e428-40a3-976a-f1404a77fb64)

**Expected behavior**

The number is correctly displayed

**(optional) Affected environments**  
Please complete the following information:

**Comment by boubaker** [comment]
Duplicates https://github.com/Meeds-io/meeds/issues/2192 which was fixed in fact
