### ISSUE TITLE
UI glitch in the taskd App

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#2202]
**Steps to reproduce**

1. Go to 'Tasks dashbord'
2. See screenshot
![image (5)](https://github.com/Meeds-io/meeds/assets/40363501/6ef674ea-2bbf-437d-ae0d-0a1b33b613fd)

**Comment by boubaker** [comment]
Already fixed by https://github.com/Meeds-io/meeds/issues/2192
