### ISSUE TITLE
Add Text ellipsis to task title

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#2208]
Steps to reproduce the issue:

1. Open the 'Tasks App'.
2. Navigate to a project containing tasks.
3. Select the board view.
4. Notice that the task title does not display a text ellipsis (see screenshot).
![Screenshot from 2024-06-19 09-40-24](https://github.com/Meeds-io/meeds/assets/40363501/14eefdc4-72ff-4fd9-bc0e-3899b3937148)

**Comment by boubaker** [comment]
duplicates https://github.com/Meeds-io/meeds/issues/2205
