### ISSUE TITLE
[Contributions] Be able  to cancel an announce

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#221]
**Is your feature request related to a problem? Please describe.**
I did a mistaken announce and couldn't cancel it

**Describe the solution you'd like**
Be able  to cancel an announce

**Comment by srenault-meeds** [comment]
Edit: 
We suggest to enhance this as the following:
* Automatic cancellation of an action
Each an action is undone (activity is deleted or the action is reverted), then the achievement is rejected and noted as is in the achievement board. These following actions are eligible for such business rule:
- Announcement deleted
- Gamified event deleted / undone:
Space stream: Activity in hosted space
Space stream: Comment activity in space
Space stream: Like activity in space
Space stream: Like comment in space
Space stream: Post activity in a space
Space stream: Receive comment in a space
Space stream: Receive like comment in space
Space stream: Receive like to space's post
Kudos: Receive kudos
Kudos: Send kudos
Space: Join space

* Manual cancellation of an action:
In addition to this, we suggest to propose a solution for users to cancel action they would like to undo, like sending kudos or announcing achievements.
Thus,
- When announcing achievement, from the three dots of the activity, the author can find an option "Cancel announcement"
- When sending a kudos, from the three dots of the activity (or comment), the author can find an option "Cancel sending a kudos". By doing this, the achievement is rejected and the kudos is removed from the counter of number of kudos to send and the activity (or comment) is removed

**Comment by srenault-meeds** [comment]
Done for achievement announcement
