### ISSUE TITLE
Automated processes 

### ISSUE THREAD

**Issue by obajemu4255** [Meeds-io/meeds#2219]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I see some tasks are removed as a result of shortage in reviewers ..

**Describe the solution you'd like**

Automate Processes, Leverage smart contracts to automate tasks, voting, and decision-making processes, reducing the need for intermediaries.

**Describe alternatives you've considered**
More hands (reviewers) can also be taken in to aid faster review of contributions 

**Additional context**
As in the tasks of the medium boost suspended, more reviewers can be taken to hasten it review

**Comment by srenault-meeds** [comment]
Hi, 

Do you have exact sample of what you are reporting please?

> I'm always frustrated when I see some tasks are removed as a result of shortage in reviewers ..
