### ISSUE TITLE
Portlet storageid is updated when edit page layout

### ISSUE THREAD

**Issue by hakermi** [Meeds-io/meeds#2228]
**Steps to reproduce**

1. Go My team page edit settings of the organisational portlet chart including the header translation as they are linked with the portlet `storageId` '...'
2. Edit the page layout and Save
3. The settings are lost and the translations are lost because they were associated with the portlet `storageId`  which has been updated because of edit layout.

**Expected behavior :**
Adding or modifying an existing portlet should not affect or regenerate the existing portlets storageIds

**Current behavior:**
The existing portlet storageId is updated

**Comment by boubaker** [comment]
This is not an issue, but a feature. Can you please detail what is the functional problem ?

**Comment by boubaker** [comment]
With a steps to reproduce if possible or at least the random fail that you didn't determined its reproduction steps

**Comment by hakermi** [comment]
> With a steps to reproduce if possible or at least the random fail that you didn't determined its reproduction steps

already added the steps to reproduce in the decsription:

**Comment by hakermi** [comment]
> This is not an issue, but a feature. Can you please detail what is the functional problem ?

You mean its' expected behavior ?

**Comment by hakermi** [comment]
@boubaker In fact we base our settings in some portlets like the orgchart and the newslistportlet on the portlet storageId.
once its changed we are losing our saved data

**Comment by boubaker** [comment]
> You mean its' expected behavior ?

Yes, it's expected since we use a draft mode of pages which duplicates the portlets with its settings (portlet preferences). The storageId is a technical identifier and shouldn't be used to be referenced, only JSR (portlet preferences) should be used to make sure that data is preserved.

**Comment by boubaker** [comment]
> once its changed we are losing our saved data

Do you mean that portlet preferences aren't cloned ?

**Comment by hakermi** [comment]
> > once its changed we are losing our saved data
> 
> Do you mean that portlet preferences aren't cloned ?

No, for example, when integrate the translation-field in the newslistportlet, we need to associate the translations to an objectId, which in our case is the portlet its self, we do not save any other things in the database to associate with

**Comment by boubaker** [comment]
> > > once its changed we are losing our saved data
> > 
> > 
> > Do you mean that portlet preferences aren't cloned ?
> 
> No, for example, when integrate the translation-field in the newslistportlet, we need to associare the translations to an objectId, which in our case is the portlet its self, we do not save any other things in the database to associate with

Yes, IMO you need to use same strategy as `CMSPortlet` based portlets, like Links, Image & SNV. In fact you have to rely on an identifier generated in portlet preferences and not on the identifier of the portlet itself.

**Comment by hakermi** [comment]
> > > > once its changed we are losing our saved data
> > > 
> > > 
> > > Do you mean that portlet preferences aren't cloned ?
> > 
> > 
> > No, for example, when integrate the translation-field in the newslistportlet, we need to associare the translations to an objectId, which in our case is the portlet its self, we do not save any other things in the database to associate with
> 
> Yes, IMO you need to use same strategy as `CMSPortlet` based portlets, like Links, Image & SNV. In fact you have to rely on an identifier generated in portlet preferences and not on the identifier of the portlet itself.

OK, in fact we didn't have such behavior before thus we were relying on the portlet storageId. now seems that we are going to refactor what we have done.

**Comment by boubaker** [comment]
> OK, in fact we didn't have such behavior before thus we were relying on the portlet storageId. now seems that we are going to refactor what we have done.

Nope, in fact the problem exists already. If you rely on `storageId` and then use the `importMode=merge` (when upgrading from a version to another), then a new `storageId` was regenerated and thus the customers looses their content each version upgrade. The `CMS Portlet` introduced and used in Meeds-io/MIPs#98, Meeds-io/MIPs#93 and Meeds-io/MIPs#93 to allow preserving such data and to not loose data of portlet preferences each time there is a upgrade.

**Comment by boubaker** [comment]
Thus even without the Layout Editor strategy of `storageId` creation (introduced already some months ago BTW), the problem of referencing a `storageId` remains a problem. (Same problem that we faced in SCV & CLV tens of years ago BTW)

**Comment by boubaker** [comment]
So IMHO, we knew that referencing the `storageId` was a bad practice years ago and that we attempted to not rely on it anymore each time we make a customer Hub upgrade.

**Comment by boubaker** [comment]
BTW2, knowing this, that was why I proposed a different architecture on News that **is fortunately adopted** now using the Targeting which relies on portlet preferences Id (Target Id) to retrieve the list of news rather than adding the list of news one by one in the list of portlet preferences. (when `importMode` = merge, when the target is embedded, the list isn't cleared while when adding the listed news one by one in News List, the list is cleared each time the page layout is re-imported from XML)

**Comment by hakermi** [comment]
OK, I see, thanks for these valuable information.

**Comment by boubaker** [comment]
> OK, I see, thanks for these valuable information.

With pleasure, I 'm available if needing more information about the usage of `CMSPortlet API`
