### ISSUE TITLE
[Notifications] Organize notification by date (default), type and priority

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#223]
**Is your feature request related to a problem? Please describe.**
Indeed, the notifications are organized by date which is most of the time not relevant to easily access an important notification.

**Describe the solution you'd like**
I propose to add some key features for organizing notifications: (1) In addition to the existing organization by date, (2) a grouping of notifications by spaces, type of activity (news, poll, etc.), and (3) most important a grouping by **priority**: User can set his own priority notifications grouping by app (task, agenda, social (we can divide social into different sub-domains)). Thanks

**Comment by srenault-meeds** [comment]
- Notifications are now grouped by category and you can see it from expanded view
- notifications can be filtered to unread activities only

So considered as done for now.
If you have more feedbacks knowing this exists, please create another issue
