### ISSUE TITLE
[Language] Default language UI

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#2230]
**Is your feature request related to a problem? Please describe.**
It is currently possible to update with a fetch the default platform language which is used:
- when sending email to users, not logged in yet
- when creating content using translation field. Then, this default platform language is used.

After some months of usage, it appears that:
- this fetch is finally used for all French Customers
- tests was missing to check the expected behaviour of emails sent OR regression occured (difficult to know)
Example: If an onboarding email is sent to external users, it has to be sent using the default language but it wasn't ok after some time. So maybe a missing test or a regression
Cf. discussion there: https://builders.meeds.io/portal/meeds/tasks/taskDetail/3327

**Describe the solution you'd like**
A UI in branding option so we can set it as an admin

<img width="589" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/4803322c-0e24-4501-a17d-c155714f5acc">

**Comment by boubaker** [comment]
> regression has been observed to some use case

Do you mean Regression Tests has been made and that the feature is sufficiently stable to allow adding this as is with a dedicated UI ?

**Comment by srenault-meeds** [comment]
Not really, I will review the description

**Comment by srenault-meeds** [comment]
Description updated

**Comment by boubaker** [comment]
Thanks, clear !
