### ISSUE TITLE
Enhance Dashboard Contributions Widget

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#2240]
**Is your feature request related to a problem? Please describe.**
The name of the programs displayed in Weekly Contributions Widget are often badly displayed (Return to the line)
![Capture d’écran du 2024-06-29 07-20-33](https://github.com/Meeds-io/meeds/assets/594824/ba8a53e9-d762-4b55-a856-7748ed9a6a9b)

**Describe the solution you'd like**
Change the label to displayed a fixed with label like percentage with the avatar of the program instead of its name and let the associated color and name displayed in tooltip instead.
![Capture d’écran du 2024-06-29 07-28-21](https://github.com/Meeds-io/meeds/assets/594824/e3984559-99b8-49b1-a48b-05074334a641)

**Comment by srenault-meeds** [comment]
Reviewed with the review of the gadget during the contribute site review
