### ISSUE TITLE
[Onboarding] Profile Completion: Create a partial circle for the incomplete profile on the profile avatar (main menu)

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#226]
**Is your feature request related to a problem? Please describe.**
Many users are unaware of profile completion due to a lack of engagement guidance.
**Describe the solution you'd like**
When a user has not completed his profile. (avatar, phone number, job, etc ...). We could surround his avatar in the hamburger menu with an incomplete yellow circle (part of the circle ie: percentage of completion) with a “Your profile is not complete, ...” tooltip or something like that. to encourage him to complete his profile. Here is a rough example attached.
![image](https://user-images.githubusercontent.com/27370604/180841160-0efddad4-9ed0-49ac-bdcd-98ccf57f9eaf.png)

**Comment by plamarque** [comment]
To encourage users fill their profile, we may be more explicity by displaying a progress % and a clear message to take action. 

Additionnally, we could also gamify it by offering an automated challenge (see #227) with points attributed when they complete the profile 100%.

**Comment by srenault-meeds** [comment]
Will be considered in a dedicated MIP
