### ISSUE TITLE
[Contributions] Implement automatic challenges based on events 

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#227]
**Is your feature request related to a problem? Please describe.**
All existing challenges are user-defined. why not implement automatic challenges?
**Describe the solution you'd like**
Some challenges could be implemented automatically such as:
- Completion of the profile (all the elements are filled in, avatar, phone number, etc.)
- First post in a public space.
- First article in a public space.
- First note in a public space.
- Many more...
- Reach a level of the gamification domain (Social, Engagement, etc.)
This functionality can be extended by other third parties.

**Comment by plamarque** [comment]
or completing your user profile (see #226)

**Comment by srenault-meeds** [comment]
Done for profile avatar, banner, bio, contact, work experiences, wallet
Other request/ideas can be done from UI and a rework is planned to be done so it will be possible from UI to identify which space, which app, which activity is watched and then gamified
