### ISSUE TITLE
Proposal for Enhancing Website Alignment with the United Nations Sustainable Development Goals (SDGs)

### ISSUE THREAD

**Issue by Abuteslimah99** [Meeds-io/meeds#2304]
**Is your feature request related to a problem? Please describe.**
While your website offers a variety of valuable features, I believe it lacks clear alignment with the United Nations Sustainable Development Goals (SDGs). As a user who is deeply committed to supporting sustainable practices, the absence of this alignment leaves me feeling somewhat disconnected. It’s challenging to fully understand how the products, services, or initiatives on your platform contribute to broader global goals, which can be frustrating for those of us who are eager to make informed, responsible choices.

**Describe the solution you'd like**
I kindly suggest incorporating a feature that highlights your website’s alignment with specific SDGs. This could involve a dedicated section or badges on product pages that clearly indicate how they contribute to the SDGs. Additionally, including a brief explanation or visual representation of your commitment to these goals would provide much-needed context and help users like myself make more informed decisions.

**Describe alternatives you've considered**
Should this not be feasible at the moment, an alternative could be to integrate blog posts, articles, or an FAQ section that educates users about your company’s sustainability efforts and how they tie into the SDGs. Another option could be to partner with organizations committed to these goals and showcase their work on your platform.

**Additional context**
As sustainability becomes increasingly important to consumers, aligning with the SDGs not only supports global initiatives but also enhances your brand’s reputation as a socially responsible entity. Many users, myself included, are actively seeking out businesses that demonstrate a genuine commitment to these goals. By making this alignment more transparent, you would not only improve user satisfaction but also potentially attract a broader, more engaged audience.

**Comment by srenault-meeds** [comment]
I'm sorry, I don't understand your proposition. Please be more specific
