### ISSUE TITLE
[Notifications] No marge between buttons and divider in the footer of notifications drawer

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#235]
**Steps to reproduce**
1-Open the notification drawer
2-consult the footer and the  buttons of  the drawer 

Actual behavior : 
The two buttons " SEE  ALL " and "MARK ALL AS READ"  are not well displayed  ( no marge between buttons and the divider)
![Selection_232](https://user-images.githubusercontent.com/50736962/181780803-1c4c1e28-f029-4305-bfc4-0159bbc7153e.png)

Expected behavior :
The footer & two buttons should be well displayed

**Comment by srenault-meeds** [comment]
Done by MIP https://github.com/Meeds-io/MIPs/issues/80
