### ISSUE TITLE
[Portlets] Remove My Reputation from contributions category

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#2363]
Current result:
My Reputation Instance is listed in the contributions Category
While it has been slightly replaced by the instance "Kudos Overview" in the overview page

Expected:
Remove the instance "My Reputation" from the category "Contribution"

**Comment by boubaker** [comment]
Already done in fact at the same time than Meeds-io/MIPs#156 when by improving the Upgrade Plugin to apply the same change on "Gamification Popular Spaces" portlet in spaces page, which is replaced by "Analytics Spaces List".
