### ISSUE TITLE
Activity reactions: indication of more like in the Last avatar is not clickable

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#237]
**Steps to reproduce**

1. create an activity
2. react to the activity add more than 4 likes 
3. click on the last avatar that contains "+X"

![ReactionsAvatars](https://user-images.githubusercontent.com/49310007/181784813-298a70cf-df84-4577-b27a-94489237fd8e.png)

**Current behavior**

The reactions drawer is not opened

**Expected behavior**

The reactions drawer should be opened

**Comment by srenault-meeds** [comment]
Fixed
