### ISSUE TITLE
Click on activity hidden likers count doesn't open likers drawer

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#238]
**Steps to reproduce**

1. Post anew activity in a space
2. Like the activity with more than 3 users
3. Click on empty avatar displaying the number of hidden likers
![image](https://user-images.githubusercontent.com/594824/182317097-479bbd69-2a98-4d18-af6d-657888694355.png)
4. Nothing happens

**Expected behavior**

When clicking on (+7) empty avatar (see attached screenshot above), the likers drawer should be opened

**Comment by plamarque** [comment]
duplicates #237
