### ISSUE TITLE
stream not displayed in spaces 

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#239]
**Steps to reproduce**

1. Go to ['Marketing' space on builders](https://builders.meeds.io/portal/g/:spaces:marketing/marketing)

It displays a placeholder text saying _'Sorry, you haven't bookmarked yet any space as favorite, go to the spaces page to do so.'_
<img width="755" alt="marketing-stream-placeholder-bug" src="https://user-images.githubusercontent.com/227828/182388304-f7924e4f-f04b-4786-b0af-429988df6e8a.png">

**(optional) Affected version**

builders version 1.4-20020901

**Current behaviour**

It does not make sense in the context of a space to display this placeholder because a space stream only display the activities of current space. I suspect it's related to filtering recently added. Note that on the /stream page, I have use the _'my favorite spaces filters'_ and I do have favorite spaces indeed.

**Expected behavior**

Display the activities of the marketing space or the empty stream placeholder if there are none, but not placeholder warning about lack of favorite spaces.

** Affected environments**  
 - Version :

**Comment by srenault-meeds** [comment]
Not reproduced for now
