### ISSUE TITLE
It is possible to set a space not a member of as a favorite + Misleading favorite behavior

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#240]
**Steps to reproduce**

1- Go to Spaces, Select a space that the current user is not a member of.
2- Navigate to the space. Capture the space ID from the Space homepage body source
3- Assuming the space id is `6`. Executing the following fetch command:
```js
fetch("https://builders.meeds.io/portal/rest/v1/social/favorites/space/6?parentObjectId=&spaceId=6&ignoreWhenExisting=true", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7,ar;q=0.6",
    "sec-ch-ua": "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Linux\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "https://builders.meeds.io/portal/meeds/spaces",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```
(Captured from normal HTTP request).
The space is submitted as a favorite. We should check membership before on the server side.

Another remark: when using a mismatch space ID it bookmarks to activity with a broken view:

![image](https://user-images.githubusercontent.com/27370604/182413143-d92d31f1-6814-437a-8d94-5e8a75c0783b.png)

**Comment by srenault-meeds** [comment]
Hi will be fixed in the next deployment.
