### ISSUE TITLE
[Links] Allow links portlet to provide mailto or tel or sms options

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#2401]
**Steps to reproduce**

1. Go to portlet link
2. add an item and define in the url : mailto:margondicco@exoplatform.com or tel:+33115651545 or sms:+33115651545 
3. See error
![image](https://github.com/user-attachments/assets/3e26f9f9-3a07-4d88-a16c-f8b4ea49382b)
 

**Expected behavior**
we must accept this type of url and its execution on click

**Comment by srenault-meeds** [comment]
Ok. We'll study it as an enhancement

**Comment by srenault-meeds** [comment]
Please, add another issue for phone number

**Comment by srenault-meeds** [comment]
> Please, add another issue for phone number

Will be finally improved here
