### ISSUE TITLE
Analytics - table : impossible to mention a value in a field

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#2404]
**Steps to reproduce**

1. Add a table report in a page
2. Open the settings of the portlet
3. Try to mention a value in the field of the main column 
4. Add a newx column and try to define a filter

result : impossible to define the valeur of the fields

![image](https://github.com/user-attachments/assets/7df0c281-57d1-4e0f-abc9-6cb4f5255895)

**Comment by srenault-meeds** [comment]
Merged to develop
