### ISSUE TITLE
Upgrade Spring Boot to latest (3.3)

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#2417]
Currently, the development branch of Meeds is using the version 3.2 of spring-boot-dependencies. We have to upgrade to latest stable version of 3.3 to benefit from security fixes and improvements such as Tomcat and Hibernate.
Besides, the `jcabi-plugin` isn't compatible anymore and has to be replaced by `aspectj-maven-plugin`.

----

### Merge Parent Poms
- https://github.com/Meeds-io/maven-parent-pom/pull/62
- https://github.com/Meeds-io/addons-parent-pom/pull/9
- https://github.com/exoplatform/maven-exo-parent-pom/pull/9 (eXo)
- https://github.com/exoplatform/addons-exo-parent-pom (eXo)
### Release Parent Poms
Release from develop a dedicated Milestone
### Update all projects with the newly released parent pom on Meeds
For all projects update project POM use the newly released parent POM
### Merge Meeds PRs
- https://github.com/Meeds-io/maven-depmgt-pom/pull/168
- https://github.com/Meeds-io/gatein-portal/pull/978
- https://github.com/Meeds-io/commons/pull/657
- https://github.com/Meeds-io/social/pull/4067
- https://github.com/Meeds-io/analytics/pull/227
- https://github.com/Meeds-io/gamification/pull/1744
- https://github.com/Meeds-io/gamification-github/pull/206
- https://github.com/Meeds-io/gamification-twitter/pull/107
- https://github.com/Meeds-io/perk-store/pull/349
- https://github.com/Meeds-io/wallet/pull/565
- https://github.com/Meeds-io/push-notifications/pull/67
- https://github.com/Meeds-io/notes/pull/1135
- https://github.com/Meeds-io/task/pull/428
- https://github.com/Meeds-io/addons-manager/pull/35
### Rebase develop-exo
Rebase all Meeds project to get changes from develop onto develop-exo
### Merge eXo PRs
After Build finishes on develop-exo, merge the following PRs:
- https://github.com/exoplatform/jcr/pull/330
- https://github.com/exoplatform/ecms/pull/2405
- https://github.com/exoplatform/dlp/pull/62
- https://github.com/exoplatform/agenda/pull/693
- https://github.com/exoplatform/onlyoffice/pull/267
- https://github.com/exoplatform/web-conferencing/pull/335
- https://github.com/exoplatform/multifactor-authentication/pull/77
- https://github.com/exoplatform/data-upgrade/pull/248
- https://github.com/exoplatform/chat-application/pull/773

**Comment by boubaker** [comment]
## Strategy for Merge
### Merge Parent Poms
- https://github.com/Meeds-io/maven-parent-pom/pull/62
- https://github.com/Meeds-io/addons-parent-pom/pull/9
- https://github.com/exoplatform/maven-exo-parent-pom/pull/9 (eXo)
- https://github.com/exoplatform/addons-exo-parent-pom (eXo)
### Release Parent Poms
Release from develop a dedicated Milestone
### Update all projects with the newly released parent pom on Meeds
For all projects update project POM use the newly released parent POM
### Merge Meeds PRs
- https://github.com/Meeds-io/maven-depmgt-pom/pull/168
- https://github.com/Meeds-io/gatein-portal/pull/978
- https://github.com/Meeds-io/commons/pull/657
- https://github.com/Meeds-io/social/pull/4067
- https://github.com/Meeds-io/analytics/pull/227
- https://github.com/Meeds-io/gamification/pull/1744
- https://github.com/Meeds-io/gamification-github/pull/206
- https://github.com/Meeds-io/gamification-twitter/pull/107
- https://github.com/Meeds-io/perk-store/pull/349
- https://github.com/Meeds-io/wallet/pull/565
- https://github.com/Meeds-io/push-notifications/pull/67
- https://github.com/Meeds-io/notes/pull/1135
- https://github.com/Meeds-io/task/pull/428
- https://github.com/Meeds-io/addons-manager/pull/35
### Rebase develop-exo
Rebase all Meeds project to get changes from develop onto develop-exo
### Merge eXo PRs
After Build finishes on develop-exo, merge the following PRs:
- https://github.com/exoplatform/jcr/pull/330
- https://github.com/exoplatform/ecms/pull/2405
- https://github.com/exoplatform/dlp/pull/62
- https://github.com/exoplatform/agenda/pull/693
- https://github.com/exoplatform/onlyoffice/pull/267
- https://github.com/exoplatform/web-conferencing/pull/335
- https://github.com/exoplatform/multifactor-authentication/pull/77
- https://github.com/exoplatform/data-upgrade/pull/248

**Comment by boubaker** [comment]
Ready for test & review @rdenarie for this technical upgrade. The mips ACCs and FBs has been updated as well (please see issue description for detailed steps for merged if all is ok)

**Comment by rdenarie** [comment]
Hi, Majority of PRs validated. I commented few of them with a question

**Comment by boubaker** [comment]
> Hi, Majority of PRs validated. I commented few of them with a question

Thanks, replied

**Comment by rdenarie** [comment]
all pr validated

**Comment by boubaker** [comment]
> all pr validated

Thanks

**Comment by hbenali** [comment]
Added: 
- https://github.com/exoplatform/jitsi-call/commit/25459fc928b12b8396d0fad2bb298e36e38036c2 
- https://github.com/exoplatform/jitsi-call/commit/39a89ad600be270eedb132a007cdf2d3c93a3537
