### ISSUE TITLE
[Onboarding] [Documentation] Add What's new Page

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#242]
**Is your feature request related to a problem? Please describe.**
A normal user is not aware of platform changes.

**Describe the solution you'd like**
Add a single page called What's New which illustrates all the features added to the platform. It should contain screenshots and videos. etc ...

**Technical Spec:**
This page should be extensible with Meeds Add-ons.

**Comment by srenault-meeds** [comment]
Hi @hbenali,

What you actually describe reminds me something like a documentation that is implemented continuously. And the what's new can display the latest documentation added / updated (by default or by choice)
WDYT?

**Comment by srenault-meeds** [comment]
Link added in the bottom of the left nav
