### ISSUE TITLE
[Layout] Application of custom display to IDE App

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#2428]
**Steps to reproduce**

1. Create a portlet from the IDE
2. Add the porlet on a page
3.  Define properties as border or background

Error : 
The properties aren't applied

https://github.com/user-attachments/assets/71dbc8a7-e633-475c-aff2-ea9398ab024a

**Comment by srenault-meeds** [comment]
FYI @margondicco it is expected for more flexibility.
If you need to apply custom style to your IDE, you can use class helper like application-layout-style, application-border, etc.

Class Helper Referential: [here](https://github.com/Meeds-io/platform-ui/blob/develop/platform-ui-skin/src/main/webapp/skin/less/core/layout/pagelayout.less)

I am available if needed to talk about it.
