### ISSUE TITLE
Navigation : clicking on group item on top bar opens a blank page

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#2437]
**Steps to reproduce**

1. in public site, define a new item of type Group and make it visible

![Screenshot 2024-09-27 at 14 50 34](https://github.com/user-attachments/assets/026df327-691e-4f86-ac9c-d535c090da5f)

2. add 2 subnodes of type group also
3. open the public site and click on the first item

**Current behaviour**

the item is clickable and opens a blank page
![Screenshot 2024-09-27 at 14 53 12](https://github.com/user-attachments/assets/9ef993e1-e98f-4d06-8c28-8f0cc2ef255a)

**Expected behavior**

the item should not be clickable

**Comment by srenault-meeds** [comment]
Improved @plamarque
