### ISSUE TITLE
Freeze the Web3 nonsense and focus on AI tools

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#2446]
**Is your feature request related to a problem? Please describe.**
Web3 is dead. We should admit it and no more work on it! It's quite late to include AI stuff on notes, task, stream composer, articles,... (such AI suggestion, autocompletion) 
**Describe the solution you'd like** 
Start brainstorming with AI and cut off with the most no sense technology web3 of 21th century

Thanks

**Comment by srenault-meeds** [comment]
Let's discuss it in a room.
That'd be more appropriate :)
