### ISSUE TITLE
[Analytics] Ability to edit JSON settings to manage sorting, parameters - Advanced User

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#2447]
**Is your feature request related to a problem? Please describe.**

_As advanced user_
When adding the application analytics report, we cannot sort the column by UI or using the JSON
When adding the application analytics chart or report or rate, we cannot use the JSON to manage parameters more easily than searching in the UI Settings

**Expected**
A minimum output would be to give the ability to edit the JSON file proposed in the three dots:
- Open "Settings JSON" from three dots
- A drawer opens (instead of the current popup) with the JSON
- Option to expand the drawer if needed for better use
- At the bottom, we have a save and a close button
- Once saved, the chart/report is updated accordingly with no page refresh needed

_Precision: Provide to analytics report a 3-dots._
Currently, only a cog is proposed to access the settings.
Group it into a 3-dots with:
- Settings
- JSON Settings

**Comment by margondicco** [comment]
Hello

@srenault-meeds 
Not agree with the feature enhancement. I could do it before (by editing the json) and now the table report is no longer usable

**Comment by boubaker** [comment]
> Hello
> 
> @srenault-meeds Not agree with the feature enhancement. I could do it before (by editing the json) and now the table report is no longer usable

Yes, you was able to do it using the old Layout Editor in eXo Addons, with the new Layout Editors in Meeds, we don't have such feature. You may mean, this feature should be brought to Analytics as core feature, but until now it doesn't exists, thus I think it's a new feature request/ quick win rather than a bug fix.

**Comment by boubaker** [comment]
In few terms, this  wasn't possible on Meeds since the beginning

**Comment by srenault-meeds** [comment]
Enhanced and Delivered on develop.
Enjoy @margondicco

**Comment by margondicco** [comment]
Hello a big thank you for that !!
