### ISSUE TITLE
Stream Filters : no refresh when unmarking activity as favorite

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#245]
**Steps to reproduce**

1. Go to a space activity stream
2. mark th first activity as favorite
3. Click on the stream filters pulldown and select 'favorite activities'
4. Unmark the first activity as favorite
5. The stream is not updated : activity still visible : 

<img width="565" alt="favorite-removed" src="https://user-images.githubusercontent.com/227828/182855383-610e5d05-1000-4dfd-b976-029ed2bb7abb.png">

**(optional) Affected version**

1.4.0-20220802_1

**Current behaviour**

Marking and unmarking the task as favorite does not refresh the screen when favorite activities is selected, while it should.

**Expected behavior**

The stream should be refreshed with the first activity (unmarked as favorite) disappearing.

**Comment by srenault-meeds** [comment]
Improved. Thanks
