### ISSUE TITLE
Hidden space + Space label appear on activity

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#248]
**Steps to reproduce**

1. As platform **administrator**, post activity in a hidden space (not a member of)
2. Refer to the main or space activity stream
3. Two labels "Hidden Space" and "Space name" appear on the activity which is confusing.

![image](https://user-images.githubusercontent.com/27370604/184096928-d96c34df-1c6c-4a8c-97d9-918c48ff7000.png)
**Affected version**

1.4.0-20220809

**Current behavior**

Two labels appear "Hidden Space" and "Space name
**Expected behavior**

Display only one label, if the current user is an admin display the space name, otherwise hide the space name.

**Comment by srenault-meeds** [comment]
Fixed now in the 1.4.x version. Thanks
