### ISSUE TITLE
Bad display of the MEED price when selecting the USD currency

### ISSUE THREAD

**Issue by MayTekayaa** [Meeds-io/meeds#249]
**Steps to reproduce**

1. Go to 'https://investors.meeds.io/dapp/'
2. Click on 'USD' currency at the top right.
3. See the price of MEED on the graph at the top left.

Screenshot of the bug: 
![Screenshot from 2022-08-12 14-35-27](https://user-images.githubusercontent.com/100131287/184366277-323afe74-7686-44ba-99ca-411089d77c9e.png)

**Comment by srenault-meeds** [comment]
Hi @MayTekayaa can you please explain what the expected behaviour is.
Thanks

**Comment by srenault-meeds** [comment]
Ok noted after discussion with Mayssa:
That should be 0.33$ and not 0.33$US
Same feedback when EUR currency is chosen

cc @Imenmakni can you take care of it please?

**Comment by MayTekayaa** [comment]
@Samuel-Renault-eXo this bug isn't reproduced when EUR currency is chosen and for the USD currency, treated and merged on develop and it will be soon on prod.

**Comment by srenault-meeds** [comment]
Yes right sorry for the mistake :-)
