### ISSUE TITLE
[Layout] Page template - Image Background not displayed for externals

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#2502]
1. Go to portal/administration/home/development/template/pages and create a pageX as new page template
2. Make sure to add one or many images as various blocks background and save
3. Create new spaceX and invite userExternal (external user) 
4. edit any page in spaceX by applying pageX template 
5-COnnect with userExternal and got to updated spaceX page

**Current behaviour**
Background images aren't displayed

**Expected behavior**
Background images should be displayed 

screenshot : 
![Screenshot from 2024-10-21 17-27-08](https://github.com/user-attachments/assets/592f9ddf-9fc4-4a76-bdaa-11b30423a720)

**Comment by Jihed525** [comment]
meeds issue created as discussed @margondicco 
fyi @srenault-meeds

**Comment by srenault-meeds** [comment]
Hi @Jihed525 do you take care of this one?
Thanks

**Comment by Jihed525** [comment]
not yet included in top priority, but if it will be, I will update you
eXo Task ID : [74982](https://community.exoplatform.com/portal/dw/tasks/taskDetail/74982)
