### ISSUE TITLE
[Spaces] [Analytics] Recent spaces / Most active spaces no more updated in spaces list

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#2524]
**Steps to reproduce**

1. Go to /portal/mycraft/dashboard
2. Check the "spacesList" and specially the part "Recent spaces" & "Most active"
3. Go to a space with is not in the list
4. Add a post, manage tasks, add notes in this space
5. Go to /portal/mycraft/dashboard

**Problem:**
Recent spaces list is not updated
Most active list is not updated

**Expected behaviour :** 
Recent spaces list and most active list must be updated depending on the access / activity

Screencast explaining the problem: 
https://github.com/user-attachments/assets/4ad5e9b1-4776-403f-bfe5-96775e5078a7

**Comment by boubaker** [comment]
That's normal since the left menu didn't changed yet. The analytics takes time to be considered, thus it's asynchronous and not synchronous as made in the left menu.

**Comment by rdenarie** [comment]
How long time it take to consider ?

**Comment by boubaker** [comment]
> That's normal since the left menu didn't changed yet. The analytics takes time to be considered, thus it's asynchronous and not synchronous as made in the left menu.

Finally, I tested the behavior and in fact **it's a bug since the list isn't updated even after a while**

> How long time it take to consider ?

Theoretically few seconds

**Comment by srenault-meeds** [comment]
I have updated the description and the name to not only report the "recent spaces" list but also the "most active"
