### ISSUE TITLE
[Space] Wrong space member count on popover after deleting members

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#253]
**Steps to reproduce**
1-Create a space 
2-add a post to the space
3-Add 3 users to the space 
4-Remove one user from the space and keep the others
5-Hover the space name from the previous post and check the number of members

Actual behavior : The space member count is still with the previous count  
https://youtu.be/vmLMj7xkWfM 
Expected behavior : The space member count should be updated according to remove action

**Comment by srenault-meeds** [comment]
Space popover and topbar space popover / reproduced. Thanks!

**Comment by srenault-meeds** [comment]
Fixed in the next deployment (when updating members from space members app)
