### ISSUE TITLE
Remove the ability to tap enter in the fields of links portlet

### ISSUE THREAD

**Issue by sirinebenabbes** [Meeds-io/meeds#2535]
** Affected version**
7.x and 6.5.x

**Steps to reproduce**

1. Add a link portlet to any page
2. Add a title for the added link portlet then click on keyboard "Enter" button

**Current behaviour**

The page is reloaded and the typed title isn't saved

**Expected behavior**

Remove the ability of saving by "Enter" button in the fields of links portlet
Only clicking on the button **Confirm** should save the typed data

**Comment by srenault-meeds** [comment]
Not a bug but enhancement

**Comment by boubaker** [comment]
Renamed as well to not adding Labels in Title of the issue

**Comment by sirinebenabbes** [comment]
eXo task:
https://community.exoplatform.com/portal/dw/tasks/taskDetail/75120
