### ISSUE TITLE
Drop Infinispan 8

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#2537]
**Is your feature request related to a problem? Please describe.**

Currently, Infinispan 8 is added into Meeds package while it's not used

**Describe the solution you'd like**

Cleanup ISPN based Cache and TransactionService. At the same time, drop javax libraries brought through ISPN 8 and cleanup dependency tree from useles libraries.

**Comment by boubaker** [comment]
Dev Meed PRs:
- https://github.com/Meeds-io/maven-depmgt-pom/pull/176
- https://github.com/Meeds-io/kernel/pull/67
- https://github.com/Meeds-io/core/pull/100
- https://github.com/Meeds-io/ws/pull/45
- https://github.com/Meeds-io/gatein-sso/pull/51
- https://github.com/Meeds-io/gatein-portal/pull/998
- https://github.com/Meeds-io/commons/pull/667
- https://github.com/Meeds-io/social/pull/4158
- https://github.com/Meeds-io/gamification/pull/1770
- https://github.com/Meeds-io/kudos/pull/550
- https://github.com/Meeds-io/perk-store/pull/357
- https://github.com/Meeds-io/wallet/pull/607
- https://github.com/Meeds-io/analytics/pull/241
- https://github.com/Meeds-io/notes/pull/1195
- https://github.com/Meeds-io/meeds/pull/2561

**Comment by boubaker** [comment]
Meeds PRs to develop:
- https://github.com/Meeds-io/maven-depmgt-pom/pull/178
- https://github.com/Meeds-io/kernel/pull/68
- https://github.com/Meeds-io/core/pull/101
- https://github.com/Meeds-io/ws/pull/46
- https://github.com/Meeds-io/gatein-sso/pull/52
- https://github.com/Meeds-io/gatein-portal/pull/1003
- https://github.com/Meeds-io/commons/pull/670
- https://github.com/Meeds-io/social/pull/4192
- https://github.com/Meeds-io/gamification/pull/1775
- https://github.com/Meeds-io/kudos/pull/554
- https://github.com/Meeds-io/perk-store/pull/359
- https://github.com/Meeds-io/wallet/pull/615
- https://github.com/Meeds-io/analytics/pull/246
- https://github.com/Meeds-io/notes/pull/1210
- https://github.com/Meeds-io/meeds/pull/2579

eXo PRs:
- https://github.com/exoplatform/maven-exo-depmgt-pom/pull/25
- https://github.com/exoplatform/commons-exo/pull/55
- https://github.com/exoplatform/jcr/pull/332
- https://github.com/exoplatform/ecms/pull/2430
- https://github.com/exoplatform/multifactor-authentication/pull/79

**Comment by boubaker** [comment]
Ready for Review @rdenarie on MIP ACCs

**Comment by rdenarie** [comment]
Hello. 
Ok for me, you can process to merge

**Comment by boubaker** [comment]
Merged to develop for Meeds & eXo PRs
