### ISSUE TITLE
[Perks] technical label has been detected in the add new product drawer in Perks

### ISSUE THREAD

**Issue by ArfaouiMohamedAmine** [Meeds-io/meeds#254]
**Steps to reproduce**

1. Go to 'perks'
2. Click on 'add product'
3. upload an image for the product
4. delete the uploaded image (I changed my mind)
5. Find error with technical label on it

![Screenshot from 2022-08-18 16-30-56](https://user-images.githubusercontent.com/101107377/185435551-d8d78210-1625-4355-a101-fb5943b54494.png)

**Comment by srenault-meeds** [comment]
@Imenmakni can we take it in consideration for the cleanup phase?
cc @ArfaouiMohamedAmine

**Comment by srenault-meeds** [comment]
should be ok now
