### ISSUE TITLE
[Rewards] Missing info for rewards history

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#2540]
Issue:

**Steps to reproduce**
- Access the overview page
- Check the rewards portlet
- See error:
   - last rewards info is missing
   - when clicking to see all, the rewards tab is empty

![image](https://github.com/user-attachments/assets/c0735313-5094-479c-8843-7ba3bb6629a6)
![image](https://github.com/user-attachments/assets/fafd1184-d94b-4cb1-b8ef-3f2b70f11753)

**Expected**
- Last rewards is displayed in the app when the case
- Clicking to it opens the drawer of rewards focused to rewards history

**Comment by Ultimecia1463** [comment]
is there any money incentive for issues with 'reward' label?

**Comment by srenault-meeds** [comment]
Hi, adding a label to an issue helps us to organize issues.
Hence, you can get 5 points per label added, knowing that points can be rewarded with Meeds Token.

If you want to know more, please visit meeds.io and join us on Builders
