### ISSUE TITLE
[Space Template] Missing tooltip for template status

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#2551]
**Is your feature request related to a problem? Please describe.**
In space template administration, the switch button about Status is not self explanatory. We do not understand quickly what is the purpose of the button.
In user management, we have the same switch, with a little tooltip, which give information about the status.

**Describe the solution you'd like**
Add the same tooltip in space template administration.

**Comment by boubaker** [comment]
It should be better now IMO
![image](https://github.com/user-attachments/assets/24bcd85c-3101-4b0b-821a-f674d756a54e)
