### ISSUE TITLE
Accessibility issue on top bar

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#2567]
**Steps to reproduce**

Check the accessibility of the top bar.

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**
The left menu button and the edit navigation buttons have no accessible name. 
![image](https://github.com/user-attachments/assets/3bb04d90-7f93-4ed6-b139-5d5d32f04775)

**Expected behavior**
They have accessible name and we don't find accessibility issue when checking with Lighthouse. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds it might be fixed during the review of left navigation. It's a small thing but it reduces the accessibility score of all pages. 

cc @margondicco

**Comment by srenault-meeds** [comment]
Yes already reported there: https://github.com/Meeds-io/meeds/issues/2413
