### ISSUE TITLE
[Branding] Favicon missing for the Meeds Builders site

### ISSUE THREAD

**Issue by ahamdi** [Meeds-io/meeds#2568]
**Steps to reproduce**

1. Go to https://builders.meeds.io
2. Check the website icon 
3. No icon is there
4. Check screenshot

![image](https://github.com/user-attachments/assets/e805e75c-8f0b-462e-8355-91972f1e5c49)

![image](https://github.com/user-attachments/assets/f170bb54-16f2-4030-9a56-e1c02c73ddd5)

Current behaviour: favicon setting from branding page is empty

**Expected**
Favicon added from branding is well displayed and favicon remain added in the branding

**Comment by plamarque** [comment]
go to where ?

**Comment by ahamdi** [comment]
@plamarque to the Meeds builders website
