### ISSUE TITLE
[Spaces] List unlisted spaces to admins when not member of

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#2574]
**Steps to reproduce the behavior:**
1. Log with an simple user : john and create a space : spaceTest
2. spaceTest is unlisted for non members (hidden)
3. Logout, and login with an admin
4. Three cases:
   - Search for this space in the spaces directory: it is not listed for admins when not member of
   - From space template conf, try searching for the space to add a permission for the group
   - From members sync, try searching for the space for a members sync

**Current Result**
The spaceTest is not proposed.

**Expected Result**
As soon as the user is an admin, it is possible to access any space even if unlisted and not member of it.
Thus, it must be possible to search for it too (unified search or suggestor search

**Comment by srenault-meeds** [comment]
Done with MIP160
