### ISSUE TITLE
[Navigation] Options for opening links or existing page doesn't work

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#2576]
**Steps to reproduce the behavior**

FIRST ISSUE
Given adding an item
When choosing **_link_** or **_existing page_**
Then I can choose to make it open in a new tab or not

**Current behavior**
- If new tab chosen (switch off), 
   - once applied, it is ok
   - When editing it, the switch is back to on 
   - When switching it to off, it is not considered and the page is open in same tab
- If new tab chosen (switch on), 
   - When switching it to off, it is not considered and the page is open in same tab

[Vidéo](https://youtu.be/bDGMpuWkPfs)

**Expected**
When adding an item to a site (space or site) 
No matter it is a link or an existing page
- If the option  "Open in the same tab" is true : when i click the url opens in the same tab
- if the option  "open in the same tab" is false : when i click, the url opens in a new tab

Another requirements : 
I should not clean my cache. 
It works with Firefox, Safari or a chromium browser

**Comment by srenault-meeds** [comment]
Video is private FYI @margondicco

**Comment by margondicco** [comment]
> Video is private FYI @margondicco

done thank you

**Comment by margondicco** [comment]
cc @srenault-meeds i added a new issue on it because it's really close. FYI it's blocker for a publication on a store

**Comment by srenault-meeds** [comment]
Can you create another issue please?
This is different.

BTW I don't reproduce it for now

**Comment by srenault-meeds** [comment]
ok reproduced only from tabbar nav (when using tablet/mobile view). As discussed, this will be explained in another task
