### ISSUE TITLE
[Profile] About me & Work experiences not visible to non-admins

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#2577]
**Steps to reproduce**

1. As userAlpha, fill your profile including the about me and the work experiences
2. As a regular user (no admin), access the userAlpha profile
3. See error: I can't see the about me and the work experiences of userAlpha

Indeed, only platform admin can see it

**Expected behavior**
Any registered user (internal or external) must be able to see the informations of a user, incl. about me and work experiences

**Comment by Jihed525** [comment]
Related eXO Task : [75378](https://community.exoplatform.com/portal/dw/tasks/taskDetail/75378)

**Comment by boubaker** [comment]
Considered in Meeds Board as well, [PR](https://github.com/Meeds-io/social/pull/4193) in under test

**Comment by Jihed525** [comment]
@boubaker @srenault-meeds For clarity purpose, I have created the eXo task in order to track the fix progress as a patch might be needed, but rest assured that no work is being invested on eXo side on this issue as it is being already treated on meeds side.

**Comment by boubaker** [comment]
> @boubaker @srenault-meeds For clarity purpose, I have created the eXo task in order to track the fix progress as a patch might be needed, but rest assured that no work is being invested on eXo side on this issue as it is being already treated on meeds side.

cool, thanks :+1:
