### ISSUE TITLE
[Contributions] Contributions cannot be cancelled

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#2578]
**Steps to reproduce**

1. Go to https://builders.meeds.io/portal/contribute/contributions/achievements
2. Filter on this week and contributor : Ether Udosen
3. on any of the actions, click (x) icon to cancel
4. a tooltip indicates it's not possible with message : "status cannot be updated because rewards have been sent"

In this case, it's not correct. rewards cannot be sent on current week (it must be done on finished week).

![Screenshot 2024-11-14 at 13 55 21](https://github.com/user-attachments/assets/17810c74-5f17-4ab5-8f85-d6ff3b0303fb)

**Current behaviour**

Impossible to cancel contibution and misleading message

**Expected behavior**

I should be able to cancel the contribution

**Comment by srenault-meeds** [comment]
Related to MIP154 and fixed. Delivered soon

**Comment by srenault-meeds** [comment]
Fixed @plamarque
