### ISSUE TITLE
Choosing a period for achievements calculation is buggy on dates selection

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#258]
**Steps to reproduce**

1. Admin -> achievements
2. Click on a previous month first and last day
=> you cannont, the widget is stuck on the current month
As an extension of this, the behaviour of the widget is weird, you cannot select dates as you want

Please complete the following information: 
 - OS: MacOS
 - Browser : chrome
 - Version Version 104.0.5112.79 (Build officiel) (arm64)
 - Device: MacBookPro

**Comment by srenault-meeds** [comment]
cc @Imenmakni please consider it while we are reworking the achievements table.

**Comment by Imenmakni** [comment]
i can not repoduce it, @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
Ok thanks @Imenmakni indeed.
@souillac is that possible to organize a call so I can try understand what is going on?
Thanks

**Comment by srenault-meeds** [comment]
Reproduced today with a 1.3.0 meeds version (6.3.0 exo platform). Please check the gif there. It is annoying and to check if ok with 1.4.x.

![pb achievements datepicker](https://user-images.githubusercontent.com/58853195/187863919-2ce71d73-14ff-4617-9dc6-3053abd40be1.gif)


@Imenmakni
