### ISSUE TITLE
Rewards table ordering does not wok

### ISSUE THREAD

**Issue by souillac** [Meeds-io/meeds#259]
**Steps to reproduce**

1. Go to Admin -> Rewards
2. Click on "name" column title

=> attached

Please complete the following information: 
 - OS: MacOS
 - Browser chrome
 - Version  104.0.5112.79 (Build officiel) (arm64)
<img width="355" alt="Capture d’écran 2022-08-22 à 09 06 32" src="https://user-images.githubusercontent.com/5012996/185860315-dd2ffcca-991f-4948-afe2-31b2b23e08e9.png">

 - Device: MacBookPro

**Comment by srenault-meeds** [comment]
Please @Imenmakni can you catch this?

**Comment by srenault-meeds** [comment]
Fixed on 1.4.x meeds
