### ISSUE TITLE
[Spaces] Impossible to access to a space public site as registered user

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#2592]
**Steps to reproduce**

1. Create a space public site with option register users for the space Alpha
2. WIth another user, open the space directory and click on the space card of the space Alpha
3. Error : a blank page opens

![Video_24-11-16_09-10-22](https://github.com/user-attachments/assets/c9c105c0-d060-485e-b87e-51d4d5f007a6)

Precision: it is ok when visible to anyone

**Comment by boubaker** [comment]
Related to Meeds-io/MIPs#160, can you please add a comment there since it's not in production yet.

**Comment by srenault-meeds** [comment]
I take care of it 😉

**Comment by srenault-meeds** [comment]
Here : https://github.com/Meeds-io/MIPs/issues/160#issuecomment-2480479254

**Comment by boubaker** [comment]
Should be fixed by now

**Comment by srenault-meeds** [comment]
Indeed thanks
