### ISSUE TITLE
unresolved label strings in notification email

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#2599]
**Steps to reproduce**

1. Receive an email notification for new action on. Builders Hub
2. subject and body are in the form "Notification." string instead of an English label
![Screenshot 2024-11-19 at 01 33 24](https://github.com/user-attachments/assets/81d48b37-4a5a-4cb5-ab49-3a64b5a7e8f7)

**Current behaviour**

subject and body strings are not resolved

**Expected behavior**

Should be displayed in English or in user preferred language

**Comment by srenault-meeds** [comment]
Duplicated: https://github.com/Meeds-io/meeds/issues/2596

And fixed now
