### ISSUE TITLE
[OIDC] Unable to connect with OIDC on ADFS

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#260]
**Steps to reproduce**

1. Configure meeds server to allow login with OpenId connect, using ADFS as Identity Server
2. Open meeds login page
3. Click on Openid Connect Button
4. Log on ADFS Identity Server
5. Error 500

**Affected version**
6.3.0+

**Current behaviour**
The openid connect with ADFS Identity Server make error 500 during login process 

**Expected behavior**
When using oidc with ADFS, user must be loggued in meeds correctly

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
Done
