### ISSUE TITLE
[Contributions] Export action comment or link in the exported file

### ISSUE THREAD

**Issue by BalouBalou** [Meeds-io/meeds#2601]
**Current behavior**

**Use case** 
I use de contribution programm in webinars. Example : https://community.exoplatform.com/portal/dw/activity?id=445883#comment-comment446623 
I ask questions to my participants and I get answers from the community. 
So this works fine.

But what is currently missing: I would like to extract the community answers in the xls. file. This is momentary, not possible. 

**Expected behavior**
So my improvement suggestion would be to make community answers available in the xls file. 
[report_Actions.xlsx](https://github.com/user-attachments/files/17814015/report_Actions.xlsx)

**Comment by srenault-meeds** [comment]
@BalouBalou it is now possible to access the contribution details in the export:
- if auto, link to the activity
- if manual, comment + link to the activity

**Comment by BalouBalou** [comment]
LOve it !!! Big thanks
