### ISSUE TITLE
Okhttp library generate a Skyk issue report

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#261]
Snyk targets okttp:3.8.1 as vulnerable to [CWE-200](https://cwe.mitre.org/data/definitions/200.html).

This library is a dependency of org.web3j:core:4.5.11
We need to update to org.web3j:core:4.9.4 which is the last released version. This version comes with okhttp3:4.9.0.

This will allow us to reduce the gap between the version we use and the last available one.

**(optional) Affected version**

Observed in plf 6.4.x

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
done
