### ISSUE TITLE
Unread activities can create a huge number of lines in SOC_METADATA_ITEMS

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#2618]
Scenario :
Create few spaces (around 10), space group bonded on users groups (all users are added in spaces).
Add few thousand of users (2000 at least).
Create activities in spaces. Each activity creates 2000 metadata unread activities.
Create 2000 activities in all spaces.

Current Behavior :
The request to build the user recent space list is long to execute (more than 1 minutes).

We have 2 working path on this :
How to reduce the execution time of the request which get unread activities by space ?
Functionaly, should we limit unread activities at some point ?

**Comment by Jihed525** [comment]
related eXo task 75572

**Comment by srenault-meeds** [comment]
FYI @Jihed525 As discussed with @margondicco we will study it with the MeedsLab team
