### ISSUE TITLE
Tika version1.25 have reported vulnerabilities

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#262]
Tika libraries are currently in version 1.25

Snyk shows vulnerabilities in this version :

tika-core : [cwe.mitre.org/data/definitions/1333.html](https://cwe.mitre.org/data/definitions/1333.html)
tika-parsers : [cwe.mitre.org/data/definitions/835.html](https://cwe.mitre.org/data/definitions/835.html)
junrar (tika dependency, version 7.4.0) : [cwe.mitre.org/data/definitions/400.html](https://cwe.mitre.org/data/definitions/400.html)

Update to the last version 1.28.4 should resolve theses problems.

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
done
