### ISSUE TITLE
jdom2 is present in version 2.0.5, and have security vulnerability

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#263]
Snyk report a vulnerability CWE-611 in jdom2:2.0.5. This version comes from com.rometools:rome:1.15.0

To resolv this issue we need to update rome to last available version 1.18.0

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
done
