### ISSUE TITLE
[Stream] User is unable to post in a space from the global stream

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#2638]
**Steps to reproduce**

1. Create a user with a capital letter in his username. It is not possible by default with interface, but it can be done with curl request : 
curl --location 'http://www.localhost:8080/rest/private/v1/social/users' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data-raw '{
  "email": "franck.smith@exoplatform.com",
  "firstname": "Franck",
  "lastname": "Smith",
  "password": "Password1234",
  "username": "Franck"
}'

Replace Authorization with basic authentication header of an administrator

2. Create a space 'test space' and invite franck into
3. Log with franck, accept invitation, and go to global stream page : http://localhost:8080/portal/mycraft/dashboard
4. Click on "Start a post", choose "One of your spaces", and type 'test'
5. The test space is not founded
6. Log with the space creator, try same scenario, space is found

**Comment by srenault-meeds** [comment]
Related commit: https://github.com/Meeds-io/social/pull/4261
