### ISSUE TITLE
org.json:json:20070829 has a security vulnerability raised by Snyk

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#264]
We currently use org.json:json:20070829

Snyk raise an issue on this version : [cwe.mitre.org/data/definitions/400.html](https://cwe.mitre.org/data/definitions/400.html)

We should update to the last available version : 20220320

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
done
