### ISSUE TITLE
Event isn't created when inviting users by uppercase email letters

### ISSUE THREAD

**Issue by sirinebenabbes** [Meeds-io/meeds#2676]
**(optional) Affected version**

On 7.x and 6.5.x

**Steps to reproduce**

 

1. Open agenda application of a space
2. Create an event or a poll and invite a user by typing his email with at least one char in uppercase

  

 
**Current behaviour**

Event isn't created

**Expected behavior**

1. Event is well created
2. Email is well sent to invited user

**eXo related task**  

 https://community.exoplatform.com/portal/dw/tasks/taskDetail/75566

**Comment by srenault-meeds** [comment]
Meeds does not provide agenda app FYI
Unless this is related to Meeds code, I suggest we remove this issue

@Jihed525
