### ISSUE TITLE
[Update from 1.5 to last version 7.0.x] The page portal:global:activity have a display problem

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#2690]
**Steps to reproduce**

1. Start meeds 1.5.x
2. Migration to meeds 7.0.x
3. Go to page activity in any portal (to see the global activity page)

**Current Behaviour**
There is no margin displayed, and there is a problem in the DOM :
![image](https://github.com/user-attachments/assets/9e40c570-51d8-45d0-b583-6dc27714a15d)

![image](https://github.com/user-attachments/assets/d58444fc-f3a8-4b97-a08e-75216df47884)
A double quote is missing

**Expected behaviour**
The page should be correctly display, and the DOM should be : 

<div class="UIContainer UITableColumnContainer"   id=" singlepageapplicationcontainer">

**Comment by boubaker** [comment]
You can find here the complete list of groovy templates to impact:
https://github.com/Meeds-io/gatein-portal/commit/c1d3fce23b87fe39f270a62498cd53d7272828bc

**Comment by rdenarie** [comment]
@boubaker do you prefer to continue the fix ? I can abandon my commit on feature/maintenance, and so you continue withyyour commit ?

**Comment by boubaker** [comment]
> @boubaker do you prefer to continue the fix ? I can abandon my commit on feature/maintenance, and so you continue withyyour commit ?

Nope, just to help, because I saw the first commit made didn't fixed all gtmpl files

**Comment by rdenarie** [comment]
ok, I'll use your commit, and finalize the fix the repair all templates.
Thanks
