### ISSUE TITLE
[Space] Regular member must not access settings of a space

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#2699]
**Steps to reproduce**

1. As space member and not admin 
2. Access a space
3. At the end of the URL, add /home**/settings**
4. See error: the user who is a regular member can access settings page of the space

**Expected behavior**

Space members must not access the settings even with the direct link

Precision: the space member can access it but it is not possible for him to update anything

**Comment by boubaker** [comment]
This is a normal behavior since the page is a global page, thus the page must be accessible to all users including externals even

**Comment by srenault-meeds** [comment]
Ok thanks. I cancel this one then
