### ISSUE TITLE
Mute space: left Menu becomes none responsive

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#2701]
1. Set left menu to icon view
2. on space menu section mute spaceX 
3. try to open your own settings OR click on your own profile icon OR logout
Actual behavior
Neither of listed actions above are possible to choose as drawer closes (https://community.exoplatform.com/portal/download-document/f7bddb0eac12000f4d772692d15d80fc)
If menu is locked or hidden : Neither of listed actions above are possible to choose
Expected Behvaior
The message displayed shouldn't disable the action on other icons

**Comment by Jihed525** [comment]
@srenault-meeds

**Comment by boubaker** [comment]
@Jihed525 I think this is an expected behavior since you hover the Snackbar and no more the Sidebar. You can close the snackbar to access the Sidebar buttons if needed or wait until the Snackbar disappears within 10 seconds. IMO, it's better to not make any modification to workaround this.

**Comment by srenault-meeds** [comment]
Thanks @boubaker for replying to it
