### ISSUE TITLE
Spaces list drawer: 3 dots menu is still displayed even if space is changed

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#2702]
1. on spaces list left menu, open spaceA 3 dots menu 
2. Click on spaceB to open its secondary drawer
Actual:
The 3 dots menu is still displayed (https://community.exoplatform.com/portal/download-document/f7c85eaaac12000f4826386864eb7226)
Expected:
Opening SpaceB secondary drawer should hide the 3 dots menu displayed on previous space

**Comment by Jihed525** [comment]
@srenault-meeds

**Comment by boubaker** [comment]
IMHO, I don't think it's too much annoying. Why is it expected that the menu closes @Jihed525 ?

**Comment by srenault-meeds** [comment]
Already reported there: https://github.com/Meeds-io/meeds/issues/2575

I have indeed already reminded my opinion there: https://github.com/Meeds-io/meeds/issues/2575#issuecomment-2474135884

I agree with Boubaker
