### ISSUE TITLE
[Contributions] Favorite challenges

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#273]
**Is your feature request related to a problem? Please describe.**
As a users willing to take a few challenges, it's not easy to retrieve them before declaring an achievement. There is also nothing that easily mark the interesting challenges for me to take in the future.

**Describe the solution you'd like**
Add the ability to mark a challenge as favorite so we can retrieve it easily. We could also have a gadget favorite challenges for it that may be on the homepage, so I can easily connect to declare a challenge.

**Comment by srenault-meeds** [comment]
This option has been added and it will be deployed in few days
