### ISSUE TITLE
[Task] Changing priority on task isn't working 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#276]
**Steps to reproduce**

1. Go to 'task '
2. Create new task 
3. Change priority of this task from "none " to "high"

**Current behaviour**

Changing priority on task is'nt working 
**Expected behavior**

Priority of task should be changed from none to high 

![priority task](https://user-images.githubusercontent.com/83289222/187939373-91beedee-1e8a-42c0-a719-d0effc96c6d7.gif)

**Comment by srenault-meeds** [comment]
@Imenmakni do you still face the problem?

**Comment by Imenmakni** [comment]
It's working now we can close it @Samuel-Renault-eXo
