### ISSUE TITLE
Stream filters - the selected filter is not the right one

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#277]
**Steps to reproduce**

1. Go to page /portal/meeds/stream
2. Click on filter "favorite spaces
3. Open a new page
4. Go to page /portal/meeds/stream
5. Bug : the selected filter is All but the selected activities are those of the filter "favorite spaces)
 
It should be "favorite spaces"

![streamfilters saving ko](https://user-images.githubusercontent.com/31288011/188084694-03192028-56e2-4a26-9ecd-7421bba41489.gif)

**Comment by srenault-meeds** [comment]
Fixed since today
