### ISSUE TITLE
[Notifications] Add a job for web notification history retention window

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#280]
**Is your feature request related to a problem? Please describe.**
Web notifications are saved indefinitely, so why not clean up the old ones?
**Describe the solution you'd like**
The solution would be to have a periodic (daily) job driven by two key web notification retention widow(s) parameters:

- **System window:** Configurable by the Server side internally through configuration files and properties
- **User window(optional):** Each user can define his own retention window. This window should be **smaller** than the system one and its value could be the default one.

**Technical concern**:
We should study the impact of the cleanup job on the server performance and avoid usage peak hours.

**Technical benefits**:
Less notification rendering + gain disk size.

**Comment by srenault-meeds** [comment]
Cleanup is done every 30 days
