### ISSUE TITLE
[Contributions] Add a button declare a challenge in the drawer Challenge detail

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#284]
**Is your feature request related to a problem? Please describe.**
My concern : To highlight a challenge, I provide a link to access the challenge directly. By clicking on this link, the details of the challenge will open correctly. But I don't see how to declare. I have to close the drawer, find the challenge in the list and click OK.

**Describe the solution you'd like**

Proposal: add a Declare button

**Comment by srenault-meeds** [comment]
Done since we have reworked the challenge detail to provide a direct way to announce
