### ISSUE TITLE
[OIDC] When issuer is different from the IdentityServer domain name, oidc connexion does not work

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#288]
**Steps to reproduce**

1. Configure eXo to use OIDC server
2. The issuer parameter must be different from the IDP domain name. For example issuer = https://www.test.com/oidc/ and the well-know-configuration like https://www.test.com/oidc/config/.well-known/openid-configuration
3. When you try to login, there is a 500 error :
`2022-09-12 10:53:20,856 | ERROR | Error when Read Data From BufferReader https://www.test.com/oidc//.well-known/openid-configuration [o.g.s.o.o.RemoteJwkSigningKeyResolver<http-nio-0.0.0.0-8080-exec-14>] `

Expected behaviour : 
the platform should use the correct well-known url

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
Done
