### ISSUE TITLE
[Notifications] Keep the unread notification number on the bell icon

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#289]
**Is your feature request related to a problem? Please describe.**
On the notification icon, we have the number (in the red circle) of new notifications since the last time we open the notification drawer.
When I open the notification drawer the number of notifications on the bell icon disappeared whether I read or not all the notifications corresponding to this number. 
So if for one reason or another I close the drawer I lose this information and I have no idea of how long I should delete the notification in the drawer until I reach the old read notification. 

**Describe the solution you'd like**
I would expect to have on the notification icon, the number of unread notifications and to keep this number until I read all the notifications or mark all as read. 

So if I have 10 notifications and I read or delete just one notification the number should be still here and decrease by one. 

**Describe alternatives you've considered**
If we have notifications on the latest space, I will have also the information but I expect that the number is kept if I do not read the new activity. In another case, the issue will be the same. 

But if this is implemented without improving the notification icon, I will totally abandon the notification center.

**Comment by srenault-meeds** [comment]
Rejected as we have reworked the way unread notifications can be retrieved
