### ISSUE TITLE
Clean Ckeditor WCM custom config

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#291]
Some Ckeditor WCM custom configurations still exists in commons module of Meeds. We should clean these unneeded configurations.

Not scenario for reproducing on meeds

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@azayati

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
