### ISSUE TITLE
Library poi-scratchpad:4.1.2 has a security vulnerability 

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#292]
Snyk report a vulnerability CWE-400 in poi-scratchpad:4.1.2. 

To resolv this issue we need to update poi library to last available version 5.2.2

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
Done
