### ISSUE TITLE
Library org.jsoup:jsoup:1.14.2 has a security vulnerability

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#293]
Snyk report a vulnerability CWE-79 in org.jsoup:jsoup:1.14.2.

To resolv this issue we need to update jsoup library to last available version 1.15.3

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
Done
