### ISSUE TITLE
[Task] Like a comment on a task

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#295]
**Is your feature request related to a problem? Please describe.**
If someone mentions me in a comment on a task, I can't notify him that I have well seen this message without writing a message. If I do so it will make the conversation longer for no reason. 

**Describe the solution you'd like**
I expect to be able to like comments as in the stream to easily notify my collaborator that I have well seen his message.

**Describe alternatives you've considered**
Presently I can write a message. 

**Additional context**
![Like comment in a task](https://user-images.githubusercontent.com/105866381/190418120-ed545b60-fead-4e01-8e76-6c2c5973b66d.gif)

**Comment by srenault-meeds** [comment]
duplicated with this one: https://github.com/Meeds-io/meeds/issues/173
