### ISSUE TITLE
Task - Edit a comment

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#296]
**Is your feature request related to a problem? Please describe.**
When I post a comment on a task I can't edit it. If I forgot something I have to delete it and redo my comment or complete it by another comment. In both cases, it causes a double notification and if I delete users may even misleading has they don't find the first comment.

**Describe the solution you'd like**
I expect to be able to modify a comment on a task as it's already possible on the stream. 

**Describe alternatives you've considered**
Delete and redo the post but there is side effect.

**Additional context**
![Edit comment on task](https://user-images.githubusercontent.com/105866381/190622517-3f5c8eba-e0cd-4a51-bd6b-f3924dea0b84.gif)

**Comment by srenault-meeds** [comment]
Duplicated with this one: https://github.com/Meeds-io/meeds/issues/141
