### ISSUE TITLE
Blank page displayed when Login with non existing email 

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#298]
**Steps to reproduce**

1. Go to login page
2. Try to login with an email not used in the platform.

screencast: youtu.be/pxGe7Qsr700

**Affected version**

eXo 6.4/6.3

**Current behaviour**

A blank page is displayed after Login tentative.

**Expected behavior**

The login form is displayed with a message saying that the login is incorrect (same message as if the mail exists)

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@azayati

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
