### ISSUE TITLE
Engage a new chat conversation via the chat box

### ISSUE THREAD

**Issue by BalouBalou** [Meeds-io/meeds#299]
**Problem**
When I am in the chat space I cannot contact a new person.
![image](https://user-images.githubusercontent.com/113687906/190658184-c61b8737-69e8-4546-8d9b-5d2c443ad603.png)
Have a look on this picture. You see that I am in contact with 3 chat persons.
I would like to engage a conversation with a fourth person from this space but I can't and I will loose time by using the workaround.

**Solution**
I would like to have a button next to the filter button which offers me the possibility to engage a new conversation.  
![image](https://user-images.githubusercontent.com/113687906/190658985-e80cc294-0a7d-4aa7-952d-86bd2ffeb3a2.png)

**Comment by srenault-meeds** [comment]
For you @margondicco :-)
