### ISSUE TITLE
Ether is used instead of MATIC and MEED is used instead of Ɱ

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#300]
1. Download a fresh server
2. Start the server
3. Go to Wallet Administration

Result:
* Ether is used instead of MATIC
* MEED symbol is wrong

Expected Result:

Use MATIC instead of ether knowing that the MEED contract is bridged on Polygon and used in default bundle now.

**Comment by srenault-meeds** [comment]
Looks fixed to me. Reopen it if not please
