### ISSUE TITLE
[Reward] Display rewarded achievements in User Wallet and Reward Administration

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#301]
**GAP**: Currently, the rewarded achievements aren't displayed in detail inside Admin Reward when sending payments (to verify rewarded points for some wallets by example). Same thing for User Wallet who receives the rewards, he/she can't determine, with an analytic point of view, which achievements (type or achievements) had been rewarded. (The admin can disable a rule and thus, the user will not know that a rule isn't rewarded anymore)

**Proposition**: Make a strong integration between wallet applications and gamification aspects (even integration between wallet & perk-store is poor, no direct link from wallet to perk-store order or product illustration & link) by adding more details about sent / received funds.

**Comment by srenault-meeds** [comment]
Being dealt by MIP 154
