### ISSUE TITLE
Bad display for coworkers indication in tasks 

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#307]
**Steps to reproduce**

1- usera create a task 
2-userb assign the task as coworker 

**Actual behavior :**  Bad display for coworkers indication in tasks  
![bad display for coworker](https://user-images.githubusercontent.com/50736962/191309252-214b6206-715f-4308-9135-35edc0beda5e.png)

Expected behavior : The number indication for coworker should be well displayed

**Comment by srenault-meeds** [comment]
Fixed
