### ISSUE TITLE
[Notes] Can't see draft pages in Notes

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#309]
**Steps to reproduce**

1. Go to Notes inside a space
2. Click on Tree icon to see tree drawer
3. Click on "Published" dropdown
4. Nothing happens

![Capture d’écran du 2022-09-21 14-54-12](https://user-images.githubusercontent.com/594824/191524019-01d4a186-5b75-419d-8b57-55c778dffc3c.png)

**Expected behavior**

A dropdown allowing to select draft pages should be displayed.

**Comment by srenault-meeds** [comment]
Seems to be fixed now. Isn't it @boubaker ?

**Comment by boubaker** [comment]
Yep, I confirm @srenault-meeds
