### ISSUE TITLE
Space administrator still a space member when he deletes his own space membership from group management

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#310]
**Steps to reproduce**

1. UserX creates a spaceX and invites UserA to be member
2. UserA joins SpaceX
3. Connect as platform Admin
4.  Go to Administration > Groups
5. Click add a group
6. Add group 's drawer will open, add Name="spacesmanagers", Label ="spacesManagers", Description ="spacesmanagers", click Save
7. Click on the created group "spacesmanagers".
8. Click on add member in group add "userA" with role member or " * ", click save
9. Go to "Administration > Spaces ", Go to "Permissions" section on top .
10. ON "Manage spaces" Line, click edit "the pen icon" 
11. Type the name of group added previously "spacesmanagers" , and save (floppy disk icon) 
12. Go to administration > Groups > PLatform>Administration add userA  with role "*"
13. Connect to platform as userA
14. Go to Administration > Groups > spaces ,SpaceX, remove userA from the list of spaceX members
15. Close Administration page
16. Go to SpaceX, go to members, check members List

**Current behaviour**

UserA is still showing in spaceX's list of members (NB , only reproduced if userA deletes himself from the admin>group>space list of members)

**Expected behavior**

UserA should not appear in SpaceX's list of members

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@azayati

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
