### ISSUE TITLE
Account is locked when password is changed

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#311]
**Steps to reproduce**

1. log with root
2. create a user john
3. log with john (with remember me activated)
4. try log with john in another browser. Use wrong password twice
5. request for forget password. Click in the link in forgot password email
6. change the password, and log with the new password.
7. Restart the server. It will invalidate JSESSION_ID cookie for the tab from 3)
8. in the tab opened in 3), refresh the page. A login is done with the remember me token which is no more valid => the account is locked.

**Affected version**

1.3.1

**Current behaviour**

After changing his password, the user account is locked

**Expected behavior**

When the first tab is refreshed, no authentication is attempted, and the login page is displayed. In addition, the account is not locked

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
This one is done. I close
