### ISSUE TITLE
Fix export/ import a note lead to disappearance of images in it .

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#314]
**`Steps to reproduce`**

1. create `note1` containing image in `spaceX`.
2. export that note.
3. go notes app of `spaceY`.
4. menu-> import the exported note.
5. open it.

**`Affected version`**

This affects all versions Meeds until 1.4.x.

**`Current behaviour`**

The image disappreared.

**`Expected behaviour`**

The image should remain in the note.

**Comment by srenault-meeds** [comment]
It seems to be eXo related and not meeds as we don't manage importing images in notes
@azayati @rdenarie

**Comment by azayati** [comment]
A fix is already done on notes that's why we have created the meeds issue @Samuel-Renault-eXo

**Comment by rdenarie** [comment]
Even if it is not possible to add images in notes in meeds, the code to manage it is in meeds codebase.
As the fix is in this repository, we need this issue

**Comment by srenault-meeds** [comment]
Ok I see. Thanks for the clarification

**Comment by azayati** [comment]
it can be closed as completed @Samuel-Renault-eXo since it is already done
