### ISSUE TITLE
[App Center ] SushiSwap Pair redirect to page 404 not found

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#318]
**Steps to reproduce**

1. Go to 'App center'
2. Click on 'SushiSwap Pair'

**Current behaviour**

By clicking on SushiSwap Pair it redirect me to page 404 not found

**Expected behavior**
By clicking on SushiSwap Pair should redirect me to associated url
![SushiSwap Pair](https://user-images.githubusercontent.com/83289222/193309911-0584a6ab-5357-4e05-8622-883b7722a79d.gif)

**Comment by plamarque** [comment]
Sushi has updated their app, the URL has changed. I fixed it by using the link to the old app : https://app.sushi.com/analytics/pools/0x960bd61d0b960b107ff5309a2dcced4705567070?chainId=1
