### ISSUE TITLE
Short message - UI glitches 

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#321]
**Steps to reproduce**

1. Open short message
2. Write a message or a comment

**Current behaviour**

the message "share your thoughts here" doen't disapear

![image](https://user-images.githubusercontent.com/31288011/193407951-1687f0c2-84ed-4997-b480-b2251f26fccb.png)

**(optional) Affected environments**  
Please complete the following information: 
 - OS: Mas Os Monterey
 - Browser : Brave latest
 - Device: Mac

**Comment by srenault-meeds** [comment]
Fixed!
