### ISSUE TITLE
[Notifications] Link in a notification display a blank page

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#322]
I receive a notification by mail for a kudos on the changlog.
When I click on "View full discussion", a blank page is displayed (only the top bar is visible) : 
![2022-10-04_08-31](https://user-images.githubusercontent.com/807839/193750044-9c4777ea-7207-4763-a852-19eb9786cac7.png)

I think this is because I'm not member of the space.

**Comment by srenault-meeds** [comment]
Indeed, we should display a dedicated page explaining why you cannot see this activity.

**Comment by srenault-meeds** [comment]
If not member of the space, then you have now a placeholder
