### ISSUE TITLE
Can't add an image for an new note

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#324]
**Steps to reproduce**

1. Create new note page.
2. try to upload an image from computer

**Affected version**

This affects all versions Meeds until 1.4.x .

**Current behaviour**

using BRAVE browser : upload form isn't displayed.
using FF : Uplaod can't be processed as it stays stuck in 100%.

**Expected behaviour**

in both browsers, whether FF or Brave, the upload should be displayed and upload from computer should work as expected (image to be added successfully).

**Comment by srenault-meeds** [comment]
as it is eXo related, and not meeds, why is it in /meeds/issues?
@azayati @rdenarie

**Comment by azayati** [comment]
A fix is already done on notes that's why we have created the meeds issue @Samuel-Renault-eXo

**Comment by rdenarie** [comment]
@Samuel-Renault-eXo even if it is not possible to add image in notes in meeds side, the plugin to add image is in meeds codebase. So this issue is needed.

I close it as resolved as it is already merged. Feel free to reopen if needed
