### ISSUE TITLE
Can't upload an empty resource

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#325]
**Steps to reproduce**

Trying to upload an empty resource

**Current behaviour**

A null pointer exception occurs

**Expected behavior**

The upload should finish correctly without exceptions

**Comment by srenault-meeds** [comment]
As it is eXo, why is it identified in /meeds/issues @azayati @rdenarie ?
Thanks

**Comment by azayati** [comment]
it is not eXo, it is a meeds issue and already fixed in gatein-portal @Samuel-Renault-eXo
