### ISSUE TITLE
Can't search for multiple mtadata filters

### ISSUE THREAD

**Issue by mkrout** [Meeds-io/meeds#326]
1. Go to Unified search
2. Select "Files"
3. Click on Tags then selct some tags

**Current behaviour**

Only the Favorite filter is considered in the result of the elastic search

**Expected behavior**

The result should be filterd by Favorites and selcted tags

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@mkrout

**Comment by srenault-meeds** [comment]
@mkrout have you seen the previous question?

**Comment by srenault-meeds** [comment]
@mkrout @rdenarie any news about the status of this one please?

**Comment by mkrout** [comment]
@srenault-meeds It's done, sorry didn't see your message :)
