### ISSUE TITLE
Fix task due and start dates issues

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#327]
**Steps to reproduce**

1. `User1` creates `task1`

2. `User1` sets the start and due date of `task1` to 1/1/2023

3. `User1` saves the task

4. open the task and check these dates

**(optional) Affected version**

This affects all versions `Meeds` until 1.4.x.

**Current behaviour**

The due date and start date are delayed with one year each time `user1` opens the `task1` .

**Expected behavior**

Each time `user1` opens the `task1` the due date and start date should be set correctly to 1/1/2023 .

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@akhanfir

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
