### ISSUE TITLE
Fix hide delete icon and add icon when banner is not hovered over

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#328]
**Steps to reproduce**

1. Hover over the profile banner.

**(optional) Affected version**

This affects all versions Meeds until 1.4.x.

**Current behaviour**

Delete and edit icons are always displayed if mouse isn't over.

**Expected behavior**

Delete and edit icons shouldn't be displayed if mouse isn't over.

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@akhanfir

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
