### ISSUE TITLE
Perf regression: some prefetched REST URLs aren't used in page

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#336]
**Steps to reproduce**

1. Go to Activity Stream Page (or any other page)
2. Open DevTools of browser

**Current behavior**: Some URLs are prefetched while it's not used immediately in page rendering phase
**Expected behavior**: Prefetch only necessary URLs used for the first rendering of the page

**Comment by srenault-meeds** [comment]
Fixed
