### ISSUE TITLE
Kudos - Refill kudos for specific user

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#341]
**Is your feature request related to a problem? Please describe.**
For some specific events as a team manager or team animator, I want to congratulate each member of my team. The issue I do have not enough kudos during the week for each member.

**Describe the solution you'd like**
It could be interesting to give the possibility to an administrator to refill the kudos to a specific user in order to allow him to congratulate all his team members. 

That way it's at the discretion of the administrator, to decide the necessity to give more kudos according to the user demand. 

A history of kudos refills could allow us to track them and help the administrator to decide whether to grant or not the extra kudos.

**Describe alternatives you've considered**
Presently, I should wait until next week or I should ask someone else to send kudos. It may give a feeling of favoritism to those who should wait.

**Additional context**

**Comment by srenault-meeds** [comment]
Hi, that is actually the price of the scarcity to have a limitation. Indeed, how to deal afterwards with the privilege of one requester and not another one? Your request seems more related to a team kudos which is another suggestion request you have done.
In addition to the fact that you will have ability in the future to manage a team challenge. That way, both solutions should help you manage the concern you have faced.
For now, I put this issue as closed.
