### ISSUE TITLE
Kudos for team

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#342]
**Is your feature request related to a problem? Please describe.**
When we want to congratulate a whole team, we usually send kudos to the one who does the communication. Frequently it's the team manager or animator. So it is always the same person who had the kudos which creates a misbalance in the recognition. 

**Describe the solution you'd like**
We could imagine special kudos for all teams that allow recognizing a group of people thanks to a space or a group. 

We could have a number of this type of kudos very low compared to kudos and why not give the possibility to limit this type of kudos to some specific users as manager. 

**Describe alternatives you've considered**
We have to send kudos to each people, so we need to have enough kudos for all and it takes time. These kudos could be very useful for the manager and usually, it's this type of user that have not a lot of time so they do the fastest and send only kudos to the one who communicates and congratulates all the team in the message. 

**Additional context**

**Comment by srenault-meeds** [comment]
It is now possible to send a kudos to a space
