### ISSUE TITLE
Fix bad display in insert portal link window

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#343]
**Steps to reproduce the behavior**

Browsing portal sites navigations from insert portal link ckeditor plugin.

**Current behavior**

Folder component is displayed in the upper right of the displayed insert portal link popup window. 

![baddisplay](https://user-images.githubusercontent.com/27963909/196460776-393b6263-2eca-4c83-8524-b8858866d560.png)

**Expected behavior**

Folder component should be displayed at the left side of the insert portal link popup window.

![good-display](https://user-images.githubusercontent.com/27963909/196460615-c0707101-672a-44ea-9b04-fe8bf73357f2.png)

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@sofyenne

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
