### ISSUE TITLE
Hide digest mail notification from settings menu

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#348]
**Steps to reproduce the behavior**

Many issues are related to digest email feature are reported and it needs to be fixed. Until re-worked this option needs to be disabled.

**Current behavior**

The digest mail notifications settings view and edit are displayed in manage notification settings.

**Expected behavior**

- For all users, we have hidden the digest mail notifications settings view and edit from manage notification settings with the FT flag exo.feature.digestMailNotifiaction which will be added and configured as false by default
- For old users having already enabled digestMailNotification settings, we have configured as following: "${exo.notification.NotificationDailyJob.expression:59 59 0,23 31 DEC ? 2099}" "${exo.notification.NotificationWeeklyJob.expression:59 59 0,23 31 DEC ? 2099}"
the default values of NotificationDailyJob and NotificationWeeklyJob expression properties with very distant period in order to guarantee that they will not receive digest mail notifications anymore despite their stored digestMailNotification settings as enabled (daily/weekly)

**attachment**

![digest](https://user-images.githubusercontent.com/27963909/197563393-e2027132-2a77-4587-82d1-b05ecb5f5ea6.png)

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@sofyenne

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
