### ISSUE TITLE
Fix vertical and horizontal scroll bars to tasks display in Planview

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#350]
**Steps to reproduce**

  1. open space Tasks application
  2. switch to PLAN view

**(optional) Affected version**

This affects all versions Meeds until 1.4.x.

**Current behaviour**

-  Only the upper 10 tasks are displayed vertically.
-  Only some of the tasks are displayed horizontally depending on when they are scheduled .

**Expected behavior**

Vertical and horizontal scroll bars should be displayed allowing the user to scroll horizontally and vertically in order to see all tasks.

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@IlhemEssaadi

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
