### ISSUE TITLE
[Notes] Several version created when I edit for the first time the note Home

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#355]
**Steps to reproduce**

1. Find a space with a note Home that have been never edited (you could create a new space also)
2. Go on the Home note and check the version number = v1
3. Edit the note and modify it  then save it
4. Check the version number = v3 or v4r

**(optional) Affected version**

It's reproduced with eXo 6.3.1. 

> Edit: reproduced in 1.4.x notes - version are duplicated when updating the home note.

**Current behaviour**

When we edit the Home note for the first time there are 2 or 3 versions created instead of 1. These versions are empty. After this first edition, the versioning is working correctly. It works correctly when you create a new note. 

**Expected behavior**

We should have only one version created with the first edit. We should have a version 2 only.

https://user-images.githubusercontent.com/105866381/197963892-ab0600d9-5494-411b-a719-bad16d5b288c.mp4

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
What is the status?

**Comment by srenault-meeds** [comment]
Looks ok now
