### ISSUE TITLE
Bad display for Task collaborators

### ISSUE THREAD

**Issue by MayTekayaa** [Meeds-io/meeds#358]
**Steps to reproduce**

1. Go to the Builders application.
2. Click on the tasks in the center app, then click on the Meeds FT project.
3. Scroll down to the merged tasks (when there is more than one collaborator on the task).
4. See the bad display.

![Screenshot from 2022-10-26 09-21-18](https://user-images.githubusercontent.com/100131287/197974987-ff612c19-2986-4288-8639-00cd48dcde86.png)

**Comment by srenault-meeds** [comment]
Fixed
