### ISSUE TITLE
Fix typed label filter isn't maintained

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#360]
**Steps to reproduce**

1. As member in space create tasks
2. Assign it to you and add labels to the created tasks
3. Go to task tab-> filter button
4. From labels tab type a label from the previous created task and click on confirm button
5. Reclick on filter button

**Current behavior**

-  the previously typed label isn't maintained

**Expected behavior**

- typed label should be maintained

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@IlhemEssaadi

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
