### ISSUE TITLE
JS and CSS cache TTL are not aligned

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#362]
**Steps to reproduce**
**Current behaviour**
Load a page. Look at network tab. CSS are cached during 1 day, js during 7 days.

**Expected behavior**
CSS and JS TTL should be aligned for better performances.
As a properties exists for set cache ttl : 
gatein.assets.css.max-age
gatein.assets.script.max-age
default value in old property file (https://github.com/Meeds-io/gatein-portal/blob/develop/component/common/src/main/resources/conf/configuration-tomcat.properties) is 7 days.

In addition, we have mechanism to invalidates assets caches when we have a new version, so we can increase css cache ttl to the same time as js file without problem

**Comment by srenault-meeds** [comment]
@rdenarie is that still reproduced since the css/js cleanup mip?

**Comment by rdenarie** [comment]
No, it is fixed
