### ISSUE TITLE
UI BUG on Space topbar Avatar 

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#368]
1. Go to space page
2. Put a new avatar with a big height/ or big width
3. The space avatar is not displayed in square form (as mentioned in our UX guideline)
4. See screen shot
![Screenshot from 2022-10-25 15-53-00](https://user-images.githubusercontent.com/40363501/198676420-72826f83-cde9-479f-bdd8-0f10080f80a7.png)
![Screenshot from 2022-10-25 15-50-48](https://user-images.githubusercontent.com/40363501/198676473-3cfa16c2-8325-4b4d-96c6-1b8c3ae525e7.png)

**Expected behavior**
The Space avatar must displayed in square form as displayed in space top banner popover.

**Comment by srenault-meeds** [comment]
Fixed!
