### ISSUE TITLE
Fix disappear of the text containing the character  "% " when posting an activity

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#369]
**Steps to reproduce**

   1. Open short message editor of spaceX
   2. Paste link with preview
   3. Add text above it
   4. Copy a sentence containing "%" (from wherever) paste it under what you've already typed
   5. Add some text below it
   6. Click on post button

**Current behaviour**

  - Sentence containing "%" and what have been writtin afterwards dissapear

**Expected behavior**

  - Text should be maintained as it is

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@IlhemEssaadi

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
