### ISSUE TITLE
fix : Fix generated operation without name when uploading file

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#372]
**Step to reproduced**

1. create an activity with attached  file ,
2. browsing analytics application and select user Id on settings Data Filter of chart activities,
3. select samples of same chart.

**current behavior**
operation without name is displayed on list of operations 

**expected behavior**
operation without name shouldn't be displayed

**Comment by srenault-meeds** [comment]
Hi @sofyenne We can't create activity with attached file with Meeds. eXo does give this possibility. 
It seems that this one should be taken in consideration by eXo team.
cc @rdenarie @margondicco

**Comment by rdenarie** [comment]
I confirm, @sofyenne can you raise a tribe feedback for this issue ? 
Thanks a lot

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo, even if it is related to upload docs, the fix is done in analytics as a meeds module
