### ISSUE TITLE
Challenge link in announcement does't open the challenge's drawer 

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#373]
**Steps to reproduce**

1. Go to a space which hosts a challenge and which contains an announcement of a challenge
2. Click on the challenge's title (represented as link) from the announcement 

**Current behaviour**

Challenges app is opened

**Expected behavior**

The challenge details drawer is opened

Please complete the following information: 
 - OS: Linux
 - Browser Brave
 - Version v1.45.116
 - Device: Desktop

**Comment by srenault-meeds** [comment]
Fixed
