### ISSUE TITLE
Fix can't edit activity containing % character and link with preview

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#374]
**Steps to reproduce**

1. Go to space X 
2. Open short message editor
3. Add a text containing % character 
4. Add a link with preview 
5. Save and try to edit 

**Current behavior**

Activity can't be edited and an error in the browser consolei is displayed : _URIError: URI malformed at decodeURIComponent (<anonymous>) at Object.getBodyToEdit_ 

**Expected behavior**

Activity should be editable

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@sofyenne

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
