### ISSUE TITLE
UI Bug : I see the blue color as the primary color in many places in the platform

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#379]
1. Go to 'space hosts list portlet, to the space top baner popver, to activities stream filter'

![Screenshot from 2022-11-04 16-08-41](https://user-images.githubusercontent.com/40363501/200011030-6bd3466f-b814-4e25-a751-ee6a095c69ec.png)
![Screenshot from 2022-11-04 16-08-49](https://user-images.githubusercontent.com/40363501/200011040-290bbb0f-a542-4968-bae2-d146bc5e163b.png)
![Screenshot from 2022-11-04 16-11-44](https://user-images.githubusercontent.com/40363501/200011042-339877ff-105f-4fec-a92e-747a9abec2ca.png)
![Screenshot from 2022-11-04 16-12-12](https://user-images.githubusercontent.com/40363501/200011044-17807c4f-9310-49d9-93f7-e697d4807a58.png)

**Current behaviour**

The color is blue

**Expected behavior**

The color must be the primary color in the settings.

**Comment by srenault-meeds** [comment]
@Imenmakni this seems to be something we should indeed deal with for consistency purpose. WDYT?

**Comment by Imenmakni** [comment]
I agree, i will add it into product backlog @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
Part of the issue should be fixed and ok with the next deployment
- labels in blue

Filters placeholder to be done later

**Comment by srenault-meeds** [comment]
fixed
