### ISSUE TITLE
Can not announce the twitter challenge

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#385]
**Steps to reproduce**

1. Like or RT a twitter challenge
2. Go to contributions app > Challenges tab and search for the Twitter challenge
3. Click on Announce button and fill in the needed fields (assignee, description) 
4. Click on Create button

**Current behaviour**
An error message appears "Error saving announcement"
[https://screenbud.com/s/9nJlY7YpNF7](https://screenbud.com/s/9nJlY7YpNF7)

**Expected behavior**

Announcement is done and a post is added to the audience space

**Affected environments**  
Please complete the following information: 
 - OS: Linux
 - Browser Brave
 - Version 1.45.118 
 - Device: Desktop

**Comment by srenault-meeds** [comment]
Duplication with this one: https://github.com/Meeds-io/meeds/issues/388
I close this one. Bug will be treated. Thanks!
