### ISSUE TITLE
[Contributions] Cannot add a rule to a program

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#386]
**Steps to reproduce**

1. Go to programs in builders
2. Try adding the rule "Post activity in space"
3. When validating the adding of the rule, an error is displayed telling that the rule is already used.

Problem: it seems that is not used after checkking here and there (mostly in the current rules administration page)

https://user-images.githubusercontent.com/58853195/200619130-de39224a-bdd2-4735-9759-a3bc3f25cceb.mp4

**Expected behavior**

Unless the rule has been disabled, then I should be able to use this one.
If this has been disabled, then I should at least see in the rules administration page.

**Comment by srenault-meeds** [comment]
@Imenmakni Is that possible to help me please?

**Comment by Imenmakni** [comment]
Task added to the board https://builders.meeds.io/portal/meeds/tasks/taskDetail/767, be able to see disabled rules.

Is that help you ?  @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
Depends if this rule is actually disabled. Don't know

**Comment by Imenmakni** [comment]
Yes, i think it depends, if it's a disabled rule or a deleted rule have the same event see reported bug : https://github.com/Meeds-io/meeds/issues/397

**Comment by srenault-meeds** [comment]
Fixed
