### ISSUE TITLE
[Contributions] Cannot link a rule to a domain

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#387]
**Steps to reproduce**

1. Go to the admin rules page
2. Add the rule Post in stream (space) and try linking it to the program Share knowledge - Help others 
3. Error: I can't see it in the dropdown list

https://user-images.githubusercontent.com/58853195/200619650-32061729-5584-400f-8c8d-96a722c7f07c.mp4

**Expected behavior**

I should see the program in the drop down list

**Comment by Imenmakni** [comment]
@Samuel-Renault-eXo I think it is an obsolete bug, since we will delete page rule

**Comment by srenault-meeds** [comment]
Ok if we can deal with this following problem: https://github.com/Meeds-io/meeds/issues/386
