### ISSUE TITLE
Unable to announce the "Twitter challenge" (Reproduced on builders.meeds.io)

### ISSUE THREAD

**Issue by samehaidi** [Meeds-io/meeds#388]
**Steps to reproduce**

1. Go to the "Contributions" application and open the "Challenges" Tab 
2. Click on The button "Announce" related to the Twitter challenge
3. Fill in the field : "Describe the achievement" and click on the button "Create"
4. An error is displayed and the achievement is not announced

See attached screenshot.
![Bug twitter challenge](https://user-images.githubusercontent.com/45466574/200678927-1f7e1343-ec65-4854-b167-ddb1126fa98d.PNG)

Reproduced on builders.meeds.io

**Comment by srenault-meeds** [comment]
Thanks @samehaidi 
It seems that we have a 500 error when trying to do such challenge. @boubaker any idea?
<img width="956" alt="image" src="https://user-images.githubusercontent.com/58853195/200780549-a585249a-d197-4ffa-a260-a6d93a65c9ba.png">

**Comment by samehaidi** [comment]
I just tested it and it works. Thanks @Samuel-Renault-eXo
