### ISSUE TITLE
[Tasks] I can remove a label thanks to delete key

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#391]
**Steps to reproduce**

1. Go to a task
2. Open the task
3. Add several labels on the task
4. Click on the label placeholder.
5. Press delete on keyboard. The last label will be selected.
6. Press delete again. The label is removed. No success message is displayed.
7. Click on the task to continue to edit it. No success message is displayed.
9. Close the task. 
10. Open it again. The label is still here. 

https://user-images.githubusercontent.com/105866381/200778492-c9553fd5-986c-43e7-8d97-30e7af888131.mp4

**(optional) Affected version**

eXo 6.4.X (sorry don't know to which Meeds version it corresponds). 

**Current behaviour**

You have the feeling that you can remove a label from a task by pressing delete on the keyboard but it's not working. It is even possible for the simple members that should not have the ability to remove a label. 

**Expected behavior**

I should be able to do it only if I have the right and the label should be removed with a success message. The other option is to not have the ability to remove a label thanks to the keyboard. 

IMO the first option is better. 

**(optional) Affected environments**  
Please complete the following information: 
 - Browser : Brave
 - Version Version 1.45.118 Chromium: 107.0.5304.91 (Build officiel) (64 bits)](https://brave.com/latest/)

**Comment by srenault-meeds** [comment]
Meeds 1.4.x ;-)

**Comment by srenault-meeds** [comment]
Requalified as a bug

**Comment by Julien-Dubois-eXo** [comment]
How can I know the version of Meeds?
