### ISSUE TITLE
[Contributions] Rule is truncated in actions column of a program

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#393]
**Steps to reproduce**

1. Go to Contributions App > Programs tab
2. Select a program and open its details by clicking on its card
3. Focus on Actions column

**Current behaviour**
Rule is truncated when it is longer than the column length
check the screenshots
![image](https://user-images.githubusercontent.com/1576297/200806530-6255b726-64ed-4913-b3a6-f4d0d712bd9c.png)

![image](https://user-images.githubusercontent.com/1576297/200806704-bbec4797-25e6-4b32-8ff6-b35166236f03.png)

**Expected behavior**

Display the whole rule text either by adding an ellipsis and tooltip or enlarging the actions length 

**(optional) Affected environments**  
Please complete the following information: 
 - OS: Linux
 - Browser: Brave

**Comment by srenault-meeds** [comment]
Fixed
