### ISSUE TITLE
fix: Fix email notifications aren't received when external username contains "@" char

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#395]
**Steps to reproduce**

    1. In SpaceA members app, invite an external user.
    2. In external user creation form, first name or last name should include "@" char for example : maude@!!.st-Jean+
    3. Submit the form and login
    4. SpaceA admin mentions recently created external user or make an action in the space

**Current behaviour**

  - The email notifications aren't received log server displays warning considering that the email isn't valid, yet in fact, the system is considering the username as email

**Expected behavior**

  - As the external user email is valid, the email input should be always considered to send email notifications

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@IlhemEssaadi

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
