### ISSUE TITLE
[Contributions] Cannot add a rule having same event as a deleted rule

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#397]
**Steps to reproduce**

1. Go to 'contribution > program > program details'
2. Click on 'add rules '
3. Add rule
4. Delete the added rule 
5. Add new rule with the same event as a deleted rule

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

cannot add a the new rule , error message is displayed : Rule with same event already exist
![image](https://user-images.githubusercontent.com/83289222/200889074-6734f3e2-c253-4a7d-a045-aa0da0a5bbcb.png)

**Expected behavior**
 Be able to add new rule having same event as a deleted rule
**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Fixed
