### ISSUE TITLE
Duplicated encoded link in an activity

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#398]
**Steps to reproduce**

1. Post an activity with a link copied from brave browser for example https://facebook.com/ or https://twitter.com/ 

![link activity](https://user-images.githubusercontent.com/1579929/201109319-5fc99460-26bf-45df-86de-bf24c5f1fa6f.png)

**Current behavior**

A duplicated encoded link is displayed in the posted activity body

**Expected behavior**

Only one link should be displayed with preview

**Comment by srenault-meeds** [comment]
Indeed, seems like a REG to me. WDYT? @Imenmakni

**Comment by Imenmakni** [comment]
Yes but I can't reproduce it @Samuel-Renault-eXo @azayati

**Comment by srenault-meeds** [comment]
@Imenmakni Reproduced here: https://builders.meeds.io/portal/meeds/activity?id=2276

**Comment by azayati** [comment]
@Jihed525 to inform @Samuel-Renault-eXo that this can be closed once the fix is deployed in production and backported.

**Comment by srenault-meeds** [comment]
Thanks @azayati I have marked this issue as Doing as it is the case.

**Comment by srenault-meeds** [comment]
@azayati does your work include the fact that this is displayed twice also in mail notifications?
https://github.com/Meeds-io/meeds/issues/236

**Comment by Jihed525** [comment]
> @azayati does your work include the fact that this is displayed twice also in mail notifications? #236

No @Samuel-Renault-eXo it doesn't cover email notification

**Comment by srenault-meeds** [comment]
thanks @Jihed525
