### ISSUE TITLE
Fix first and last name allowing the use of illegal eXo characters for external user names

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#399]
**Steps to reproduce**

    1. In space A members app, add non existing email to invite an external user.
    2. In email received, when creating external profile, first name or last name should include illegal eXo characters.

**Current behavior**

- The creation external user form is well submitted, the external user is well created and the login is done successfully.

**Expected behavior**

-  As the username of the created external user isn't valid, the form shouldn't be submitted and the first name and last name fields should follow the username field validation of simple users creation.

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@IlhemEssaadi

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo
