### ISSUE TITLE
Achievements filter - duplicated programs

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#400]
**Steps to reproduce**

1. Go to 'contribution center / Achievements tab
2. Click on filter

Many programs are duplicated

![Capture 2022-11-11 à 12 00 39](https://user-images.githubusercontent.com/31288011/201327186-54ec955c-dd80-49c9-8010-0927d7a69a2f.png)

**Comment by srenault-meeds** [comment]
@Imenmakni to check if we can remove this duplicated programs from the db (only reproduced in builders, but to check)

**Comment by srenault-meeds** [comment]
Duplicated with this one actually: https://github.com/Meeds-io/meeds/issues/380
