### ISSUE TITLE
[Overview] UI glitch on Points overview Card

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#406]
**Steps to reproduce**

1. Go to 'Stream Page or overview page in the right sidebar'
2. In welcome back portlet click to see your gamification points
3. Bug UI in the points card (we should add padding)

![Screenshot from 2022-11-14 15-49-40](https://user-images.githubusercontent.com/40363501/201692049-ced2acae-e5ac-4f11-9ec4-5168375e165c.png)

**Current behaviour**

the content of the card is attached to the card border

**Expected behavior**

We should add a margin or padding between the content of the card and its border

**Comment by srenault-meeds** [comment]
Fixed
