### ISSUE TITLE
Programs name are not well displayed inside tooltip when hovering on the chart from "My Contributions" portlet 

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#407]
**Steps to reproduce**

1. Go to 'Overview page'
2. Focus  on 'My contributions' portlet 
3. Hover on the chart to check the programs name

**Current behaviour**

Some tooltip are not well displayed , the text written inside tooltip seems to be truncated . (check video)
https://youtu.be/NxyoWzWxkB8

**Expected behavior**
Program name should be well displayed inside tooltip

**Comment by srenault-meeds** [comment]
Fixed
