### ISSUE TITLE
[Contributions] Program name is not well displayed in badge drawer when it is long

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#408]
**Steps to reproduce**

1. Go to 'Overview page '
2. Click on a badge related to a program with a long name  from the "My reputation" portlet
3. once the badge drawer is displayed , check the header

**Current behaviour**
The header is not well displayed , truncated at the end . (check video)
https://youtu.be/P2111fwZwxg

**Expected behavior**
The program name should be well displayed when it is long

**Comment by srenault-meeds** [comment]
fixed
