### ISSUE TITLE
[Overview] [Mobile][iOS][MyReputation_Porltet] Bad display of block kudos received

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#410]
**Steps to reproduce**

1. Go to 'Overview page' via safari
2. Scroll down to 'MyReputation_Porltet'

**(optional) Affected version**

Indicate the version where the bug is observed.
![E512B73E-4D15-4903-BD2A-5BCB4662F951](https://user-images.githubusercontent.com/83289222/201715556-65f6e967-3ae7-488a-a7c8-d7284832c891.jpg)

**Current behaviour**

Icon, number and text received are not algined 
**Expected behavior**
Icon, number and text received should be aligned as sent block

**(optional) Affected environments**  
Please complete the following information: 
 - OS: [iOS]
 - Browser [safari]
 - Device: [iPhone 12]

**Comment by srenault-meeds** [comment]
I recommend to display the text below number in any case we are viewing it with a mobile view
That way we ensure this is consistent
@Imenmakni

**Comment by srenault-meeds** [comment]
FIxed
