### ISSUE TITLE
[Left menu] Bad hyphenation in the space detail panel

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#411]
**Steps to reproduce**

1. Go to the left menu
2. Click on the arrow to open the space detail

The hyphenation of the space title AND of some words in the description are wrong

cf image

![Capture 2022-11-14 à 19 53 18](https://user-images.githubusercontent.com/31288011/201742267-b436085a-3338-48eb-8426-97544e258ffd.png)

**Comment by srenault-meeds** [comment]
@Imenmakni Please can we track this in our board?

**Comment by srenault-meeds** [comment]
Should be fixed and ok with the next deployment
