### ISSUE TITLE
[Analytics] Fix titles of analytics chart are not translated

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#412]
**Steps to reproduce**

1. Change your platform language to French.
2. Navigate to analytics application.

**Current behavior**

- The title of charts Distinct logins , Users count , Spaces count and Activities are not translated

**Expected behavior**

- Chart titles should be translated.

**Comment by azayati** [comment]
it is already done @Samuel-Renault-eXo

**Comment by azayati** [comment]
It is already done @Samuel-Renault-eXo
