### ISSUE TITLE
Fix encoded link preview still displayed when removing a link

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#417]
**Steps to reproduce**

1. Edit an activity containing a link with preview
2. Remove the link and the related preview then add a text

**Current behavior**

The edited activity link and related preview still displayed.

**Expected behavior**

Activity should be updated without link and related preview as the original link was already deleted.

**Comment by srenault-meeds** [comment]
@azayati Is that something ongoing?

**Comment by azayati** [comment]
it is always in progress @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
Fixed
