### ISSUE TITLE
After setting my home page, I still see the overview page

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#419]
**Steps to reproduce**

1. Go on stream page
2. In left menu set stream page as home page
3. Go on another page
4. Click on Meeds logo in top bar => you are redirect on stream which is your home page => ok
5. Type in url https://builders.meeds.io/ => you are redirected on your home page => ok
6. Type in url https://builders.meeds.io/portal => you are redirected on your home page => ok
7. Type in url https://builders.meeds.io/portal/meeds => you are redirected on overview page => KO

**Current behaviour**

The home page is not always taken in account

**Expected behavior**

Your home page is displayed in all cases a specific page is not used in url.
If my home page is set to stream, if I go to /, /portal, /portal/meeds, I should see my homepage. To see the overview page, I have to go on /portal/meeds/overview

**Comment by Imenmakni** [comment]
@rdenarie FYI, it's also reproduced on tribe https://community.exoplatform.com/portal/dw/

**Comment by srenault-meeds** [comment]
Looks ok now
