### ISSUE TITLE
fix : Fix duplicated encoded link in activity - EXO-60750 - Meeds-io/meeds

### ISSUE THREAD

**Issue by sofyenne** [Meeds-io/meeds#421]
**Steps to reproduce**

1. Copy link with preview from brave browser ,
2. Post activity contains text and the copied link .

**Current behavior**

> Activity posted displays a duplicated encoded link 

**Expected behavior**

> Activity posted should be displayed without duplicated encoded link

**Comment by azayati** [comment]
Duplicated with https://github.com/Meeds-io/meeds/issues/398

**Comment by azayati** [comment]
Duplicated with https://github.com/Meeds-io/meeds/issues/398 @sofyenne
