### ISSUE TITLE
Achievements table is badly displayed in mobile device

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#425]
**Steps to reproduce**

Using a mobile device with exo mobile app
1. Go to "Contributions" app
2. Click on "Achievements" tab

**Current behaviour**

The table is badly displayed, no clear information
![Achievements](https://user-images.githubusercontent.com/1576297/203059914-89165ddf-5b6a-4006-907c-e772a87a5f91.jpg)

**Expected behavior**

Either make the table mobile friendly or hide the table from mobile devices

**(optional) Affected environments**  
Please complete the following information: 

- eXo app version
- Device: Samsung S10

**Comment by srenault-meeds** [comment]
Thanks @mzorai It is considered and will be treated in few days

**Comment by mzorai** [comment]
Good thanks @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
Improved!
