### ISSUE TITLE
[Stream] Editing a message of a challenge announcement is not impacted in the activity

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#426]
**Steps to reproduce**

1. Succeed in a challenge (in my case bug hunt)
2. Go to "Contributions" app > Challenges > Scroll down to the concerned challenge
3. Announce the challenge
4. Go to the challenge's space and scroll to the posted announcement
5. Click on 3 dots of the announcement > Edit and change the posted message and then save >> the posted announcement isn't updated with recent changes
6. Re click on 3 dots > Edit >> the changes are well displayed in the composer but not in the announcement (check screen shot)

![image](https://user-images.githubusercontent.com/1576297/203063998-a2acc5d9-b5ac-48a8-8363-045885fafde9.png)

**Current behaviour**

The changes made are not impacted in the posted announcement

**Expected behavior**

The made changes should be visible in the announcement
 
Please complete the following information: 
 - OS: Linux
 - Browser Brave

**Comment by srenault-meeds** [comment]
Fixed FYI

**Comment by mzorai** [comment]
I got this issue again today cc @srenault-meeds

**Comment by srenault-meeds** [comment]
I can't reproduce it :(
