### ISSUE TITLE
[People][Leaderboard] When i hoover on username or avatar user then popover is displayed empty

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#431]
**Steps to reproduce**

1. Go to '[...](https://builders.meeds.io/portal/meeds/people)'
2. Hoover on 'hoover on username or avatar user'

![image](https://user-images.githubusercontent.com/83289222/203303525-8235b410-79a7-4b8b-98c2-8bed81c6e843.png)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Popover is displayed empty
**Expected behavior**

Display popover user 
**(optional) Affected environments**

**Comment by srenault-meeds** [comment]
It shouldn't be BTW the popover but the pie chart for the user you are hovering. @ichaieb can you please confirm this?
Thanks!
cc @Imenmakni

**Comment by ichaieb** [comment]
> It shouldn't be BTW the popover but the pie chart for the user you are hovering. @ichaieb can you please confirm this? Thanks! cc @Imenmakni

Yes I confirm a pie chart for the user should be displayed .

**Comment by Imenmakni** [comment]
ok thanks @ichaieb @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
fixed
