### ISSUE TITLE
Weird message when using OIDC

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#437]
**Steps to reproduce**

1-Connect using OIDC
2-Close tab
3- Open a new tab, and access directly to oidc entry point : http://localhost:8080/portal/openidAuth in a new tab
4- Connect using OIDC account

Actual behavior : 
Popup displayed reminding of used account
![2022-11-24_14-46](https://user-images.githubusercontent.com/807839/203799502-aaaeebe0-5584-4de3-8c9c-077f227b6fd1.png)

**(optional) Affected version**

meeds-1.3.2

**Expected behavior**

No popup should be displayed if same user account, else, user must be logged in and previous session should be invalidated.

If your session is still active, you should not be redirect to Identity Provider, and so you should not have to select an account.

**Comment by srenault-meeds** [comment]
Is it still in progress?
@rdenarie

**Comment by rdenarie** [comment]
Fixed.
