### ISSUE TITLE
[Contributions] How can I earn points pages is outdated

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#440]
**Is your feature request related to a problem? Please describe.**
Steps to get the behavior:
- On Stream page, click on Points widget of "Welcome back" section
- Click on (i) icon on the top right > Achievements drawer appears
- Click on (i) icon on the header of Achievements drawer > I am redirected to the page "How can I earn points?" with empty content

**Describe the solution you'd like**
IMO it would be better to redirect to /portal/meeds/contributions/programs page as it gives an overview about points to gain per program

**Describe alternatives you've considered**

**Additional context**

**Comment by srenault-meeds** [comment]
Fixed
