### ISSUE TITLE
[Notes] Drawer version history displays empty

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#442]
**Steps to reproduce**

1. Go to 'Notes' of space
2. Click on 'Icon Version'
3. See drawer "Version history"

**(optional) Affected version**
![Version history](https://user-images.githubusercontent.com/83289222/204515042-b20d6dbc-9d98-42d8-af99-ee67ce6c1026.gif)

**Current behavior**

Drawer version history displays empty

**Expected behavior**

Should display previous version of this note

**Comment by Imenmakni** [comment]
@Samuel-Renault-eXo  i think it's related to this MIP https://github.com/Meeds-io/MIPs/issues/19

**Comment by srenault-meeds** [comment]
thanks @Imenmakni 
@mkrout @hakermi as you have worked this lately, can you please help us?

**Comment by srenault-meeds** [comment]
@rdenarie hello is that something related to the work done lately on versions drawer? I can see it is ok when using tribe but not builders. Something related to a missing upgrade, maybe?
Thanks for your help

**Comment by rdenarie** [comment]
Yes, a commit is missing in develop, we are working on the backport.

**Comment by srenault-meeds** [comment]
Fixed FYI @Imenmakni Thanks to eXo team
