### ISSUE TITLE
Stream :  I can't mention someone on comment or Kudos using navigator Brave

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#443]
**Steps to reproduce**

1. Go to 'stream '
2. Click on 'comment.'
3. enter @withname to mention

![mention brave](https://user-images.githubusercontent.com/83289222/204550204-ea307377-2a4d-4495-ade6-06f02f98e236.gif)

**Current behaviour**

It displays search in progress
**Expected behavior**

Display list of person with the mention 

**(optional) Affected environments**  
Please complete the following information: 

 - Browser [Brave]

**Comment by srenault-meeds** [comment]
Strange, I cannot reproduce this case. To study

**Comment by Imenmakni** [comment]
![image](https://user-images.githubusercontent.com/83289222/204557054-5bdda7ae-16bf-4841-ab49-b6a0c3dc088e.png)

Error that i see in console @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
@Imenmakni Do you still face this issue?
Thanks

**Comment by Imenmakni** [comment]
It's seems good for me, it's no more reproduced @srenault-meeds
