### ISSUE TITLE
multiple public folder creation

### ISSUE THREAD

**Issue by hthabti** [Meeds-io/meeds#445]
affected version: 6.4.x/6.3.x

prerequisite: upload files in personal doc folder (public)

steps:
open tasks app from center app
go to spaceX project
create task1
add attachement1-> use existing upload-> personnal doc-> choose folder (music, public...) 
create task2
add attachement2-> use existing upload-> personnal doc-> choose folder
check document app of spaceX

actual:
second attachment is saved under path "space>public>task ID" + multiple public folders are created
=> same behavior if document retrieved from another space instead of personal folder

expected:

public folder shouldn't be created and attachments should be save in folder task in a specific folder labelled with task ID

Space project :
attachments are saved in folder task of the the space in a specific folder labelled with the task ID, and they are saved as a symlink.

Personal project :
attachments are saved in folder Personal document in a specific folder labelled with the task ID.

exo task link:
https://community.exoplatform.com/portal/dw/tasks/taskDetail/58740

**Comment by srenault-meeds** [comment]
Hello, meeds doesn't support attachments AFAIK so we don't support this either, no?
@margondicco @rdenarie

**Comment by rdenarie** [comment]
You're right, no need of meeds issue.
You can close
