### ISSUE TITLE
I am able to manage a task in a project to which I don't have access

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#446]
**Steps to reproduce**
**prerequisites**
 userA is member  of a project, added tasks and commented tasks then userA is no longer member of that project

Steps to reproduce the behavior with userA:
Case1
1. Go to 'Welcome' portlet of another user > Click on Points widget > click on (i) icon to open his achievements drawer
2. Scroll down until you reach an action related to task "Update task" for example
3. Click on that achievement

**Current behavior**
userA can view the task and can manage it i.e. move task, edit task edit status, mark task as completed and inversly,...

Case2
1. With another user member of the project, comment a task previously added/commented by userA
2. userA recieves notifification of actions made on the task
3. userA clicks to open the task

**Current behavior**
userA can view the task and can manage it i.e. move task, edit task edit status, mark task as completed and inversely,...

![Screenshot from 2022-11-30 13-29-57](https://user-images.githubusercontent.com/1576297/204797011-985221e6-be1b-4705-8150-7f6e68ab2a3d.png)

**Expected behavior**

userA shouldn't be able to manage a task under a project he's no longer a member of

**(optional) Affected environments**  
Please complete the following information: 
 - OS: Linux
 - Browser Brave

**Comment by srenault-meeds** [comment]
Not reproduced
