### ISSUE TITLE
[Overview] Challengers names & avatars  are not well aligned vertically when we have more than 9 users in top challengers portlet

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#447]
**Steps to reproduce**

1. Go to 'Overview page'
2. Focus on 'Top challengers portlet'
3. check challengers name and avatars when there is more than 9 users 

**Current behaviour**

The challengers name & avatars are not well aligned vertically 
![Selection_322](https://user-images.githubusercontent.com/50736962/205008189-392b6898-3ffb-42fa-a340-0ff1f340652f.png)

**Expected behavior**

The challengers name & avatars should be well aligned  vertically

**Comment by srenault-meeds** [comment]
@Imenmakni can we take this in charge please?

**Comment by srenault-meeds** [comment]
fixed
