### ISSUE TITLE
technical labes for space applications

### ISSUE THREAD

**Issue by hthabti** [Meeds-io/meeds#449]
version: 6.4/6.3

steps:
create spaceX
settings> Language> german/deutsch
go back to your space

actual:
technical labels displayed for members, settings, notes, tasks

expected:
names of applications in the related langage should be displayed

exo task:
https://community.exoplatform.com/portal/dw/tasks/taskDetail/61098

**Comment by srenault-meeds** [comment]
Seems not related to the soft but to a crowdin pb, no?
BTW in meeds1.4.x no problem with settings, members and tasks. Only a problem with notes and wallet (and not technical name but English label).
@rdenarie FYI

**Comment by rdenarie** [comment]
Yes, it seems fixed in 6.4.x. So we can close
