### ISSUE TITLE
Technical Labels in Earnings drawer

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#455]
**Steps to reproduce**

1. Go to 'Overview' page
2. Click on the value of your earnings 

**Current behaviour**

Technical labels appear in the opened drawer
![image](https://user-images.githubusercontent.com/1576297/206191033-927fe7eb-34c5-4a96-8d87-7815692c523a.png)

**Expected behavior**

Clear and simple labels should appear

**(optional) Affected environments**  
Please complete the following information: 
 - OS: Linux
 - Browser Brave

**Comment by srenault-meeds** [comment]
Fixed
