### ISSUE TITLE
Character M of Meeds is not well written on Buy Meeds page

### ISSUE THREAD

**Issue by halaya** [Meeds-io/meeds#456]
**Steps to reproduce**

1. Go to 'https://holders.meeds.io/dapp/deeds'
2. Click on 'Buy Ɱeeds'

**Current behaviour**
character M of Meeds is not well written 
"Buy â±®eeds so you can:"

![Screenshot from 2022-12-07 16-33-28](https://user-images.githubusercontent.com/5815403/206222325-875970d2-677c-44b7-80ec-ee99582287ab.png)

**Comment by plamarque** [comment]
thanks for reporting. Spotted and updated in Crowdin. Should be fixed after next sync

**Comment by srenault-meeds** [comment]
Fixed :-)
