### ISSUE TITLE
[Achievement][Mobile] label load more isn't displayed on button 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#459]
**Steps to reproduce**

1. Go to 'Achievement'
2. Scroll down 
3. See button

![image](https://user-images.githubusercontent.com/83289222/206683123-7e9f436c-decf-4188-8a35-299bfeefb23b.png)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behavior**

Button displayed without label Load more 

**Expected behavior**
Button should be displayed with label Load more 

**(optional) Affected environments**  
Please complete the following information: 
 - OS: [ iOS]
 - Browser [ safari]
 - Device: [e.g. iPhone12]

**Comment by srenault-meeds** [comment]
Can you consider it please as a bug and to be tracked in the board @Imenmakni ?
Thanks

**Comment by srenault-meeds** [comment]
Not reproduced
