### ISSUE TITLE
[Dapp] Display Tab portfolio on first tab

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#462]
**Is your feature request related to a problem? Please describe.**
As no connected user i would like to see information about meeds token and meeds price, and when I access a holders app I think I have lost this option but it was displayed on the top right ( portfolio tab)

**Describe the solution you'd like**
Display Tab portfolio on first tab

**Comment by srenault-meeds** [comment]
Actually, we plan to make the homepage the marketplace and it will provide link to users so they can browse step by step the website and then get learning about the project.
Thanks for this feedback though
