### ISSUE TITLE
[Task] Add the + button to quickly add document even when an attachment is already existing

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#469]
**Is your feature request related to a problem? Please describe.**
On a task with an attachment, we have to open the full list of attachments to have the button "+" to be able to add a new attachment. It's not obvious that we have to check the list of attachments to be able to attach a new document. 
Moreover, it will add an additional click to do it and all the feedback we had from customers is more oriented on the reduction of clicks. 

**Describe the solution you'd like**
Add the "+" button just after the label "View all attachments". 

**Describe alternatives you've considered**
On the eXo Process app, we had a similar UI and UX and our customers asked us to add on the first drawer the "+" button. 

**Additional context**

https://user-images.githubusercontent.com/105866381/207870939-a716ad24-f294-4407-8175-7c4ac54364c6.mp4

**Comment by srenault-meeds** [comment]
Refused. We don't manage attachements in meeds software

**Comment by Julien-Dubois-eXo** [comment]
You are right I forgot that it's a specific point on eXo sorry.
