### ISSUE TITLE
[Contributions] Give a quick access to the challenges

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#470]
**Is your feature request related to a problem? Please describe.**
Since the new contributions center, we arrived on the page "Program" first. The page is very useful for newcomers but when we know the Program and the challenges related it's more the challenges that we want to access daily. 

So the navigation experience is longer now and I always useless click. However, I think we should still have the "Program" page first. 

**Describe the solution you'd like**
Here are several ideas that might be complementary

- Put quick access on the program card "Declare success", when you click on it you are redirected to the challenge page directly on the related program section on the page. 
- When you are on the detailed program page, you have the list of the challenges associated with the program. We could be able to: 1 click on the challenge to open the description and 2 have a new button at the end of the line "declare a success". 

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/105866381/207873710-116a6fc4-403c-4285-ac67-dd6d2b4c54d3.mp4

**Comment by srenault-meeds** [comment]
Hello, since you can do the following:
- access the program
- access challenges related to program
- announce a challenge from there
I have the feeling that answers your question.
Am I wrong?

**Comment by Julien-Dubois-eXo** [comment]
Hello yes nice! Thank you.
