### ISSUE TITLE
[Achievement][Mobile] The point earned is no longer displayed in mobile view

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#475]
**Steps to reproduce**

1. On mobile Go to 'Acheivement'
2. See points 

![41F87EAE-E2C3-4A31-AB27-EC128118A0CF](https://user-images.githubusercontent.com/83289222/208856153-ac58bf1b-584a-47a0-9e8a-5d2ca02505b4.jpg)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behavior**

The point earned is no longer displayed in mobile view

**Expected behavior**

 The point earned should be displayed in mobile view

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Task created in the backlog FYI
