### ISSUE TITLE
Can't Create a new account!

### ISSUE THREAD

**Issue by andressw3** [Meeds-io/meeds#478]
Hello, I Tried to invite my friend to joint the builders web site, but she can't create an account, Captcha image does not display
![Screenshot from 2022-12-21 16-31-07](https://user-images.githubusercontent.com/121183322/208945258-cd9ec177-1563-48b0-a38c-b32b9832680f.png)

**Comment by srenault-meeds** [comment]
Fixed @andressw3 FYI
