### ISSUE TITLE
[Contribution Center - Challenge Tab] When searching a challenge, the result category is folded

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#482]
On builders instance, 
I go to new contribution center, tab challenges. 
All challenges programs are unfolded and I can see all challenges
![image](https://user-images.githubusercontent.com/807839/209166420-9d009a94-ad44-463c-806d-5b73e246a655.png)

When I start to filter a challenge, for example "bug", the challenge list is correctly filtered but programs are folded : 
![image](https://user-images.githubusercontent.com/807839/209166643-4cf0b8cd-99c1-4abc-9325-7a9e4e7e8707.png)
It seems that there is no answer to the filter.
If I unfold the program, I can see the challenges

**Comment by rdenarie** [comment]
As there is a button mark as read in the left menu, we can close this issue

**Comment by srenault-meeds** [comment]
Fixed now
