### ISSUE TITLE
Mark as read a space is not easily accessible

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#483]
To mark all space activities as read, you have to open the left menu, click on the arrow of the space to open the second level, and mark as read. 
The button is quite hidden. 

It could be interesting to have the same button at the top of the space activity stream. So the user journey could be :
I open the left menu, seelect a space, go to the space stream, read the first unread activities, then decide that the older one are not interesting, and mark all activities of the current as read without reopening the 2 levels of the left menu

**Comment by srenault-meeds** [comment]
Ok what you propose is getting this option from the topbar space popover for example?

**Comment by rdenarie** [comment]
Could it be here :
![image](https://user-images.githubusercontent.com/807839/209180071-64599f9b-0d49-4914-a74e-1647d3fec772.png)
