### ISSUE TITLE
[TASK] Click on a link in a task's comment should open a new tab

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#484]
**Is your feature request related to a problem? Please describe.**
On the task when we click on a link in the comments, the new page opens in the same tab. So we lost the task and the context. We should do a right click open in a new tab or click on the 3rd button of the mouse. 

While, when we click on a link in the task description the link is opened in a new tab. 

**Describe the solution you'd like**
Harmonize the behavior and always opens the link in a new tab. 

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/105866381/209300455-a5471891-a873-4d14-ae03-30e510339307.mp4

**Comment by srenault-meeds** [comment]
Duplicated with this one: https://github.com/Meeds-io/meeds/issues/146
And BTW links should opened in a new tab only when it is external to the current site
