### ISSUE TITLE
Achievement : When i access to program page detail from achievement, the estimated earning points per user is displayed 0

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#485]
**Steps to reproduce**

1. Go to 'acheivement'
2. Click on 'program name'
3. Scroll up to 'title'

![points per user acheivement](https://user-images.githubusercontent.com/83289222/209304928-ed0af1da-5ae8-471f-a0ec-568be4d5c40a.gif)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

the estimated earning per user is displayed 0
**Expected behavior**

the estimated earning points per user is displayed as program page detail from program tab
**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Should be fixed after next deployment
