### ISSUE TITLE
BUG: I can't send kudos back to the one who sent me one in kudos activity

### ISSUE THREAD

**Issue by MayTekayaa** [Meeds-io/meeds#487]
**Steps to reproduce**

1. user1 sent kudos to user2 with kudos activity (not related to kudos on space)
2. user2 want to send kudos back to the user1

**Current behaviour**

Send kudos button is disabled.

![Screenshot from 2022-12-23 17-32-37](https://user-images.githubusercontent.com/100131287/209368444-606dd74c-4c0d-4049-bd92-c92d7d38c8cd.png)

**Comment by srenault-meeds** [comment]
Should be fixed in the next deployment
