### ISSUE TITLE
Issue while inviting new user/ can't see the captcha picture 

### ISSUE THREAD

**Issue by Martyna2238** [Meeds-io/meeds#488]
![image_2022-12-25_212528551](https://user-images.githubusercontent.com/121404352/209481132-01978696-d5d1-4fcd-9a81-1d36f863bfec.png)
**Steps to reproduce**

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.

**Expected behavior**

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Fixed @Martyna2238
