### ISSUE TITLE
[Achievement] Wrong icon for action on mobile 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#490]
**Steps to reproduce**

1. Go to 'contribution > achievement '
2. See icon display before action name

![image](https://user-images.githubusercontent.com/83289222/209665770-8409a30d-95dc-42e3-a09f-7883090985f3.png)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behavior**
Icon trophy is display for all action 

**Expected behavior**

for each action type should display a different icon as on desktop
**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
should be ok now
