### ISSUE TITLE
Information icon isn't well displayed for total locked value

### ISSUE THREAD

**Issue by MayTekayaa** [Meeds-io/meeds#493]
**Steps to reproduce**

1. Go to 'https://holders.meeds.io/dapp/overview'
2. Click on 'Portfolio' in the navigation Bar
3. Scroll down to 'Token informations'
4. See bad display of information icon for Total Locked Value

**(optional) Affected environments**  
 - Browser: FireFox Web Browser

![Screenshot from 2022-12-28 11-30-03](https://user-images.githubusercontent.com/100131287/209799475-789376ad-4d0e-497b-827e-e0e488f5697b.png)

**Comment by srenault-meeds** [comment]
Hi @MayTekayaa Seems to be ok now:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/58853195/215999722-dd9ab16e-23e0-4cae-8268-d5072d499f3b.png">

WDYT?
