### ISSUE TITLE
Several applications in the Overview page have the same name in the app registry

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#496]
**Steps to reproduce**

cf here

![Video_22-12-29_11-44-09](https://user-images.githubusercontent.com/31288011/209940276-0672713f-bbe7-4be3-b54a-904db780f6fa.gif)

**Current behaviour**

Several applications in the Overview page have the same name in the app registry

**Expected behavior**

The name of the portlet must be the name to be displayed

**Comment by srenault-meeds** [comment]
Fixed now
