### ISSUE TITLE
Investor App : Should change Sushi farm link

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#498]
In investor app (https://holders.meeds.io/dapp/farm), the sushi farm link is old
the new link to add is https://www.sushi.com/

**Comment by srenault-meeds** [comment]
Hi @Jihed525 When I click to the current link of sushi farm, it is actually ok for me.
Can you please precise what link you have when clicking to it?

**Comment by Jihed525** [comment]
@srenault-meeds : the actual app.sushi.com is an old one as displayed in this [screenshot](https://community.exoplatform.com/portal/dw/drives?documentPreviewId=771c99f2ac12000d0b241c965d59b11b), shouldn't the newer version url be available instead of old one ?

**Comment by srenault-meeds** [comment]
Ok thanks

**Comment by srenault-meeds** [comment]
Fixed!
