### ISSUE TITLE
Non Supported Image Format generates an exception

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#499]
**Steps to reproduce**

1. Go to User Profile
2. Rename a .txt file to a .png to simulate a not supported image format
3. Update User Profile Image with the txt file

```
ERROR | Error while resizing avatar, original Image will be returned [o.e.s.rest.impl.user.UserRestResourcesV1<http-nio-0.0.0.0-8080-exec-131>] 
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "bufferedImage" is null
	at org.exoplatform.services.thumbnail.ImageResizeServiceImpl.scaleImage(ImageResizeServiceImpl.java:35)
	at org.exoplatform.social.core.metadata.thumbnail.ImageThumbnailServiceImpl.getOrCreateThumbnail(ImageThumbnailServiceImpl.java:102)
```

**Expected behavior**

A non supported image format for generating a thumbnail should simply retrieve the original image data and avoid throwing an error.

**Comment by Jihed525** [comment]
eXo Task created : https://community.exoplatform.com/portal/dw/tasks/taskDetail/61578

**Comment by Jihed525** [comment]
issue should be fixed now https://community.exoplatform.com/portal/dw/tasks/taskDetail/61578

**Comment by boubaker** [comment]
Fixed by https://github.com/Meeds-io/commons/commit/80e4512e8abacdab125e8e95c8ecb7ac07ecb64a
