### ISSUE TITLE
[Space] REG: Space host display name font-style is wrong

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#501]
**Steps to reproduce**

1. Go visit a space
2. Check the space informations portlet and the space host
3. See error: display names for hosts only (not redactors) are bold. Shouldn't be the case.

<img width="137" alt="image" src="https://user-images.githubusercontent.com/58853195/210335203-9dbc3463-7508-4bb5-b1ef-40753b6a428e.png">

**Comment by srenault-meeds** [comment]
@rdenarie @boubaker can you help me please regarding this? I would like to know if this regression is related to any of our current work (meedslab or exo) so we can manage to fix this.
cc @Jihed525 FYI

**Comment by rdenarie** [comment]
I think it comes from here :
https://github.com/meeds-io/social/commit/c0521552071130bdb94525840ee9077862c51c59

**Comment by srenault-meeds** [comment]
Will be fixed in next MEP
