### ISSUE TITLE
Drawer rewards displays empty

### ISSUE THREAD

**Issue by walidriahi** [Meeds-io/meeds#503]
**Steps to reproduce**

1. Go to 'https://builders.meeds.io/portal/meeds/profile'
2. Click on 'Reward'

![image](https://user-images.githubusercontent.com/67702167/210355195-842d7c80-2609-4056-8116-4458655216a7.png)

**Current behaviour**

Drawer rewards displays empty

**Expected behavior**

Should display rewards 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Hi @walidriahi can you please tell us which browser and which OS you use?
Indeed, I can't reproduce it.
Thanks

**Comment by srenault-meeds** [comment]
Hi @walidriahi can you please tell us if you still reproduce it? Thanks
