### ISSUE TITLE
New post toast appeared despite applying the activity stream filter

### ISSUE THREAD

**Issue by hthabti** [Meeds-io/meeds#505]
steps:
as user1 select a filter on stream exp "favorite spaces" 
as user2 post a short message on a space were I'm member which do no figure on my favorite spaces

actual:
popup new post shown + when clicking on it no thing happens (no redirection)
same behavior using other filters

question:
what is the expected for the descried bhavior ?
if I set a particular filter for the stream, should I see "new post poup" ? hence when clicking on it I'm redirected to the related activity ?
or that popup shouldn't be displayed ?

**Comment by srenault-meeds** [comment]
Yes we should take care of this.
here is the task created months ago:
https://builders.meeds.io/portal/meeds/tasks/taskDetail/406
So the expected behaviour should be: if not filtered by all, then no chips at all

**Comment by srenault-meeds** [comment]
Enhanced :)
