### ISSUE TITLE
Share Short message: original and shared activities aren't synchronized once update/delete actions performed

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#522]
**Steps to reproduce**
Post a Short message on space1
share it on space2
edit/delete the original post in space1 

**Current behavior**

Edit case: The Short message is not updated in the shared post on space2

Delete case : changes will be taken into account => after server restart
: an empty activity is displayed.

**Expected behavior**

Edit case: Original and shared post should be synchronized and display the same content on both space1 and space2 Activity streams

Delete case: if the original post on space1 has been deleted the shared post should remain intact on space2 

**(optional) Affected version**

eXo 6.3/6.4

eXo Related task : https://community.exoplatform.com/portal/dw/tasks/taskDetail/54559

**Comment by srenault-meeds** [comment]
Hi @Jihed525 do exo plan to take care of this?
(I don't have access to the task). Thanks

**Comment by Jihed525** [comment]
I might have rushed reporting this behavior @srenault-meeds, having a second thought(hints shared by @margondicco  ), the current behavior seems to be more consistent and adapted to Digital workspace concept, I react to an activity shared based on its particular content. Thus, once updated, the new content might not be appreciated as the old one.

WDYT ?

**Comment by srenault-meeds** [comment]
Yes indeed as we don't manage where the content has been shared. Difficult to update everywhere without knowing the audience of spaces where activity has been shared.

**Comment by Jihed525** [comment]
Indeed, thus please close this issue as it is not a valid issue.
