### ISSUE TITLE
Wrong text size when copy and paste text on description of challenges from another app

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#523]
**Steps to reproduce**

1. Go to 'challenges'
2. Copy text from github and paste it on challenges description
3. Go to challenge activity

![image](https://user-images.githubusercontent.com/83289222/210795023-5f14b0de-399c-4aa1-bc3a-99c139b54262.png)

**Current behavior**

Pasted text is displayed to big size
**Expected behavior**

Pasted text should be displayed as default size of activity stream ( font-size : 14px) 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Can we consider it asap @Imenmakni ?
"ça pique les yeux" :D

**Comment by Imenmakni** [comment]
added to board @srenault-meeds

**Comment by srenault-meeds** [comment]
Should be ok after next deployment
