### ISSUE TITLE
Perk Store Technical label display 

### ISSUE THREAD

**Issue by ArfaouiMohamedAmine** [Meeds-io/meeds#542]
**Steps to reproduce**

1- Go to Perk Store 
2- Add a new product 
3- upload a product image 
4- remove the image 
5- boom
![Screenshot from 2023-01-11 18-29-45](https://user-images.githubusercontent.com/101107377/211877393-1438e7de-527a-4095-aae2-dc80d1b4060f.png)

**Comment by srenault-meeds** [comment]
Duplicated with this one: https://github.com/Meeds-io/meeds/issues/254
