### ISSUE TITLE
No Title or sub-title in the  DAO Builders login page

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#551]
**Steps to reproduce**

1. Go to the login page of Meeds DAO Builder login page
2. There is on the left side, "Titre" and "Sous-Titre"

![Capture d’écran 2023-01-16 092855](https://user-images.githubusercontent.com/105866381/212633586-1e81dce0-42d5-47f3-b8aa-c10ec1899475.png)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

On the login page, there are labels Titre and Sous-titre 

**Expected behavior**
These labels should be named I guess. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
@boubaker hello, do you confirm a task is in progress regarding this?
Thanks

**Comment by srenault-meeds** [comment]
Fixed!
