### ISSUE TITLE
inconsistency in ranks

### ISSUE THREAD

**Issue by walidriahi** [Meeds-io/meeds#554]
**Steps to reproduce**

1. Go to '[...](https://builders.meeds.io/portal/meeds/people)'
3. Click on 'show

![image](https://user-images.githubusercontent.com/67702167/212721396-f5b0f3e2-515d-4e28-a167-5cd3fdbbbc02.png)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**
inconsistency in ranks displays

**Expected behavior**

should display same rank 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Hi, I only reproduce it when filtering by program. Hence, should be updated among which filter is used

**Comment by srenault-meeds** [comment]
Done thanks to MIP #100 https://github.com/Meeds-io/MIPs/issues/100
