### ISSUE TITLE
[Picture] Enhance the way we can add picture to a profile, a space, a program

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#555]
**Is your feature request related to a problem? Please describe.**
Currently, when adding a picture for a profile avatar, for a profile banner, for a space avatar, for a space banner or for a program cover, we need to make sure it is well sized, well zoomed, etc. before uploading it.

This is not the best modern way to add a picture. Indeed, lots of platform tools where avatars and banners can be added, proposed different way to edit an image.

**Describe the solution you'd like**
We suggest to provide a nice and easy option for our end-users to set their pictures.
So that, they can:
- zoom, crop the image
- position the image
- rotate it if needed

And depending the use case, we should display a canvas so that the user knows better how the image will be displayed.
Here are the case we need to take care of:

Adding a profile avatar
![add a profile avatar](https://user-images.githubusercontent.com/58853195/212866350-44ad7879-fc96-4830-a9dd-39618a8862d1.jpg)

Adding a profile banner
![add a profile banner](https://user-images.githubusercontent.com/58853195/212866365-720f2e50-c1b5-45dd-9525-53be62b049b9.jpg)

Adding a space avatar
![add a space avatar](https://user-images.githubusercontent.com/58853195/212866326-50ad5aeb-2d12-4481-b9e5-7408a67d812a.jpg)

Adding a space banner
![add a space banner](https://user-images.githubusercontent.com/58853195/212866312-8144791d-87d6-4e4c-bdea-bde27bf8448c.jpg)

**Precisions:**
Regarding the banner, we will add a new behaviour to make sure the display of the banner is ok accordingly to what is expected by end-users and accordingly to the frame proposed when uploading the picture.
Indeed, the width will remain the same no matter the device's width and the height should adjust.

**Comment by srenault-meeds** [comment]
WDYT? @margondicco

**Comment by margondicco** [comment]
Great !

**Comment by srenault-meeds** [comment]
Add the precision regarding the banner display (same width to make sure the picture is always well displayed as accordingly expected when uploading and using the proposed frame)
