### ISSUE TITLE
Export btn isn't working

### ISSUE THREAD

**Issue by walidriahi** [Meeds-io/meeds#556]
**Steps to reproduce**

1. Go to https://builders.meeds.io/portal/meeds/contributions/achievements)
2. Click on 'exporter en xlsx'

**(optional) Affected version**

Indicate the version where the bug is observed.
![i can t export my acheivement](https://user-images.githubusercontent.com/67702167/212885392-83a7b726-5ab0-4257-b8c5-b0ec86622245.gif)

**Current behaviour**

when i click on export an empty new tab is opened 

**Expected behavior**

when i click on export should export my realisation table

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
@Imenmakni hi can you track this one please, it is a regression

**Comment by srenault-meeds** [comment]
Should be fixed after next deployment
