### ISSUE TITLE
Add Space Button is not correctly displayed in language different than en

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#560]
Configure the platform in fr
Go in All spaces page

Current Behaviour : the label on button "AddSpace" is not completly visible : 
![image](https://user-images.githubusercontent.com/807839/213122756-8421a561-b846-4f83-a8a1-c48904f22e4f.png)

Expected Behaviour : 
The label should be visible completly.

**Comment by srenault-meeds** [comment]
@rdenarie we'll take a look at it. Thanks

**Comment by srenault-meeds** [comment]
Should be fixed in next deployment
