### ISSUE TITLE
Show more button for programs in mobile is not well displayed

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#561]
**Steps to reproduce**

1. Go to 'contribution application' with your mobile
2. Scroll down 
4. check the show more button 

**Current behaviour**

The 'show more' button is now not well displayed due to the new bottom added 
![Selection_425](https://user-images.githubusercontent.com/50736962/213149611-713e206e-b4da-4199-bc2d-29b032894dec.png)

**Expected behavior** 
The 'show more' button should be well displayed

**Comment by srenault-meeds** [comment]
Related to the topbar navigation portlet. Issue being treated I think by eXo team.
@mzorai  right?

**Comment by ichaieb** [comment]
> Related to the topbar navigation portlet. Issue being treated I think by eXo team. @mzorai right?

Yes related to the new topbar navigation .
