### ISSUE TITLE
External link preview in announcement Ckeditor is not functional as it used to be 

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#562]
**Steps to reproduce**

1. Go to 'contribution' application
2.access to challenge TAB
3. announce a challenge by adding an external link with preview ( e.g : youtub , github ....)

**Current behaviour**
The preview is not shown in the CKeditor as it used to be  , then it is not displayed in the posted activity
![Selection_426](https://user-images.githubusercontent.com/50736962/213151692-0e0511a0-f0aa-474c-87fb-9770a1f399bf.png)

**Expected behavior**
The preview should be displayed as it used to be 
![Selection_427](https://user-images.githubusercontent.com/50736962/213151820-2507d719-8912-4d5e-ade5-1052c362c14c.png)

**Comment by srenault-meeds** [comment]
Should be fixed in next deployment
