### ISSUE TITLE
[Profile] Profile informations display and management

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#564]
## Problem explaination

The current profile displays UI glitches (bad alignement of call-to-action) and bad UX in some points:
- contact informations are to the right while it should be the first infos to see when viewing a profile (desktop or mobile)
- when no informations have been fulfilled by the user I see, apps are displayed while it shouldn't be
- action Connect is not well aligned

## 1. Functional requirements
Here are we suggest to improve:

1. call-to-action should be:
- well aligned

2. apps should:
- be displayed when the informations are filled by the user
- keep the current placeholder to the user when viewing its own profile and informations needs to be fulfilled
- float when scrolling down (only apps from the right column)

3. Apps should be re positioned:
- Kudos below the profile stats portlet and above the badges one - We can propose to display same app *Reputation* we have in the overview page, but contextualized depending who is seeing it
- rewards app should be removed
- contact informations below the about me and above the work experiences with same display as currently (one column)

4. Apps should be dependant to the user who is viewing it:
- When viewing another user profile: About me, My activity, My contact informations, etc.
- When viewing my own profile: About yourself, Your activity, etc.

**Case when viewing another profile**
<img width="751" alt="image" src="https://user-images.githubusercontent.com/58853195/213226596-ba46d83f-3461-4173-9871-a2f136562e18.png">

**Case when viewing my own profile**
![profile when my profile](https://user-images.githubusercontent.com/58853195/213228017-1f500537-48f8-42dd-b8bb-a9b8fec735ac.jpg)

**Case when using mobile**
<img width="482" alt="image" src="https://user-images.githubusercontent.com/58853195/213227973-9fa98550-eb44-43f8-85cd-da29a1366671.png">

**Precisions**:
We recommend to force the page import so any existing platform will benefit automatically from these changes.
Any app in the profile page should be editable when editing the layout to help out our DAO members when editing the layout

**Comment by srenault-meeds** [comment]
@margondicco I let you confirm if ok for you
Including the fact that any user will see its profile updated as expected. So any app customization will be lost

**Comment by rdenarie** [comment]
We are currently working on profile : https://github.com/Meeds-io/MIPs/issues/38
The feature is quite finished. 
Be sure to let us merge before working on that to prevent conflict

**Comment by rdenarie** [comment]
Hello,
After discussion with @margondicco it seems that your proposition will only work around containers and page contents, not on the applications content. So, it is ok for me.

The only point I have is : can you confirm that you will force the reimport of this page, and only this page ? and this for meeds AND exo ?

Thanks

**Comment by srenault-meeds** [comment]
Hello,

> The only point I have is : can you confirm that you will force the reimport of this page, and only this page ? and this for meeds AND exo ?

Yes the reimport of the page will be forced for any DAO Members so Meeds and eXo.

**Comment by rdenarie** [comment]
Only for the profile page ? No other pages impacted ?

**Comment by srenault-meeds** [comment]
cc @boubaker

**Comment by boubaker** [comment]
Yep, it will be defined for profile page only

**Comment by rdenarie** [comment]
Thanks for the clarifications.

**Comment by boubaker** [comment]
> Only for the profile page ? No other pages impacted ?

@rdenarie to help you on how to use this issue once merged:

https://github.com/Meeds-io/social/pull/2235/files#diff-9cb8b410fe72bb8b980930c433e0d0e3208f483ced3ea18710fe2bdd26eb228eR228

The property that you may change in your package to re-import the new profile layout is `exo.social.portalConfig.profilePage.importmode` which has a default value `insert`. Thus to reuse the new layout on existing installations, you may add in exo.properties the value of `exo.social.portalConfig.profilePage.importmode=merge` or to add it as done in [meeds](https://github.com/Meeds-io/meeds/blob/develop-meed/webapps/plf-meeds-extension/src/main/webapp/META-INF/exo-conf/configuration.xml#L29).

( As decided in lastest Product Committee , you can configure the property value t o use in your package )
