### ISSUE TITLE
UI glitch in Refuse button for connection notification

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#566]
**Steps to reproduce**

1. user1 send a connection request for user2
2.user2 check his notif 

**Current behaviour**

The border of refuse button is erased 
![Selection_429](https://user-images.githubusercontent.com/50736962/213419680-b3254d14-858d-4d37-91d9-ac854879ca85.png)

**Expected behavior**
The border of refuse button should be well displayed

**Comment by srenault-meeds** [comment]
Done by MIP https://github.com/Meeds-io/MIPs/issues/80
