### ISSUE TITLE
Description in challenge drawer out of the drawer

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#567]
**Steps to reproduce**

1. Go to 'challenge'
2. Add challenge with long text on description 

**Current behaviour**

The drawer is displayed with horizontal scroll
![long text challenge](https://user-images.githubusercontent.com/83289222/213463550-3bb40abe-d15c-45bc-bc5e-1db308c6cc77.gif)

**Expected behavior**

The drawer should be displayed without  horizontal scroll

**Comment by srenault-meeds** [comment]
Should be fixed after next deployment
