### ISSUE TITLE
My contribution portlet - Program truncated 

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#569]
**Is your feature request related to a problem? Please describe.**
On the page Overview page, on the My contribution portlet, we can't see in the legend the full name of the most used program. 
On hovering, over the chart, we have a tooltip that gives the full name but not on the legend. 

**Describe the solution you'd like**
Ideally, optimize the length of the display to have more chars and be able to see without interaction the program name. 
Another option is to add a tooltip on hovering over the legend as it's the case on hovering over the chart. 

**Describe alternatives you've considered**

**Additional context**
See screencast

https://user-images.githubusercontent.com/105866381/213456869-4ecae5ec-9202-4fe1-98a7-23f581c84090.mp4

**Comment by srenault-meeds** [comment]
Done
