### ISSUE TITLE
Popular space : when space name is long it display out of frame 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#570]
**Steps to reproduce**

1. Go to 'spaces '
2. Create space with long name 
3. Go to spaces , see portlet popular space 

![image](https://user-images.githubusercontent.com/83289222/213466542-ca2ca8fc-19ad-4947-9d7e-7129b26a6330.png)

Indicate the version where the bug is observed.

**Current behaviour**

Space name is displayed out of frame 

**Expected behavior**

when space name is long, it should display ellipsis 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Duplicated with this one: https://github.com/Meeds-io/meeds/issues/559
