### ISSUE TITLE
Can't add task using the quick add task button on mobile

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#571]
**Steps to reproduce**

1. Go to 'Tasks page and open any project'
2. In the bottom of a tasks column try to add a new task using the quick add task button.
3. The button is not displayed (hidden by the new menu)
4. See ScreenShot
![Screenshot from 2023-01-19 18-09-30](https://user-images.githubusercontent.com/40363501/213514354-7cb5eb80-7a29-4ade-ba0b-2915438f7482.png)

**Current behaviour**

When we scroll on the button of a tasks column, we can not add a new task using the quick add task button.

**Expected behavior**

When we scroll on the button of a tasks column, The add task button should be well displayed.

**Comment by srenault-meeds** [comment]
Indeed, related to a work in progress to improve the topbar navigation (which is a tab bar when using mobile). 
P.S. welcome back @SaraBoutej 😃
