### ISSUE TITLE
UI Glitch in the Alert message

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#572]
**Steps to reproduce**

1. Go to 'challenge page'
2. Announce a new challenge
3. A success Alert message is displayed with an UI glitch in the close alert icon
4. See screenshot

![Screenshot from 2023-01-19 18-19-02](https://user-images.githubusercontent.com/40363501/213519074-9336ccef-8fd6-448e-aa8a-5322089a2f82.png)
![Screenshot from 2023-01-19 18-31-07](https://user-images.githubusercontent.com/40363501/213519098-02467114-cd67-420d-8a2c-9c45e42add49.png)

**Current behaviour**

The close icon in the alert message is out of the alert area.
Also when I try to put an activity as favorite the close icon is not well displayed.

**Expected behavior**

The close button must be in the alert area and well displayed

**Comment by srenault-meeds** [comment]
Fixed!
