### ISSUE TITLE
Mobile Swipe Button is displayed above the drawer on mobile 

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#573]
**Steps to reproduce**

- Open the challenge or notification drawer on mobile 
- The swipe mobile button used to display the left or the right side of the page is displayed above the drawer
See screencast
 
[Screencast from 19-01-2023 18:43:15.webm](https://user-images.githubusercontent.com/40363501/213521524-daa90da0-99e9-46b3-a571-18beb6124f71.webm)

**Comment by srenault-meeds** [comment]
Should be fixed after next deployment
