### ISSUE TITLE
Task : bad display of count indicator on task view list 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#574]
**Steps to reproduce**

1. Create task 
2. Assign two user to this task 
3. Go to https://builders.meeds.io/portal/meeds/tasks/myTasks
4. view this task 
![image](https://user-images.githubusercontent.com/83289222/213554533-320b85f8-30ee-4bc5-8a99-10f61eab9acc.png)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behavior**

Count indicator should be well displayed 
**Expected behavior**

Count indicator display truncated 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Duplicated with https://github.com/Meeds-io/meeds/issues/492
