### ISSUE TITLE
Task : the assignee isn't displayed on drawer details task 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#575]
**Steps to reproduce**

1. Go to 'task app'
2. Assign a task to user 
3. Click on task 

![task assignee ](https://user-images.githubusercontent.com/83289222/213555918-c673eaaa-2539-413f-bc1d-14c1ae9c670a.gif)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behavior**

the assignee isn't displayed on drawer details task 
**Expected behavior**

the assignee isn't should be displayed on drawer details task 
**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Can't reproduce it @Imenmakni can you check again please?
