### ISSUE TITLE
Bad display for welcome back widget on profile when using tablet 

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#578]
**Steps to reproduce**

1. Go to 'your profile.'
2. check welcome back widget

**Current behaviour**

The widget welcome back is not well displayed 
![Selection_431](https://user-images.githubusercontent.com/50736962/213687378-a067ded8-f030-4e69-a083-c624b3127c47.png)

**Expected behavior**

The widget welcome back should be well displayed on Tablet

**Comment by srenault-meeds** [comment]
Should be fixed after next deployment since profile has been reworked
