### ISSUE TITLE
The thumbnail url contains twice the size in activity

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#580]
I can only reproduce in eXo platform context, with news.

Create a news with a thumbnail. Display in mobile view. 

Current behaviour, the thumbnail url is ...&size=250x150&size=250x150

Expected behaviour : size is displayed once

**Comment by srenault-meeds** [comment]
is it done @rdenarie ?

**Comment by rdenarie** [comment]
Yes it is.

**Comment by srenault-meeds** [comment]
thanks
