### ISSUE TITLE
[People Search] When searching a user, for certain users, avatar is not displayed

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#586]
**Steps to reproduce**

1. Go to People page
2. Search users, for example "dub"

**Current behaviour**

Some avatars are not displayed and generate a 404 error in network console.
It is not reproduced on local instance or acceptance, only on Tribe prod/preprod. It seems related to old data

**Expected behavior**

All avatars are displayed

**Comment by srenault-meeds** [comment]
@rdenarie is it done?

**Comment by rdenarie** [comment]
Yes, done

**Comment by srenault-meeds** [comment]
thanks
