### ISSUE TITLE
[Program] Action drawer do not display all the content

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#590]
**Steps to reproduce**

1. Go to the Contribution center
2. Go to the Program tab
3. Click on the Buy Meeds & Invest it
4. Click on an action. The drawer do not display all the content without scrolling on the side

![Capture d’écran 2023-01-25 092001](https://user-images.githubusercontent.com/105866381/214513601-52d80ac6-8a1d-4121-addb-be81f67f36d3.png)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

We can't see all the content of the drawer. 

**Expected behavior**

All the content should be seen directly in the drawer. We should have back to the line and have to scroll down not to the side. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Duplicated with this one FYI: https://github.com/Meeds-io/meeds/issues/567
And to be fixed in the next deployment
