### ISSUE TITLE
[Task] Notification for a task sends the user to its home

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#604]
**Steps to reproduce**

1. Get a notification for a task
2. Click to it
3. See error: the users is sent to its home instead of the task

Screencast there:

https://user-images.githubusercontent.com/58853195/215043763-b509d72a-58eb-4d36-9111-432e2f209d5f.mp4

**Comment by srenault-meeds** [comment]
@boubaker @rdenarie don't know if related to any of ongoing work. If you can help us, that'd be nice, thanks!

**Comment by ahamdi** [comment]
@srenault-meeds It seems to be a permission issue, to check ..
