### ISSUE TITLE
Standardize the styles/police size between notes and news pages 

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#605]
**Steps to reproduce**

1. Create an article and a note page having text with the different title styles, quotes, numbered and bulleted lists.
2. Compare the text display between note and article pages in both edition and consultation views

**Current behaviour**

The styles and police size isn't standardized between the different views .

**Expected behavior**

Standardize the styles and police size between notes and news in both consultation and editing page as follows:

- [ ] Set the normal title size to  18.6667 px

- [ ] Set Title1 size to 34 px, font-weight=400

- [ ] Set Title2 size to 28 px, font-weight =400

- [ ] Set Title3 size to 21.84 px, font-weight =400

- [ ] Set  bulleted-list: set the size to 18.6667px

- [ ] Set numbered-list set the size to 18.6667px

- [ ] Set block quote: set the size to 17.5px, font-weight=300

**Comment by srenault-meeds** [comment]
guys, please, make sure you don't duplicate issue
see there: https://github.com/Meeds-io/meeds/issues/641
