### ISSUE TITLE
Add the possibility to reload a PortalConfig programmatically

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#606]
**Is your feature request related to a problem? Please describe.**
When updating a page, or a navigation in xml files, the only way to reload it is to configure the import mode in the xml file. 
When this import mode is fixed for a version, there is no way to change it except using properties.
There is no way to make the update once, by using importMode=merge, or overwrite, and then changing it automatically to insert.

**Describe the solution you'd like**
To launch this update once, we need to add a function reloadConfig in UserPortalConfigService, which will call NewPortalConfigListener.
To find the correct portalConfig to reload, we need few parameters :

- ownerType (portal, group, user)
- predefinedUser
- location

This 3 parameters will be used to find the correct PortalConfig

Then we need : 

- importMode (overwrite, insert, merge, conserve)
- overrideMode (true/false)

When calling this, the founded PortalConfig will reloaded from xml in function of the importMode provided.
We will reload : the portal configuration, the pages configuration and the navigation.

In fact, it will be the same process as when we force the importMode with a property except than it can be call programmatically, via an UpgradePlugin for example. 
In this case, the UP is launched once, without having to take care with a property

**Comment by boubaker** [comment]
In fact, this is related I think to the study in progress here https://github.com/Meeds-io/MIPs/issues/47

**Comment by rdenarie** [comment]
Currently, we need to be able to reload a portalConfig to create an upgrade plugin

**Comment by srenault-meeds** [comment]
@rdenarie done?

**Comment by rdenarie** [comment]
Yes, it is. I will close the issue, but I dont know which status to put. "Landed" ?

**Comment by srenault-meeds** [comment]
yes, as soon as you close it, it'll go to landed status automatically
