### ISSUE TITLE
Bad display of the placeholder in the contribuitions portlet

### ISSUE THREAD

**Issue by MayTekayaa** [Meeds-io/meeds#610]
**Steps to reproduce**

1. Go to 'Builders App'
2. Access to 'Overview Page'
3. Focus on My contributions portlet 
4. See the bad display of the placeholder in the portlet

NB: Given i am a new user

![Screenshot from 2023-01-30 10-30-01](https://user-images.githubusercontent.com/100131287/215440493-22af86d3-d113-41d9-ba1e-336f13f992d7.png)

**Comment by srenault-meeds** [comment]
should be ok now
