### ISSUE TITLE
Unscheduled tasks icon is displayed out of the portlet in PLAN view 

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#611]
**Steps to reproduce**

1. Go to 'Task project'
2. Select PLAN view
3. Check the Unscheduled tasks icon

**Current behaviour**
Unscheduled tasks icon is displayed out of the portlet in PLAN view 
![Selection_446](https://user-images.githubusercontent.com/50736962/215495049-fa9e7c3e-7220-4b04-98be-bd922d4b331d.png)

**Expected behavior**
Unscheduled tasks icon should be displayed on the portlet in PLAN view

**Comment by ichaieb** [comment]
cc @srenault-meeds , I think its due to the new margin work

**Comment by srenault-meeds** [comment]
Will be done in next deployment
