### ISSUE TITLE
Click on tell others of page profile redirect me to empty page with text true

### ISSUE THREAD

**Issue by Yudacha** [Meeds-io/meeds#613]
**Steps to reproduce**

1. Go to 'https://builders.meeds.io/portal/meeds/profile'
2. Click on 'tell others'

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Click on tell others of page profile redirect me to empty page with text true

**Expected behavior**

Click on tell others of page profile  redirect me to appropriate page 

**(optional) Affected environments**  
Please complete the following information: 
 - Browser [firefox]

**Comment by srenault-meeds** [comment]
should be ok now
