### ISSUE TITLE
Click on action login to platform no redirection

### ISSUE THREAD

**Issue by Yudacha** [Meeds-io/meeds#614]
**Steps to reproduce**

1. Go to 'https://builders.meeds.io/portal/meeds/contributions/achievements'
2. Click on 'login to platform '

**(optional) Affected version**

Indicate the version where the bug is observed.
![Login to platform](https://user-images.githubusercontent.com/124036884/215757155-4e7a1351-b597-41e9-a97a-605aebba8be1.gif)

**Current behaviour**

Click on action login to platform no redirection but when i click on Introduce yourself to the community it redirect me to https://builders.meeds.io/portal/meeds/profile/yuda.chan

**Expected behavior**

Click on action login to platform should redirect to appropriate page

**(optional) Affected environments**  
Please complete the following information:

**Comment by plamarque** [comment]
Good catch!  on other types of actions it links to the source of the event to help verify the action (such as a post or a task or announcement). In case of a login action, there is nowhere to link actually. 

But we should probably not include a fake link in this case . @srenault-meeds WDYT ?

**Comment by srenault-meeds** [comment]
Hello, yes indeed, we should review the UX regarding this.
Thanks for reporting it @Yudacha!
