### ISSUE TITLE
Browser cache prevent activities roles refresh when switching users

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#615]
**Steps to reproduce**

( Using same browser tab) 

1. connect with user1
2. Create space and add some activities there
3. Connect with user2 and join space
4. connect with user1

**Current behaviour**

user1 doesn't have Edit option in three dots menu

**Expected behavior**

user1 is author of activities and should have Edit option in three dots menu

**Comment by srenault-meeds** [comment]
should be ok now
