### ISSUE TITLE
fix: Double Notifications received when user receives a Kudos

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#618]
**Steps to reproduce**

1. Send a kudos to userA
2. Login With userA and check notifications

**Current behaviour**

Two notifications are received by user, one for the activity and another for the Kudos itsself.

**Expected behavior**

Only one notification should be received and in addition, the space Web Notification has to be kept incrementing for receiver.

**Comment by srenault-meeds** [comment]
I close it as it is duplicated with this one: https://github.com/Meeds-io/meeds/issues/576
