### ISSUE TITLE
fix: Change the usage of outdated alert when closing activity composer

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#619]
**Steps to reproduce**

1. go to space Stream
2. Write an activity
3. Without posting try to refresh page
4. An alert message is displayed

![Capture d’écran du 2023-02-02 10-48-09](https://user-images.githubusercontent.com/594824/216290553-f0a9810a-063b-4ee0-80a4-eae074ae5a9d.png)

**Current behaviour**

An outdated browser alert message is displayed.

**Expected behavior**

A reusable classic modal should be displayed :

![image](https://user-images.githubusercontent.com/594824/216291027-33d40ea5-02dc-400b-8904-a0fac93f91fe.png)

**Comment by srenault-meeds** [comment]
Actually, the message is wrong because the message will be kept as a draft until the user starts a new message elsewhere.
I 'll propose something.
