### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by peterklas** [Meeds-io/meeds#62]
Hi,
I cloned and run mvn install with Java 11 and maven 3.6 and got the following error.

How can I fix it?

regards,
Peter

[INFO] Reactor Summary for eXo Meeds:: Meeds Public Distribution 1.1.x-SNAPSHOT:
[INFO]
[INFO] eXo Meeds:: Meeds Public Distribution .............. SUCCESS [  1.183 s]
[INFO] eXo Meeds:: Meeds Public Distribution - Services ... SUCCESS [  0.013 s]
[INFO] eXo Meeds:: Meeds Public Distribution - Services - Container Config SUCCESS [  0.484 s]
[INFO] eXo Meeds:: Meeds Public Distribution - Services - Community Edition Information SUCCESS [  0.189 s]
[INFO] eXo Meeds:: Meeds Public Distribution - Services - eXo Tools SUCCESS [  0.799 s]
[INFO] eXo Meeds:: Meeds Public Distribution - Services - Tomcat Portal Containers Creator SUCCESS [  0.052 s]
[INFO] eXo Meeds:: Meeds Public Distribution - Webapps .... SUCCESS [  0.004 s]
[INFO] eXo Meeds:: Meeds Public Distribution - Webapps - ROOT WebApp FAILURE [  0.200 s]
[INFO] eXo Meeds:: Meeds Public Distribution - Webapps - Tomcat Integration WebApp SKIPPED
[INFO] eXo Meeds:: Meeds Public Distribution - Webapps - meeds extension WebApp SKIPPED
[INFO] eXo Meeds:: Meeds Public Distribution - Packaging .. SKIPPED
[INFO] eXo Meeds:: Meeds Public Distribution - Packaging - Assemblies SKIPPED
[INFO] eXo Meeds:: Meeds Public Distribution - Packaging - Dependencies SKIPPED
[INFO] eXo Meeds:: Meeds Public Distribution - Packaging - Shared Resources SKIPPED
[INFO] eXo Meeds:: Meeds Public Distribution - Packaging - Tomcat Resources SKIPPED
[INFO] eXo Meeds:: Meeds Public Distribution - Packaging - Community Tomcat Standalone SKIPPED
[INFO] eXo Meeds:: Meeds Public Distribution - Packaging - Sources SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.693 s
[INFO] Finished at: 2020-12-14T15:55:46+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.6:war (default-war) on project plf-root-webapp: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.6:war failed: Cannot construct org.apache.maven.plugin.war.util.WebappStructure as it does not have a no-args constructor : Cannot construct org.apache.maven.plugin.war.util.WebappStructure as it does not have a no-args constructor
[ERROR] ---- Debugging information ----
[ERROR] message             : Cannot construct org.apache.maven.plugin.war.util.WebappStructure as it does not have a no-args constructor
[ERROR] cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
[ERROR] cause-message       : Cannot construct org.apache.maven.plugin.war.util.WebappStructure as it does not have a no-args constructor
[ERROR] class               : org.apache.maven.plugin.war.util.WebappStructure
[ERROR] required-type       : org.apache.maven.plugin.war.util.WebappStructure
[ERROR] converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
[ERROR] path                : /webapp-structure
[ERROR] version             : null
[ERROR] -------------------------------
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :plf-root-webapp

**Comment by srenault-meeds** [comment]
@boubaker WDYT please?

**Comment by boubaker** [comment]
I close this issue since it's outdated (we are currently working on version 1.4.x).
Please feel free to open a new one if you keep facing the same problem using a recent version.
Thanks for your understanding and reporting.
