### ISSUE TITLE
I can't export my contributions points

### ISSUE THREAD

**Issue by andressw3** [Meeds-io/meeds#622]
1- Go to [My contibution ](https://builders.meeds.io/portal/meeds/contributions/programs)
2- Click on achievements tab
3 Click on Button Export Spreadsheet.
4- Error : see screenshot
![Screenshot from 2023-02-05 15-54-24](https://user-images.githubusercontent.com/121183322/216826723-d406ab18-3d1a-482c-848a-1339ff9815fe.png)

**Comment by srenault-meeds** [comment]
Hi @andressw3 
I can't reproduce it. I will study it more.
However, can you please give us more precisions?
- OS used?
- browser used?
Thanks

**Comment by srenault-meeds** [comment]
Should be fixed soon
