### ISSUE TITLE
[BUG] Kudos settings interface still apperar after changing other setting in the interface

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#623]
**step to reproduce** 

user connect to PLF  and user member of the group rewarding administrators
user access the platform > Side bar (i.e. click on the hamburger menu)
user click on kudos items 
user click on others  items ( perk store ,  wallet , reward )

![Image](https://user-images.githubusercontent.com/83289222/216931866-5067bf52-ecd3-42c8-b458-46fd1fc4d8b9.png)

**Actual behavior** 

the interface kudos settings still display ( Periode type , kudos  access permissions )

**Expected behavior** 

kudos settings display only when user navigate to it

**Comment by srenault-meeds** [comment]
Reviewed and thus fixed
