### ISSUE TITLE
Can't close connection list 

### ISSUE THREAD

**Issue by Yudacha** [Meeds-io/meeds#627]
**Steps to reproduce**

1. Go to 'https://builders.meeds.io/portal/meeds/stream'
2. Click on 'connection'
3. Click on " x " button

![can't close connection list](https://user-images.githubusercontent.com/124036884/216969242-b18e1acd-b178-46d1-af05-b0b453d029c5.gif)

**Current behaviour**

When i click on x button  connection list isn't closed 

**Expected behavior**

When i click on x button  connection list should be closed

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Should be ok after next deployment
