### ISSUE TITLE
Standardize font styles/size between notes and news pages 

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#641]
**Steps to reproduce**

1. Create an article and a note page having text with the different title styles, quotes, numbered and bulleted lists
2. Compare the text display between note and article pages in both edition and consultation views

**Current behaviour**

The styles and police size isn't standardized between the different views

**Expected behavior**
Standardize the styles and police size between notes and news in both consultation and editing page as follows:

- Set the normal title size to  18.6667 px
- Set Title1 size to 34 px, font-weight=400
- Set Title2 size to 28 px, font-weight =400
- Set Title3 size to 21.84 px, font-weight =400
- Set  bulleted-list: set the size to 18.6667px
- Set numbered-list set the size to 18.6667px
- Set block quote: set the size to 17.5px, font-weight=300

**Comment by srenault-meeds** [comment]
Done?

**Comment by srenault-meeds** [comment]
@Julien-Dubois-eXo what is the status please?

**Comment by Julien-Dubois-eXo** [comment]
I have no idea of what it is. It seems an old MIP. We have reworked the news editor to have the same behavior as on notes. This one is outdated.

**Comment by srenault-meeds** [comment]
Ok so I close it. Thanks
