### ISSUE TITLE
Comment button in Tasks comment drawer is too much closer to the Ckeditor 

### ISSUE THREAD

**Issue by ichaieb** [Meeds-io/meeds#642]
**Steps to reproduce**

1. Go to 'Tasks' application 
2. access to a project 
3. create a task 
4. open the comment task drawer 

**Current behaviour**
Comment button in Tasks comment drawer is too much closer to the Ckeditor 
![Selection_458](https://user-images.githubusercontent.com/50736962/217776526-3a7c7d17-7241-40e2-b72e-4f44f0f1b6a3.png)

**Expected behavior**

Add margin between the comment button and the Ckeditor

**Comment by srenault-meeds** [comment]
Duplicated with this one ;-)
https://github.com/Meeds-io/meeds/issues/205
