### ISSUE TITLE
Make the left sidebar menu always open 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#644]
**Is your feature request related to a problem? Please describe.**
User1 connects to eXo Platform 
User1 opens the left sidebar menu
User1 clicks on AS

Current behavior:
The left sidebar menu closes

**Describe the solution you'd like**

Make the left sidebar menu stay open all the time

**Comment by srenault-meeds** [comment]
Duplicated with: https://github.com/Meeds-io/meeds/issues/707
