### ISSUE TITLE
Share Activity: multiple posts added if article if content has emojies

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/meeds#646]
PLF: Latest

Database: Mysql

Steps:

1. create artivity in space A
2. share activity : message should include emojis
3. click so many times on post

**Actual behavior:**

Browser console displays errors shared activity is posted many times

**Expected:** 

activity  shared should be posted only one time and added content should be displayed 

**Request related :**
 https://community.exoplatform.com/portal/dw/tasks/taskDetail/62155

**Issue Being treated in task :** https://community.exoplatform.com/portal/dw/tasks/taskDetail/62213

**Comment by srenault-meeds** [comment]
Done or still in progress @Jihed525 ?

**Comment by Jihed525** [comment]
done @srenault-meeds
