### ISSUE TITLE
[Activity stream][spaces] Group mention feature

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#650]
**Is your feature request related to a problem? Please describe.**
I can't mention the whole space member

**Describe the solution you'd like**
Priority 1:

space members: when I mention a space, I mention the whole members. Of course, I can mention spaces that I am member of AND in for a space activity (from the space stream or from the general stream), I can mention only the current space
Priority 2 (when the priority 1 is delivered and we have enough feedbacks about it)

plf scope: I can mention a group from /organization and /platform
mention label should be i18n (not /platform/administrators but Administrators or Administrateurs in FR, etc.)
**Describe alternatives you've considered**

**Additional context**

**Comment by srenault-meeds** [comment]
Replaced by this MIP: https://github.com/Meeds-io/MIPs/issues/109
