### ISSUE TITLE
Button "Exporter en .xls " on achievements  screen is not working 

### ISSUE THREAD

**Issue by ahnsu123** [Meeds-io/meeds#654]
**Steps to reproduce**

1. Go to '(https://builders.meeds.io/portal/meeds/contributions/achievements)'
2. Click on 'Exporter en .xls'
3. See error: a new tab is opened. Message "L'accès à builders.meeds.io a été refusé" appears on the screen 

Image 
![image](https://user-images.githubusercontent.com/124889650/217818268-d76062eb-d178-4903-8bc1-bf72e8389b83.png)

**Comment by srenault-meeds** [comment]
Thanks duplicated with this one: https://github.com/Meeds-io/meeds/issues/622
We'll take care of it soon
