### ISSUE TITLE
points for issues in GitHub

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#656]
**Is your feature request related to a problem? Please describe.**

We have a GitHub connector that tracks events on code, but for issues we need to report a challenge manually.

**Describe the solution you'd like**
The connector should be extended to allow awarding points to issues events such as creating, commenting, editing, etc...

**Describe alternatives you've considered**
Either we make them silent tracking or we keep it as a challenge with automatic announcements.

**Comment by srenault-meeds** [comment]
Done :)
