### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by ramseyboss** [Meeds-io/meeds#657]
1. Go to 'Contributions'
2. Click on 'Challenges'
3. Scroll down to 'Educate : Translate 1000 words of Whitepaper'
4. See error : Bug in the number of remaining days for the challenge.

![image](https://user-images.githubusercontent.com/122790308/218080952-2e06bd72-ad8a-4481-b46f-aa7048b0524b.png)

**Current behaviour**

If you've been one of the builders long enough you might have noticed that the number of remaining days of the translation challenges didn't change in a while and is still 299 days.

**Expected behavior**

The number of remaining days should be going down.

**(optional) Affected environments**  
Please complete the following information: 
 - OS: [e.g. Windows]
 - Browser [chrome]
 - Version [21H2]
 - Device: [HP]

**Comment by srenault-meeds** [comment]
Indeed, thanks @ramseyboss !

**Comment by srenault-meeds** [comment]
Should be ok in few days
