### ISSUE TITLE
feat: change Challenge announcement to a comment instead of activity

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#658]
**Is your feature request related to a problem? Please describe.**

Currently, I feel that I 'm spammed by the challenge announcements and frankly, I don't want to announce my challenges made to not spam others.

**Describe the solution you'd like**

Creating a challenge should make an activity to make sure that space members are aware of the existence of a new challenge. In addition, announcements should make just a comment inside this challenge activity. We can also, give the possibility, in announcement drawer the possibility to choose either a comment or activity, and then using analytics know which one is useful and needed by users. If 80% choses one of both, we could change it as default behavior, but keeping all time the choice IMO would be better.

**Comment by boubaker** [comment]
an alternative solution would be to add a dedicated notification setting for challenge announcements, so that I see unread badges only without mail and on site notifications.

**Comment by plamarque** [comment]
The problem with comments is that I will receive notifications as soon as I participated.

Also I think one activity per announcement is good to engage and learn from others.

Dedicated notifications for announcements seem better. Ideally, announcements should not trigger regular activity notifications.

**Comment by srenault-meeds** [comment]
Thanks @plamarque I would say the same :-p
