### ISSUE TITLE
selected items on filter "Programme" disappear after selecting "Inclure les programmes désactivés ou supprimés"

### ISSUE THREAD

**Issue by ahnsu123** [Meeds-io/meeds#659]
1. Go to My achievements'(https://builders.meeds.io/portal/meeds/contributions/achievements)'
2. Click on Filter
3. select "community support" in program field 
4. select  "Inclure les programmes désactivés ou supprimés"
5. See error: my selected item "community support" disappears

**Comment by srenault-meeds** [comment]
Rejected as it is expected. Thanks
