### ISSUE TITLE
 Restore the addition/edition of hyperlinks in posts and comments

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#663]
Suggested Behavior: Restoring the functionality of adding and editing hyperlinks in posts 

1. If the link is referring to something in exo, then an interpretation will be done so the link shared is "nice"
2. and then later, we will propose to users to add/edit links by double-clicking to the text so they can add/edit links (so not an option in the editor)

**Comment by srenault-meeds** [comment]
Done with richeditors links MIP :)
