### ISSUE TITLE
Bad UX in Challenge Announcement leads to creating it twice

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#667]
**Steps to reproduce**

1. Go to Overview Page
2. Show DevTools on browser and simulate a Network latency
3. Announce a challenge by clicking twice on the button quickly before the drawer gets closed
4. Go To Stream Page

https://user-images.githubusercontent.com/594824/218246424-c20c8bc6-64dc-45aa-aff3-609b4e48111c.mp4

**Current behaviour**

The announcement is declared twice

**Expected behavior**

The announcement has to be declared once.

In fact, the Bad UX of **not making the button disabled + loading effect** when clicking on it the first time leads to this bug.

**Comment by srenault-meeds** [comment]
Should be fixed in next deployment
