### ISSUE TITLE
feat: Improve Announce button in Challenge Drawer

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#668]
**Is your feature request related to a problem? Please describe.**
The UI of "Announce" link is similar to texts displayed in the same drawer. It's hard to **know that there is a possible action** that we can do when opening the drawer.
![image](https://user-images.githubusercontent.com/594824/218246650-d5d4893b-4809-4fa9-9284-366c672abee5.png)

**Describe the solution you'd like**
We have to add a visible and big button

![image](https://user-images.githubusercontent.com/594824/218246680-2bbe37e9-92af-49c2-87f7-c5d6c03ed361.png)

**Describe alternatives you've considered**
Add a simple primary button in the footer of the drawer, as any other drawer to let user know about possible actions that can be done + change the button name when clicking on it to post the announcement, for example.

**Comment by srenault-meeds** [comment]
Already considered indeed in the contributions UX review
