### ISSUE TITLE
My Wallet shows 3 Meeds, even though earnings of the week are not yet distributed

### ISSUE THREAD

**Issue by ahnsu123** [Meeds-io/meeds#673]
PREREQUISITES:

WEEK1:
My wallet is initially with 0 balance.  
Gains: show an estimation of 3 meeds 

WEEK2: 
today is thursday, and earnings of the week are not yet distributed (see scrennshot that shows no transactions)

**Steps to reproduce**
1. Go to 'Overview'
2. See error: My wallet shows 3 Meeds instead of 0 Meeds (see screenshot below)

![image](https://user-images.githubusercontent.com/124889650/218708286-3bd69df3-549d-4bd0-a876-08cba973f97a.png)

**Comment by srenault-meeds** [comment]
Hi @ahnsu123 I don't see the problem. Because you actually have 3 Meeds on your wallet and rewards are about to be sent (around 105) for this week.
So for me it is ok
