### ISSUE TITLE
Performance regression on people search ( Meeds-io/MIPs#39 )

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#680]
**Steps to reproduce**

1. Go to People page
2. Use slow network throttling
3. Search on first user already displayed in UI
4. See banner slow reload

https://user-images.githubusercontent.com/594824/218946064-a7b2adaf-87b8-44fa-a925-9769146939d5.mp4

**Current behaviour**

The banner URLs of users are reloaded using an URL that doesn't uses HTTP caches

**Expected behavior**

Uses the same banner and avatar URLs for retrieving user information without search

**Comment by srenault-meeds** [comment]
FYI @margondicco @mzorai for next time, please, can we apply good practice regarding perf? Thanks
