### ISSUE TITLE
Margin between space cards and people card 

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#691]
I suggest to put the margin between space cards and people card like project cards!
See screenshots below: 

![Screenshot from 2023-02-15 14-51-24](https://user-images.githubusercontent.com/40363501/219049235-4593fd9f-27fa-48c0-8760-2fefce0d22f0.png)
![Screenshot from 2023-02-15 14-48-02](https://user-images.githubusercontent.com/40363501/219049244-cabb1ffb-06a8-4bfa-aaa2-0eb7c25846ad.png)
![Screenshot from 2023-02-15 14-47-55](https://user-images.githubusercontent.com/40363501/219049249-209f701f-f3d8-4c76-b74b-45ade16111d8.png)

**Comment by srenault-meeds** [comment]
Hi @SaraBoutej I suggest to list 3 items per row and to have the same display we have in contributions center for program and challenges
So for tasks, people, spaces and apps, we will have same display of card
WDYT?
Something like that
<img width="463" alt="people cards max 3 per row" src="https://user-images.githubusercontent.com/58853195/220372129-cdbf247c-8f7b-49b0-b311-c1e1d0663637.png">

**Comment by SaraBoutej** [comment]
@srenault-meeds Ok

**Comment by srenault-meeds** [comment]
Done by Builders 1836
