### ISSUE TITLE
Publishers filter absent in space members

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#694]
**Steps to reproduce**

1. Create a space 'test'
2. Go to 'test' space members application
3. Click on the filter

**(optional) Affected version**

Meeds 1.5.x, 1.4.x _**with property exo.feature.publisherRolePromotion.enabled=true**_

**Current behaviour**

The publishers filter is absent

**Expected behavior**

The publishers filter should be displayed

**Comment by srenault-meeds** [comment]
Done or still in progress @azayati  ?

**Comment by srenault-meeds** [comment]
up @azayati @Julien-Dubois-eXo

**Comment by srenault-meeds** [comment]
up @azayati @Julien-Dubois-eXo is it still in progress....?

**Comment by Julien-Dubois-eXo** [comment]
I guess not, it's done.
