### ISSUE TITLE
Profile - Position not updated as expected (REG)

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#695]
**Steps to reproduce**

1. Go to your profile
2. Fill in the contact informations the position / job title to be displayed in the contact informations & below the display name in the profile's header
3. Save
5. See error: the information is well added in the contact informations but NOT in the profile's header. The user needs to reload the page
This is a regression

Take the other way:
1. Your profile has been updated with a position / job title information inside
2. Update contact info and remove the position from there
3. See error: the information is well removed from the contact informations but NOT from the profile's header. The user needs to reload the page
This is a regression

https://user-images.githubusercontent.com/58853195/219299732-4744a100-dae6-4d84-b5d1-c5b21069c7cd.mp4

**Comment by srenault-meeds** [comment]
@Jihed525 @rdenarie what is the status please for this issue?

**Comment by rdenarie** [comment]
@Julien-Dubois-eXo @Jihed525 can you check this one please ?

**Comment by Jihed525** [comment]
This issue is resolved now

**Comment by srenault-meeds** [comment]
Thanks @Jihed525
