### ISSUE TITLE
Profile - URL field if not 10 char no alert

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#698]
**Steps to reproduce**

1. Go to your profile
2. Request to edit your contact informations
3. In the URL field: If I put less than 10 char, I can't save. Indeed, a minimum of 10 char. is expected BUT no alert displayed to the user that 10 char minimum are expected

https://user-images.githubusercontent.com/58853195/219301385-f553572f-d855-4f1f-9141-0d71a3b1d82f.mp4

**Comment by srenault-meeds** [comment]
@mzora @Jihed525 still on?
Or is it fixed?

**Comment by Jihed525** [comment]
indeed @srenault-meeds , this rule no longer applied, you can add lesser than 10 chars as far as i checked

**Comment by srenault-meeds** [comment]
Ok thanks
