### ISSUE TITLE
Profile - Display name not updated (REG)

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#702]
**Steps to reproduce**

1. Go to your profile
2. Request to edit your contact informations
3. Update your display name and save the changes to apply it
4. See error: Display name not updated in the profile's header
It is a Regression

https://user-images.githubusercontent.com/58853195/219303840-d82129ce-c7c7-4814-8024-a03a07d2bac1.mp4

**Comment by srenault-meeds** [comment]
@Jihed525 @rdenarie what is the status please for this issue?

**Comment by rdenarie** [comment]
This one is fixed

**Comment by srenault-meeds** [comment]
Not yet deployed to production right? @rdenarie

**Comment by rdenarie** [comment]
Hum, I thought it was.
cc @Jihed525 @Julien-Dubois-eXo can you check please ?

**Comment by Jihed525** [comment]
should be fixed actually, do you confirm @srenault-meeds ?

**Comment by srenault-meeds** [comment]
Yes! thanks
