### ISSUE TITLE
Profile - Informations are not updated or cannot be removed (REG)

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#703]
**Steps to reproduce**

Different steps to reproduce it
**Number 1:**
1. Edit your profile contact informations
2. Add all your contact informations, save
3. without reloading your page, edit it again and remove all of them, save the changes
4. See error: still displayed on the portlet even after reloading page

https://user-images.githubusercontent.com/58853195/219304694-d2c82bb4-04d9-4620-a9ee-fc477597a10b.mp4

5. After this, reopen the drawer and remove one more time all infos 
6. See error: two fields still displayed on portlet but empty
![Selection_470](https://user-images.githubusercontent.com/58853195/219304591-fd4923b6-a167-4c2d-8adc-1a89cc575431.png)

**Number 2:**
1. Edit your profile contact informations
2. Add contact informations, save
3. Without reloading your page, try to remove
4. See error: info still displayed in the portlet + in the drawer 

![Selection_471](https://user-images.githubusercontent.com/58853195/219304981-80fd971c-5e19-4972-8eb2-4e8917277de3.png)

https://user-images.githubusercontent.com/58853195/219305027-0b4c6f05-92a3-4348-a7b0-9cf1ed94cb88.mp4

**Number 3:**
1. Reload page
2. Add info in contact info edition
3. Save, it is displayed
4. Without reloading page
5. Edit info (the same) and save
6. Error: 
- The info is not updated
- even after reloading the page, it is not ok

https://user-images.githubusercontent.com/58853195/219305307-722ace67-f1eb-4633-88d4-e851f76e3555.mp4

**Comment by srenault-meeds** [comment]
@Jihed525 @rdenarie what is the status please for this issue?

**Comment by rdenarie** [comment]
I think yes. @Jihed525 can you confirm please ?

**Comment by srenault-meeds** [comment]
@Jihed525 Can you please tell me if ok now?

**Comment by Jihed525** [comment]
I confirm

**Comment by srenault-meeds** [comment]
thanks
