### ISSUE TITLE
Add Pagination in the Achievement table instead of load more button

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#705]
Add Pagination in the bottom of Achievement table instead of load more button, See screenshots
![Screenshot from 2023-02-16 09-33-53](https://user-images.githubusercontent.com/40363501/219312273-c6c15082-f999-4683-9759-3a6f8a9206e4.jpg)
![example-with-pagibation](https://user-images.githubusercontent.com/40363501/219312282-03a885e5-8bd8-49bd-a94a-a50883ef5242.jpg)

**Comment by srenault-meeds** [comment]
The current UX identified is indeed the load more pagination
