### ISSUE TITLE
Fix space and user popover position

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#706]
**Steps to reproduce**

1. Create a space
2. Add few activities into
3. Go back to stream page
4. hover the space name

**Current behaviour**

- The space popover appear, but hide the space name.
- When the popover is here, scroll down or up. The space popover stay displayed even if the mouse is no more over the space name.
- The problem is the same for user popover

**Expected behavior**

- Space and user popover are displayed under the space/user name, to no hide it.
- when scrolling up or down, the popover disappear when the mouse is no more hovering the space/user name

**Comment by srenault-meeds** [comment]
Done or still in progress @IlhemEssaadi ?
