### ISSUE TITLE
[Navigation] Give the ability for a user to stick the menu

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#707]
**Rationale**

Lately, we provided a new way to see what's up in your communities thanks to unread activities notifications.

To pursue this UX enhancement, we'd like to provide you a way to stick the menu.

That would mean the left menu could remained displayed no matter which page you are opening.
That way:
👉 while you are reading a note
👉 while you are working in a task project

✅ You will be able to see where you have received new unread activities without opening the left menu to check.

**Suggested solution**

- Opening the left menu would be changed

Users can still click to it if needed to open the left menu
- When using mobile or tablet, no way to stick the menu
- When using desktop, from 1280px (equal or more)

This means that when fixing the left menu:
* the topbar is reduced so we can see it even if the left menu is displayed
* the page is resized so we see the page and do anything inside
* when scrolling down the page, topbar and left menu are fixed
* when browsing any other page, the left menu remains displayed

When clicking back to the option, then the left menu is back to default status

Precision
This preference should be saved for the user so no matter what he is using, the preference he has chosen should be reminded.

**Comment by boubaker** [comment]
Merged to develop.
