### ISSUE TITLE
Load more button still displayed when no achievements to display

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#710]
1- Open ==> contributions/achievements
2- Change the period (date) when no achievement made
Current behavior: the load more button is displayed in the bottom of the page (seen screenshot)
Expected behavior: the load more button must be hidden
Load more button still display when no achievements to display!
![Screenshot from 2023-02-16 17-20-47](https://user-images.githubusercontent.com/40363501/219426717-6836971d-44fe-430c-8d97-d1bfc0e15d8b.png)

**Comment by Imenmakni** [comment]
It's duplicated with https://github.com/Meeds-io/meeds/issues/616 @SaraBoutej 
cc @srenault-meeds
