### ISSUE TITLE
My reputation portlet loader never end

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#714]
**Steps to reproduce**

1. Go to Overview pag
2. See error

https://user-images.githubusercontent.com/105866381/219651360-cace74fc-b2b6-4368-9d85-fc298e462261.mp4

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The portlet my reputation is loading and never stop to load. 

**Expected behavior**

The loader should be ended and something should be loaded. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Duplicated with this one
