### ISSUE TITLE
Reframe image - not homogeneous behavior in move 

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#725]
**Is your feature request related to a problem? Please describe.**
When you want to reframe an image in your profile, space banner, etc if you move the fame with the mouse it's the frame that moves but if you want to use the arrow it's the image that moves.

So you have the feeling that when you use the arrow the motion is inverted. 

**Describe the solution you'd like**
The arrow should move the frame and not the image.

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/105866381/219701820-be556d7a-c7e7-4a9a-8840-aa2061aa6c0a.mp4

**Comment by srenault-meeds** [comment]
No, as you rotate the image by using rotation, or as you zoom in or out by using zoom option, the arrow are there to move the image, not the frame. 
It is an expected behaviour
