### ISSUE TITLE
Tooltip "Click here to mark as read" always displayed when scrolling up/down

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#734]
**Steps to reproduce**

- On mobile tap on the unread red dot of an activity

- scroll up/down the screen 

**(optional) Affected version**

6.4.0-RC02 with iOS and Android devices

**Current behaviour**

The tooltip is always displayed unless you tap again on the screen

**Expected behavior**

The tooltip disappears after few seconds.

**Comment by srenault-meeds** [comment]
Not reproduced
