### ISSUE TITLE
[MOBILE] UI glitch when clicking on bottom menu item

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#751]
Current behaviour : when you are in mobile view and click on an element of the bottom menu, there is a white line which appear.

Expected : No white line

**Comment by boubaker** [comment]
@GouadriaHanen could you attach a screenshot please to describe better the problem, I can't figure out what was fixed. Thanks.

**Comment by srenault-meeds** [comment]
Is it done?
and @GouadriaHanen have you seen the last comment?

**Comment by srenault-meeds** [comment]
What is the status please? @Jihed525
