### ISSUE TITLE
[TC64] Unable to add new IMs when updating the field

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#761]
**Steps to reproduce**

Prerequisites:
Have your profile filled with at least one IMs

- Go to your profile
- Click on edit icon of contact information 
- Go to Ims field
- Click on "Add new"
- Open the dropdown list

**Current behaviour**

Only already filled options are displayed in the dropdown and no other ones 

**Expected behavior**

All IMs choices should be displayed in the dropdown

**Comment by srenault-meeds** [comment]
Is it done?
