### ISSUE TITLE
Left menu opened : when browsing tabs, left menu should remain without loading

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/meeds#772]
**Is your feature request related to a problem? Please describe.**
left menu opened : When browsing tabs on left menu, the left menu is always charging with display empty:

**Describe the solution you'd like**
I suggest When browsing tabs on left menu, only the dynamic area should load and the left menu should remain fixed without loading

![left menu loading](https://user-images.githubusercontent.com/83289222/221553739-798d364a-04c3-4b40-8869-18ae702a6d13.gif)

**See example :** 

![example fb](https://user-images.githubusercontent.com/83289222/221554282-f8b4c573-46a0-48a4-bbfe-61dc68f67472.gif)

**Comment by srenault-meeds** [comment]
+1 I have thought about this last week and didn't have time to report it. Good point!
@boubaker @SaraBoutej WDYT?

**Comment by boubaker** [comment]
+1 to improve in fact

**Comment by srenault-meeds** [comment]
Should be ok once deployed
