### ISSUE TITLE
My gains for last week are not reinitialized 

### ISSUE THREAD

**Issue by ahnsu123** [Meeds-io/meeds#773]
**Steps to reproduce**

This morning my gains were over 100 meeds. They were not zeroed as usual, and the number keeps going down, as other members gain points 
1. Go to 'Overview'
2. See error on gains 

![image](https://user-images.githubusercontent.com/124889650/221554075-4c32112a-8736-449d-850f-291861149024.png)

**Comment by srenault-meeds** [comment]
That is a normal behaviour. Indeed, if you go to your wallet and update the balance, it will update it.
<img width="117" alt="image" src="https://user-images.githubusercontent.com/58853195/224328919-383aa011-3913-4f20-b8e6-40484daa4737.png">
