### ISSUE TITLE
Bad display for SpaceWallet on the Top menu of spaces

### ISSUE THREAD

**Issue by halaya** [Meeds-io/meeds#779]
**Steps to reproduce**

1. Go to 'any Space'
2. On the Top menu the text label of SpaceWallet looks bad, is displayed #{SpaceWallet.label.name}

![Screenshot from 2023-03-01 10-43-54](https://user-images.githubusercontent.com/5815403/222107622-dfa7d461-1de4-42da-b895-036c49d8ef6f.png)

**Current behaviour**

On the Top menu the text label of SpaceWallet looks bad, is displayed #{SpaceWallet.label.name}

**(optional) Affected environments**  

 - Browser [chrome]
Version 110.0.5481.100

**Comment by srenault-meeds** [comment]
In addition to that, the reward portlet in overview page is loading to death due to this unavailability of the wallet

**Comment by srenault-meeds** [comment]
Fixed
