### ISSUE TITLE
unable to edit a challenge

### ISSUE THREAD

**Issue by Matthew7ash** [Meeds-io/meeds#782]
**Steps to reproduce**

1. Go to 'contributions' / challenges
2. Announce a challenge
3. Go back to the stream page
4. Click on the three dots next to the challenge you have announced in "2"
5. Nothing happens

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.

**Expected behavior**

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
@Matthew7ash Hi thanks. I can't reproduce it. Can you please try to redo it?
And if still KO, then can you please tell me which environment you use (OS, Browser, Device, version, etc.)?
Thanks

**Comment by Matthew7ash** [comment]
Hi @srenault-meeds 
I just tried to edit a challenge and it worked.
I couldn't do it last week.

**Comment by srenault-meeds** [comment]
Thanks!
