### ISSUE TITLE
Change in profile management field is not applied to profile until the cache is cleared

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#786]
**Steps to reproduce**

1. Go to 'profileManagement' page
2. Edit "First name" profile setting
3. Make the profile setting "First name" not visible
4. Go to my profile

**Current behaviour**

-  The "First name" is still visible on view profile even if we logout/login, clearing brower cache is needed.

**Expected behavior**

- The "First name" should be not visible on view profile without clearing browser cache

**Comment by srenault-meeds** [comment]
Is it done?

**Comment by srenault-meeds** [comment]
What is the status please? @Jihed525
