### ISSUE TITLE
fix: Can't not add a new phone number just after removing the last old one

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#788]
Steps of reproduction:

- Go to profile containing a phone number

- Edit contact information

- Remove the existing phone number to add another

Current behavior

- The "Add new" button disappear preventing the add of a new phone number

Expected behavior:

- The "Add new" button must always exist after removing the phone number

**Comment by srenault-meeds** [comment]
Is it done?

**Comment by srenault-meeds** [comment]
What is the status please? @Jihed525
