### ISSUE TITLE
Profile - sub attributes are not saved in profile

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#801]
Step to reproduce:

Access to administration> Organization> Profile
Add a new profile attribute "test"
Add some profile sub-attributes of the profile attribute "test"
Back to profile > Edit my profile and fill the newly added profile sub-attributes of the profile attribute "test" and save
View my profile
Current behavior:

The profile sub-attributes are not displayed and not saved at all

Expected behavior:

The profile sub-attributes should be displayed and saved

Link to feedback https://community.exoplatform.com/portal/dw/tasks/taskDetail/63182

video link https://www.youtube.com/watch?v=_zjbbJx9V68

**Comment by srenault-meeds** [comment]
is it done?

**Comment by srenault-meeds** [comment]
status please? @Jihed525
