### ISSUE TITLE
Document warning snack bar during document upload conflict is not in the foreground

### ISSUE THREAD

**Issue by IlhemEssaadi** [Meeds-io/meeds#810]
**Steps to reproduce**

1. Go to documents app
2. Create a folder
3. Upload several documents
4. Upload again the same documents

**Current behaviour**

- There are snack bars displayed in the background under the gray overlay.

**Expected behavior**

- The snack bar should be displayed in the foreground in front of the grey overlay.

**Comment by srenault-meeds** [comment]
not meeds right? @rdenarie @IlhemEssaadi

**Comment by srenault-meeds** [comment]
What is the status please? @Jihed525
