### ISSUE TITLE
Work experience: Missing indication for required fields

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#814]
- Go to your profile 

- Access to the section "Contact information" and "Work experience"

Current behavior:

- There isn't any indication for required fields in the section "Work experience"  as displayed when editing  "Contact information"

Expected behavior:

- An indication for "Organization" and "Job title" fields should be added to indicate that there are required (coherence with the Contact information section)

**Comment by srenault-meeds** [comment]
is it done?

**Comment by srenault-meeds** [comment]
What is the status please? @Jihed525
