### ISSUE TITLE
Activity params keys case insensitivity block activity updates

### ISSUE THREAD

**Issue by hakermi** [Meeds-io/meeds#815]
Environment: 6.4.0-RC02 (Only on Mysql)

Step to reproduce:

Edit a document
On Only office editor, create a version with a comment. A post is generated in the stream
Like the post
Current behavior

- We can't like the post.

Expected behavior

-We can like the post.

**Comment by srenault-meeds** [comment]
related to meeds?

**Comment by hakermi** [comment]
> related to meeds?

Yes
