### ISSUE TITLE
Erroneous number of search results when using advanced people search.

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#818]
**Steps to reproduce**

1. Go to People page.

2. Make an advanced search on a field and confirm.

**Current behaviour**

The number of results displayed on the top of the page is lesser than the real number of cards displayed by 1 card i.e. when we have 6 cards, the label displays 5 results.

**Expected behavior**

Have the real number of CARDs in the results.

**Comment by srenault-meeds** [comment]
is it done?

**Comment by srenault-meeds** [comment]
What is the status please? @Jihed525
