### ISSUE TITLE
People - UI issue on the leadearboard - the month rank is displayed on the week tab

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#819]
**Steps to reproduce**

1. Go to People page
2. Click on Month tab in the Leaderboard
3. Check your rank
4. Click on the Week tab
6. See error

https://user-images.githubusercontent.com/105866381/225618665-f3b2006b-8bb8-4965-9b4d-049041b9098a.mp4

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

My Month rank is displayed in the Week tab

**Expected behavior**

We should have a rank corresponding to the Week or not rank as it seems that there is no rank for week tab.

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Done thanks to MIP #100 https://github.com/Meeds-io/MIPs/issues/100
