### ISSUE TITLE
People - Detail of point is not corresponding to the tab selected

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/meeds#826]
**Steps to reproduce**

1. Go to People page
2. Hovering over you rank in the tab Week or Month and then over the graph section
3. See error

https://user-images.githubusercontent.com/105866381/225644005-86aef8dc-67c0-4636-a931-032c7c8973b3.mp4

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

The graph is displaying the global point earned instead of the week or month period that I'm watching.

**Expected behavior**

I want to have the details of the point for the week or the month. 

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Not a bug but a feature enhancement ;-)

**Comment by srenault-meeds** [comment]
Done thanks to MIP #100 https://github.com/Meeds-io/MIPs/issues/100
