### ISSUE TITLE
Put the white area in perkstore page on the full height of the screen

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#849]
In the perkstore page, when no products found I suggest to put the white area on the full height of the screen.

![Screenshot from 2023-03-22 11-49-29](https://user-images.githubusercontent.com/40363501/226924375-9c0f6626-15ce-4ddd-a7f3-c4ffddd0596e.png)

**Comment by srenault-meeds** [comment]
Will be ok after next deployment
