### ISSUE TITLE
[Challenges] I'm able to announce a disabled challenge

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#853]
1. With root, create a user "admin". Add it in the group "Reward administrators"
2. Log with "admin", and create an space
3. Go to Contribution Center, create a program. For audience, choose the created space
4. Add a challenge in this program
5. Announce this challenge
6. Edit the challenge to disable it
7. Go to the space, and, in the activity, click on the challenge name
8. In the drawer, you can announce your disabled challenge

**Affected version**

Meeds 1.5.x-SNAPSHOT

**Current behaviour**

I'm able to announce a disabled challenge

**Expected behavior**

A disabled challenge must not be announced.

**Comment by srenault-meeds** [comment]
Fixed!
