### ISSUE TITLE
[Challenge] When changing audience of a program, it is not changed in the announcement drawer

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#855]
1. With root, create a user "admin". Add it in the group "Reward administrators"
2. Log with "admin", and create an space
3. Go to Contribution Center, create a program. For audience, choose the created space
4. Add a challenge in this program
4. Go in the program, and click on the "Announce" button. In the annoucnement drawer, the audience is the created space
5. Create a second space. modify the program and change the audience to the second space
6. click on the "Announce" button of the challenge

**(optional) Affected version**

Meeds-1.5.-xSNAPSHOT

**Current behaviour**

The audience in the announcement space is still the first one.

**Expected behavior**

It must be the correct space

**Remarks**
It seems to be a cache pb. When restarting the server, and opening the announcement drawer display the correct audience

**Comment by srenault-meeds** [comment]
Indeed, the announcement is posted on the right space but the composer still shows the previous audience. Even after emptying the browser cache
