### ISSUE TITLE
Unable to cancel an anouncement

### ISSUE THREAD

**Issue by Matthew7ash** [Meeds-io/meeds#857]
**Steps to reproduce**

1. Go to 'Stream' page 
2. Click on 'the three horizental points next to an announcement that you've done'
3. Choose the option "Cancel announcement"
==> Nothing happens (Tried on google chrome and firefox)

If applicable, add screenshots to help explain your problem:
![image](https://user-images.githubusercontent.com/124496730/227761006-d13f95ce-0759-4663-9957-545ee44c418d.png)

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

Describe the bug with a clear and concise description of what the problem is.

**Expected behavior**

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Not reproduced
