### ISSUE TITLE
UI Improvement: add border radius to all white container in the stream page

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#866]
In the stream page all activities white container have border-radius: 5 px;
But the other white container in the right sidebar has no border radius.
I suggest adding a border radius to all white container in the stream page to have a consistent UI
![Screenshot from 2023-03-29 08-57-47](https://user-images.githubusercontent.com/40363501/228470364-c3b29056-5bd1-41a1-ace6-8713d55c7053.jpg)

**Comment by srenault-meeds** [comment]
Good point!
@boubaker Do you think we can apply this border-radius for any box in a simple way? Or does that need to be done box by box?
cc @SaraBoutej

**Comment by srenault-meeds** [comment]
Being dealt by the mip81
