### ISSUE TITLE
Filter Icon in space and people pages when mobile

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#870]
Put the same  filter icon in the space and people pages  when mobile for UI consistency
![Screenshot from 2023-03-31 08-01-16](https://user-images.githubusercontent.com/40363501/229051064-dbd087ca-d935-4621-8548-5ec461ab8b02.png)
![Screenshot from 2023-03-31 08-01-10](https://user-images.githubusercontent.com/40363501/229051145-e4f8ca36-bbe5-47ba-9ec6-60ecbfc41857.png)

**Comment by srenault-meeds** [comment]
Indeed. @margondicco Can we update the filter icon of the people page to the one of the spaces page?
