### ISSUE TITLE
Change the color of filter button in perkstore page

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#871]
Change the color of the filter button in the perkstore page toolbar in primary color to be uniform with other filter button in the platform.
![Screenshot from 2023-03-30 12-04-25](https://user-images.githubusercontent.com/40363501/229052022-9ab4075f-7193-4a7c-9113-6a6de957515c.png)
![Screenshot from 2023-03-30 12-03-08](https://user-images.githubusercontent.com/40363501/229052028-b0a3741f-7b1e-4514-bc72-fc123dc78e74.png)
![Screenshot from 2023-03-30 12-02-59](https://user-images.githubusercontent.com/40363501/229052038-de2b1a45-89aa-4a57-83ac-78935bf4b3de.png)

**Comment by srenault-meeds** [comment]
@SaraBoutej thanks. Can we take this one in the current task you are doing?

**Comment by SaraBoutej** [comment]
Yes cc @srenault-meeds

**Comment by srenault-meeds** [comment]
Thanks :)
