### ISSUE TITLE
Url for "Become famous" gamification point is broken

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#874]
**Steps to reproduce**

1. Go to achievement tab in contribution center
2. See the achievement "Become Famous :-)"
![image](https://user-images.githubusercontent.com/807839/229059902-c9641080-1b78-4c43-a7ef-9835b8b32388.png)
3. Click on the achivement link (url is https://builders.meeds.io/portal/intranet/profile/0x7f6b400def95a330744b2ca6adc13aaef5b64143)

**(optional) Affected version**
Builders instance

**Current behaviour**
Display a 404 page

**Expected behavior**
Must display the user profile page

**(optional) Affected environments**  
Please complete the following information:

**Comment by srenault-meeds** [comment]
Indeed. Thanks @rdenarie.
It seems that any other action related to connection (send /receive) sends a wrong URL (portal/intranet/...)

**Comment by srenault-meeds** [comment]
Not reproduced with new achievement related to network
