### ISSUE TITLE
Image rendering enhancement

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#880]
When adding an image, due to optimizations done to image size,
If GIF or if image has specific metadata, then we have problems:
- gif is not viewable from the thumbnail, or if avatar, if banner
- image is not well oriented as expected

We suggest we improve this by making sure that:
*when the image is a GIF (animated image), then it is well displayed animated from preview AND from the thumbnail AND from avatar / banner
*and the orientation of the image is taken as it is from the device it has been uploaded

**Comment by srenault-meeds** [comment]
@rdenarie @boubaker as discussed, I have created this issue to be done outside the MIP as it needs to be taken care from maintenance point of view

**Comment by boubaker** [comment]
Thanks @srenault-meeds
