### ISSUE TITLE
Meeds holders link is wrong 

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#886]
**Steps to reproduce**

1. Go to [meeds builders programs page](https://builders.meeds.io/portal/meeds/contributions/programs) 
2. Click on 'Meeds Holders' app

**(optional) Affected version**

Indicate the version where the bug is observed.

**Current behaviour**

We are redirected to the wrong link https://www.meeds.io/dapp/overview which not goes to dapp

**Expected behavior**

The link should be https://www.meeds.io/dapp/ instead

**(optional) Affected environments**  
Please complete the following information:

**Comment by boubaker** [comment]
Fixed, thanks.
