### ISSUE TITLE
New/Active challenge notifications

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#887]
**Is your feature request related to a problem? Please describe.**
Currently, the end user is not able to kown that a new challenge is added or becomes active, he should always go to the challenges page to check or see an announcement on it. This can be problematic especially when the duration of a challenge is short.

**Describe the solution you'd like**
The end user should be notified when a new challenge is added or activated.

**Describe alternatives you've considered**

**Additional context**

**Comment by srenault-meeds** [comment]
It is ok now that we can announce action availability and we have reworked the way new actions are listed in the gadget from overview and stream. Am I right?
