### ISSUE TITLE
OIDC connection is KO

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#894]
Scenario : 

Configure openid (with google for example)
On login form click on openid button, and choose the account. Remark : the account must not exists on exo, and will be created at first login.

Current behaviour: 

Error in log : 

> Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "usernameOrEmail" is null
>     at io.meeds.oauth.service.impl.OAuthRegistrationServiceImpl.findUser(OAuthRegistrationServiceImpl.java:248)
>     at io.meeds.oauth.service.impl.OAuthRegistrationServiceImpl.detectGateInUser(OAuthRegistrationServiceImpl.java:107)
>     ... 66 common frames omitted

**Comment by srenault-meeds** [comment]
Hello, work in progress or done?

**Comment by rdenarie** [comment]
Done
