### ISSUE TITLE
[Tasks] Task comments display KO

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#895]
**Steps to reproduce**

1. Go see a task
2. See error: comment are not displayed as expected from the task detail form and from the comment drawer
<img width="200" alt="task comment KO" src="https://user-images.githubusercontent.com/58853195/231711272-a466e55b-3d1c-497a-8054-3cf9f00f33d2.png">

<img width="199" alt="task comment drawer KO" src="https://user-images.githubusercontent.com/58853195/231711279-af8e7ab5-e4fc-47bf-a9f7-168d34d8d42f.png">

**Comment by azayati** [comment]
Fix in progress by Maintenance @srenault-meeds
