### ISSUE TITLE
Post Modification on Stream not working

### ISSUE THREAD

**Issue by m0ckingbird23** [Meeds-io/meeds#897]
1. Go to announce in the Reddit Upvotes & Save Challenge section
2. Announce your achievemnt 
3. Go to Stream and open your post
4. click on Edit and modify the post content
5. press update
=>nothing happens

**screenshot**
![image](https://user-images.githubusercontent.com/52405795/232080189-98027e3f-49b2-4caa-8a39-0685fd7d4a8d.png)

**Expected behavior**

Should get the new content on the post description (save  instead of UpVote)

**(optional) Affected environments**  
Please complete the following information: 
 - OS: Windows 10
 - Browser: Chrome 
 - Version:  --
 - Device:  computer

**Comment by srenault-meeds** [comment]
not reproduced
