### ISSUE TITLE
[Contributions] Challenge counter in challenges tab can be out of the screen

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#926]
Steps to reproduce : 

1- Access to contribution app using mobile 
2- access to challenge TAB 
3-  check challenge counter for program with long name 

Actual behavior:
The challenge counter is out of the block
<img width="147" alt="image" src="https://user-images.githubusercontent.com/58853195/235095342-88e9bf54-e77b-4cd4-be19-c86318d3e815.png">

<img width="155" alt="image" src="https://user-images.githubusercontent.com/58853195/235095477-d6bf1a12-6633-42ff-886a-17be3103ea37.png">

Expected behavior : 
The challenge counter should be well displayed

**Comment by srenault-meeds** [comment]
Reopened as it is still a problem

**Comment by boubaker** [comment]
@srenault-meeds , if the problem was resolved before and it appears again, it's better to open anew issue instead of reopening an old one. In addition, this screen of "Challenges" with those cards doesn't exist anymore.

**Comment by srenault-meeds** [comment]
Created a new issue: https://github.com/Meeds-io/meeds/issues/1013
