### ISSUE TITLE
 The X tô hide a notification is dificult to click 

### ISSUE THREAD

**Issue by jonasbrant** [Meeds-io/meeds#937]
When you try to click to hide a notification the x button is difficult to select and you goes to the task . 

![image](https://github.com/Meeds-io/meeds/assets/11363238/1c68cf22-0d41-4058-aae6-b595b1fcfc28)

 - OS: iOS
 - Browser APP and safari]

**Comment by plamarque** [comment]
+1 on mobile the touch target is too small. Extreme precision is required.

**Comment by srenault-meeds** [comment]
Fixed and improved now :)
