### ISSUE TITLE
Results are collapsed when searching a challenge

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/meeds#939]
**Steps to reproduce**

1. Go to Contributions app > Challenges tab
2. Type a keyword in the text filter (ensure that the keyword matches at least a challenge)

**Current behaviour**

The matched results are collapsed and we need to elapse to check the result

![image](https://github.com/Meeds-io/meeds/assets/1576297/975c1d17-ad15-44bf-a573-b790758491ae)

**Expected behavior**

results should be by default elapsed 

**(optional) Affected environments**  
Please complete the following information: 
 - OS: Linux
 - Browser Brave

**Comment by srenault-meeds** [comment]
Should be fixed now
