### ISSUE TITLE
Date spelling of posts should start with a capital letter

### ISSUE THREAD

**Issue by akhanfir** [Meeds-io/meeds#952]
**Steps to reproduce**

  1. space1 has several posts in different times
  2. User1 connects with a german language to the plf
  3. check the spelling of dates below the posts

**Current behaviour**

  The fist letter of the date is in lower case.

**Expected behavior**

  The fist letter of the date should be in upper case.

  Right spelling: Tagen/Minute etc

**Comment by srenault-meeds** [comment]
done?
