### ISSUE TITLE
Color outline on action cards

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#968]
I suggest to colorized the outline of aciton cards with a color that would be consistent with the color of programs. (colors of programs should be randomized enough to avoid duplicate colors)

**Comment by srenault-meeds** [comment]
Thanks something like that?
(we have discussed about it with Benjamin last Monday and today I proposed it to him)

We added the fact that points could be emphasized upon their weigh

<img width="811" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/8cbb17d5-e89e-4132-9a99-640fa590d4b4">

**Comment by plamarque** [comment]
Yes, that's what I had in mind
