### ISSUE TITLE
remove some labels in action drawer

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#973]
In action drawer labels "Achieve it for", "Participations" and "Ends in" looks innecessary because the way we display the value is self explanatory. We should remove them to better distribute space and aboiud distracting clutter. We should move them to informative tooltips like : "Earn 200 points by achieving this action", "Patrice, Bob and X others have participate", "Perform the action before..."

**Comment by srenault-meeds** [comment]
We have reviewed the display of it since this feedback. I close it then until we have new feedbacks regarding this
