### ISSUE TITLE
Add popover when hovering a challenge name from the stream

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#974]
Sometimes I wan't to read quick information about a challenge (points to earn, date left...) without redirection to the contribution center page.
I suggest to add a popover on the challenge name 
 
![popup](https://github.com/Meeds-io/meeds/assets/40363501/0e57f559-e645-4ba3-98b2-b00ae6840554)

**Comment by srenault-meeds** [comment]
As we can access the action detail drawer now, is that relevant to get a popover?
