### ISSUE TITLE
Participants drawer is empty

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#977]
1. Go to /contributions/programs/
2. Click on a program
3. Scroll down to actions list
4. Click to open participants drawer
5. See error
![chrome-capture-2023-5-2](https://github.com/Meeds-io/meeds/assets/40363501/fc7ad321-3195-44f5-9596-4b03d51d2ff9)

**Comment by srenault-meeds** [comment]
Can you try using a private navigation mode?

**Comment by srenault-meeds** [comment]
Not reproduced
