### ISSUE TITLE
Reduce le font size in challenge cards 

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#978]
See difference between two screenshots
![Screenshot from 2023-06-02 15-17-29](https://github.com/Meeds-io/meeds/assets/40363501/8ac6647e-a047-4f2e-bd38-aaf9629f58de)
![Screenshot from 2023-06-02 15-17-17](https://github.com/Meeds-io/meeds/assets/40363501/e2efcbe2-cd2d-443a-98f8-07f21b5d46da)

**Comment by plamarque** [comment]
Check on mobile also. It's really too big there

**Comment by srenault-meeds** [comment]
Is that better now?
