### ISSUE TITLE
[email] Email subject info portal name is confusing

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#992]
**Steps to reproduce**

1. Get an email from any platform (ex: when someone sends you a connection request)
2. The portal name is identified (ex: [user display name] wants to connect with you on eXo)
3. See error: exo is the portal name but not ok with meeds context

Suggestion: Replace portal name when identified by company branding name

**Comment by srenault-meeds** [comment]
@margondicco @rdenarie any objection please?
cc @boubaker

**Comment by margondicco** [comment]
OK

**Comment by rdenarie** [comment]
No objection
