### ISSUE TITLE
[Feedback] Timezone in user settings not relevant

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#993]
As the time zone is set from the browser the user use
It is not relevant to propose to him to set a time zone. It brings confusion to users

Suggestion: remove this setting from user settings

**Comment by srenault-meeds** [comment]
@margondicco WDYT?

**Comment by margondicco** [comment]
oh yes !

**Comment by srenault-meeds** [comment]
FYI it is removed now @margondicco
