### ISSUE TITLE
[Settings] Site language set to EN by default - no IHM

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#994]
**Is your feature request related to a problem? Please describe.**
By default, the site language is set to EN which is annoying for users who are not english speaker. 
Because they:
- receive by default notifications in English
- find as default language for multilingual labels the English

In addition to this, admin of the platform cannot change this parameter since no admin interface is proposed to these users

**Describe the solution you'd like**
From the general settings page, provide a way to change the default language.
Once done, notifications and site language will be set by default to the chosen language.

Mockup: 
<img width="541" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/db753cd4-97da-494c-a7fe-83ad837524f9">

**Comment by srenault-meeds** [comment]
@margondicco is that a problem for you?
That means the site configuration option you have when using eXo will be not usable anymore

**Comment by margondicco** [comment]
Refused ;-)
Because Meeds will integrate the site management functionalities and the default language is already an option
