### ISSUE TITLE
[Mail notifications] Footer link and label of mail notification

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#997]
Onboarding emails have a footer reminding the name of the platform (from branding company name) with no link
But other email notification provides a footer with the name of the portal (eXo or Meeds) with a link to their website.

Suggestion: footer label to change to the company name set in branding page + link to the related platform.

**Comment by srenault-meeds** [comment]
@margondicco any objection please?

**Comment by margondicco** [comment]
agree !
