### ISSUE TITLE
Stream like identities in drawer is wrong

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#998]
**Steps to reproduce**

1. Go to Stream
2. Add multiple activities
3. Like the activities using 3 different activities for each 
4. Open likers drawer without refresh for each activity

**Current behaviour**

The likers of first opened drawer are displayed instead of the second one.

**Expected behavior**

The likers of each activity is displayed

**Comment by srenault-meeds** [comment]
not reproduced, seems to be done
